### ISSUE TITLE
Crash on item placement

### ISSUE THREAD

**Issue by afaville** [MightyPirates/OpenComputers#1065]
As soon as any item is placed down, the game crashes and I get an error log. I can craft the items, but placing any cause the game to crash. Here is the error log:

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
    at net.minecraft.client.renderer.block.model.BakedQuad.makeVertexDataSingle(BakedQuad.java:92)
    at net.minecraft.client.renderer.block.model.BakedQuad.getVertexDataSingle(BakedQuad.java:76)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:263)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:125)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:60)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:49)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:77)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:251)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.block.model.BakedQuad.makeVertexDataSingle(BakedQuad.java:92)
    at net.minecraft.client.renderer.block.model.BakedQuad.getVertexDataSingle(BakedQuad.java:76)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:263)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:125)

-- Block model being tesselated --
Details:
    Block: opencomputers:cable
    Block location: World: (-275,92,-4123), Chunk: (at 13,5,5 in -18,-258; contains blocks -288,0,-4128 to -273,255,-4113), Region: (-1,-9; contains chunks -32,-288 to -1,-257, blocks -512,0,-4608 to -1,255,-4097)
    Using AO: true
Stacktrace:
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:60)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:49)

-- Block being tesselated --
Details:
    Block type: ID #201 (tile.oc.cable // li.cil.oc.common.block.Cable)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-275,92,-4123), Chunk: (at 13,5,5 in -18,-258; contains blocks -288,0,-4128 to -273,255,-4113), Region: (-1,-9; contains chunks -32,-288 to -1,-257, blocks -512,0,-4608 to -1,255,-4097)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:77)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['jhfu'/157, l='MpServer', x=-272.90, y=92.00, z=-4122.88]]
    Chunk stats: MultiplayerChunkCache: 702, 702
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 108.00,64.00,252.00 - World: (108,64,252), Chunk: (at 12,4,12 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 739044 game time, 884888 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 109 total; [EntityMinecartChest['container.minecart'/256, l='MpServer', x=-316.50, y=25.06, z=-4050.50], EntityPig['Pig'/257, l='MpServer', x=-325.00, y=64.00, z=-4164.00], EntityPig['Pig'/259, l='MpServer', x=-195.22, y=63.00, z=-4170.50], EntityPig['Pig'/260, l='MpServer', x=-196.84, y=63.00, z=-4170.50], EntityMinecartChest['container.minecart'/262, l='MpServer', x=-204.50, y=38.06, z=-4079.50], EntityBat['Bat'/263, l='MpServer', x=-199.25, y=39.44, z=-4065.41], EntityRabbit['Rabbit'/267, l='MpServer', x=-282.13, y=65.00, z=-4047.50], EntityBat['Bat'/275, l='MpServer', x=-327.19, y=23.09, z=-4046.06], EntityPig['Pig'/276, l='MpServer', x=-201.53, y=60.00, z=-4178.72], EntityPig['Pig'/277, l='MpServer', x=-197.41, y=64.00, z=-4181.00], EntityZombie['Zombie'/279, l='MpServer', x=-301.88, y=25.00, z=-4045.31], EntityWitch['Witch'/295, l='MpServer', x=-331.50, y=26.00, z=-4043.50], EntityWitch['Witch'/296, l='MpServer', x=-332.50, y=26.00, z=-4043.50], EntityBat['Bat'/298, l='MpServer', x=-327.25, y=22.53, z=-4045.25], EntityMinecartChest['container.minecart'/299, l='MpServer', x=-196.50, y=31.06, z=-4196.53], EntityPig['Pig'/300, l='MpServer', x=-196.50, y=64.00, z=-4199.13], EntityCreeper['Creeper'/304, l='MpServer', x=-203.63, y=39.00, z=-4044.16], EntitySkeleton['Skeleton'/305, l='MpServer', x=-204.47, y=39.00, z=-4044.47], EntityMinecartChest['container.minecart'/307, l='MpServer', x=-199.50, y=39.06, z=-4043.50], EntityItem['item.tile.stonebrick'/1386, l='MpServer', x=-274.86, y=90.07, z=-4122.23], EntityCreeper['Creeper'/158, l='MpServer', x=-282.13, y=58.00, z=-4125.38], EntitySpider['Spider'/159, l='MpServer', x=-282.31, y=61.00, z=-4123.31], EntitySpider['Spider'/160, l='MpServer', x=-276.97, y=64.00, z=-4112.25], EntityCreeper['Creeper'/161, l='MpServer', x=-270.82, y=64.00, z=-4119.73], EntityArmorStand['Armor Stand'/162, l='MpServer', x=-277.50, y=92.00, z=-4121.50], EntitySkeleton['Skeleton'/163, l='MpServer', x=-265.77, y=64.00, z=-4125.74], EntityItemFrame['entity.ItemFrame.name'/164, l='MpServer', x=-269.50, y=93.50, z=-4121.03], EntityPlayerSP['jhfu'/157, l='MpServer', x=-272.90, y=92.00, z=-4122.88], EntityBat['Bat'/166, l='MpServer', x=-258.66, y=38.97, z=-4144.93], EntityMinecartEmpty['entity.MinecartRideable.name'/167, l='MpServer', x=-267.53, y=92.06, z=-4129.50], EntityPig['Pig'/168, l='MpServer', x=-269.84, y=64.00, z=-4096.88], EntityCreeper['Creeper'/169, l='MpServer', x=-268.97, y=64.00, z=-4106.38], EntitySkeleton['Skeleton'/170, l='MpServer', x=-258.50, y=64.00, z=-4108.50], EntitySkeleton['Skeleton'/171, l='MpServer', x=-257.88, y=64.00, z=-4106.25], EntityChicken['Chicken'/172, l='MpServer', x=-290.31, y=64.00, z=-4104.41], EntityZombie['Zombie'/173, l='MpServer', x=-277.19, y=64.00, z=-4105.34], EntityItem['item.item.egg'/174, l='MpServer', x=-282.06, y=64.00, z=-4100.56], EntityCreeper['Creeper'/175, l='MpServer', x=-296.06, y=64.00, z=-4124.66], EntityCreeper['Creeper'/176, l='MpServer', x=-269.50, y=38.00, z=-4146.50], EntityCreeper['Creeper'/177, l='MpServer', x=-288.16, y=64.00, z=-4110.84], EntityCreeper['Creeper'/178, l='MpServer', x=-296.90, y=66.00, z=-4149.33], EntityPig['Pig'/179, l='MpServer', x=-242.19, y=63.00, z=-4157.81], EntityPig['Pig'/180, l='MpServer', x=-227.91, y=64.00, z=-4135.97], EntityZombie['Zombie'/181, l='MpServer', x=-254.38, y=60.00, z=-4090.94], EntityPig['Pig'/182, l='MpServer', x=-255.81, y=64.00, z=-4087.88], EntityChicken['Chicken'/183, l='MpServer', x=-253.75, y=64.00, z=-4094.34], EntityItem['item.item.egg'/184, l='MpServer', x=-252.88, y=64.00, z=-4093.59], EntityPig['Pig'/185, l='MpServer', x=-252.19, y=64.00, z=-4089.88], EntityPig['Pig'/186, l='MpServer', x=-294.09, y=64.00, z=-4090.16], EntityBat['Bat'/187, l='MpServer', x=-226.25, y=52.10, z=-4151.75], EntityPig['Pig'/188, l='MpServer', x=-229.03, y=64.00, z=-4152.06], EntityPig['Pig'/189, l='MpServer', x=-257.91, y=63.00, z=-4174.00], EntityZombie['Zombie'/190, l='MpServer', x=-216.79, y=24.01, z=-4121.16], EntityBat['Bat'/191, l='MpServer', x=-213.63, y=34.59, z=-4120.03], EntitySkeleton['Skeleton'/192, l='MpServer', x=-221.50, y=47.00, z=-4125.50], EntitySkeleton['Skeleton'/193, l='MpServer', x=-220.50, y=47.00, z=-4127.50], EntityCreeper['Creeper'/194, l='MpServer', x=-219.69, y=47.00, z=-4126.69], EntityCreeper['Creeper'/195, l='MpServer', x=-220.19, y=63.00, z=-4115.84], EntityCreeper['Creeper'/196, l='MpServer', x=-262.97, y=39.00, z=-4074.16], EntityPig['Pig'/197, l='MpServer', x=-267.88, y=63.00, z=-4077.16], EntityZombie['Zombie'/198, l='MpServer', x=-282.50, y=41.00, z=-4070.50], EntityPig['Pig'/199, l='MpServer', x=-280.00, y=64.00, z=-4067.88], EntityHorse['Horse'/200, l='MpServer', x=-317.44, y=67.00, z=-4132.41], EntityPig['Pig'/201, l='MpServer', x=-251.72, y=63.00, z=-4162.53], EntityZombie['Zombie'/202, l='MpServer', x=-213.34, y=23.00, z=-4107.91], EntityBat['Bat'/203, l='MpServer', x=-235.71, y=38.04, z=-4075.55], EntitySkeleton['Skeleton'/204, l='MpServer', x=-242.50, y=63.00, z=-4066.50], EntityRabbit['Rabbit'/205, l='MpServer', x=-246.16, y=64.00, z=-4070.94], EntityPig['Pig'/206, l='MpServer', x=-252.88, y=64.00, z=-4078.22], EntityPig['Pig'/207, l='MpServer', x=-291.03, y=63.00, z=-4070.91], EntityPig['Pig'/208, l='MpServer', x=-311.47, y=67.00, z=-4168.25], EntityZombie['Zombie'/209, l='MpServer', x=-308.56, y=62.45, z=-4150.94], EntityHorse['Horse'/210, l='MpServer', x=-295.06, y=66.00, z=-4171.00], EntityHorse['Horse'/211, l='MpServer', x=-288.69, y=65.00, z=-4173.91], EntityPig['Pig'/212, l='MpServer', x=-299.16, y=67.00, z=-4162.50], EntityCreeper['Creeper'/213, l='MpServer', x=-214.19, y=35.00, z=-4149.28], EntityBat['Bat'/214, l='MpServer', x=-218.38, y=52.13, z=-4151.38], EntityPig['Pig'/215, l='MpServer', x=-222.13, y=64.00, z=-4156.44], EntityHorse['Horse'/216, l='MpServer', x=-326.25, y=67.00, z=-4116.19], EntityCreeper['Creeper'/217, l='MpServer', x=-264.63, y=67.00, z=-4191.88], EntityZombie['Zombie'/219, l='MpServer', x=-201.41, y=36.00, z=-4127.00], EntityZombie['Zombie'/221, l='MpServer', x=-193.50, y=53.00, z=-4119.50], EntityBat['Bat'/222, l='MpServer', x=-285.09, y=37.59, z=-4048.13], EntityMinecartChest['container.minecart'/223, l='MpServer', x=-281.50, y=41.00, z=-4062.53], EntityChicken['Chicken'/224, l='MpServer', x=-277.63, y=64.00, z=-4058.63], EntityPig['Pig'/225, l='MpServer', x=-278.94, y=64.00, z=-4050.03], EntityBat['Bat'/226, l='MpServer', x=-327.79, y=44.10, z=-4102.22], EntityBat['Bat'/227, l='MpServer', x=-325.17, y=42.02, z=-4112.60], EntityBat['Bat'/228, l='MpServer', x=-329.47, y=43.78, z=-4104.78], EntityPig['Pig'/229, l='MpServer', x=-323.13, y=67.00, z=-4143.94], EntityPig['Pig'/230, l='MpServer', x=-275.06, y=64.00, z=-4191.44], EntityRabbit['Rabbit'/231, l='MpServer', x=-277.47, y=64.00, z=-4189.75], EntityCreeper['Creeper'/232, l='MpServer', x=-253.34, y=67.00, z=-4189.09], EntitySkeleton['Skeleton'/233, l='MpServer', x=-201.59, y=14.00, z=-4097.13], EntitySpider['Spider'/235, l='MpServer', x=-244.03, y=63.00, z=-4064.50], EntityCreeper['Creeper'/236, l='MpServer', x=-245.50, y=63.00, z=-4061.50], EntityZombie['Zombie'/237, l='MpServer', x=-318.25, y=63.00, z=-4069.88], EntityPig['Pig'/238, l='MpServer', x=-308.97, y=64.00, z=-4164.94], EntityPig['Pig'/239, l='MpServer', x=-317.66, y=64.00, z=-4165.81], EntityMinecartChest['container.minecart'/240, l='MpServer', x=-217.50, y=39.06, z=-4071.50], EntityBat['Bat'/241, l='MpServer', x=-288.91, y=36.00, z=-4054.75], EntityPig['Pig'/242, l='MpServer', x=-321.19, y=65.00, z=-4154.41], EntityHorse['Horse'/243, l='MpServer', x=-302.04, y=66.00, z=-4186.52], EntityHorse['Horse'/244, l='MpServer', x=-299.96, y=67.81, z=-4188.31], EntityCreeper['Creeper'/245, l='MpServer', x=-207.47, y=46.00, z=-4160.00], EntityCreeper['Creeper'/246, l='MpServer', x=-207.03, y=34.00, z=-4150.41], EntitySkeleton['Skeleton'/248, l='MpServer', x=-204.50, y=43.00, z=-4158.50], EntityCreeper['Creeper'/249, l='MpServer', x=-211.13, y=34.00, z=-4147.47], EntityZombie['Zombie'/255, l='MpServer', x=-203.50, y=12.00, z=-4093.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:399)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2488)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1175053792 bytes (1120 MB) / 2695888896 bytes (2571 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6g
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.10 FML v8.0.37.1334 Minecraft Forge 11.14.1.1334 Optifine OptiFine_1.8_HD_U_D2 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{8.0.37.1334} [Forge Mod Loader] (forge-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{11.14.1.1334} [Minecraft Forge] (forge-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.5.93} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.93-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.8.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.5.6.13} [OpenComputers] (OpenComputers-MC1.8-1.5.6.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.93-universal.jar)
  codechicken.nei.asm.NEITransformer
CCCDeobfPlugin (unknown)

CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
TransformerLoader (OpenComputers-MC1.8-1.5.6.13-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
    Launched Version: 1.8
    LWJGL: 2.9.1
    OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [Inklination [256x] 10-31-14.zip]
    Current Language: English (US)
    Profiler Position: N/A (disabled)
```

**Comment by fnuecke** [comment]
Does this also happen if OC is the only mod installed? Does it also happen when not using resource packs?

**Comment by afaville** [comment]
I found the problem, it only crashes with Optifine installed, resource packs have no effect, neither do my other mods (othet than optifine). Please help me fix this, I want to use optifine with it.

**Comment by fnuecke** [comment]
Sounds like Optifine doesn't properly support Forge's `ISmartBlockModel`, then. You'll have to take that to the Optifine dev(s) I think. I don't see how this could be caused on my end, but if they insist it's me doing something non-standard, I'd ask they have a look at the [block rendering code](http://git.io/vvo1n) and tell me what that might be.
