### ISSUE TITLE
Internal error: Mining turtle throwing internal error randomly and shutting down.

### ISSUE THREAD

**Issue by sulljason** [MightyPirates/OpenComputers#1070]
I made a simple mining robot. I tested the firmware and it operated fine, so I don't think its a bug in my code and the fact that it was an internal error not the general Lua crash and stack-trace. When it happens is fairly random, but less then a few minutes after I start the robot on a mining job.

Stack-trace:

```
[20:26:33] [OpenComputers-Computer-3/WARN] [OpenComputers/]: Architecture's runThreaded threw an error. This should never happen!
java.lang.NullPointerException
at li.cil.oc.server.machine.Machine.run(Machine.scala:881) [Machine.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_40]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_40]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

Bad but functional robot code:

```
function goBackToDrop()
robot.turnRight();
for i=0,x-1,1 do
forward();
end
for i=0,y-1,1 do
robot.down();
end
robot.turnRight();
for i=0,z-1,1 do
forward();
end
turnAround();

for i=1,robot.inventorySize(),1 do
robot.select(i);
robot.dropDown();
end

up();
os.sleep(5);
for i=1,robot.inventorySize(),1 do
robot.select(i)
gen.insert(64-gen.count())
end
robot.down();

end

function goBackToMine()
robot.turnLeft();
for i=0,x-1,1 do
forward();
end
robot.turnRight();
for i=0,y-1,1 do
up();
end
for i=0,z-1,1 do
forward();
end
end

function turnAround()
robot.turnRight();
robot.turnRight();
end

function up()
while not robot.up() do
robot.swingUp();
end
end

function mineRow()
for i=0,mineZ-1,1 do
dig();
forward();
z=z+1;
end
end

function dig()
while robot.detect() do
robot.swing();
end
end

function forward()
while not robot.forward() do
robot.swing();
end
end

comp=require("component");
gen=comp.generator;
robot=require("robot");

mineX=3;
mineY=3;
mineZ=3;

x=0;
y=0;
z=0;

while x <= mineX do

mineRow();
goBackToDrop();
if y >= mineY then
y=0;
x=x+1;
z=0;
else
y=y+1;
z=0;
end
goBackToMine();

end
goBackToDrop();
computer.shutdown();
```

**Comment by fnuecke** [comment]
Thanks for the report. This should be fixed in the next [dev build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) (number 564). If you still see this issue in later builds, please let me know.
