### ISSUE TITLE
Game crashes near NPCs

### ISSUE THREAD

**Issue by ashwinmenezes** [MightyPirates/OpenComputers#1082]
Hello! :D 
I'm sort of new to OpenComputers, just installed it yesterday, but I've been tinkering with it a lot.
The game crashed the first time when I exited my house and there was a skeleton in front of me. After that, reloading the map only seems to make it crash again, so I decided to create a new map. This time it crashes when I accidentally run into a sheep, and it won't let me reload the map. So... here's my crash report :3 Please take a look.
Much appreciated,
Ash

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8-1.5.4.9-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 18/04/15 14:21
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at li.cil.oc.util.BlockPosition$.apply(BlockPosition.scala:52)
    at li.cil.oc.client.renderer.HighlightRenderer$.onDrawBlockHighlight(HighlightRenderer.scala:34)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_HighlightRenderer$_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:271)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1321)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1032)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1048)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at li.cil.oc.util.BlockPosition$.apply(BlockPosition.scala:52)
    at li.cil.oc.client.renderer.HighlightRenderer$.onDrawBlockHighlight(HighlightRenderer.scala:34)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_HighlightRenderer$_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:271)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1321)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['6KillaDann6'/282, l='MpServer', x=-25.93, y=72.75, z=138.20]]
    Chunk stats: MultiplayerChunkCache: 210, 210
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -28.00,64.00,148.00 - World: (-28,64,148), Chunk: (at 4,4,4 in -2,9; contains blocks -32,0,144 to -17,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 15772 game time, 15772 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 77 total; [EntityZombie['Zombie'/129, l='MpServer', x=-35.09, y=23.00, z=75.50], EntityWitch['Witch'/386, l='MpServer', x=-23.50, y=31.02, z=126.50], EntitySkeleton['Skeleton'/130, l='MpServer', x=-34.50, y=36.00, z=66.50], EntitySpider['Spider'/131, l='MpServer', x=-36.50, y=23.00, z=83.50], EntityChicken['Chicken'/132, l='MpServer', x=-36.38, y=71.00, z=90.59], EntityItem['item.item.egg'/133, l='MpServer', x=-36.13, y=71.00, z=89.81], EntityBat['Bat'/402, l='MpServer', x=-37.38, y=24.00, z=89.00], EntityBat['Bat'/406, l='MpServer', x=-22.50, y=31.81, z=127.47], EntityBat['Bat'/410, l='MpServer', x=-26.34, y=31.69, z=129.44], EntityChicken['Chicken'/156, l='MpServer', x=-23.50, y=62.00, z=77.50], EntityItem['item.item.egg'/157, l='MpServer', x=-20.13, y=79.00, z=75.00], EntityPlayerSP['6KillaDann6'/282, l='MpServer', x=-25.93, y=72.75, z=138.20], EntityChicken['Chicken'/158, l='MpServer', x=-20.50, y=77.00, z=75.50], EntityItem['item.item.egg'/159, l='MpServer', x=-20.41, y=71.00, z=78.44], EntityChicken['Chicken'/160, l='MpServer', x=-20.50, y=71.00, z=78.50], EntityChicken['Chicken'/161, l='MpServer', x=-22.50, y=71.00, z=78.50], EntitySheep['Sheep'/162, l='MpServer', x=-17.03, y=71.00, z=94.06], EntitySkeleton['Skeleton'/291, l='MpServer', x=-10.50, y=72.02, z=113.50], EntityChicken['Chicken'/163, l='MpServer', x=-30.50, y=71.00, z=93.50], EntityChicken['Chicken'/164, l='MpServer', x=-31.50, y=71.00, z=93.50], EntityChicken['Chicken'/165, l='MpServer', x=-21.72, y=71.00, z=96.44], EntityItem['item.item.egg'/166, l='MpServer', x=-21.78, y=71.00, z=97.03], EntitySheep['Sheep'/167, l='MpServer', x=-26.69, y=72.00, z=139.84], EntitySpider['Spider'/296, l='MpServer', x=-7.50, y=72.02, z=110.50], EntityBat['Bat'/168, l='MpServer', x=-23.56, y=28.91, z=196.59], EntitySpider['Spider'/298, l='MpServer', x=-87.50, y=71.00, z=90.50], EntityZombie['Zombie'/432, l='MpServer', x=-63.50, y=71.02, z=83.50], EntityZombie['Zombie'/434, l='MpServer', x=-61.50, y=71.02, z=88.50], EntitySheep['Sheep'/180, l='MpServer', x=-10.06, y=72.00, z=93.97], EntityCreeper['Creeper'/436, l='MpServer', x=-88.50, y=71.02, z=73.50], EntitySkeleton['Skeleton'/438, l='MpServer', x=-86.50, y=71.02, z=79.50], EntitySpider['Spider'/182, l='MpServer', x=5.81, y=72.00, z=61.41], EntitySheep['Sheep'/183, l='MpServer', x=8.03, y=76.00, z=112.94], EntitySkeleton['Skeleton'/439, l='MpServer', x=-82.50, y=71.02, z=82.50], EntityChicken['Chicken'/60, l='MpServer', x=-100.50, y=75.00, z=167.50], EntityChicken['Chicken'/61, l='MpServer', x=-96.50, y=78.00, z=167.50], EntityChicken['Chicken'/62, l='MpServer', x=-96.50, y=76.00, z=183.50], EntitySpider['Spider'/191, l='MpServer', x=22.50, y=76.00, z=76.50], EntityChicken['Chicken'/63, l='MpServer', x=-99.50, y=76.00, z=182.50], EntityChicken['Chicken'/192, l='MpServer', x=30.50, y=73.00, z=86.50], EntityChicken['Chicken'/64, l='MpServer', x=-97.50, y=76.00, z=182.50], EntityChicken['Chicken'/193, l='MpServer', x=31.50, y=73.00, z=85.50], EntityChicken['Chicken'/65, l='MpServer', x=-96.50, y=76.00, z=181.50], EntityItem['item.item.egg'/194, l='MpServer', x=30.53, y=73.00, z=85.81], EntityItem['item.item.egg'/195, l='MpServer', x=29.53, y=77.00, z=85.53], EntityChicken['Chicken'/69, l='MpServer', x=-103.72, y=75.00, z=206.50], EntityChicken['Chicken'/70, l='MpServer', x=-104.50, y=77.00, z=203.50], EntityChicken['Chicken'/72, l='MpServer', x=-98.38, y=79.00, z=204.38], EntitySheep['Sheep'/201, l='MpServer', x=33.41, y=73.00, z=95.97], EntityItem['item.item.egg'/202, l='MpServer', x=32.34, y=73.00, z=84.97], EntityChicken['Chicken'/203, l='MpServer', x=33.50, y=73.00, z=84.50], EntitySheep['Sheep'/204, l='MpServer', x=39.50, y=75.00, z=92.50], EntitySheep['Sheep'/205, l='MpServer', x=37.53, y=74.00, z=86.03], EntityZombie['Zombie'/461, l='MpServer', x=-92.50, y=69.02, z=141.50], EntityChicken['Chicken'/77, l='MpServer', x=-104.53, y=76.00, z=215.28], EntityChicken['Chicken'/206, l='MpServer', x=33.50, y=80.00, z=86.50], EntitySheep['Sheep'/207, l='MpServer', x=34.50, y=75.00, z=98.66], EntityZombie['Zombie'/463, l='MpServer', x=-92.50, y=69.02, z=144.50], EntityCreeper['Creeper'/465, l='MpServer', x=-92.50, y=69.02, z=139.50], EntitySkeleton['Skeleton'/470, l='MpServer', x=-99.50, y=68.00, z=98.50], EntityCreeper['Creeper'/343, l='MpServer', x=-57.50, y=73.00, z=61.50], EntityBat['Bat'/347, l='MpServer', x=-4.97, y=36.03, z=208.50], EntityChicken['Chicken'/92, l='MpServer', x=-91.53, y=71.00, z=61.25], EntityChicken['Chicken'/96, l='MpServer', x=-94.50, y=72.00, z=166.50], EntityChicken['Chicken'/97, l='MpServer', x=-92.50, y=77.00, z=167.50], EntitySkeleton['Skeleton'/483, l='MpServer', x=-66.50, y=19.02, z=77.50], EntityChicken['Chicken'/100, l='MpServer', x=-93.25, y=77.00, z=193.91], EntitySkeleton['Skeleton'/484, l='MpServer', x=-65.50, y=19.02, z=76.50], EntityChicken['Chicken'/101, l='MpServer', x=-90.50, y=78.00, z=198.50], EntityChicken['Chicken'/102, l='MpServer', x=-91.50, y=77.00, z=193.50], EntitySkeleton['Skeleton'/488, l='MpServer', x=-7.50, y=35.02, z=210.50], EntitySkeleton['Skeleton'/493, l='MpServer', x=6.50, y=31.02, z=95.50], EntitySheep['Sheep'/112, l='MpServer', x=-68.03, y=73.00, z=111.03], EntityCreeper['Creeper'/369, l='MpServer', x=1.50, y=63.02, z=140.50], EntitySheep['Sheep'/113, l='MpServer', x=-71.81, y=75.00, z=119.50], EntitySheep['Sheep'/114, l='MpServer', x=-69.75, y=75.00, z=117.16], EntitySheep['Sheep'/115, l='MpServer', x=-70.19, y=75.00, z=119.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2488)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 208852768 bytes (199 MB) / 512495616 bytes (488 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.42.1339 Minecraft Forge 11.14.1.1339 5 mods loaded, 5 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{8.0.42.1339} [Forge Mod Loader] (forge-1.8-11.14.1.1339.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{11.14.1.1339} [Minecraft Forge] (forge-1.8-11.14.1.1339.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.5.4.9} [OpenComputers] (OpenComputers-MC1.8-1.5.4.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8-1.5.4.9-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
    Launched Version: 1.8-Forge11.14.1.1339
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3412, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [default3dmodelsv188440793.zip]
    Current Language: English (US)
    Profiler Position: N/A (disabled)
```

**Comment by fnuecke** [comment]
Please update OC. This has been fixed a few versions back.

**Comment by ashwinmenezes** [comment]
Thanks a bunch!!!
I think this happened because I downloaded this from skydaz.com... 
Sorry! ^^,

**Comment by gjgfuj** [comment]
Never download mods from skydaz.com. you don't need to ever.

**Comment by ashwinmenezes** [comment]
Alright thanks :D
