### ISSUE TITLE
OpenComputers-dev75 - component

### ISSUE THREAD

**Issue by TheRealKANi** [MightyPirates/OpenComputers#110]
Hi again..
When ever im trying to utilize component.'whatever' it gives me an error.
![2014-01-30_20 55 50](https://f.cloud.github.com/assets/1286819/2044252/91845c0e-89e8-11e3-859e-ac4119c051ac.png)

My server console gives me this:

``` java
2014-01-30 20:52:14 [WARNING] [OpenComputers] Exception in Lua callback.
java.io.FileNotFoundException
    at li.cil.oc.server.fs.InputStreamFileSystem$class.open(InputStreamFileSystem.scala:34)
    at li.cil.oc.server.fs.FileSystem$BufferedFileSystem.li$cil$oc$server$fs$OutputStreamFileSystem$$super$open(FileSystem.scala:100)
    at li.cil.oc.server.fs.OutputStreamFileSystem$class.open(OutputStreamFileSystem.scala:19)
    at li.cil.oc.server.fs.FileSystem$BufferedFileSystem.open(FileSystem.scala:100)
    at li.cil.oc.server.component.FileSystem.open(Filesystem.scala:121)
    at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at li.cil.oc.server.network.Component$Callback.apply(Component.scala:146)
    at li.cil.oc.server.network.Component$class.invoke(Component.scala:75)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.invoke(Network.scala:464)
    at li.cil.oc.server.component.machine.Machine.invoke(Machine.scala:214)
    at li.cil.oc.server.component.machine.NativeLuaArchitecture$$anonfun$init$23.apply(NativeLuaArchitecture.scala:465)
    at li.cil.oc.server.component.machine.NativeLuaArchitecture$$anonfun$init$23.apply(NativeLuaArchitecture.scala:460)
    at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:17)
    at com.naef.jnlua.LuaState.lua_pcall(Native Method)
    at com.naef.jnlua.LuaState.call(LuaState.java:669)
    at li.cil.oc.server.component.machine.NativeLuaArchitecture.runSynchronized(NativeLuaArchitecture.scala:55)
    at li.cil.oc.server.component.machine.Machine.liftedTree1$1(Machine.scala:359)
    at li.cil.oc.server.component.machine.Machine.update(Machine.scala:358)
    at li.cil.oc.common.tileentity.Computer.func_70316_g(Computer.scala:104)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:317)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:115)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

```

WTF..?

**Comment by TheRealKANi** [comment]
PS.. term.clear() not working in scripts either.. both component and term.clear works fine in LUA prompt.. Nothing in server console with term.clear() but on screen:
![2014-01-30_21 02 12](https://f.cloud.github.com/assets/1286819/2044309/7ac61df8-89e9-11e3-9336-ccd99de59b4e.png)

**Comment by fnuecke** [comment]
The file not found thing is probably because it looks for some file that doesn't exist. Note that these warnings in Lua callbacks are usually completely normal, they're just part of the control flow.

As for the component is nil thingy, starting with 1.2 anything that's not standard Lua has to be "required" (i.e. in your scripts you add `local component = require("component")` at the start as you would in normal Lua 5.2), since we finally have a reimplementation of the package module, and I'd like to keep things as "real Lua"-ish as possible. I'm aware it's confusing when coming from 1.1. There'll be a "what changed in 1.2" thing once it's ready for beta/release where this change will be prominently featured.

**Comment by TheRealKANi** [comment]
I like your thinking about keeping the system pure.. ;-)
