### ISSUE TITLE
Disassembler Issue

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#1107]
Playing with the Disassembler in a SSP world with OpenComputers 1.57, saw this:

```
Whoops, something went wrong when trying to figure out an item's parts.
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lnet.minecraft.item.ItemStack;
    at li.cil.oc.util.ItemUtils$.getIngredients(ItemUtils.scala:71) [ItemUtils$.class:?]
    at li.cil.oc.common.tileentity.Disassembler.func_94041_b(Disassembler.scala:162) [Disassembler.class:?]
    at net.minecraft.tileentity.TileEntityHopper.func_145885_a(TileEntityHopper.java:503) [api.class:?]
    at net.minecraft.tileentity.TileEntityHopper.func_145899_c(TileEntityHopper.java:515) [api.class:?]
    at net.minecraft.tileentity.TileEntityHopper.func_145889_a(TileEntityHopper.java:489) [api.class:?]
    at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:288) [api.class:?]
    at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:205) [api.class:?]
    at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:190) [api.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
```

I had TNT in Hopper going to Disassembler. I believe arrows and a few other vanilla items gave the same or similar

**Comment by fnuecke** [comment]
~~Is this with `disassembleAllTheThings` enabled or not?
(AKA is the check for which items can be inserted broken or just the cost computation.)~~
NVM, could reproduce, fixed it.
