### ISSUE TITLE
Enhanced Portals Issue

### ISSUE THREAD

**Issue by tlf30** [MightyPirates/OpenComputers#1121]
I am not sure if I should post this issue here or in the EnhancedPortals GitHub, but I am getting this error on server start:

```
[12:58:38] [Server thread/TRACE] [OpenComputers/enhancedportals]: Injecting interface.
[12:58:38] [Server thread/WARN] [OpenComputers/enhancedportals]: Failed injecting component logic into class enhancedportals.tileentity.TileController.
java.lang.RuntimeException: java.lang.ClassNotFoundException: enhancedportals.portal.PortalException
    at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at li.cil.oc.common.asm.ClassTransformer.writeClass(ClassTransformer.scala:380) ~[OpenComputers-MC1.7.10-1.5.9.21-universal.jar:?]
    at li.cil.oc.common.asm.ClassTransformer.injectEnvironmentImplementation(ClassTransformer.scala:348) ~[OpenComputers-MC1.7.10-1.5.9.21-universal.jar:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:138) [OpenComputers-MC1.7.10-1.5.9.21-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) [?:1.7.0_79]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) [?:1.7.0_79]
    at enhancedportals.network.CommonProxy.registerBlocks(CommonProxy.java:104) [CommonProxy.class:?]
    at enhancedportals.EnhancedPortals.preInit(EnhancedPortals.java:116) [EnhancedPortals.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533) [Loader.class:?]
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[12:58:38] [Server thread/TRACE] [FML/enhancedportals]: Optional removal - found optionals for class enhancedportals.tileentity.TileController - processing
[12:58:38] [Server thread/TRACE] [FML/enhancedportals]: Optional removal skipped - mod present OpenComputers
```

**Comment by fnuecke** [comment]
Can't reproduce. Forge version? Does this also happen if OC and EP are the only two mods loaded?

**Comment by tlf30** [comment]
I am using the latest version of forge: 10.13.3.1399, which is the only thing that has change in the mod pack.

**Comment by fnuecke** [comment]
Ah, looks like the made a somewhat breaking change. There's even an issue on this on FML, luckily with a description of a workaround...

**Comment by fnuecke** [comment]
[Build 613](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) should fix this issue, confirmation would be appreciated.
