### ISSUE TITLE
[SimpleComponent] Message

### ISSUE THREAD

**Issue by Dream-Master** [MightyPirates/OpenComputers#1166]
I get this in my Console. (using Forge 1407 and Open computers  1.5.10.22)

§aOpenComputers§f: An addon (yours?) using the §aSimpleComponent§f interface did §esomething wrong§f. Component logic could not be injected. Please check your log file for more information.

I look inside the log but i don't find it.

Last Log:
https://gist.github.com/Dream-Master/b64ffafdc818457ec60e#file-gistfile1-txt

Last fml log
https://gist.github.com/Dream-Master/e4db21da1f9913bf5c6c#file-gistfile1-txt

Is this a serious bug?

**Comment by gjgfuj** [comment]
The game log please, like, the log that the launcher, (whatever it is)
gives you while its running. Also, it'd be a bug with an add-on not oc, can
you give a list of any mods you've got with oc integration that you know of?

**Comment by fnuecke** [comment]
The relevant part from the log, for future reference:

```
[11:15:49] [Client thread/WARN] [OpenComputers/ThaumicTinkerer]: Failed injecting component logic into class thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.
java.lang.NullPointerException
    at li.cil.oc.common.asm.ClassTransformer.isFinal(ClassTransformer.scala:368) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
    at li.cil.oc.common.asm.ClassTransformer.isAssignable(ClassTransformer.scala:360) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
    at li.cil.oc.common.asm.ClassTransformer$$anon$1.getCommonSuperClass(ClassTransformer.scala:396) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
    at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at li.cil.oc.common.asm.ClassTransformer.writeClass(ClassTransformer.scala:408) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
    at li.cil.oc.common.asm.ClassTransformer.injectEnvironmentImplementation(ClassTransformer.scala:348) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:138) [OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_45]
    at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:266) [guava-16.0.jar:?]
    at thaumic.tinkerer.common.registry.TTRegistry.registerClasses(TTRegistry.java:36) [TTRegistry.class:?]
    at thaumic.tinkerer.common.registry.TTRegistry.preInit(TTRegistry.java:66) [TTRegistry.class:?]
    at thaumic.tinkerer.common.core.proxy.TTCommonProxy.preInit(TTCommonProxy.java:88) [TTCommonProxy.class:?]
    at thaumic.tinkerer.client.core.proxy.TTClientProxy.preInit(TTClientProxy.java:75) [TTClientProxy.class:?]
    at thaumic.tinkerer.common.ThaumicTinkerer.preInit(ThaumicTinkerer.java:66) [ThaumicTinkerer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:241) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

I'll look into it.

**Comment by fnuecke** [comment]
Please try the [latest build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) (636+), see if that fixes it.

This was introduced in the workaround for the Forge versions that broke class transformers. I'm not sure how what's `null` here can be `null`, but I'm trying to handle that now.

**Comment by Dream-Master** [comment]
Ok Error is gone thanks.

Is this version stable enough to use this on Servers ?

**Comment by fnuecke** [comment]
Yes, it's just as stable as the release! I'll probably push it as a hotfix soon, too. Thanks for confirming.

**Comment by Dream-Master** [comment]
Thank you!
