### ISSUE TITLE
Game crashed when I tried to turn a computer on

### ISSUE THREAD

**Issue by vilu85** [MightyPirates/OpenComputers#1192]
Everything has worked fine until now. Suddenly when I turned the new computer on for the first time, the game crashed and there is this text in the console output which says that I should report this. Here are console output and stacktrace that I got after turning computer on:

```
    [09:19:27] [Server thread/WARN] [OpenComputers]: There was a problem writing a TileEntity description packet. Please report this if you see it!
    java.lang.NullPointerException
        at li.cil.oc.server.network.Node$class.connect(Node.scala:39) ~[Node$class.class:?]
        at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.connect(Network.scala:626) ~[Network$ComponentConnectorBuilder$$anon$1.class:?]
        at li.cil.oc.common.tileentity.Microcontroller.connectItemNode(Microcontroller.scala:135) ~[Microcontroller.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$3.applyOrElse(ComponentInventory.scala:73) ~[ComponentInventory$$anonfun$connectComponents$3.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$3.applyOrElse(ComponentInventory.scala:72) ~[ComponentInventory$$anonfun$connectComponents$3.class:?]
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136) ~[PartialFunction$$anonfun$runWith$1.class:?]
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135) ~[PartialFunction$$anonfun$runWith$1.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[IndexedSeqOptimized$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
        at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282) ~[TraversableLike$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.collect(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.connectComponents(ComponentInventory.scala:72) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Microcontroller.connectComponents(Microcontroller.scala:25) ~[Microcontroller.class:?]
        at li.cil.oc.common.tileentity.traits.ComponentInventory$class.writeToNBTForClient(ComponentInventory.scala:30) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Microcontroller.li$cil$oc$common$tileentity$traits$RedstoneAware$$super$writeToNBTForClient(Microcontroller.scala:25) ~[Microcontroller.class:?]
        at li.cil.oc.common.tileentity.traits.RedstoneAware$class.writeToNBTForClient(RedstoneAware.scala:118) ~[RedstoneAware$class.class:?]
        at li.cil.oc.common.tileentity.Microcontroller.li$cil$oc$common$tileentity$traits$Computer$$super$writeToNBTForClient(Microcontroller.scala:25) ~[Microcontroller.class:?]
        at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBTForClient(Computer.scala:166) ~[Computer$class.class:?]
        at li.cil.oc.common.tileentity.Microcontroller.writeToNBTForClient(Microcontroller.scala:219) ~[Microcontroller.class:?]
        at li.cil.oc.common.tileentity.traits.TileEntity$class.getDescriptionPacket(TileEntity.scala:101) [TileEntity$class.class:?]
        at li.cil.oc.common.tileentity.Microcontroller.func_145844_m(Microcontroller.scala:25) [Microcontroller.class:?]
        at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:594) [qr.class:?]
        at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:535) [qr.class:?]
        at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:69) [qq.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223) [qt.class:?]
        at WorldServerOF.func_72835_b(WorldServerOF.java:37) [WorldServerOF.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:692) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258) [cyk.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
    [09:19:36] [Client thread/INFO]: [CHAT] §6Last error§f: no bios found; install a configured EEPROM
    [09:19:36] [Client thread/INFO]: [CHAT] §6Number of connected components§f: 1/8
    [09:19:36] [Client thread/INFO]: [CHAT] §6Total stored energy§f: 0,00/1000,00
    [09:19:36] [Client thread/INFO]: [CHAT] §6Component name§f: computer
    [09:19:36] [Client thread/INFO]: [CHAT] §6Address§f: ea4f8db2-e92d-48ad-9c4d-e46bc06b11db
    [09:20:21] [Client thread/INFO]: [CHAT] §6Number of connected components§f: 4/8
    [09:20:21] [Client thread/INFO]: [CHAT] §6Total stored energy§f: 0,00/1000,00
    [09:20:21] [Client thread/INFO]: [CHAT] §6Component name§f: computer
    [09:20:21] [Client thread/INFO]: [CHAT] §6Address§f: 3dac9001-2b7b-44f9-b303-b127cdd6493d
    [09:20:38] [Server thread/INFO]: Saving and pausing game...
    [09:20:38] [Server thread/INFO]: Saving chunks for level '1.8test'/Overworld
    [09:20:39] [Server thread/INFO]: Saving chunks for level '1.8test'/Nether
    [09:20:39] [Server thread/INFO]: Saving chunks for level '1.8test'/The End
    [09:20:55] [Server thread/INFO]: Saving and pausing game...
    [09:20:55] [Server thread/INFO]: Saving chunks for level '1.8test'/Overworld
    [09:20:56] [Server thread/INFO]: Saving chunks for level '1.8test'/Nether
    [09:20:56] [Server thread/INFO]: Saving chunks for level '1.8test'/The End
    [09:43:22] [Server thread/INFO]: Stopping server
    [09:43:22] [Server thread/INFO]: Saving players
    [09:43:22] [Server thread/INFO]: Saving worlds
    [09:43:22] [Server thread/INFO]: Saving chunks for level '1.8test'/Overworld
    [09:43:22] [Server thread/INFO]: Saving chunks for level '1.8test'/Nether
    [09:43:22] [Server thread/INFO]: Saving chunks for level '1.8test'/The End
    [09:43:25] [Server thread/INFO] [FML]: Unloading dimension 0
    [09:43:25] [Server thread/INFO] [FML]: Unloading dimension -1
    [09:43:25] [Server thread/INFO] [FML]: Unloading dimension 1
    [09:43:25] [Server thread/INFO] [FML]: Applying holder lookups
    [09:43:25] [Server thread/INFO] [FML]: Holder lookups applied
    [09:43:27] [Client thread/FATAL]: Unreported exception thrown!
    java.util.ConcurrentModificationException
        at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339) ~[guava-17.0.jar:?]
        at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345) ~[guava-17.0.jar:?]
        at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:239) ~[cza.class:?]
        at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195) ~[czh.class:?]
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2100) ~[bsu.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028) ~[bsu.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    [09:43:27] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:571]: ---- Minecraft Crash Report ----
    // Surprise! Haha. Well, this is awkward.

    Time: 31.5.2015 9:43
    Description: Unexpected error

    java.util.ConcurrentModificationException
        at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
        at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
        at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:239)
        at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2100)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
        at net.minecraft.client.main.Main.main(SourceFile:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------

    -- Head --
    Stacktrace:
        at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
        at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
        at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:239)
        at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195)

    -- Affected level --
    Details:
        Level name: MpServer
        All players: 1 total; [EntityPlayerSP['vilu'/95, l='MpServer', x=2032,87, y=91,00, z=-1676,91]]
        Chunk stats: MultiplayerChunkCache: 1089, 1089
        Level seed: 0
        Level generator: ID 00 - default, ver 1. Features enabled: false
        Level generator options: 
        Level spawn location: -104,00,64,00,244,00 - World: (-104,64,244), Chunk: (at 8,4,4 in -7,15; contains blocks -112,0,240 to -97,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Level time: 2914096 game time, 2926096 day time
        Level dimension: 0
        Level storage version: 0x00000 - Unknown?
        Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
        Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
        Forced entities: 86 total; [EntityMimic['Mimic'/128, l='MpServer', x=2028,50, y=50,00, z=-1666,50], EntityMimic['Mimic'/129, l='MpServer', x=2026,50, y=50,00, z=-1666,50], EntityMimic['Mimic'/263, l='MpServer', x=1994,50, y=19,00, z=-1698,50], EntityMimic['Mimic'/136, l='MpServer', x=2036,50, y=53,00, z=-1602,50], EntitySheep['Sheep'/264, l='MpServer', x=1984,38, y=77,00, z=-1710,38], EntityMimic['Mimic'/137, l='MpServer', x=2017,50, y=35,00, z=-1624,50], EntitySheep['Sheep'/265, l='MpServer', x=1985,53, y=77,00, z=-1709,66], EntityMimic['Mimic'/138, l='MpServer', x=2039,50, y=42,00, z=-1706,50], EntitySheep['Sheep'/266, l='MpServer', x=2020,34, y=71,00, z=-1735,84], EntitySheep['Sheep'/139, l='MpServer', x=2043,66, y=75,00, z=-1706,47], EntityCreeper['Creeper'/51979, l='MpServer', x=1994,50, y=32,00, z=-1733,50], EntityMimic['Mimic'/270, l='MpServer', x=1977,50, y=13,00, z=-1659,50], EntityMimic['Mimic'/271, l='MpServer', x=1983,50, y=33,00, z=-1650,50], EntitySkeleton['Skeleton'/50195, l='MpServer', x=1987,50, y=70,00, z=-1717,50], EntitySheep['Sheep'/148, l='MpServer', x=2097,53, y=70,00, z=-1698,59], EntityHorse['Donkey'/149, l='MpServer', x=2110,00, y=70,00, z=-1703,06], EntitySkeleton['Skeleton'/50197, l='MpServer', x=1993,50, y=70,00, z=-1715,50], EntityHorse['Donkey'/151, l='MpServer', x=2113,94, y=69,00, z=-1687,88], EntityMimic['Mimic'/159, l='MpServer', x=2099,50, y=20,00, z=-1605,50], EntityMimic['Mimic'/160, l='MpServer', x=2101,50, y=20,00, z=-1604,50], EntityChicken['Chicken'/289, l='MpServer', x=1980,59, y=70,00, z=-1638,31], EntityChicken['Chicken'/290, l='MpServer', x=1977,63, y=70,00, z=-1645,34], EntityBat['Bat'/48802, l='MpServer', x=1970,52, y=12,86, z=-1671,46], EntityMimic['Mimic'/291, l='MpServer', x=1983,50, y=17,00, z=-1675,50], EntityBat['Bat'/51747, l='MpServer', x=2061,25, y=18,00, z=-1723,50], EntityChicken['Chicken'/164, l='MpServer', x=2001,25, y=72,00, z=-1648,63], EntityMimic['Mimic'/292, l='MpServer', x=1979,50, y=31,00, z=-1679,50], EntityMimic['Mimic'/165, l='MpServer', x=2065,50, y=21,00, z=-1725,50], EntityMimic['Mimic'/293, l='MpServer', x=1977,50, y=24,00, z=-1678,50], EntitySheep['Sheep'/166, l='MpServer', x=2075,94, y=72,00, z=-1712,97], EntityMimic['Mimic'/294, l='MpServer', x=1979,50, y=37,00, z=-1667,50], EntityMimic['Mimic'/167, l='MpServer', x=2011,50, y=22,00, z=-1647,50], EntityMimic['Mimic'/168, l='MpServer', x=2002,50, y=27,00, z=-1671,50], EntityMimic['Mimic'/169, l='MpServer', x=2048,50, y=34,00, z=-1716,50], EntityMimic['Mimic'/170, l='MpServer', x=2055,50, y=32,00, z=-1721,50], EntityChicken['Chicken'/298, l='MpServer', x=1978,50, y=70,00, z=-1628,69], EntityMimic['Mimic'/171, l='MpServer', x=2058,50, y=32,00, z=-1723,50], EntityMimic['Mimic'/172, l='MpServer', x=2080,50, y=10,00, z=-1720,50], EntityRabbit['Rabbit'/300, l='MpServer', x=2045,25, y=73,00, z=-1745,63], EntityMimic['Mimic'/173, l='MpServer', x=2093,50, y=11,00, z=-1723,50], EntityRabbit['Rabbit'/301, l='MpServer', x=2044,16, y=73,00, z=-1748,59], EntityMimic['Mimic'/176, l='MpServer', x=2021,50, y=51,00, z=-1602,50], EntityMimic['Mimic'/178, l='MpServer', x=2002,50, y=32,00, z=-1616,50], EntityMimic['Mimic'/179, l='MpServer', x=2005,50, y=21,00, z=-1690,50], EntityMimic['Mimic'/180, l='MpServer', x=2006,50, y=21,00, z=-1692,50], EntityCreeper['Creeper'/52277, l='MpServer', x=2009,50, y=27,00, z=-1722,50], EntityMimic['Mimic'/182, l='MpServer', x=2046,50, y=36,00, z=-1714,50], EntityBat['Bat'/48566, l='MpServer', x=2099,71, y=31,86, z=-1752,29], EntitySkeleton['Skeleton'/52279, l='MpServer', x=2007,50, y=27,00, z=-1719,50], EntitySkeleton['Skeleton'/52280, l='MpServer', x=2010,50, y=27,00, z=-1718,50], EntitySkeleton['Skeleton'/52281, l='MpServer', x=2013,50, y=27,00, z=-1716,50], EntitySkeleton['Skeleton'/45499, l='MpServer', x=1966,50, y=70,00, z=-1637,50], EntityMimic['Mimic'/319, l='MpServer', x=1967,50, y=52,00, z=-1618,50], EntityMimic['Mimic'/320, l='MpServer', x=1967,50, y=29,00, z=-1680,50], EntitySquid['Squid'/49217, l='MpServer', x=2083,47, y=61,16, z=-1619,78], EntitySquid['Squid'/49218, l='MpServer', x=2090,03, y=62,00, z=-1623,53], EntitySquid['Squid'/49219, l='MpServer', x=2086,97, y=62,06, z=-1623,03], EntitySquid['Squid'/49220, l='MpServer', x=2090,25, y=62,19, z=-1615,31], EntityCreeper['Creeper'/48840, l='MpServer', x=1967,50, y=67,00, z=-1650,50], EntityCreeper['Creeper'/48843, l='MpServer', x=2026,53, y=71,00, z=-1709,69], EntityMimic['Mimic'/204, l='MpServer', x=2108,50, y=14,00, z=-1714,50], EntityMimic['Mimic'/210, l='MpServer', x=2076,50, y=32,00, z=-1734,50], EntityZombie['Zombie'/48850, l='MpServer', x=2097,50, y=22,02, z=-1602,50], EntityMimic['Mimic'/211, l='MpServer', x=2068,50, y=33,00, z=-1728,50], EntityMimic['Mimic'/212, l='MpServer', x=2075,50, y=59,00, z=-1741,50], EntityBat['Bat'/50399, l='MpServer', x=1993,01, y=23,69, z=-1750,25], EntityMimic['Mimic'/224, l='MpServer', x=1989,50, y=20,00, z=-1678,50], EntityPlayerSP['vilu'/95, l='MpServer', x=2032,87, y=91,00, z=-1676,91], EntityBat['Bat'/50402, l='MpServer', x=1992,27, y=23,16, z=-1750,02], EntityArmorStand['Armor Stand'/99, l='MpServer', x=2065,50, y=94,00, z=-1672,50], EntityArmorStand['Armor Stand'/100, l='MpServer', x=2064,50, y=94,00, z=-1672,50], Drone['Drone'/102, l='MpServer', x=2058,78, y=95,00, z=-1667,38], EntityArmorStand['Armor Stand'/104, l='MpServer', x=2062,50, y=94,00, z=-1672,50], EntityArmorStand['Armor Stand'/105, l='MpServer', x=2061,50, y=94,00, z=-1672,50], EntityArmorStand['Armor Stand'/106, l='MpServer', x=2063,50, y=94,00, z=-1672,50], EntitySheep['Sheep'/107, l='MpServer', x=2066,06, y=75,00, z=-1701,00], EntitySheep['Sheep'/113, l='MpServer', x=2088,06, y=71,00, z=-1695,97], EntitySpider['Spider'/50161, l='MpServer', x=2106,50, y=70,00, z=-1695,50], EntityCreeper['Creeper'/50163, l='MpServer', x=2102,50, y=70,00, z=-1683,19], EntitySheep['Sheep'/116, l='MpServer', x=2104,91, y=70,00, z=-1694,13], EntityHorse['Donkey'/117, l='MpServer', x=2102,38, y=70,00, z=-1684,78], EntityRabbit['Rabbit'/246, l='MpServer', x=2056,06, y=73,00, z=-1741,66], EntityMimic['Mimic'/121, l='MpServer', x=2021,50, y=50,00, z=-1646,50], EntitySpider['Spider'/51964, l='MpServer', x=2059,50, y=69,00, z=-1616,50], EntityMimic['Mimic'/253, l='MpServer', x=1996,50, y=17,00, z=-1693,50], EntityMimic['Mimic'/254, l='MpServer', x=1994,50, y=20,00, z=-1684,50]]
        Retry entities: 0 total; []
        Server brand: fml,forge
        Server type: Integrated singleplayer server
    Stacktrace:
        at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:399)
        at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2501)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
        at net.minecraft.client.main.Main.main(SourceFile:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

    -- System Details --
    Details:
        Minecraft Version: 1.8
        Operating System: Windows 7 (amd64) version 6.1
        Java Version: 1.8.0_45, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 425670400 bytes (405 MB) / 932294656 bytes (889 MB) up to 1060372480 bytes (1011 MB)
        JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
        FML: MCP v9.10 FML v8.99.18.1419 Minecraft Forge 11.14.1.1419 Optifine OptiFine_1.8_HD_U_D1 6 mods loaded, 6 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{8.99.18.1419} [Forge Mod Loader] (forge-1.8-11.14.1.1419.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge{11.14.1.1419} [Minecraft Forge] (forge-1.8-11.14.1.1419.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        newmobs{0.7.4} [New mobs] (newmobs-1.8-0.7.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenComputers{1.5.12.29} [OpenComputers] (OpenComputers-MC1.8-1.5.12.29-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Loaded coremods (and transformers): 
    TransformerLoader (OpenComputers-MC1.8-1.5.12.29-universal.jar)
      li.cil.oc.common.asm.ClassTransformer
    NewmobsLoadingPlugin (newmobs-1.8-0.7.4.jar)
      mod.vilu.newmobs.asm.NewmobsTransformer
        Launched Version: 1.8-Forge11.14.1.1419
        LWJGL: 2.9.1
        OpenGL: GeForce 610M/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
        GL Caps: Using GL 1.3 multitexturing.
    Using GL 1.3 texture combiners.
    Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
    Shaders are available because OpenGL 2.1 is supported.
    VBOs are available because OpenGL 1.5 is supported.

        Using VBOs: No
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs: []
        Current Language: English (US)
        Profiler Position: N/A (disabled)
    [09:43:27] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:571]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\vilu\AppData\Roaming\.minecraft\crash-reports\crash-2015-05-31_09.43.27-client.txt
```

**Comment by fnuecke** [comment]
Please try [build 158](http://ci.cil.li/job/OpenComputers-dev-MC1.8/), this _should_ be fixed in that and newer builds. If it isn't, please let me know here. Thanks.

**Comment by gamax92** [comment]
Still able to reproduce the SoundManager crash, running latest dev version of 1.8

```
java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:239)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2093)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1021)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by fnuecke** [comment]
With OC only? If that didn't fix it, I don't know what else in OC it could be. That was the only place the sound system was accessed from a different thread as far as I'm aware.

**Comment by jadenquinn** [comment]
I got the crash too on 1.7.10. Anyone have a fix?

**Comment by ff66theone** [comment]
With the same error ? Can you send the logs please ? (debug and latest)
Can you try with only OC installed ? (no Optifine or other optimization mods)
