### ISSUE TITLE
Problems with old CPUs from before the Lua 5.3 update

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1213]
Tried to start one of my computers, which immediately shut down again and produced this:

```
[Netty Server IO #1/WARN] [OpenComputers]: Received a badly formatted packet.
java.lang.InstantiationException
    at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_45]
    at li.cil.oc.server.machine.Machine$$anonfun$onHostChanged$4.apply(Machine.scala:128) ~[Machine$$anonfun$onHostChanged$4.class:?]
    at li.cil.oc.server.machine.Machine$$anonfun$onHostChanged$4.apply(Machine.scala:122) ~[Machine$$anonfun$onHostChanged$4.class:?]
    at scala.collection.Iterator$class.find(Iterator.scala:796) ~[Iterator$class.class:?]
    at scala.collection.AbstractIterator.find(Iterator.scala:1174) ~[AbstractIterator.class:?]
    at scala.collection.IterableLike$class.find(IterableLike.scala:79) ~[IterableLike$class.class:?]
    at scala.collection.AbstractIterable.find(Iterable.scala:54) ~[AbstractIterable.class:?]
    at li.cil.oc.server.machine.Machine.onHostChanged(Machine.scala:122) ~[Machine.class:?]
    at li.cil.oc.server.machine.Machine.start(Machine.scala:194) ~[Machine.class:?]
    at li.cil.oc.server.PacketHandler$.trySetComputerPower(PacketHandler.scala:104) ~[PacketHandler$.class:?]
    at li.cil.oc.server.PacketHandler$.onComputerPower(PacketHandler.scala:66) ~[PacketHandler$.class:?]
    at li.cil.oc.server.PacketHandler$.dispatch(PacketHandler.scala:39) ~[PacketHandler$.class:?]
    at li.cil.oc.common.PacketHandler.onPacketData(PacketHandler.scala:33) [PacketHandler.class:?]
    at li.cil.oc.server.PacketHandler$.onPacket(PacketHandler.scala:32) [PacketHandler$.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_90_PacketHandler$_onPacket_ServerCustomPacketEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at net.minecraftforge.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:105) [FMLEventChannel.class:?]
    at net.minecraftforge.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:32) [NetworkEventFiringHandler.class:?]
    at net.minecraftforge.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:20) [NetworkEventFiringHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) [SimpleChannelInboundHandler.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:4.0.15.Final]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:4.0.15.Final]
    at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:79) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:136) [gr.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:414) [gr.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) [SimpleChannelInboundHandler.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:418) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:242) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:50) [NetworkDispatcher.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) [SimpleChannelInboundHandler.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) [DefaultChannelHandlerContext.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) [DefaultChannelHandlerContext.class:4.0.15.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:4.0.15.Final]
    at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:312) [LocalChannel.class:4.0.15.Final]
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:44) [LocalChannel.class:4.0.15.Final]
    at io.netty.channel.local.LocalChannel$6.run(LocalChannel.java:298) [LocalChannel$6.class:4.0.15.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:4.0.15.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [NioEventLoop.class:4.0.15.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:4.0.15.Final]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```

The problem was the boot HDD - when I took it out of the case, I got this:

```
[Server thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.InstantiationException
java.util.concurrent.ExecutionException: java.lang.InstantiationException
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_45]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_45]
    at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258) [cyk.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.InstantiationException
    at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_45]
    at li.cil.oc.server.machine.Machine$$anonfun$onHostChanged$4.apply(Machine.scala:128) ~[Machine$$anonfun$onHostChanged$4.class:?]
    at li.cil.oc.server.machine.Machine$$anonfun$onHostChanged$4.apply(Machine.scala:122) ~[Machine$$anonfun$onHostChanged$4.class:?]
    at scala.collection.Iterator$class.find(Iterator.scala:796) ~[Iterator$class.class:?]
    at scala.collection.AbstractIterator.find(Iterator.scala:1174) ~[AbstractIterator.class:?]
    at scala.collection.IterableLike$class.find(IterableLike.scala:79) ~[IterableLike$class.class:?]
    at scala.collection.AbstractIterable.find(Iterable.scala:54) ~[AbstractIterable.class:?]
    at li.cil.oc.server.machine.Machine.onHostChanged(Machine.scala:122) ~[Machine.class:?]
    at li.cil.oc.common.tileentity.traits.Computer$class.markDirty(Computer.scala:176) ~[Computer$class.class:?]
    at li.cil.oc.common.tileentity.Case.func_70296_d(Case.scala:19) ~[Case.class:?]
    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:74) ~[ajk.class:?]
    at li.cil.oc.common.container.ComponentSlot.func_75218_e(ComponentSlot.scala:52) ~[ComponentSlot.class:?]
    at net.minecraft.inventory.Container.func_75144_a(Container.java:380) ~[aib.class:?]
    at li.cil.oc.common.container.Player.func_75144_a(Player.scala:36) ~[Player.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:978) ~[rj.class:?]
    at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:31) ~[ma.class:?]
    at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:9) ~[ma.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_45]
    at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
    ... 5 more
```

At some point the HDD item disappeared entirely. The files are still in the world folder, so I didn't lose any data.

Version info:
- Oracle JRE 1.8.0_45 x64
- Minecraft 1.8
- Forge 11.14.3.1446
- OpenComputers 1.5.13.164-dev (currently newest dev build)
- Optifine 1.8_HD_U_D3 (probably not important)

**Comment by fnuecke** [comment]
No clue why that'd affect the HDD (sure it's not a graphical glitch?), but could you try resetting the CPU's architecture (sneak-rightclick while holding it in hand). If that helps I know what it is.

**Comment by dgelessus** [comment]
Okay, it seems that after I try to boot with the broken CPU, every time I take an item out of the case I get the second traceback, and sometimes the item positions desync and somehow some of the items disappear. o_O

The CPU's architecture is set to native Lua, the NBT data looks like this: `{"oc:archClass": "li.cil.oc.server.machine.luac.NativeLuaArchitecture", "oc:archName": "Lua"}`

Interestingly when I first shitf-right-clicked the CPU it first switched to Lua 5.2, even though that was already the active arch and it should have gone to LuaJ (which I have enabled in the config). Now the NBT data is `{"oc:archClass": "li.cil.oc.server.machine.luac.NativeLua52Architecture", "oc:archName": "Lua 5.2"}`. So I guess the migration from "versionless native Lua" to "native Lua 5.2" didn't go as it should have?

**Comment by fnuecke** [comment]
Yeah, that's exactly what I was expecting. Is the item issue gone after adjusting the arch?

**Comment by dgelessus** [comment]
The inventory desync only happened after I tried to power on the computer with the broken CPU. Before I did that the inventories worked fine, and reopening the GUI resyncs the inventory data (duh).
