### ISSUE TITLE
Can't craft or give EEPROM, "unbalaned quotation"

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1300]
I tried crafting an EEPROM, but it didn't work when I tried turning on the computer. I tried making it into a Lua BIOS with a book in a crafting table, but that didn't work either. The recipes for both items are exactly the same in NEI. I also tried OPing myself and /giving the Lua BIOS, but it told me there was an "unbalanced quotation".

All the errors are here:
http://i.imgur.com/STDuZqO.png

If it has anything to do with it, none of the several hosts I have tried have supported persistence, and I got tired of canceling and trying new ones to find one that does. I have tried downloading the latest version and have also deleted the config to no avail. At this point, the mod is non-functional for me.

**Comment by gjgfuj** [comment]
You're crafting it with the OC manual and not just a regular book right?

**Comment by ghost** [comment]
Nope. Got it to work now. Actually tried it and came back to see there was already a reply. All the wikis I have seen show a regular book, and NEI was no help. OK, so it boots alright. Any possibility anyone has an idea why persistence isn't working? I've tried a few hosts, but so far every one has thrown the error about not persisting.

**Comment by makkarpov** [comment]
Is OpenComputers complaining about LuaJ fallback in console?

AFAIK, OpenComputers tries to unpack it's native library into system /tmp and fallbacks to LuaJ if it's failed.

**Comment by ghost** [comment]
Just says "native libraries not available" to me when I join. The logs say unsupported platform. Both BeastNode and MPserv, two of the highest ranked hosts have this problem, and neither one could figure out what the problem was.

**Comment by makkarpov** [comment]
Please check that your server root directory (not system `/`, but a place where you installed server) is writable. OC extracts it's native library as `<server root>/OpenComputersMod-VERSION-native.ARCH.so`

**Comment by makkarpov** [comment]
Oh, didn't read about `Unsupported platform`. Which one? It works perfectly on Linux & Windows.

**Comment by ghost** [comment]
It tries to load the following library:
[OpenComputers/OpenComputers]: Could not load native library 'OpenComputersMod-1.5.14.30-lua52-native.64.so'.

I'm pretty sure the server is running on Linux, judging from the above file, but they didn't specifically say for either host. I also cannot change the permissions for the root directory, and no Lua library is in the root directory.

**Comment by makkarpov** [comment]
```
    # Extract the native library with Lua into the system's temporary
    # directory instead of the game directory (e.g. /tmp on Linux). The
    # default is to extract into the game directory, to avoid issues when
    # the temporary directory is mounted as noexec (meaning the lib cannot)
    # be loaded. There is also less of a chance of conflicts when running
    # multiple servers or server and client on the same machine.
    nativeInTmpDir=false
```

Please try this setting in config.

**Comment by makkarpov** [comment]
```
    # Logs the full error when a native library fails to load. This is
    # disabled by default to avoid spamming the log, since libraries are
    # iterated until one works, so it's very likely for some to fail. Use
    # this in case all libraries fail to load even though you'd expect one
    # to work.
    logFullNativeLibLoadErrors=false
```

And also this one

**Comment by ghost** [comment]
I'm guessing I was supposed to set both of those to true? I did, still no joy. But this is new:

```
[11:19:51] [Server thread/TRACE] [OpenComputers/OpenComputers]: Could not load native library 'OpenComputersMod-1.5.14.30-lua52-native.64.so'.
java.lang.UnsatisfiedLinkError: /tmp/OpenComputersMod-1.5.14.30-lua52-native.64.so: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /tmp/OpenComputersMod-1.5.14.30-lua52-native.64.so)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.7.0_01]
    at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.7.0_01]
    at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.7.0_01]
    at java.lang.Runtime.load0(Unknown Source) ~[?:1.7.0_01]
    at java.lang.System.load(Unknown Source) ~[?:1.7.0_01]
    at li.cil.oc.server.machine.luac.LuaStateFactory$$anon$1.load(LuaStateFactory.scala:114) ~[LuaStateFactory$$anon$1.class:?]
    at li.cil.repack.com.naef.jnlua.LuaState.<clinit>(LuaState.java:134) ~[LuaState.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua52$$anonfun$create$1.apply(LuaStateFactory.scala:32) ~[LuaStateFactory$Lua52$$anonfun$create$1.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua52$$anonfun$create$1.apply(LuaStateFactory.scala:32) ~[LuaStateFactory$Lua52$$anonfun$create$1.class:?]
    at scala.Option.fold(Option.scala:157) ~[scala-library-2.11.1.jar:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua52$.create(LuaStateFactory.scala:32) ~[LuaStateFactory$Lua52$.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory.init(LuaStateFactory.scala:255) [LuaStateFactory.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory.<init>(LuaStateFactory.scala:272) [LuaStateFactory.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua52$.<init>(LuaStateFactory.scala:29) [LuaStateFactory$Lua52$.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua52$.<clinit>(LuaStateFactory.scala) [LuaStateFactory$Lua52$.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$.isAvailable(LuaStateFactory.scala:24) [LuaStateFactory$.class:?]
    at li.cil.oc.common.Proxy.preInit(Proxy.scala:76) [Proxy.class:?]
    at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34) [OpenComputers$.class:?]
    at li.cil.oc.OpenComputers.preInit(OpenComputers.scala) [OpenComputers.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_01]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_01]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_01]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_01]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_01]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[11:19:51] [Server thread/WARN] [OpenComputers/OpenComputers]: Unsupported platform, you won't be able to host games with persistent computers.
[11:19:51] [Server thread/TRACE] [OpenComputers/OpenComputers]: Could not load native library 'OpenComputersMod-1.5.14.30-lua53-native.64.so'.
java.lang.NoClassDefFoundError: li.cil.repack.com.naef.jnlua.LuaState
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua53$$anonfun$create$3.apply(LuaStateFactory.scala:50) ~[LuaStateFactory$Lua53$$anonfun$create$3.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua53$$anonfun$create$3.apply(LuaStateFactory.scala:50) ~[LuaStateFactory$Lua53$$anonfun$create$3.class:?]
    at scala.Option.fold(Option.scala:157) ~[scala-library-2.11.1.jar:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua53$.create(LuaStateFactory.scala:50) ~[LuaStateFactory$Lua53$.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua53$.create(LuaStateFactory.scala:47) ~[LuaStateFactory$Lua53$.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory.init(LuaStateFactory.scala:255) [LuaStateFactory.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory.<init>(LuaStateFactory.scala:272) [LuaStateFactory.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua53$.<init>(LuaStateFactory.scala:47) [LuaStateFactory$Lua53$.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$Lua53$.<clinit>(LuaStateFactory.scala) [LuaStateFactory$Lua53$.class:?]
    at li.cil.oc.server.machine.luac.LuaStateFactory$.isAvailable(LuaStateFactory.scala:25) [LuaStateFactory$.class:?]
    at li.cil.oc.common.Proxy.preInit(Proxy.scala:76) [Proxy.class:?]
    at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34) [OpenComputers$.class:?]
    at li.cil.oc.OpenComputers.preInit(OpenComputers.scala) [OpenComputers.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_01]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_01]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_01]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_01]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_01]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_01]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[11:19:51] [Server thread/WARN] [OpenComputers/OpenComputers]: Unsupported platform, you won't be able to host games with persistent computers.
[11:19:51] [Server thread/INFO] [OpenComputers/OpenComputers]: Done with pre init phase.
[11:19:51] [Server thread/TRACE] [OpenComputers/OpenComputers]: Sent event FMLPreInitializationEvent to mod OpenComputers

```

**Comment by makkarpov** [comment]
Hmm, looks like I can't help you anymore. I think you have to wait until @fnuecke answers in this thread.

**Comment by magik6k** [comment]
Looks like your provider has really outdated system. You should poke them about upgrade. Compiling native libs for older glibc should work too.

**Comment by ghost** [comment]
If the issue cannot be resolved another way, does anyone have the name of a host that for sure supports OpenComputers? Pestering hosts to upgrade hasn't done any good on any of the hosts I've tried.

**Comment by dgelessus** [comment]
It's possible that your server hosts don't want their users to run their own native code, so they decided to not provide `libc`, or at least not make it accessible. (I'm fairly certain that without `libc` you could do basically nothing on a Unix machine.)

But whatever host you got the log from is really using outdated software. I mean, Java 7 update 1? Are you kidding? I can understand (sort of) that they want to stick to Java 7 instead of 8 for now, but there's no excuse for using a Java version released a year or two ago.

**Comment by makkarpov** [comment]
> I'm fairly certain that without libc you could do basically nothing on a Unix machine.

BTW, you are wrong. You can still do anything that you done with libc through Linux system calls, or, at least, bundle your own libc. If they wanted to do it, they would just put minecraft server root under `noexec` FS, but disallowing of native code loading will break a lot of things like SQLite DB's.

**Comment by dgelessus** [comment]
That's why I said _basically_ nothing. Sure, you can write your stuff in Assembly and do everything the low-level way, but C programs need `libc` to run, right? But you're right, disallowing access to `libc` wouldn't be a very effective security measure.

**Comment by makkarpov** [comment]
> but C programs need libc to run, right

C programs can be linked statically and after that they can run even in `chroot`. A simple test case:

```
[makkarpov@Desktop libc]$ cat test.c
#include <stdio.h>

int main() {
        printf("Hello, World!\n");
        return 0;                                                                                                                                                                                                                            
}                                                                                                                                                                                                                                            
[makkarpov@Desktop libc]$ gcc -o test_dyn test.c
[makkarpov@Desktop libc]$ gcc -static -o test_stat test.c                                                                                                                                                                                 
[makkarpov@Desktop libc]$ ls -lh                                                                                                                                                                                                             
итого 840K                                                                                                                                                                                                                                   
-rw-rw-r--. 1 makkarpov makkarpov   74 июл 15 15:52 test.c                                                                                                                                                                                   
-rwxrwxr-x. 1 makkarpov makkarpov 8,4K июл 15 15:54 test_dyn                                                                                                                                                                                 
-rwxrwxr-x. 1 makkarpov makkarpov 822K июл 15 15:54 test_stat                                                                                                                                                                                
[makkarpov@Desktop libc]$ sudo chroot . /test_dyn
chroot: failed to run command ‘/test_dyn’: No such file or directory                                                                                                                                                                         
[makkarpov@Desktop libc]$ sudo chroot . /test_stat
Hello, World!             
[makkarpov@Desktop libc]$ ldd ./test_dyn 
        linux-vdso.so.1 =>  (0x00007fff3f27f000)                                                                                                                                                                                             
        libc.so.6 => /lib64/libc.so.6 (0x00000033e6800000)                                                                                                                                                                                   
        /lib64/ld-linux-x86-64.so.2 (0x00000033e6400000)                                                                                                                                                                                     
[makkarpov@Desktop libc]$ ldd ./test_stat                                                                                                                                                                                                    
        not a dynamic executable
```

**Comment by fnuecke** [comment]
This is getting a tad off-topic...

So. I can try compiling the libs against an older libc - can someone tell me how to explicitly specify the version to use when compiling to save me some time? Or even better, adjust the [build.gradle](https://github.com/MightyPirates/OC-Natives/blob/master/build.gradle) accordingly and make a PR?

**Comment by SaphireLattice** [comment]
Or you could make a fallback to a static lib.

**Comment by Kubuxu** [comment]
glibc is now working well when linked statically. It is system specific library.

**Comment by ghost** [comment]
I can't craft the Lua Bios EEPROM. using a blank eeprom and the OC manual returns the same blank eeprom. I'm playing on a Horizons mod pack.

**Comment by ghost** [comment]
Wow, figured it out. If you put the Blank eeprom into the computer, you cannot just take it out and then craft the Lua eeprom. it has to be a fresh eeprom...strange.
