### ISSUE TITLE
Game crashes when opening the OpenComputers inventory tab

### ISSUE THREAD

**Issue by danaketh** [MightyPirates/OpenComputers#1316]
It might be a conflict with other mods but pretty much all the mods are working fine but OpenComputers will crash the game every time I try to open it's inventory tab.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
  TransformerLoader (OpenComputers-MC1.8-1.5.14.32-universal.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 20.7.15 22:13
Description: Rendering item

java.lang.IndexOutOfBoundsException: -11
    at java.nio.DirectIntBufferU.put(Unknown Source)
    at net.minecraft.client.renderer.WorldRenderer.func_178972_a(SourceFile:226)
    at net.minecraft.client.renderer.WorldRenderer.func_178988_b(SourceFile:213)
    at net.minecraft.client.renderer.WorldRenderer.func_178968_d(SourceFile:438)
    at net.minecraft.client.renderer.entity.RenderItem.func_175033_a(RenderItem.java:218)
    at net.minecraft.client.renderer.entity.RenderItem.func_175032_a(RenderItem.java:228)
    at net.minecraft.client.renderer.entity.RenderItem.func_175045_a(RenderItem.java:142)
    at net.minecraft.client.renderer.entity.RenderItem.func_175036_a(RenderItem.java:122)
    at net.minecraft.client.renderer.entity.RenderItem.func_180454_a(RenderItem.java:165)
    at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:374)
    at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:413)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:267)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:46)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:620)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:459)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1081)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.nio.DirectIntBufferU.put(Unknown Source)
    at net.minecraft.client.renderer.WorldRenderer.func_178972_a(SourceFile:226)
    at net.minecraft.client.renderer.WorldRenderer.func_178988_b(SourceFile:213)
    at net.minecraft.client.renderer.WorldRenderer.func_178968_d(SourceFile:438)
    at net.minecraft.client.renderer.entity.RenderItem.func_175033_a(RenderItem.java:218)
    at net.minecraft.client.renderer.entity.RenderItem.func_175032_a(RenderItem.java:228)
    at net.minecraft.client.renderer.entity.RenderItem.func_175045_a(RenderItem.java:142)
    at net.minecraft.client.renderer.entity.RenderItem.func_175036_a(RenderItem.java:122)
    at net.minecraft.client.renderer.entity.RenderItem.func_180454_a(RenderItem.java:165)
    at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:374)

-- Item being rendered --
Details:
    Item Type: li.cil.oc.common.block.Item@1232691
    Item Aux: 0
    Item NBT: null
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:413)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:267)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:46)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:620)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:459)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (305, 197). Absolute: (611, 84)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['danaketh'/71, l='MpServer', x=-51,13, y=72,00, z=483,09]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -39,00,64,00,62,00 - World: (-39,64,62), Chunk: (at 9,4,14 in -3,3; contains blocks -48,0,48 to -33,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1221161 game time, 9657 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 105 total; [EntityPlayerSP['danaketh'/71, l='MpServer', x=-51,13, y=72,00, z=483,09], EntityMinecartChest['container.minecart'/72, l='MpServer', x=-53,50, y=13,06, z=493,50], EntityZombie['Zombie'/73, l='MpServer', x=-34,09, y=59,00, z=472,38], EntityZombie['Zombie'/74, l='MpServer', x=-33,19, y=59,00, z=473,31], EntitySkeleton['Skeleton'/75, l='MpServer', x=-33,50, y=36,00, z=500,16], EntityCustomNpc['Silk'/76, l='MpServer', x=-53,50, y=146,00, z=461,50], EntityZombie['Zombie'/77, l='MpServer', x=-25,50, y=31,00, z=493,50], EntitySkeleton['Skeleton'/78, l='MpServer', x=-31,50, y=36,00, z=487,50], EntitySheep['Sheep'/79, l='MpServer', x=-62,97, y=73,00, z=519,94], EntitySheep['Sheep'/80, l='MpServer', x=-53,69, y=71,00, z=523,88], EntitySheep['Sheep'/81, l='MpServer', x=-72,44, y=77,00, z=521,66], EntityBat['Bat'/82, l='MpServer', x=-67,53, y=12,12, z=461,00], EntityBat['Bat'/83, l='MpServer', x=-69,75, y=14,10, z=458,44], EntityBat['Bat'/84, l='MpServer', x=-70,75, y=15,10, z=461,75], EntityCow['Cow'/85, l='MpServer', x=-48,41, y=66,00, z=442,63], EntitySpider['Spider'/86, l='MpServer', x=-24,41, y=20,00, z=466,59], EntityCreeper['Creeper'/87, l='MpServer', x=-27,25, y=19,00, z=467,06], EntityCow['Cow'/88, l='MpServer', x=-17,88, y=67,00, z=466,00], EntityZombie['Zombie'/89, l='MpServer', x=-20,50, y=31,00, z=502,50], EntityCreeper['Creeper'/90, l='MpServer', x=-23,59, y=36,00, z=496,94], EntitySkeleton['Skeleton'/91, l='MpServer', x=-17,50, y=32,00, z=508,50], EntityBat['Bat'/92, l='MpServer', x=-30,25, y=36,10, z=508,25], EntitySkeleton['Skeleton'/93, l='MpServer', x=-86,50, y=86,00, z=448,50], EntityRabbit['Rabbit'/94, l='MpServer', x=-16,88, y=68,00, z=452,59], EntityCreeper['Creeper'/95, l='MpServer', x=-28,50, y=39,00, z=517,50], EntityCow['Cow'/96, l='MpServer', x=-23,63, y=67,00, z=519,34], EntitySheep['Sheep'/97, l='MpServer', x=-18,44, y=67,00, z=524,66], EntitySheep['Sheep'/98, l='MpServer', x=-66,97, y=70,00, z=545,97], EntitySkeleton['Skeleton'/99, l='MpServer', x=-98,63, y=18,00, z=473,81], EntitySkeleton['Skeleton'/100, l='MpServer', x=-40,16, y=18,00, z=435,50], EntitySheep['Sheep'/101, l='MpServer', x=-12,09, y=67,00, z=510,94], EntitySpider['Spider'/102, l='MpServer', x=-44,41, y=45,00, z=528,28], EntityCreeper['Creeper'/103, l='MpServer', x=-47,03, y=45,00, z=529,41], EntityZombie['Zombie'/104, l='MpServer', x=-32,66, y=42,00, z=531,16], EntityBat['Bat'/105, l='MpServer', x=-37,97, y=46,97, z=547,09], EntityBat['Bat'/106, l='MpServer', x=-41,38, y=48,10, z=540,34], EntityCow['Cow'/107, l='MpServer', x=-47,50, y=73,00, z=542,50], EntitySheep['Sheep'/108, l='MpServer', x=-37,84, y=69,00, z=543,63], EntityCreeper['Creeper'/109, l='MpServer', x=-87,47, y=24,00, z=538,19], EntityCreeper['Creeper'/110, l='MpServer', x=-88,06, y=24,00, z=537,34], EntitySheep['Sheep'/111, l='MpServer', x=-86,09, y=94,00, z=537,97], EntitySheep['Sheep'/112, l='MpServer', x=-83,56, y=93,00, z=540,31], EntityBat['Bat'/113, l='MpServer', x=-110,57, y=52,89, z=456,53], EntitySheep['Sheep'/114, l='MpServer', x=-105,56, y=121,00, z=448,13], EntitySheep['Sheep'/115, l='MpServer', x=-10,34, y=64,00, z=457,75], EntitySkeleton['Skeleton'/117, l='MpServer', x=-26,53, y=18,00, z=526,84], EntitySheep['Sheep'/118, l='MpServer', x=-17,06, y=68,00, z=530,94], EntityPig['Pig'/119, l='MpServer', x=-16,13, y=67,00, z=537,00], EntityCreeper['Creeper'/120, l='MpServer', x=-126,50, y=27,00, z=481,50], EntityBat['Bat'/121, l='MpServer', x=-115,59, y=54,10, z=478,19], EntityMinecartChest['container.minecart'/122, l='MpServer', x=13,50, y=16,06, z=491,47], EntityCow['Cow'/123, l='MpServer', x=-56,16, y=70,00, z=554,88], EntitySheep['Sheep'/124, l='MpServer', x=-49,09, y=69,00, z=546,84], EntityCow['Cow'/126, l='MpServer', x=-76,44, y=75,00, z=553,34], EntitySkeleton['Skeleton'/127, l='MpServer', x=-117,53, y=62,00, z=509,81], EntitySkeleton['Skeleton'/128, l='MpServer', x=-120,47, y=53,00, z=465,84], EntityBat['Bat'/129, l='MpServer', x=-114,25, y=55,10, z=463,25], EntityZombie['Zombie'/130, l='MpServer', x=-113,50, y=54,00, z=466,91], EntitySheep['Sheep'/131, l='MpServer', x=-126,34, y=91,00, z=467,78], EntitySheep['Sheep'/132, l='MpServer', x=-113,91, y=112,00, z=467,66], EntityZombie['Zombie'/133, l='MpServer', x=-66,50, y=39,00, z=426,50], EntityBat['Bat'/134, l='MpServer', x=9,26, y=26,03, z=454,49], EntityZombie['Zombie'/135, l='MpServer', x=3,88, y=59,00, z=469,63], EntityRabbit['Rabbit'/136, l='MpServer', x=7,31, y=64,00, z=502,66], EntityCow['Cow'/137, l='MpServer', x=3,44, y=66,00, z=502,28], EntityCreeper['Creeper'/138, l='MpServer', x=-45,63, y=45,00, z=556,00], EntityCreeper['Creeper'/139, l='MpServer', x=-46,09, y=44,00, z=545,53], EntityCreeper['Creeper'/140, l='MpServer', x=-47,09, y=45,00, z=552,53], EntityCreeper['Creeper'/141, l='MpServer', x=-48,19, y=45,00, z=555,16], EntitySheep['Sheep'/142, l='MpServer', x=-45,06, y=70,00, z=555,06], EntitySheep['Sheep'/143, l='MpServer', x=-49,16, y=70,00, z=548,94], EntityPig['Pig'/144, l='MpServer', x=-4,56, y=66,00, z=533,31], EntityRabbit['Rabbit'/145, l='MpServer', x=-7,44, y=67,00, z=541,88], EntitySkeleton['Skeleton'/146, l='MpServer', x=-115,75, y=61,00, z=515,16], EntitySkeleton['Skeleton'/147, l='MpServer', x=-118,47, y=62,00, z=512,81], EntitySkeleton['Skeleton'/148, l='MpServer', x=-115,31, y=62,00, z=512,44], EntityZombie['Zombie'/149, l='MpServer', x=-114,06, y=50,00, z=468,41], EntitySkeleton['Skeleton'/150, l='MpServer', x=-114,50, y=63,00, z=457,50], EntityBat['Bat'/151, l='MpServer', x=-118,12, y=54,96, z=467,83], EntitySheep['Sheep'/152, l='MpServer', x=-124,47, y=128,00, z=458,34], EntitySkeleton['Skeleton'/153, l='MpServer', x=13,50, y=24,00, z=516,50], EntityCreeper['Creeper'/154, l='MpServer', x=-22,06, y=20,00, z=546,53], EntitySheep['Sheep'/155, l='MpServer', x=-104,00, y=73,00, z=552,44], EntitySheep['Sheep'/156, l='MpServer', x=-101,88, y=86,00, z=546,84], EntityRabbit['Rabbit'/157, l='MpServer', x=-123,66, y=92,00, z=499,34], EntityCreeper['Creeper'/158, l='MpServer', x=-118,97, y=16,00, z=432,44], EntityMinecartChest['container.minecart'/159, l='MpServer', x=9,50, y=23,06, z=443,50], EntitySkeleton['Skeleton'/160, l='MpServer', x=19,47, y=34,00, z=475,81], EntityPig['Pig'/161, l='MpServer', x=0,47, y=65,00, z=531,28], EntityCreeper['Creeper'/162, l='MpServer', x=-7,53, y=56,00, z=557,06], EntityPig['Pig'/163, l='MpServer', x=-10,22, y=67,00, z=546,28], EntitySpider['Spider'/164, l='MpServer', x=-127,72, y=20,00, z=474,69], EntityBat['Bat'/166, l='MpServer', x=-128,75, y=47,10, z=478,25], EntityZombie['Zombie'/171, l='MpServer', x=-121,66, y=21,00, z=427,34], EntityCreeper['Creeper'/172, l='MpServer', x=-117,94, y=20,00, z=423,41], EntityCreeper['Creeper'/173, l='MpServer', x=-116,59, y=19,00, z=420,03], EntitySkeleton['Skeleton'/174, l='MpServer', x=3,44, y=27,00, z=548,84], EntityCreeper['Creeper'/175, l='MpServer', x=-107,47, y=76,00, z=415,66], EntitySkeleton['Skeleton'/176, l='MpServer', x=-105,53, y=83,00, z=411,84], EntityZombie['Zombie'/196, l='MpServer', x=-114,50, y=16,00, z=406,50], EntityCreeper['Creeper'/197, l='MpServer', x=26,69, y=41,00, z=550,09], EntityCreeper['Creeper'/198, l='MpServer', x=26,50, y=41,00, z=547,50], EntityEnderman['Enderman'/199, l='MpServer', x=25,06, y=43,00, z=558,50], EntityBat['Bat'/211, l='MpServer', x=25,75, y=15,61, z=405,11], EntityBat['Bat'/212, l='MpServer', x=6,85, y=15,02, z=410,83]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 200652432 bytes (191 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1491 19 mods loaded, 19 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1491.jar) 
    UCHIJA  Forge{11.14.3.1491} [Minecraft Forge] (forge-1.8-11.14.3.1491.jar) 
    UCHIJA  OpenComputers|Core{1.5.14.32} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJA  bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
    UCHIJA  AutoSapling{1.0} [AutoSapling] (AutoSap-MC1.8-1.2.jar) 
    UCHIJA  BetterFoliage{1.1.5} [Better Foliage] (BetterFoliage-mc1.8-1.1.5.jar) 
    UCHIJA  customnpcs{1.8.0_beta} [CustomNpcs] (CustomNPCs_1.8.0_beta.jar) 
    UCHIJA  fluxducts{1.0.2} [Flux Ducts] (fluxducts-mc1.8-1.0.2.jar) 
    UCHIJA  LunatriusCore{1.1.2.28} [LunatriusCore] (LunatriusCore-1.8-1.1.2.28-universal.jar) 
    UCHIJA  MemoryCleaner{1.0} [Memory Cleaner] (MemoryCleaner-1.4-mc.1.8.jar) 
    UCHIJA  minions{1.9.7} [Minions] (Minions-1.8.jar) 
    UCHIJA  cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8-build1(1.8).jar) 
    UCHIJA  OpenComputers{1.5.14.32} [OpenComputers] (OpenComputers-MC1.8-1.5.14.32-universal.jar) 
    UCHIJA  progressiveautomation{1.6.15} [Progressive Automation] (ProgressiveAutomation-1.8-1.6.15.jar) 
    UCHIJA  securitycraft{v1.7.0} [SecurityCraft] (SecurityCraft-Mod-1.8.jar) 
    UCHIJA  Treecapitator{1.8} [Treecapitator] (Tree-Capitator-Mod-1.8.jar) 
    UCHIJA  AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.jar) 
    UCHIJA  teleporter{1.4.2} [Vanilla-Inspired Teleporters] (VanillaTeleporter-1.8-1.4.2.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
  mods.betterfoliage.loader.impl.BetterFoliageTransformer
TransformerLoader (OpenComputers-MC1.8-1.5.14.32-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 660 Ti/PCIe/SSE2'
    Launched Version: 1.8-Forge11.14.3.1491
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
```

**Comment by danaketh** [comment]
Ok, identified the problem - this issue is duplicity of #1116 so I'm closing it...
