### ISSUE TITLE
Dead Lock - server hanged, required hard reboot

### ISSUE THREAD

**Issue by Kubuxu** [MightyPirates/OpenComputers#1322]
It happened while pulling out server from rack: http://hastebin.com/ekaqimubos.txt

The root of a problem is on the end:

```
"Server thread":
    at li.cil.oc.server.machine.Machine.close(Machine.scala:841)
    - waiting to lock <0x00000315f09c26d0> (a li.cil.oc.server.machine.Machine)
    - locked <0x00000315f2643d38> (a scala.collection.mutable.Stack)
    at li.cil.oc.server.machine.Machine.onDisconnect(Machine.scala:601)
    at li.cil.oc.server.network.Node$class.onDisconnect(Node.scala:59)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.li$cil$oc$server$network$Connector$$super$onDisconnect(Network.scala:618)
    at li.cil.oc.server.network.Connector$class.onDisconnect(Connector.scala:113)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.onDisconnect(Network.scala:618)
    at li.cil.oc.server.network.Network$$anonfun$remove$1.apply(Network.scala:148)
    at li.cil.oc.server.network.Network$$anonfun$remove$1.apply(Network.scala:148)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at li.cil.oc.server.network.Network.remove(Network.scala:148)
    at li.cil.oc.server.network.Network$Wrapper.remove(Network.scala:736)
    at li.cil.oc.server.network.Node$class.remove(Node.scala:43)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.remove(Network.scala:618)
    at li.cil.oc.common.tileentity.ServerRack.onItemRemoved(ServerRack.scala:468)
    at li.cil.oc.common.inventory.Inventory$class.setInventorySlotContents(Inventory.scala:51)
    at li.cil.oc.common.tileentity.ServerRack.func_70299_a(ServerRack.scala:34)
    at li.cil.oc.common.inventory.Inventory$class.decrStackSize(Inventory.scala:25)
    at li.cil.oc.common.tileentity.ServerRack.func_70298_a(ServerRack.scala:34)
    at net.minecraft.inventory.Slot.func_75209_a(Slot.java:93)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:232)
    at li.cil.oc.common.container.Player.func_75144_a(Player.scala:34)
    at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
    at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
    at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    - locked <0x000003158a690610> (a java.util.Collections$SynchronizedRandomAccessList)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at fastcraft.c.p.a(F:19)
    at fastcraft.Hooks.aq(F:153)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
"OpenComputers-Computer-3":
    at li.cil.oc.server.machine.Machine.run(Machine.scala:900)
    - waiting to lock <0x00000315f2643d38> (a scala.collection.mutable.Stack)
    - locked <0x00000315f09c26d0> (a li.cil.oc.server.machine.Machine)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

As you can see ServerThread waits for Machine while locking Stack and worker thread waits for Stack and keeps Machine locked.

**Comment by fnuecke** [comment]
Thanks! I'll look into it as soon as I can, so probably tomorrow / this weekend.

**Comment by Kubuxu** [comment]
It was totally random and probably won't happen again for us  (the window for it is tight) but someone might be clueless when it happens.

**Comment by fnuecke** [comment]
Aye, deadlocks can be pretty elusive, so that trace is worth a lot. Will see if I can figure out why it's happening.
