### ISSUE TITLE
Unsupported processor type - APU

### ISSUE THREAD

**Issue by spannerman79** [MightyPirates/OpenComputers#1404]
Forge 1448
OC: OpenComputers-MC1.7.10-1.5.16.32-universal
MC: 1.7.10
Reproduction steps;
Hold _any_ APU, Shift+RClick to change LUA version;

```
java.lang.IllegalArgumentException: Unsupported processor type.
        at li.cil.oc.integration.opencomputers.DriverCPU.setArchitecture(DriverCPU.scala:66) ~[DriverCPU.class:?]
        at li.cil.oc.common.item.traits.CPULike$class.onItemRightClick(CPULike.scala:34) ~[CPULike$class.class:?]
        at li.cil.oc.common.item.APU.onItemRightClick(APU.scala:10) ~[APU.class:?]
        at li.cil.oc.common.item.Delegator.func_77659_a(Delegator.scala:149) ~[Delegator.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:172) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:383) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:825) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
```

**Comment by mpevner** [comment]
Can confirm this issue, same versions involved. In a multiplayer scenario the client will crash back to menu and the server continues. The CPU type remains unchanged.

**Comment by fnuecke** [comment]
Whoops. Will probably make 1.5.17 a hotfix for this, sorry about that!
