### ISSUE TITLE
"Errors running the class transformer" when Open Computers is paired up with AcademyCraft

### ISSUE THREAD

**Issue by BBoldt** [MightyPirates/OpenComputers#1509]
![](http://i.imgur.com/vD7cY9A.png)

For some reason this only happens when this mod is installed alongside Open Computers:
http://minecraft.curseforge.com/projects/academycraft
http://minecraft.curseforge.com/projects/lambdalib

Reporting because the message told me to. :P
- OpenComputers-MC1.7.10-1.5.19.37-universal
- AcademyCraft-1.0pr2_1
- LambdaLib-1.0

Full modlist: https://gist.github.com/75dd8e96c0b0eed4cc15

All the log files:
fml-client-latest.log: https://gist.github.com/4515ce40598a5a583ce9
latest.log: https://gist.github.com/7346d1f50a5bb3131ee9

This was singleplayer so I do not have the server log that the error message was asking for.

**Comment by fnuecke** [comment]
Thanks. Looks like there's at least three class transformers involved... fun. Can't yet say if this is OC's fault or not (aka whether I can actually do anything about it), will have a closer look when I can.

For reference to self, the relevant part from the log.

```
java.lang.ClassCircularityError: scala/collection/mutable/HashMap
    at scala.collection.mutable.ArrayOps$ofRef.<init>(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
    at scala.Predef$.refArrayOps(Predef.scala:339) ~[Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.19.37-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at cn.annoreg.asm.NetworkCallVisitor$NetworkCallMethodVisitor.visitAnnotation(NetworkCallVisitor.java:90) [NetworkCallVisitor$NetworkCallMethodVisitor.class:?]
    at org.objectweb.asm.ClassReader.b(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at cn.annoreg.asm.RegistryTransformer.transform(RegistryTransformer.java:58) [RegistryTransformer.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_65]
    at java.lang.ClassLoader.defineClass(Unknown Source) [?:1.8.0_65]
    at java.security.SecureClassLoader.defineClass(Unknown Source) [?:1.8.0_65]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at scala.collection.AbstractSeq.<init>(Seq.scala:41) [AbstractSeq.class:?]
    at scala.collection.immutable.List.<init>(List.scala:83) [List.class:?]
    at scala.collection.immutable.Nil$.<init>(List.scala:419) [Nil$.class:?]
    at scala.collection.immutable.Nil$.<clinit>(List.scala) [Nil$.class:?]
    at scala.sys.SystemProperties$.propertyHelp$lzycompute(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.propertyHelp(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.addHelp(SystemProperties.scala:65) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.bool(SystemProperties.scala:68) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression$lzycompute(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$.<clinit>(NoStackTrace.scala) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22) [NoStackTrace$class.class:?]
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94) [BreakControl.class:?]
    at java.lang.Throwable.<init>(Unknown Source) [?:1.8.0_65]
    at scala.util.control.BreakControl.<init>(Breaks.scala:94) [BreakControl.class:?]
    at scala.util.control.Breaks.<init>(Breaks.scala:29) [Breaks.class:?]
    at scala.collection.Traversable$.<init>(Traversable.scala:95) [Traversable$.class:?]
    at scala.collection.Traversable$.<clinit>(Traversable.scala) [Traversable$.class:?]
    at scala.package$.<init>(package.scala:40) [package$.class:?]
    at scala.package$.<clinit>(package.scala) [package$.class:?]
    at scala.Predef$.<init>(Predef.scala:89) [Predef$.class:?]
    at scala.Predef$.<clinit>(Predef.scala) [Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.19.37-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:457) [GsonBuilder.class:3.2.3.1]
    at openeye.logic.GsonUtils.setupCommonBuilder(GsonUtils.java:26) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.GsonUtils.<clinit>(GsonUtils.java:32) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.Storages.<init>(Storages.java:25) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.Storages.init(Storages.java:31) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.Bootstrap.startup(Bootstrap.java:45) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.SetupHook.call(SetupHook.java:12) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.SetupHook.call(SetupHook.java:8) [OpenEye-0.6-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133) [forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[13:43:46] [main/WARN] [OpenComputers/]: Something went wrong!
java.lang.ClassCircularityError: scala/collection/mutable/HashMap
    at scala.collection.mutable.ArrayOps$ofRef.<init>(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
    at scala.Predef$.refArrayOps(Predef.scala:339) ~[Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.19.37-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at cn.annoreg.asm.NetworkCallVisitor$NetworkCallMethodVisitor.visitAnnotation(NetworkCallVisitor.java:91) [NetworkCallVisitor$NetworkCallMethodVisitor.class:?]
    at org.objectweb.asm.ClassReader.b(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at cn.annoreg.asm.RegistryTransformer.transform(RegistryTransformer.java:58) [RegistryTransformer.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_65]
    at java.lang.ClassLoader.defineClass(Unknown Source) [?:1.8.0_65]
    at java.security.SecureClassLoader.defineClass(Unknown Source) [?:1.8.0_65]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at scala.collection.AbstractSeq.<init>(Seq.scala:41) [AbstractSeq.class:?]
    at scala.collection.immutable.List.<init>(List.scala:83) [List.class:?]
    at scala.collection.immutable.Nil$.<init>(List.scala:419) [Nil$.class:?]
    at scala.collection.immutable.Nil$.<clinit>(List.scala) [Nil$.class:?]
    at scala.sys.SystemProperties$.propertyHelp$lzycompute(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.propertyHelp(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.addHelp(SystemProperties.scala:65) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.bool(SystemProperties.scala:68) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression$lzycompute(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$.<clinit>(NoStackTrace.scala) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22) [NoStackTrace$class.class:?]
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94) [BreakControl.class:?]
    at java.lang.Throwable.<init>(Unknown Source) [?:1.8.0_65]
    at scala.util.control.BreakControl.<init>(Breaks.scala:94) [BreakControl.class:?]
    at scala.util.control.Breaks.<init>(Breaks.scala:29) [Breaks.class:?]
    at scala.collection.Traversable$.<init>(Traversable.scala:95) [Traversable$.class:?]
    at scala.collection.Traversable$.<clinit>(Traversable.scala) [Traversable$.class:?]
    at scala.package$.<init>(package.scala:40) [package$.class:?]
    at scala.package$.<clinit>(package.scala) [package$.class:?]
    at scala.Predef$.<init>(Predef.scala:89) [Predef$.class:?]
    at scala.Predef$.<clinit>(Predef.scala) [Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.19.37-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:457) [GsonBuilder.class:3.2.3.1]
    at openeye.logic.GsonUtils.setupCommonBuilder(GsonUtils.java:26) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.GsonUtils.<clinit>(GsonUtils.java:32) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.Storages.<init>(Storages.java:25) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.Storages.init(Storages.java:31) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.logic.Bootstrap.startup(Bootstrap.java:45) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.SetupHook.call(SetupHook.java:12) [OpenEye-0.6-1.7.10.jar:?]
    at openeye.SetupHook.call(SetupHook.java:8) [OpenEye-0.6-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133) [forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by WeAthFoLD** [comment]
LambdaLib 1.0 used wrong version of ASM. I think that is likely to be the source. If that's so this is automatically fixed in our next release.
https://github.com/LambdaInnovation/LambdaLib/pull/5

**Comment by fnuecke** [comment]
Interesting. @BBoldt let me know if that fixes it or not, please.

**Comment by BBoldt** [comment]
Will do once that new version is released.

**Comment by Alaberti** [comment]
I just tried this with LambdaLib 1.1.0, AcademtCraft pr3, and OpenCOmputers 1.5.21.41 and picked up the same error.

FML Client Latest: https://gist.github.com/Alaberti/7070663d9299208cd023

**Comment by Alaberti** [comment]
Appears to be fixed in version pr3_1 of AcademyCraft.

**Comment by fnuecke** [comment]
Cool, thanks for the update!

**Comment by fnuecke** [comment]
Some people are apparently getting this on pr3_1?
