### ISSUE TITLE
Crash on launch in 1.7.10

### ISSUE THREAD

**Issue by japherwocky** [MightyPirates/OpenComputers#1516]
Hi -

Adding opencomputers to our server pack gives a crash like:

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/5/15 5:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable
    at li.cil.oc.common.Proxy.preInit(Proxy.scala:29)
    at li.cil.oc.client.Proxy.preInit(Proxy.scala:36)
    at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34)
    at li.cil.oc.OpenComputers.preInit(OpenComputers.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigMergeable
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 40 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 736270096 bytes (702 MB) / 1751646208 bytes (1670 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1541 58 mods loaded, 58 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
    UCH Forge{10.13.4.1541} [Minecraft Forge] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
    UCH CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    UCH NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCH OpenComputers|Core{1.5.19.37} [OpenComputers (Core)] (minecraft.jar) 
    UCH OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
    UCH BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCH CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCH BrandonsCore{1.0.0.8} [Brandon's Core] (BrandonsCore-1.0.0.8.jar) 
    UCH chancecubes{1.7.10-1.4.3.41} [Chance Cubes] (ChanceCubes-1.7.10-1.4.3.41.jar) 
    UCH ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCH Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
    UCH Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCH TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
    UCH ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
    UCH DraconicEvolution{1.0.2-snapshot_5} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2-Snapshot_5-Bugfix.jar) 
    UCH eiramoticons{1.0.78} [EiraMoticons] (eiramoticons-mc1.7.10-1.0.78.jar) 
    UCH endercore{1.7.10-0.2.0.30_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.30_beta.jar) 
    UCH Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCH EnderIO{1.7.10-2.3.0.417_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.417_beta.jar) 
    UCH EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCH enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
    UCH ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
    UCH ftfloocraft{1.7.10-1.4.1} [Floocraft] (Floocraft-1.7.10-1.4.1.jar) 
    UCH GraveStone{2.15.0} [GraveStone] (GraveStone-2.15.0.jar) 
    UCH HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar) 
    UCH headcrumbs{1.6.2} [Headcrumbs] (Headcrumbs-1.6.2.jar) 
    UCH inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
    UCH journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCH LavaMonsters{2.2.1} [Lava Monsters] (LavaMonsters-1.7.10-2.2.1.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
    UCH NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
    UCH OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
    UCH OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
    UCE OpenComputers{1.5.19.37} [OpenComputers] (OpenComputers-MC1.7.10-1.5.19.37-universal.jar) 
    UCH harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10k.jar) 
    UCH ProjectE{1.7.10-PE1.9.3} [ProjectE] (ProjectE-1.7.10-PE1.9.3h.jar) 
    UCH RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    UCH libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
    UCH xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
    UCH Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
    UCH simplyjetpacks{1.5.2} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.2.jar) 
    UCH SpecialMobs{3.2.0} [Special Mobs] (SpecialMobs-1.7.10-3.2.0.jar) 
    UCH TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
    UCH thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCH TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCH UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) 
    UCH witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
    UCH WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCH WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCH WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCH McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.50' Renderer: 'GeForce GTX 960/PCIe/SSE2'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
```

Am I missing a core library or something?

**Comment by fnuecke** [comment]
You have a broken Forge installation (missing at least the typesafe-config lib). Reinstall or copy your libs from a working installation.
