### ISSUE TITLE
OpenComputers/Forestry Incompatibility

### ISSUE THREAD

**Issue by spannerman79** [MightyPirates/OpenComputers#1520]
Minecraft: 1.7.10
Forge 1448
OC: 1.5.19.37
Forestry: [4.1.1](http://jenkins.ic2.player.to/job/Forestry/46/)

```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: forestry/core/gadgets/TileAnalyzer
    at li.cil.oc.integration.forestry.DriverAnalyzer.getTileEntityClass(DriverAnalyzer.scala:15)
    at li.cil.oc.api.prefab.DriverTileEntity.worksWith(DriverTileEntity.java:11)
    at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:70)
    at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:70)
    at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
    at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
    at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:70)
    at li.cil.oc.api.Driver.driverFor(Driver.java:96)
    at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:58)
    at li.cil.oc.common.block.Adapter.onNeighborChange(Adapter.scala:42)
    at net.minecraft.world.World.func_147453_f(World.java:4567)
    at net.minecraft.world.World.func_147475_p(World.java:3196)
    at cofh.core.block.BlockCoFHBase.func_149749_a(BlockCoFHBase.java:84)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
    at net.minecraft.world.World.func_147465_d(World.java:812)
    at net.minecraft.world.World.func_147468_f(World.java:954)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1359)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1353)
    at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:307)
    at net.minecraft.server.management.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:300)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:344)
    at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:185)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:732)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)
```

I am unsure who is at fault here......

**Comment by Voidi** [comment]
Forestry changed some API with 4.1
you could try it with the latest OpenComputers dev build http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.7.10-1.5.20.799-dev-universal.jar

**Comment by fnuecke** [comment]
Yeah, fixed in the dev builds, grab one of those. I'll try to make a patch release soonish.
