### ISSUE TITLE
Crash on MC 1.8 startup

### ISSUE THREAD

**Issue by fagci** [MightyPirates/OpenComputers#1626]
Hello! =)
Cannot run OC 1.5.21.42 on windows. 

```
Current machine: Windows 8.1 6.3 x64, Java 1.8.0_45 (1.8), 3982 MB RAM, 2 cores
Selected version: Forge 1.8
```

Produces:

```
java.lang.IllegalAccessError: tried to access field net.minecraft.client.audio.SoundManager.field_148620_e from class li.cil.oc.client.Sound$
+   at li.cil.oc.client.Sound$.soundSystem(Sound.scala:56)
+   at li.cil.oc.client.Sound$.onTick(Sound.scala:122)
+   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_103_Sound$_onTick_ClientTickEvent.invoke(.dynamic)
+   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
+   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
+   at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:366)
+   at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1609
```

Same setup works on linux properly.

**Comment by fnuecke** [comment]
Are you sure you have the right OC version for the MC version?
If so, full log please?

**Comment by fagci** [comment]
Sorry. Really wrong version..downloaded for 1.8.8...
Thanks! Updated to latest=)
