### ISSUE TITLE
Error creating the world

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#163]
Hi!
On my client installed 48 mods. If i delete BiomesOPlenty, client crash after 1 minute in game. Sometimes without error.

[20:57:02 INFO]: Client> 2014-03-16 20:57:02 [WARNING] [OpenComputers] Update check failed.
[20:57:02 INFO]: Client> java.lang.NoClassDefFoundError: scala/io/BufferedSource
[20:57:02 INFO]: Client>    at scala.io.Source$.createBufferedSource(Source.scala:161)
[20:57:02 INFO]: Client>    at scala.io.Source$.fromInputStream(Source.scala:168)
[20:57:02 INFO]: Client>    at li.cil.oc.UpdateCheck$.initialize(UpdateCheck.scala:36)
[20:57:02 INFO]: Client>    at li.cil.oc.UpdateCheck$.result$lzycompute(UpdateCheck.scala:21)
[20:57:02 INFO]: Client>    at li.cil.oc.UpdateCheck$.result(UpdateCheck.scala:21)
[20:57:02 INFO]: Client>    at li.cil.oc.UpdateCheck$$anon$1.run(UpdateCheck.scala:25)
[20:57:02 INFO]: Client> Caused by: java.lang.ClassNotFoundException: scala.io.BufferedSource
[20:57:02 INFO]: Client>    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
[20:57:02 INFO]: Client>    at java.lang.ClassLoader.loadClass(Unknown Source)
[20:57:02 INFO]: Client>    at java.lang.ClassLoader.loadClass(Unknown Source)
[20:57:02 INFO]: Client>    ... 6 more
[20:57:02 INFO]: Client> Caused by: java.lang.NoClassDefFoundError: scala/io/Source
[20:57:02 INFO]: Client>    at java.lang.ClassLoader.defineClass1(Native Method)
[20:57:02 INFO]: Client>    at java.lang.ClassLoader.defineClass(Unknown Source)
[20:57:02 INFO]: Client>    at java.security.SecureClassLoader.defineClass(Unknown Source)
[20:57:02 INFO]: Client>    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
[20:57:02 INFO]: Client>    ... 8 more
[20:57:02 INFO]: Client> Caused by: java.lang.ClassNotFoundException: scala.io.Source
[20:57:02 INFO]: Client>    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:97)
[20:57:02 INFO]: Client>    at java.lang.ClassLoader.loadClass(Unknown Source)
[20:57:02 INFO]: Client>    at java.lang.ClassLoader.loadClass(Unknown Source)
[20:57:02 INFO]: Client>    ... 12 more

**Comment by fnuecke** [comment]
Can you post the full log, please? (pastebin or so)

**Comment by ghost** [comment]
Of course.
Log with new error:
http://rghost.ru/53110327
And if i give 2GB for Minecraft:
http://rghost.ru/53110483
Client simply freezes.

And sorry for my English :)

**Comment by fnuecke** [comment]
Yeah, the first one is definitely the PermGen memory being too low. Since you're writing 2G which is much too large a value to be PermGen, did you also increase that?
I.e. `-XX:MaxPermSize=256m -XX:PermSize=256m`?

If so, I have no idea why it'd just freeze without an error. The mod list doesn't look too massive, so maybe you could try to figure out in combination with which mod(s) this happens? That would at least give me a lead to investigate. Thanks!

**Comment by ghost** [comment]
Thank, flag "-XX: MaxPermSize = 256m-XX: PermSize = 256m" solved my problem.
But I never use it, is this normal? This is not a problem of mod?

**Comment by fnuecke** [comment]
That's normal when you use a lot of mods. It controls the amount of memory Java reserves for the actual classes - the more mods, the more classes, the more memory needed.
