### ISSUE TITLE
"There were errors running the class transformer. ..."

### ISSUE THREAD

**Issue by LlubNek** [MightyPirates/OpenComputers#1636]
When entering a new world this message appeared in chat:

> OpenComputers: There were errors running the class transformer. Please report this, together with your (full!) FML latest.log/fml-server-latest.log logfile, thank you!

Here's latest.log:
http://pastebin.com/tWiqJVxG

**Comment by mmalfatti** [comment]
Same issue.  I am running Buildcraft Dev version.  Without Buildcraft message does not show up.

Thank you.

[Archive.zip](https://github.com/MightyPirates/OpenComputers/files/118801/Archive.zip)

**Comment by HalestormXV** [comment]
I can report I receive the same issue. Here is my log as well, rather than just create an entire new report that will likely be merged anyway.:

As requested here is the fml-server-latest.log: http://pastebin.com/EmLr4gQM

Regards,

**Comment by gamax92** [comment]
For existing and future people: Please note that this error message is a generic message and that the actual error behind them may not be the same. For example:
In mmalfatti's log (1.8.9):

```
java.lang.NullPointerException
    at DummyCore.ASM.DCASMManager.handlePotionColor(DCASMManager.java:91)
    at DummyCore.ASM.DCASMManager.transform(DCASMManager.java:55)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraft.block.Block.func_149671_p(Block.java:2272)
    at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:512)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1407)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
```

But in HalestormXV's log (1.7.10):

```
[00:03:35] [main/WARN] [OpenComputers/]: Something went wrong!
java.lang.ClassCircularityError: scala/collection/mutable/HashMap
    at scala.collection.mutable.ArrayOps$ofRef.<init>(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
    at scala.Predef$.refArrayOps(Predef.scala:339) ~[Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.21.41-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at cn.lambdalib.networkcall.asm.NetworkCallVisitor$NetworkCallMethodVisitor.visitAnnotation(NetworkCallVisitor.java:84) [NetworkCallVisitor$NetworkCallMethodVisitor.class:?]
    at org.objectweb.asm.ClassReader.b(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at cn.lambdalib.core.asm.RegistryTransformer.transform(RegistryTransformer.java:54) [RegistryTransformer.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_65]
    at java.lang.ClassLoader.defineClass(Unknown Source) [?:1.8.0_65]
    at java.security.SecureClassLoader.defineClass(Unknown Source) [?:1.8.0_65]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at scala.collection.AbstractSeq.<init>(Seq.scala:41) [AbstractSeq.class:?]
    at scala.collection.immutable.List.<init>(List.scala:83) [List.class:?]
    at scala.collection.immutable.Nil$.<init>(List.scala:419) [Nil$.class:?]
    at scala.collection.immutable.Nil$.<clinit>(List.scala) [Nil$.class:?]
    at scala.sys.SystemProperties$.propertyHelp$lzycompute(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.propertyHelp(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.addHelp(SystemProperties.scala:65) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.bool(SystemProperties.scala:68) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression$lzycompute(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$.<clinit>(NoStackTrace.scala) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22) [NoStackTrace$class.class:?]
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94) [BreakControl.class:?]
    at java.lang.Throwable.<init>(Unknown Source) [?:1.8.0_65]
    at scala.util.control.BreakControl.<init>(Breaks.scala:94) [BreakControl.class:?]
    at scala.util.control.Breaks.<init>(Breaks.scala:29) [Breaks.class:?]
    at scala.collection.Traversable$.<init>(Traversable.scala:95) [Traversable$.class:?]
    at scala.collection.Traversable$.<clinit>(Traversable.scala) [Traversable$.class:?]
    at scala.package$.<init>(package.scala:40) [package$.class:?]
    at scala.package$.<clinit>(package.scala) [package$.class:?]
    at scala.Predef$.<init>(Predef.scala:89) [Predef$.class:?]
    at scala.Predef$.<clinit>(Predef.scala) [Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.21.41-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_65]
    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:109) [KCauldron-1.7.10-1614.UNOFFICIAL.jar:1.7.10-1614.UNOFFICIAL]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [KCauldron-1.7.10-1614.UNOFFICIAL.jar:1.7.10-1614.UNOFFICIAL]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [KCauldron-1.7.10-1614.UNOFFICIAL.jar:1.7.10-1614.UNOFFICIAL]
```

These are not the same errors and belong in separate issues.

**Comment by gamax92** [comment]
@LlubNek Your log has no error message in it, can you upload your **fml-server-latest.log** file to pastebin instead?

**Comment by fnuecke** [comment]
@HalestormXV 's is reportedly fixed (see #1509) in a newer version of LambdaLib.

@mmalfatti 's indicates BC's `IToolWrench` interface changed, I'll look into adjusting for that.

@LlubNek What @gamax92 said.

**Comment by jhagrid77** [comment]
In about 4 days, I will upload mine, I have gotten this too, although I use 1.6 snapshot sooo.

**Comment by fnuecke** [comment]
Closing due to no feedback. If you get errors and have AcademyCraft installed and don't when you remove it, please continue the discussion in #1509.
