### ISSUE TITLE
idk, the game told me to report

### ISSUE THREAD

**Issue by el-germi** [MightyPirates/OpenComputers#1645]
relevant?:
`[04:23:11] [main/WARN] [OpenComputers]: Something went wrong!
java.lang.ClassCircularityError: scala/collection/mutable/HashMap
    at scala.collection.mutable.ArrayOps$ofRef.<init>(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
    at scala.Predef$.refArrayOps(Predef.scala:339) ~[Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.21.41-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at cn.lambdalib.networkcall.asm.NetworkCallVisitor$NetworkCallMethodVisitor.visitAnnotation(NetworkCallVisitor.java:90) [NetworkCallVisitor$NetworkCallMethodVisitor.class:?]
    at org.objectweb.asm.ClassReader.b(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at cn.lambdalib.core.asm.RegistryTransformer.transform(RegistryTransformer.java:60) [RegistryTransformer.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_71]
    at java.lang.ClassLoader.defineClass(Unknown Source) [?:1.8.0_71]
    at java.security.SecureClassLoader.defineClass(Unknown Source) [?:1.8.0_71]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at scala.collection.AbstractSeq.<init>(Seq.scala:41) [AbstractSeq.class:?]
    at scala.collection.immutable.List.<init>(List.scala:83) [List.class:?]
    at scala.collection.immutable.Nil$.<init>(List.scala:419) [Nil$.class:?]
    at scala.collection.immutable.Nil$.<clinit>(List.scala) [Nil$.class:?]
    at scala.sys.SystemProperties$.propertyHelp$lzycompute(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.propertyHelp(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.addHelp(SystemProperties.scala:65) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.bool(SystemProperties.scala:68) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression$lzycompute(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$.<clinit>(NoStackTrace.scala) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22) [NoStackTrace$class.class:?]
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94) [BreakControl.class:?]
    at java.lang.Throwable.<init>(Unknown Source) [?:1.8.0_71]
    at scala.util.control.BreakControl.<init>(Breaks.scala:94) [BreakControl.class:?]
    at scala.util.control.Breaks.<init>(Breaks.scala:29) [Breaks.class:?]
    at scala.collection.Traversable$.<init>(Traversable.scala:95) [Traversable$.class:?]
    at scala.collection.Traversable$.<clinit>(Traversable.scala) [Traversable$.class:?]
    at scala.package$.<init>(package.scala:40) [package$.class:?]
    at scala.package$.<clinit>(package.scala) [package$.class:?]
    at scala.Predef$.<init>(Predef.scala:89) [Predef$.class:?]
    at scala.Predef$.<clinit>(Predef.scala) [Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.21.41-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.Class.getDeclaredConstructors0(Native Method) [?:1.8.0_71]
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) [?:1.8.0_71]
    at java.lang.Class.getConstructor0(Unknown Source) [?:1.8.0_71]
    at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_71]
    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:108) [forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[04:23:11] [main/WARN] [OpenComputers]: Something went wrong!
java.lang.ClassCircularityError: scala/collection/mutable/HashMap
    at scala.collection.mutable.ArrayOps$ofRef.<init>(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
    at scala.Predef$.refArrayOps(Predef.scala:339) ~[Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.21.41-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at cn.lambdalib.networkcall.asm.NetworkCallVisitor$NetworkCallMethodVisitor.visitAnnotation(NetworkCallVisitor.java:91) [NetworkCallVisitor$NetworkCallMethodVisitor.class:?]
    at org.objectweb.asm.ClassReader.b(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) [asm-all-5.0.3.jar:5.0.3]
    at cn.lambdalib.core.asm.RegistryTransformer.transform(RegistryTransformer.java:60) [RegistryTransformer.class:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_71]
    at java.lang.ClassLoader.defineClass(Unknown Source) [?:1.8.0_71]
    at java.security.SecureClassLoader.defineClass(Unknown Source) [?:1.8.0_71]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at scala.collection.AbstractSeq.<init>(Seq.scala:41) [AbstractSeq.class:?]
    at scala.collection.immutable.List.<init>(List.scala:83) [List.class:?]
    at scala.collection.immutable.Nil$.<init>(List.scala:419) [Nil$.class:?]
    at scala.collection.immutable.Nil$.<clinit>(List.scala) [Nil$.class:?]
    at scala.sys.SystemProperties$.propertyHelp$lzycompute(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.propertyHelp(SystemProperties.scala:63) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.addHelp(SystemProperties.scala:65) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.bool(SystemProperties.scala:68) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression$lzycompute(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.sys.SystemProperties$.noTraceSupression(SystemProperties.scala:80) [SystemProperties$.class:?]
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$.<clinit>(NoStackTrace.scala) [NoStackTrace$.class:?]
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22) [NoStackTrace$class.class:?]
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94) [BreakControl.class:?]
    at java.lang.Throwable.<init>(Unknown Source) [?:1.8.0_71]
    at scala.util.control.BreakControl.<init>(Breaks.scala:94) [BreakControl.class:?]
    at scala.util.control.Breaks.<init>(Breaks.scala:29) [Breaks.class:?]
    at scala.collection.Traversable$.<init>(Traversable.scala:95) [Traversable$.class:?]
    at scala.collection.Traversable$.<clinit>(Traversable.scala) [Traversable$.class:?]
    at scala.package$.<init>(package.scala:40) [package$.class:?]
    at scala.package$.<clinit>(package.scala) [package$.class:?]
    at scala.Predef$.<init>(Predef.scala:89) [Predef$.class:?]
    at scala.Predef$.<clinit>(Predef.scala) [Predef$.class:?]
    at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:164) [OpenComputers-MC1.7.10-1.5.21.41-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_71]
    at java.lang.Class.getDeclaredConstructors0(Native Method) [?:1.8.0_71]
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) [?:1.8.0_71]
    at java.lang.Class.getConstructor0(Unknown Source) [?:1.8.0_71]
    at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_71]
    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:108) [forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by jhagrid77** [comment]
This about the class transformer?

**Comment by fnuecke** [comment]
Looks like #1509.
