### ISSUE TITLE
Near infinite hang on crafting.

### ISSUE THREAD

**Issue by NoxyNixie** [MightyPirates/OpenComputers#1651]
While playing around with enviromine and backpacks I wanted to automate the process a bit using OC. While seeing if OC was capable of crafting with these enviromine backpacks that are attached to armors I found a (near) deadlock.

The code that triggered the deadlock while having one bottle of water next to a armor with a backpack attached to it:

``` lua
=component.crafting.craft()
```

(Yes that was all)

Eventhough I am not entirely certain I am highly suspicious of the following line of code: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/UpgradeCrafting.scala#L30 

To verify this suspicion I tried the code:

``` lua
=component.crafting.craft(1)
```

with the exact same items and it worked perfectly.

May I propose a change where `Int.MaxValue` is changed into `64`.

Hope this bug report is helpful and thanks for the always awesome Open Computers ;)

Below I provide a jstack -l I did during this hang of the main thread:

```
"Server thread" prio=10 tid=0x00007fc148d1c800 nid=0x6827 runnable [0x00007fc136ace000]
   java.lang.Thread.State: RUNNABLE
        at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(SourceFile:31)
        at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
        at li.cil.oc.server.component.UpgradeCrafting$CraftingInventory$$anonfun$craft$1.apply$mcV$sp(UpgradeCrafting.scala:46)
        at scala.util.control.Breaks.breakable(Breaks.scala:38)
        at li.cil.oc.server.component.UpgradeCrafting$CraftingInventory$.craft(UpgradeCrafting.scala:44)
        at li.cil.oc.server.component.UpgradeCrafting.craft(UpgradeCrafting.scala:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123)
        at li.cil.oc.server.network.Component$class.invoke(Component.scala:113)
        at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:599)
        at li.cil.oc.server.network.Component$class.invoke(Component.scala:20)
        at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:599)
        at li.cil.oc.server.machine.Machine.invoke(Machine.scala:336)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
        at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74)
        at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24)
        at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method)
        at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:677)
        - locked <0x00000006f8c389c8> (a li.cil.repack.com.naef.jnlua.LuaState)
        at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runSynchronized(NativeLuaArchitecture.scala:180)
        at li.cil.oc.server.machine.Machine.update(Machine.scala:515)
        at li.cil.oc.common.EventHandler$$anonfun$onServerTick$2.apply(EventHandler.scala:142)
        at li.cil.oc.common.EventHandler$$anonfun$onServerTick$2.apply(EventHandler.scala:140)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
        at li.cil.oc.common.EventHandler$.onServerTick(EventHandler.scala:140)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_780_EventHandler$_onServerTick_ServerTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by fnuecke** [comment]
Thanks for reporting this!
