### ISSUE TITLE
vis_reader:getAspects()

### ISSUE THREAD

**Issue by nailfor** [MightyPirates/OpenComputers#1666]
im trying get aspects from vis reader, his connected to essentia locus by crystalline eye and show all essentia of my base.
When im call getAspects() method im get error "invalid type of return value 0: expected TABLE, got [{name=Tenebrae, quantity=573},//here all essentia of my base separated by {..}//]
stack traceback:
[0]: in function 'error'
machine: 971: in function machine:968
"

**Comment by fnuecke** [comment]
What versions? I'm assuming MC 1.7.10 because the integration was disabled in 1.8 until today.

If you weren't on the latest OC version please grab a dev-build and try with that (Jenkins is at ci.cil.li).

**Comment by nailfor** [comment]
yes, it is MC 1.7.10.
ok, I'll write a after test

**Comment by nailfor** [comment]
after loading "dev" version i have server crash

```
[18:19:50] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[18:19:50] [Server thread/ERROR] [FML]: 
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCH     mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
        UCH     FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
        UCH     Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
        UCH     appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
        UCH     CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
        UCH     MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
        UCH     NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) 
        UCH     OpenComputers|Core{1.5.22.46} [OpenComputers (Core)] (minecraft.jar) 
        UCH     OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
        UCH     WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
        UCH     OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
        UCH     <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
        UCH     CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
        UCH     BuildCraft|Core{7.1.15} [BuildCraft] (buildcraft-7.1.15.jar) 
        UCH     BuildCraft|Transport{7.1.15} [BC Transport] (buildcraft-7.1.15.jar) 
        UCH     BuildCraft|Silicon{7.1.15} [BC Silicon] (buildcraft-7.1.15.jar) 
        UCH     BuildCraft|Factory{7.1.15} [BC Factory] (buildcraft-7.1.15.jar) 
        UCH     additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.1.jar) 
        UCH     AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
        UCH     appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
        UCH     Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
        UCH     Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
        UCH     arcanearteries{5} [Arcane Arteries] (ArcaneArteries0.8.2.jar) 
        UCH     Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
        UCH     Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
        UCH     bagginses{2.1.1} [Bagginses] (Bagginses-2.1.1.jar) 
        UCH     BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) 
        UCH     ExtrabiomesXL{3.16.1} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.1.jar) 
        UCH     BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) 
        UCH     Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
        UCH     Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
        UCH     Forestry{3.6.12.3} [Forestry for Minecraft] (forestry_1.7.10-3.6.12.3.jar) 
        UCH     BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
        UCH     BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
        UCH     Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
        UCH     ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
        UCH     ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
        UCH     Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
        UCH     AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
        UCH     Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
        UCH     BuildCraft|Builders{7.1.15} [BC Builders] (buildcraft-7.1.15.jar) 
        UCH     BuildCraft|Energy{7.1.15} [BC Energy] (buildcraft-7.1.15.jar) 
        UCH     BuildCraft|Robotics{7.1.15} [BC Robotics] (buildcraft-7.1.15.jar) 
        UCH     BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
        UCH     CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
        UCH     Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
        UCH     ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
        UCH     chisel{2.3.9.36} [Chisel 2] (Chisel2-2.3.9.36.jar) 
        UCH     ChiselFacades{1.7.10-2.10-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.10-cricket.jar) 
        UCH     climatecontrol{0.4} [Climate Control] (ClimateControl-0.4.beta17.jar) 
        UCH     inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
        UCH     CreeperCollateral{1.7.10R1.0.0B3} [CreeperCollateral] (CreeperCollateral-[1.7.10]1.0.0B3-6.jar) 
        UCH     Enchiridion2{2.0f} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0f-63.jar) 
        UCH     Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) 
        UCH     EnderZoo{1.7.10-1.0.9.18} [Ender Zoo] (EnderZoo-1.7.10-1.0.9.18.jar) 
        UCH     EnhancedInventories{1.7.10-1.0.11} [Enhanced Inventories] (EnhancedInventories-1.7.10-1.0.11.jar) 
        UCH     TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
        UCH     ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
        UCH     FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
        UCH     ForbiddenMagic{1.7.10-0.573} [Forbidden Magic] (Forbidden Magic-1.7.10-0.573.jar) 
        UCH     GardenCore{1.7.10-1.5.6} [Garden Core] (GardenStuff-1.7.10-1.5.6.jar) 
        UCH     GardenContainers{1.7.10-1.5.6} [Garden Containers] (GardenStuff-1.7.10-1.5.6.jar) 
        UCH     GardenStuff{1.7.10-1.5.6} [Garden Stuff] (GardenStuff-1.7.10-1.5.6.jar) 
        UCH     GardenTrees{1.7.10-1.5.6} [Garden Trees] (GardenStuff-1.7.10-1.5.6.jar) 
        UCH     GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) 
        UCH     guideapi{1.7.10-1.0.1-23} [Guide-API] (Guide-API-1.7.10-1.0.1-23.jar) 
        UCH     HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode] (HQM-The Journey (4.2.4).jar) 
        UCH     JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
        UCH     magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) 
        UCH     MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) 
        UCH     Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
        UCH     MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
        UCH     Mekanism{8.1.8} [Mekanism] (Mekanism-1.7.10-8.1.8.258.jar) 
        UCH     MekanismGenerators{8.1.8} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.8.258.jar) 
        UCH     MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
        UCH     MobProperties{0.3.3} [Mob Properties] (MobProperties-1.7.10-0.3.4.jar) 
        UCH     modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
        UCH     NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) 
        UCH     NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) 
        UCH     NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) 
        UCH     NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) 
        UCH     NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) 
        UCH     NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
        UCH     MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
        UCH     ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
        UCH     ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
        UCE     OpenComputers{1.5.22.46} [OpenComputers] (OpenComputers-MC1.7.10-1.5.22.46-dev.jar) 
        UCH     OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
        UCH     OpenPeripheralCore{1.3} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-7.jar) 
        UCH     OpenPeripheral{0.5.1} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-7.jar) 
        UCH     OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-7.jar) 
        UCH     ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
        UCH     ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
        UCH     ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
        UCH     Quadrum{1.2.0} [Quadrum] (Quadrum-1.7.10-1.2.0.B13-universal.jar) 
        UCH     AS_Ruins{14.6} [Ruins Spawning System] (Ruins-1.7.10.jar) 
        UCH     Sanguimancy{1.7.10-1.1.9-33} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-33.jar) 
        UCH     StevesBarrenLands{1} [Steve's Barren Lands] (StevesBarrenLands.jar) 
        UCH     StorageDrawers{1.7.10-1.8.0} [Storage Drawers] (StorageDrawers-1.7.10-1.8.0.jar) 
        UCH     StorageDrawersForestry{1.7.10-1.1.2} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.1.2.jar) 
        UCH     StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.1.jar) 
        UCH     supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) 
        UCH     thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) 
        UCH     ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
        UCH     TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
        UCH     witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
        UCH     WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
        UCH     McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
        UCH     IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) 
        UCH     ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
[18:19:50] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[18:19:50] [Server thread/ERROR] [FML]: Caught exception from OpenComputers
java.lang.NoSuchFieldError: iron
        at li.cil.oc.common.block.SimpleBlock$.$lessinit$greater$default$1(SimpleBlock.scala:28) ~[SimpleBlock$.class:?]
        at li.cil.oc.common.block.Switch.<init>(Switch.scala:11) ~[Switch.class:?]
        at li.cil.oc.common.block.AccessPoint.<init>(AccessPoint.scala:8) ~[AccessPoint.class:?]
        at li.cil.oc.common.init.Blocks$.init(Blocks.scala:42) ~[Blocks$.class:?]
        at li.cil.oc.common.Proxy.preInit(Proxy.scala:33) ~[Proxy.class:?]
        at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34) ~[OpenComputers$.class:?]
        at li.cil.oc.OpenComputers.preInit(OpenComputers.scala) ~[OpenComputers.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[18:19:50] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: iron

        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559) ~[Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchFieldError: iron
        at li.cil.oc.common.block.SimpleBlock$.$lessinit$greater$default$1(SimpleBlock.scala:28) ~[SimpleBlock$.class:?]
        at li.cil.oc.common.block.Switch.<init>(Switch.scala:11) ~[Switch.class:?]
        at li.cil.oc.common.block.AccessPoint.<init>(AccessPoint.scala:8) ~[AccessPoint.class:?]
        at li.cil.oc.common.init.Blocks$.init(Blocks.scala:42) ~[Blocks$.class:?]
        at li.cil.oc.common.Proxy.preInit(Proxy.scala:33) ~[Proxy.class:?]
        at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34) ~[OpenComputers$.class:?]
        at li.cil.oc.OpenComputers.preInit(OpenComputers.scala) ~[OpenComputers.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) ~[Loader.class:?]
        ... 5 more
[18:19:50] [Server thread/ERROR]: This crash report has been saved to: /opt/usr/minecraft/regrowth2/./crash-reports/crash-2016-03-14_18.19.50-server.txt
[18:19:50] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[18:19:50] [Server thread/INFO] [FML]: Applying holder lookups
[18:19:50] [Server thread/INFO] [FML]: Holder lookups applied
Mar 14, 2016 6:19:50 PM climateControl.utils.ConfigManager clearWorldFile
INFO: clearing 
[18:19:50] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:19:50] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

```

**Comment by fnuecke** [comment]
`-dev`/`-dev-dev` is deobf, i.e. for other mod developers, you need the `-universal` ones.

**Comment by nailfor** [comment]
hmm... so i already have last -universal version in first message
