### ISSUE TITLE
Apparent IC2 Issue

### ISSUE THREAD

**Issue by Matchlighter** [MightyPirates/OpenComputers#180]
I'm getting a lag-spike when attempting to access a computer or server case. This occasionally appears in the log as well:

```
2014-03-27 19:36:07 [WARNING] [OpenComputers] Error in scheduled tick action.
java.lang.NullPointerException
at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:26)
at net.minecraftforge.event.ASMEventHandler_54_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
at net.minecraftforge.event.EventBus.post(EventBus.java:108)
at li.cil.oc.server.TickHandler$$anonfun$scheduleIC2Add$1.apply$mcV$sp(TickHandler.scala:32)
at li.cil.oc.server.TickHandler$$anonfun$tickEnd$1.apply(TickHandler.scala:53)
at li.cil.oc.server.TickHandler$$anonfun$tickEnd$1.apply(TickHandler.scala:52)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
at li.cil.oc.server.TickHandler$.tickEnd(TickHandler.scala:52)
at li.cil.oc.server.TickHandler$.tickEnd(TickHandler.scala:15)
at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:274)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:622)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-03-27 19:36:07 [WARNING] [Minecraft-Server] Can't keep up! Did the system time change, or is the server overloaded?
```

Problem in 1.2.3 or 1.2.4.

**Comment by Matchlighter** [comment]
58dcea4f629ae9bbd5cea18b02684f2729b22aa1 Fixes the console spam, but there is still a lag-spike accompanied by `Can't keep up! Did the system time change, or is the server overloaded?`

**Comment by fnuecke** [comment]
So to clarify: this happens _every_ time you open the GUI of a computer case or sever rack?

**Comment by Matchlighter** [comment]
Yes. But it _may_ be fixed in the latest dev build - I retried the latest build a few hours ago (as opposed to the latest build when posting the issue) and it doesn't seem to cause the lag spike anymore.

**Comment by fnuecke** [comment]
Well, let's hope it stays this way :-)
