### ISSUE TITLE
Crash mit Chromaticraft

### ISSUE THREAD

**Issue by Ryius** [MightyPirates/OpenComputers#1902]
sobald ich von dem Mod Chromaticraft die Bloecke World Rift setzte beckomme ich diesen Crash
java.lang.NullPointerException: Unexpected error
    at li.cil.oc.server.network.Network.contains(Network.scala:212)
    at li.cil.oc.server.network.Network.connect(Network.scala:79)
    at li.cil.oc.server.network.Network$Wrapper.connect(Network.scala:749)
    at li.cil.oc.server.network.Node$class.connect(Node.scala:38)
    at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.connect(Network.scala:599)
    at Reika.ChromatiCraft.TileEntity.Transport.TileEntityRift.onLinkTo(TileEntityRift.java:221)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:61)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:93)
    at Reika.ChromatiCraft.Items.ItemLinkedTilePlacer.func_77648_a(ItemLinkedTilePlacer.java:88)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Haggle1996** [comment]
ReikaKalseki/Reika_Mods_Issues#992

**Comment by Ryius** [comment]
Yep thanks

**Comment by Ryius** [comment]
@Haggle1996 have you prove the Issue or is it just for me

**Comment by Haggle1996** [comment]
I can replicate your scenario exactly; OpenComputers, DragonAPI, and ChromatiCraft, all latest versions.

EDIT: I don't know which side is at fault, except that ChromatiCraft works for me if I take out OpenComputers.

**Comment by Ryius** [comment]
ah and it crashed?

**Comment by Ryius** [comment]
okey thanks for your help

**Comment by Ryius** [comment]
still not fixed

**Comment by Ryius** [comment]
is ther a fix coming ?

**Comment by payonel** [comment]
i can't get this to crash now. i can place tons of rifts, computers, etc -- no crash
