### ISSUE TITLE
FileNotFoundException on first start

### ISSUE THREAD

**Issue by Player3324** [MightyPirates/OpenComputers#1924]
Looks like an ordering issue, just annoying console spam.

```
[Server thread/WARN] [OpenComputers]: Failed saving config.
java.io.FileNotFoundException: /home/minecraft/mc/config/opencomputers/settings.conf (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
at java.io.PrintWriter.<init>(PrintWriter.java:263)
at li.cil.oc.Settings$.load(Settings.scala:472)
at li.cil.oc.common.Proxy.preInit(Proxy.scala:36)
at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:37)
at li.cil.oc.OpenComputers.preInit(OpenComputers.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:573)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:593)
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by Inari-Whitebear** [comment]
I also noticed that on first start it makes no settings file, just the recipe configs :/ Had to start it again to get the settings config too

**Comment by fnuecke** [comment]
Hrrm, I'm afraid I can't reproduce this, and I don't see why this would happen in the first place. Maybe it's a Linux only thing? I'd need to set up a VM to test in that case.

**Comment by Inari-Whitebear** [comment]
I'm using windows.

**Comment by fnuecke** [comment]
Welp, then I _really_ don't know why/when this would happen.

**Comment by Inari-Whitebear** [comment]
Said this on IRC already but Sangar went away again, so just going to note it here:

Well it happens on first start. So I think, it is because the folder isn't there yet, hence a file cannot be created. The recipe-writing stuff creates the folder, but those are after the settings conf

**Comment by fnuecke** [comment]
Good point. Let's see if this fixes it...
