### ISSUE TITLE
[1.10.2] Computer system not accepting power

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1937]
This bug was observed on a testing server for ME^EX 1.10.2, our curse modpack, which is running the latest version of OpenComputers for MineCraft 1.10.2. In essence, I was not able to feed power into my capacitor, my power converter, or my tier 3 computer case, the only OC objects I tried it with. I tried to feed power in using the following methods, each one resulting with total failure: a hand cranked generator as well as an advanced power cube from Calculator, an enhanced energy conduit and a basic capacitor bank from EnderIO, a clockwork engine from forestry, a generator from TechReborn (I know EU isn't supposed to work, but I tried it anyways), and a power relay from RFTools. I am most certainly positive that every system I tried had power to supply, but none of the apparatus would accept it: conduits wouldn't connect, and clockwork engine didn't auto-align; further, an analyzer and many failed attempts at starting my computer confirm that it indeed accepted none of my power. If you wish to join the server to see for yourself, please give me your MineCraft IGN so I can whitelist you.

~Sam

**Comment by xarses** [comment]
There should be some log messages either during initialization or when you attempt to connect the power provider up to the OC Power converter. If so these may be helpful. I'm not sure about 1.10, but RF and EU mods work just fine in 1.7.10 so I'd expect them to continue to function

**Comment by dgilbert999** [comment]
I'm seeing the same issue with OpenComputers-MC1.10-1.6.0.2-beta.4.jar   Tried direct connect with EnderIO generator, then with EnderIO conduit, then tried to use OpenComputers energy converter. none of them would connect.

**Comment by xarses** [comment]
do the computers register that the require power? Please check the logs for any messages about what's going on

**Comment by ghost** [comment]
I'm seeing no messages of this nature in the in game chat, game output, or log file. Analyzer output isn't helping either.

**Comment by fnuecke** [comment]
I'm wondering if maybe they've completely switched to capabilities... will look into it when I'm back.

**Comment by ghost** [comment]
Tried a generator from IndustrialCraft found this in the fml-server-latest.log, hope it helps:

`[14:53:27] [Server thread/WARN] [OpenComputers/]: Error in scheduled tick action.
java.lang.ClassCastException: li.cil.oc.common.tileentity.Case cannot be cast to ic2.api.energy.tile.IEnergyTile
    at li.cil.oc.common.EventHandler$$anonfun$scheduleIC2Add$1.apply$mcV$sp(EventHandler.scala:116) ~[EventHandler$$anonfun$scheduleIC2Add$1.class:?]
    at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:161) [EventHandler$$anonfun$onServerTick$1.class:?]
    at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:160) [EventHandler$$anonfun$onServerTick$1.class:?]
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [IndexedSeqOptimized$class.class:?]
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ArrayOps$ofRef.class:?]
    at li.cil.oc.common.EventHandler$.onServerTick(EventHandler.scala:160) [EventHandler$.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_404_EventHandler$_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

Edit: No error / console output while trying RF Power (conduits just won't connect)

**Comment by ghost** [comment]
bug MINOR! I can't use anything from the mod!

**Comment by skyem123** [comment]
@samuelroy21, it's "minor" as it's hopefully relatively easy to fix. It's not fixed already because @fnuecke is busy and hasn't got much spare time to actually work on it.
Hopefully he gets some free time soon, so he can actually work on OC (and other things)! :stuck_out_tongue: 

It's worth noting that you're running the current Beta of OC, and on top of that, the first release for MC 1.10, it being broken (even in a way that makes it unusable in survival) is not that surprising.

However, I do hope that it gets fixed soon! Let's wish @fnuecke luck and free time, etc!

**Comment by WhiteScholar** [comment]
For the time being you can continue to use the mod by setting the config to not require power, and reenable power needs at a later time when things are working again.

**Comment by payonel** [comment]
might I add that it is "minor" because there is a work around, in addition to it being a 1.10 bug (which is a lower priority version at this time)

**Comment by jmcaffee** [comment]
Same issue here: Doesn't accept power from Ender IO conduit.

Minecraft 1.10.2
Pack: All the Mods (beta)

Here's the log output:

```
[20:46:29] [Server thread/WARN]: Error in scheduled tick action.
java.lang.ClassCastException: li.cil.oc.common.tileentity.PowerConverter cannot be cast to ic2.api.energy.tile.IEnergyTile
    at li.cil.oc.common.EventHandler$$anonfun$scheduleIC2Add$1.apply$mcV$sp(EventHandler.scala:116) ~[EventHandler$$anonfun$scheduleIC2Add$1.class:?]
    at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:161) [EventHandler$$anonfun$onServerTick$1.class:?]
    at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:160) [EventHandler$$anonfun$onServerTick$1.class:?]
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [IndexedSeqOptimized$class.class:?]
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ArrayOps$ofRef.class:?]
    at li.cil.oc.common.EventHandler$.onServerTick(EventHandler.scala:160) [EventHandler$.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_803_EventHandler$_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[20:46:58] [Server thread/WARN]: Error in scheduled tick action.
java.lang.ClassCastException: li.cil.oc.common.tileentity.PowerConverter cannot be cast to ic2.api.energy.tile.IEnergyTile
    at li.cil.oc.common.EventHandler$$anonfun$scheduleIC2Add$1.apply$mcV$sp(EventHandler.scala:116) ~[EventHandler$$anonfun$scheduleIC2Add$1.class:?]
    at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:161) [EventHandler$$anonfun$onServerTick$1.class:?]
    at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:160) [EventHandler$$anonfun$onServerTick$1.class:?]
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [IndexedSeqOptimized$class.class:?]
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ArrayOps$ofRef.class:?]
    at li.cil.oc.common.EventHandler$.onServerTick(EventHandler.scala:160) [EventHandler$.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_803_EventHandler$_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

```

**Comment by Redlotus99** [comment]
I assume this fix has not been pushed to Curse as of yet?

**Comment by DarkMorford** [comment]
This appears to still be an issue in OC 1.6.0.4 (using the Direwolf20 mod pack). I can use the Power Converter block to get energy into my computer, but the computer case itself won't accept RF energy.

**Comment by payonel** [comment]
This appears to only have been merged to our minecraft 1.10 versions (not 1.7.10 nor any other)
OpenComputerse version 1.6 and 1.6-dev have this fix (for minecraft 1.10) since August.
If you are using a stable build, it would need to be equal or later than: OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
If you are using dev releases, it would need to be equal or later than: OpenComputers-MC1.10.2-1.6.0.25-dev.jar

If you need to update, please use our latest version on curse:
https://minecraft.curseforge.com/projects/opencomputers/files
direct link: https://minecraft.curseforge.com/projects/opencomputers/files/2344182

**Comment by payonel** [comment]
@DarkMorford I probably closed this ticket in error. "OC 1.6.0.4" is probably referring to OpenComputers-MC1.10.2-1.6.0.4.jar which IS for 1.10. Can you confirm that is the version you are using?

**Comment by DarkMorford** [comment]
I am using OpenComputers-MC1.10.2-1.6.0.4.jar, yes. However, after doing some more research, I seem to have misidentified the issue. The computer cases do seem to be correctly handling the RF API (i.e., power conduits connect to them), but they don't appear to have any internal buffer. Using an Analyzer on the computer shows "Total stored energy: 0.00/0.00".
Connecting a Power Converter block to the computer gives it a buffer of 1000, which fills from the power supply and allows the computer to run, but removing that block drops the buffer back to 0/0 and halts the computer.
Curiously, if I restart the server any computers that had already been placed have a power buffer of 500, as configured. Breaking and replacing them resets their buffer capacity back to 0, so this seems to only affect newly-placed computers.
I'd be happy to file this as a new issue if you'd like, and I'll provide logs or other information if you need it.

**Comment by payonel** [comment]
@DarkMorford very good update, thank you. I'll make a new ticket for you and close this one.
