### ISSUE TITLE
Crash: ME Upgrade in Upgrade Container

### ISSUE THREAD

**Issue by amesgen** [MightyPirates/OpenComputers#1981]
My game crashes if I place a ME Upgrade (Tier II) in a Tier II Upgrade Container in a robot.
https://gist.github.com/condensedapple/c0c015196579a7194eb517aa194fb24d

Using latest OC and EC release.
Also see https://github.com/ExtraCells/ExtraCells2/issues/413

EDIT: After a restart, the ME Upgrade is actually in the robot, but the Robot GUI cant be opened anymore, and the robot is rapidly changing its name in its WAIlA display (its name in my inventory remains the same). Renaming in an anvil does not help, so the robot is now completely unusable.

**Comment by inklit** [comment]
This also happens with Chunk Loader Upgrades.

**Comment by amesgen** [comment]
Here is the error message in the terminal on world loading:

```
[16:38:51] [Server thread/WARN] [OpenComputers]: There was a problem writing a TileEntity description packet. Please report this if you see it!
java.lang.AbstractMethodError
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$2.apply$mcVI$sp(ComponentInventory.scala:52) ~[ComponentInventory$$anonfun$connectComponents$2.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$2.apply(ComponentInventory.scala:47) ~[ComponentInventory$$anonfun$connectComponents$2.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$2.apply(ComponentInventory.scala:47) ~[ComponentInventory$$anonfun$connectComponents$2.class:?]
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) ~[scala-library-2.11.1.jar:?]
        at scala.collection.immutable.Range.foreach(Range.scala:160) ~[scala-library-2.11.1.jar:?]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) ~[scala-library-2.11.1.jar:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.connectComponents(ComponentInventory.scala:47) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Robot.connectComponents(Robot.scala:51) ~[Robot.class:?]
        at li.cil.oc.common.tileentity.traits.ComponentInventory$class.writeToNBTForClient(ComponentInventory.scala:130) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$traits$Rotatable$$super$writeToNBTForClient(Robot.scala:51) ~[Robot.class:?]
        at li.cil.oc.common.tileentity.traits.Rotatable$class.writeToNBTForClient(Rotatable.scala:144) ~[Rotatable$class.class:?]
        at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$traits$RedstoneAware$$super$writeToNBTForClient(Robot.scala:51) ~[Robot.class:?]
        at li.cil.oc.common.tileentity.traits.RedstoneAware$class.writeToNBTForClient(RedstoneAware.scala:121) ~[RedstoneAware$class.class:?]
        at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$traits$AbstractBusAware$$super$writeToNBTForClient(Robot.scala:51) ~[Robot.class:?]
        at li.cil.oc.common.tileentity.traits.AbstractBusAware$class.writeToNBTForClient(AbstractBusAware.scala:70) ~[AbstractBusAware$class.class:?]
        at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$traits$Computer$$super$writeToNBTForClient(Robot.scala:51) ~[Robot.class:?]
        at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBTForClient(Computer.scala:187) ~[Computer$class.class:?]
        at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$traits$PowerInformation$$super$writeToNBTForClient(Robot.scala:51) ~[Robot.class:?]
        at li.cil.oc.common.tileentity.traits.PowerInformation$class.writeToNBTForClient(PowerInformation.scala:49) ~[PowerInformation$class.class:?]
        at li.cil.oc.common.tileentity.Robot.writeToNBTForClient(Robot.scala:468) ~[Robot.class:?]
        at li.cil.oc.common.tileentity.RobotProxy.writeToNBTForClient(RobotProxy.scala:153) ~[RobotProxy.class:?]
        at li.cil.oc.common.tileentity.traits.TileEntity$class.getDescriptionPacket(TileEntity.scala:96) [TileEntity$class.class:?]
        at li.cil.oc.common.tileentity.RobotProxy.func_145844_m(RobotProxy.scala:24) [RobotProxy.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540) [mw.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276) [mw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
        at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

@inklit Do you have the same (or a similiar) error message?

**Comment by inklit** [comment]
I don't know if its similar or the same, but the server does crash under the same circumstances.
I can't really tell you the error message since I don't have a development server up right now and I disabled them on my public server to prevent crashing.

**Comment by fnuecke** [comment]
> java.lang.AbstractMethodError

Incompatible APIs. The version of EC you have probably uses the OC 1.5 API.

**Comment by amesgen** [comment]
@DrummerMC Does there exist a EC version with 1.6 support?
