### ISSUE TITLE
"no such method" for extended classes

### ISSUE THREAD

**Issue by einsteinK** [MightyPirates/OpenComputers#2007]
I got an environment that looks a bit like this (related to the bug):

``` java
public class MyThingy implements ManagedEnvironment {
    @Callback
    public Object[] basic(Context c, Arguments a) throws Exception {}
}
```

I got another environment that extends the first one:

``` java
public class MyAdvancedThingy extends MyThingy {
    @Callback
    public Object[] advanced(Context c, Arguments a) throws Exception {}
}
```

Using the component of the first class in-game works perfectly fine, just like expected.

For a component using the extended class:
When in-game displaying the component, both methods are shown (with their documentation). If I use component.methods, both are listed. I can index both functions, no problem.

The issue: When I try to call comp.basic(), it'll error "no such method". Calling comp.advanced() works fine. It seems like calling callbacks that aren't directly implemented in the environment is very... bad. This is especially weird considering that the method is listed and can be accessed. Only actually calling the function gives the error:

``` text
no such method
stack traceback:
    machine: 756: in function <machine:751>
    [C]: in function 'error'
    machine:984: in function <machine:981>
    (...tail calls...)
    [C]: in function 'xpcall'
    machine:751: in function 'xpcall'
    /bin/lua.lua:146: in main chunk
    [C]: in function 'xpcall'
    machine:751: in function 'xpcall'
    /lib/process.lua:78: in function </lib/process.lua:71>
```

_(Not very helpful. Here's my machine.lua: http://pastebin.com/FykuHgvW)_

After playing a bit around with string.dump and other stuff, I discovered that:
- Doing `component.invoke(address,"advanced")`  has the exact same error.
- The error isn't thrown in machine.lua but in Machine.scala or submethods _(based on ^)_

I've checked `Machine.invoke(address: String, method: String, args: blablabla)` a bit. If the node isn't a Component, it'll error. I've copied the address from in-game, ran some code to list all nodes in the network to check if it's a component, it gave me this node and its class:

``` text
Node(4bf61423-15d9-46ac-a42a-0c696cb38a90, li.cil.oc.server.driver.CompoundBlockEnvironment@61e6f2e0)@tardis_landingpad
class li.cil.oc.server.network.Network$ComponentBuilder$$anon$2
```

Seems right, as it should be, otherwise my `comp.advanced()` should _also_ fail.

I haven't gone further, I'm pretty sure this is a fault in OC, not my mod. The only thing I can do to "fix" it, is by (re)declaring all callbacks in my extended class. I'll guess that's what I'll do for now, as I don't really have another choice.

_(now that I'm gonna submit it, it seems I wrote a lot. Most seems useful-ish though... eh)_

**Comment by fnuecke** [comment]
Hrm, OC uses inheritance heavily in its components, and I've not seen this before. Not sure what's going on there. My best guess it that it might be related to the callback wrappers emitted dynamically (similar thing that's done for event handlers), and the emitted bytecode is somehow wrong for your scenario.

Try enabling `logCallbackErrors` in the config for a full stack trace and see where it happens exactly, please. Thanks.

**Comment by thiakil** [comment]
Running into this same issue. Seem to need to override both the method and the annotation for it to work (thereby making it redundant).

`[Server thread/WARN] [OpenComputers]: Exception in Lua callback.
java.lang.NoSuchMethodException
	at li.cil.oc.server.network.Component$class.invoke(Component.scala:113) ~[Component$class.class:?]
	at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:608) ~[Network$ComponentBuilder$$anon$2.class:?]
	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:358) ~[Machine.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) ~[ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) ~[ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24) [ExtendedLuaState$ExtendedLuaState$$anon$1.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) [LuaState.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:681) [LuaState.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runSynchronized(NativeLuaArchitecture.scala:177) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.Machine.update(Machine.scala:562) [Machine.class:?]
	at li.cil.oc.common.tileentity.traits.Computer$class.updateComputer(Computer.scala:120) [Computer$class.class:?]
	at li.cil.oc.common.tileentity.Case.updateComputer(Case.scala:28) [Case.class:?]
	at li.cil.oc.common.tileentity.traits.Computer$class.updateEntity(Computer.scala:103) [Computer$class.class:?]
	at li.cil.oc.common.tileentity.Case.updateEntity(Case.scala:69) [Case.class:?]
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6) [Tickable$class.class:?]
	at li.cil.oc.common.tileentity.Case.update(Case.scala:28) [Case.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1942) [World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:646) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:783) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`

Forge 12.18.3.2185 (1.10.2)
OC 1.6.2.7

**Comment by payonel** [comment]
@thiakil are you saying the solution is to override both and we can close this?
can you provide a code sample of the solution in this ticket for records

**Comment by thiakil** [comment]
I think i just had to structure differently, as it couldnt find the method somehow

**Comment by thiakil** [comment]
to use the OP's code, 

```
public class MyAdvancedThingy extends MyThingy {
    @Callback
    public Object[] advanced(Context c, Arguments a) throws Exception {}
    @Callback
    public Object[] basic(Context c, Arguments a) throws Exception {return super.basic(c,a);}
}
```

making inheritance a little silly

**Comment by payonel** [comment]
ah ok, i think this is a reasonable work around. not ideal, but i'm fine leaving things this way
thanks
