### ISSUE TITLE
Crash. NPE: Ticking block entity

### ISSUE THREAD

**Issue by tachigami** [MightyPirates/OpenComputers#2024]
```
java.lang.NullPointerException: Ticking block entity
    at li.cil.oc.common.tileentity.traits.Environment$class.isConnected(Environment.scala:30)
    at li.cil.oc.common.tileentity.Robot.isConnected(Robot.scala:51)
    at li.cil.oc.common.tileentity.traits.Computer$class.updateEntity(Computer.scala:111)
    at li.cil.oc.common.tileentity.Robot.func_145845_h(Robot.scala:326)
    at li.cil.oc.common.tileentity.RobotProxy.func_145845_h(RobotProxy.scala:106)
    at net.minecraft.world.World.func_72939_s(World.java:2529)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)

-- Block entity being ticked --
Details:
    Name: oc:robot // li.cil.oc.common.tileentity.RobotProxy
    Block type: ID #936 (Robot // li.cil.oc.common.block.RobotProxy)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-723,35,812), Chunk: (at 13,2,12 in -46,50; contains blocks -736,0,800 to -721,255,815), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Actual block type: ID #936 (Robot // li.cil.oc.common.block.RobotProxy)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2529)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
```

Any suggestions about this? More info by your wish.

**Comment by OfficialStamper** [comment]
I am also getting exact same error when placing robot in world for the  first time.

No  work around discovered as yet.,

Please advise, thanks

**Comment by LizzyTrickster** [comment]
1) How did this crash happen? / How can the devs reproduce it?
2) Mod Versions (full versions, not _latest_).
3) Does it happen with just OC?

**Comment by tachigami** [comment]
@LizzyTrickster we do not know the exact problem :-\ It was only 3 times due to the same one robot running following program. 
Full crash logs:
- http://pastebin.com/gP9uyhDR
- http://pastebin.com/jUxzjmNb
- http://pastebin.com/gRuedzNM

Lua program:
- http://pastebin.com/ggXjqGfF
