### ISSUE TITLE
drone crash

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2031]
I putted the drone in my world and it instantly crashed my game and every time I start the world again it crashes 
 v=opencomputer 1.6.0.3-rc----minecraft 1.10.2 (all the mods---modpack)
maybe this helps:
java.lang.NullPointerException: Saving entity NBT
    at li.cil.oc.common.entity.Drone.func_70014_b(Drone.scala:592)
    at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582)
    at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:137)
    at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:22)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:122)
    at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:74)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:107)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_792_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at li.cil.oc.common.entity.Drone.func_70014_b(Drone.scala:592)

-- Entity being saved --
Details:
    Entity Type: OpenComputers.Drone (li.cil.oc.common.entity.Drone)
    Entity ID: 11076
    Entity Name: Drone
    Entity's Exact location: -58.63, 94.05, 314.60
    Entity's Block location: World: (-59,94,314), Chunk: (at 5,5,10 in -4,19; contains blocks -64,0,304 to -49,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: 0.00, -0.04, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582)
    at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:137)
    at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:22)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:122)
    at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:74)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:107)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_759_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)

**Comment by BaalEvan** [comment]
_[1.10.2] [OpenComputers-MC1.10.2-1.6.0.3-rc.1] [All the mods - 1.10.2 v1.13c]_ 

Same here.

[fml-client-latest.log.txt](https://github.com/MightyPirates/OpenComputers/files/429199/fml-client-latest.log.txt)
[crash-2016-08-22_02.56.54-client.txt](https://github.com/MightyPirates/OpenComputers/files/429200/crash-2016-08-22_02.56.54-client.txt)

**Comment by wollfxp** [comment]
Same error here, except I'm playing FTB Unstable 1.10.2 with OpenComputers-MC1.10.2-1.6.0.3-rc.1

[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/439852/fml-client-latest.txt)
[crash-2016-08-26_21.00.txt](https://github.com/MightyPirates/OpenComputers/files/439853/crash-2016-08-26_21.00.txt)
_UPDATE:_ stack trace hints that it is something wrong with Wawla (obviously). Disabling Wawla for me solved the issue. Still don't know if it is a bug in Wawla or some API integration issue.

**Comment by payonel** [comment]
can anyone/everyone here retest with our latest dev build? http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.31-dev.jar

Thanks

**Comment by BaalEvan** [comment]
[1.10.2] [OpenComputers-MC1.10.2-1.6.0.31-dev] [All the mods - 1.10.2 v1.15]

Still Crashing

[fml-client-latest.log.txt](https://github.com/MightyPirates/OpenComputers/files/440433/fml-client-latest.log.txt)
[crash-2016-08-27_05.06.48-client.txt](https://github.com/MightyPirates/OpenComputers/files/440434/crash-2016-08-27_05.06.48-client.txt)

Same error with Robit from Mekanism it's related to Waila/Wawla after disable drones works

**Comment by wollfxp** [comment]
Same with the dev jar provided. Game still crashes when drone is placed.

[crash-2016-08-27_14.30.22-client.txt](https://github.com/MightyPirates/OpenComputers/files/440622/crash-2016-08-27_14.30.22-client.txt)
[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/440623/fml-client-latest.txt)

**Comment by MayhemBill** [comment]
Removing Wawla from Client and Server fixed this issue for me. No more crashes (related to OC, anyway)
