### ISSUE TITLE
latest version of forge crash 1.10.2

### ISSUE THREAD

**Issue by mightydanp** [MightyPirates/OpenComputers#2056]
[04:11:26] [Client thread/WARN] [OpenComputers]: Failed patching btb.renderLeash, method not found.
[04:11:27] [Client thread/WARN]: Skipping bad option: lastServer:
[04:11:30] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121) ~[bnz.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: bxl
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224) ~[Restriction.class:?]
    at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498) ~[VersionRange.class:?]
    at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106) ~[GuiModsMissing.class:?]
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) ~[bnz.class:?]
    ... 9 more
[04:11:30] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

**Comment by fnuecke** [comment]
Just to make sure, you are using the right OC version, yes?

**Comment by payonel** [comment]
no update, no repro
