### ISSUE TITLE
crash minecraft 1.10.2

### ISSUE THREAD

**Issue by PapyRedstone** [MightyPirates/OpenComputers#2077]
Hello
Each time i want to close a opencomputer gui i have a crash, my minecraft shutdown
I have the following mods install:
-1.10.2-forge1.10.2-12.18.1.2011
-EnderCore-1.10.2.jar
-Ender-IO-Mod-1.10.2.jar
-InventoryTweaks-1.61-58.jar
-ironchest-1.10.2-7.0.7.795.jar
-jei_1.10.2-3.7.3.221.jar
-Mekanism-1.10.2-9.2.0.292.jar
-MekanismGenerators-1.10.2-9.2.0.292.jar
-MekanismTools-1.10.2-9.2.0.292.jar
-OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
-OptiFine_1.10.2_HD_U_C3.jar

Here is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.57-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 02/10/16 20:03
Description: Updating screen events

java.lang.NoSuchMethodError: mezz.jei.api.IItemListOverlay.highlightStacks(Ljava/util/Collection;)V
    at li.cil.oc.client.gui.DynamicGuiContainer$$anonfun$resetJEIHighlights$1.apply(DynamicGuiContainer.scala:230)
    at li.cil.oc.client.gui.DynamicGuiContainer$$anonfun$resetJEIHighlights$1.apply(DynamicGuiContainer.scala:230)
    at scala.Option.foreach(Option.scala:245)
    at li.cil.oc.client.gui.DynamicGuiContainer.resetJEIHighlights(DynamicGuiContainer.scala:230)
    at li.cil.oc.client.gui.DynamicGuiContainer.func_146281_b(DynamicGuiContainer.scala:188)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:936)
    at mezz.jei.gui.RecipesGui.open(RecipesGui.java:316)
    at mezz.jei.gui.RecipesGui.showRecipes(RecipesGui.java:357)
    at mezz.jei.gui.RecipesGui.showRecipes(RecipesGui.java:351)
    at mezz.jei.input.InputHandler.handleMouseClickedFocus(InputHandler.java:150)
    at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:85)
    at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:62)
    at mezz.jei.GuiEventHandler.onGuiMouseEvent(GuiEventHandler.java:145)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_103_GuiEventHandler_onGuiMouseEvent_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:514)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at li.cil.oc.client.gui.DynamicGuiContainer$$anonfun$resetJEIHighlights$1.apply(DynamicGuiContainer.scala:230)
    at li.cil.oc.client.gui.DynamicGuiContainer$$anonfun$resetJEIHighlights$1.apply(DynamicGuiContainer.scala:230)
    at scala.Option.foreach(Option.scala:245)
    at li.cil.oc.client.gui.DynamicGuiContainer.resetJEIHighlights(DynamicGuiContainer.scala:230)
    at li.cil.oc.client.gui.DynamicGuiContainer.func_146281_b(DynamicGuiContainer.scala:188)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:936)
    at mezz.jei.gui.RecipesGui.open(RecipesGui.java:316)
    at mezz.jei.gui.RecipesGui.showRecipes(RecipesGui.java:357)
    at mezz.jei.gui.RecipesGui.showRecipes(RecipesGui.java:351)
    at mezz.jei.input.InputHandler.handleMouseClickedFocus(InputHandler.java:150)
    at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:85)
    at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:62)
    at mezz.jei.GuiEventHandler.onGuiMouseEvent(GuiEventHandler.java:145)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_103_GuiEventHandler_onGuiMouseEvent_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:514)

-- Affected screen --
Details:
    Screen name: li.cil.oc.client.gui.Assembler

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['ThojeX14'/5298, l='MpServer', x=-265,06, y=82,00, z=162,28]]
    Chunk stats: MultiplayerChunkCache: 281, 281
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-256,64,156), Chunk: (at 0,4,12 in -16,9; contains blocks -256,0,144 to -241,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 842 game time, 842 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 74 total; [EntityFallingBlock['Falling Block'/5194, l='MpServer', x=-306,50, y=21,73, z=272,50], EntityZombie['Zombie'/7243, l='MpServer', x=-285,80, y=30,00, z=177,55], EntitySquid['Squid'/7288, l='MpServer', x=-259,82, y=60,82, z=105,66], EntitySquid['Squid'/7289, l='MpServer', x=-279,27, y=55,48, z=121,51], EntitySquid['Squid'/7302, l='MpServer', x=-204,82, y=57,34, z=223,28], EntitySquid['Squid'/7327, l='MpServer', x=-279,32, y=62,28, z=191,31], EntitySquid['Squid'/7331, l='MpServer', x=-218,60, y=60,82, z=179,81], EntitySquid['Squid'/7334, l='MpServer', x=-295,48, y=53,51, z=116,05], EntitySquid['Squid'/7340, l='MpServer', x=-231,72, y=53,71, z=176,54], EntitySquid['Squid'/7341, l='MpServer', x=-322,95, y=58,14, z=112,25], EntitySquid['Squid'/7358, l='MpServer', x=-298,52, y=59,59, z=142,87], EntitySquid['Squid'/7359, l='MpServer', x=-254,24, y=54,80, z=121,83], EntitySquid['Squid'/7366, l='MpServer', x=-199,53, y=59,46, z=155,60], EntitySkeleton['Skeleton'/7405, l='MpServer', x=-250,50, y=30,00, z=168,50], EntityBat['Bat'/6457, l='MpServer', x=-276,25, y=27,00, z=102,75], EntityFallingBlock['Falling Block'/5488, l='MpServer', x=-372,50, y=3,00, z=114,50], EntityFallingBlock['Falling Block'/5509, l='MpServer', x=-368,50, y=33,00, z=245,50], EntityFallingBlock['Falling Block'/5511, l='MpServer', x=-369,50, y=33,00, z=246,50], EntityFallingBlock['Falling Block'/5512, l='MpServer', x=-368,50, y=33,00, z=246,50], EntityFallingBlock['Falling Block'/5514, l='MpServer', x=-369,50, y=33,00, z=247,50], EntityFallingBlock['Falling Block'/5515, l='MpServer', x=-370,50, y=35,00, z=246,50], EntityFallingBlock['Falling Block'/5516, l='MpServer', x=-371,50, y=34,00, z=246,50], EntityFallingBlock['Falling Block'/5517, l='MpServer', x=-370,50, y=33,00, z=247,50], EntityFallingBlock['Falling Block'/5518, l='MpServer', x=-371,50, y=32,00, z=248,50], EntityFallingBlock['Falling Block'/5519, l='MpServer', x=-370,50, y=31,00, z=248,50], EntityFallingBlock['Falling Block'/5520, l='MpServer', x=-369,50, y=34,00, z=245,50], EntityFallingBlock['Falling Block'/5521, l='MpServer', x=-369,50, y=32,00, z=248,50], EntityFallingBlock['Falling Block'/5522, l='MpServer', x=-372,50, y=32,00, z=246,50], EntityFallingBlock['Falling Block'/5523, l='MpServer', x=-372,50, y=31,00, z=247,50], EntityFallingBlock['Falling Block'/5524, l='MpServer', x=-371,50, y=33,00, z=247,50], EntityFallingBlock['Falling Block'/5525, l='MpServer', x=-373,50, y=31,00, z=247,50], EntityFallingBlock['Falling Block'/5526, l='MpServer', x=-373,50, y=32,00, z=246,50], EntityFallingBlock['Falling Block'/5527, l='MpServer', x=-372,50, y=31,00, z=248,50], EntityCreeper['Creeper'/6584, l='MpServer', x=-331,50, y=14,00, z=143,50], EntityBat['Bat'/6678, l='MpServer', x=-235,68, y=27,70, z=161,24], EntityZombie['Zombie'/6688, l='MpServer', x=-294,50, y=26,00, z=91,50], EntityBat['Bat'/6700, l='MpServer', x=-341,96, y=19,70, z=88,11], EntityCreeper['Creeper'/6753, l='MpServer', x=-306,50, y=16,00, z=130,50], EntityPlayerSP['ThojeX14'/5298, l='MpServer', x=-265,06, y=82,00, z=162,28], EntitySkeleton['Skeleton'/6763, l='MpServer', x=-344,50, y=22,00, z=107,50], EntitySkeleton['Skeleton'/6772, l='MpServer', x=-284,50, y=28,00, z=85,50], EntityZombie['Zombie'/6812, l='MpServer', x=-323,50, y=18,00, z=239,50], EntityZombie['Zombie'/6814, l='MpServer', x=-236,50, y=29,00, z=234,50], EntityZombie['Zombie'/6817, l='MpServer', x=-286,65, y=15,00, z=190,35], EntitySkeleton['Skeleton'/6836, l='MpServer', x=-262,50, y=30,00, z=165,50], EntityZombie['Zombie'/6862, l='MpServer', x=-294,50, y=25,00, z=105,50], EntitySpider['Spider'/6882, l='MpServer', x=-274,50, y=21,00, z=93,50], EntityFallingBlock['Falling Block'/4914, l='MpServer', x=-372,50, y=4,50, z=114,50], EntityFallingBlock['Falling Block'/4915, l='MpServer', x=-372,50, y=5,50, z=113,50], EntityFallingBlock['Falling Block'/4916, l='MpServer', x=-373,50, y=5,50, z=114,50], EntityFallingBlock['Falling Block'/4917, l='MpServer', x=-373,50, y=5,50, z=115,50], EntityFallingBlock['Falling Block'/4943, l='MpServer', x=-368,50, y=36,65, z=246,50], EntityZombie['Zombie'/6992, l='MpServer', x=-340,50, y=22,00, z=109,50], EntityFallingBlock['Falling Block'/4945, l='MpServer', x=-368,50, y=35,65, z=245,50], EntityFallingBlock['Falling Block'/4946, l='MpServer', x=-368,50, y=36,65, z=247,50], EntityFallingBlock['Falling Block'/4948, l='MpServer', x=-369,50, y=35,65, z=246,50], EntityFallingBlock['Falling Block'/4949, l='MpServer', x=-369,50, y=35,65, z=247,50], EntityFallingBlock['Falling Block'/4950, l='MpServer', x=-370,50, y=34,65, z=246,50], EntityFallingBlock['Falling Block'/4951, l='MpServer', x=-370,50, y=35,65, z=247,50], EntityFallingBlock['Falling Block'/4952, l='MpServer', x=-370,50, y=35,65, z=248,50], EntityFallingBlock['Falling Block'/4953, l='MpServer', x=-369,50, y=35,65, z=245,50], EntityFallingBlock['Falling Block'/4954, l='MpServer', x=-369,50, y=35,65, z=248,50], EntityFallingBlock['Falling Block'/4955, l='MpServer', x=-372,50, y=34,65, z=246,50], EntityCreeper['Creeper'/7003, l='MpServer', x=-307,50, y=14,00, z=104,50], EntityFallingBlock['Falling Block'/4956, l='MpServer', x=-372,50, y=35,65, z=247,50], EntityFallingBlock['Falling Block'/4957, l='MpServer', x=-371,50, y=33,65, z=246,50], EntityFallingBlock['Falling Block'/4958, l='MpServer', x=-371,50, y=33,65, z=247,50], EntityFallingBlock['Falling Block'/4959, l='MpServer', x=-371,50, y=34,65, z=248,50], EntityFallingBlock['Falling Block'/4960, l='MpServer', x=-373,50, y=35,65, z=247,50], EntityFallingBlock['Falling Block'/4961, l='MpServer', x=-372,50, y=35,65, z=248,50], EntityFallingBlock['Falling Block'/4962, l='MpServer', x=-373,50, y=34,65, z=246,50], EntityFallingBlock['Falling Block'/4963, l='MpServer', x=-373,50, y=35,65, z=248,50], EntityItem['item.tile.doublePlant.syringa'/7045, l='MpServer', x=-314,49, y=73,00, z=186,00], EntityZombie['Zombie'/7090, l='MpServer', x=-289,50, y=28,00, z=88,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 4.4.0-38-generic
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 349355584 bytes (333 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2011 Optifine OptiFine_1.10.2_HD_U_C3 14 mods loaded, 14 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAAAAAAA  Forge{12.18.1.2011} [Minecraft Forge](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAAAAAAA  OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAAAAAAA  endercore{1.10-0.4.0.33-alpha} [EnderCore](EnderCore-1.10.2.jar) 
    UCHIJAAAAAAAAA  EnderIO{1.10-3.0.0.55_alpha} [Ender IO](Ender-IO-Mod-1.10.2.jar) 
    UCHIJAAAAAAAAA  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAAAAAAA  IronChest{7.0.7.795} [Iron Chest](ironchest-1.10.2-7.0.7.795.jar) 
    UCHIJAAAAAAAAA  JEI{3.7.3.221} [Just Enough Items](jei_1.10.2-3.7.3.221.jar) 
    UCHIJAAAAAAAAA  mcmultipart{1.2.0_74} [MCMultiPart](MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJAAAAAAAAA  Mekanism{9.2.0} [Mekanism](Mekanism-1.10.2-9.2.0.292.jar) 
    UCHIJAAAAAAAAA  MekanismGenerators{9.2.0} [MekanismGenerators](MekanismGenerators-1.10.2-9.2.0.292.jar) 
    UCHIJAAAAAAAAA  MekanismTools{9.2.0} [MekanismTools](MekanismTools-1.10.2-9.2.0.292.jar) 
    UCHIJAAAAAAAAA  OpenComputers{1.6.0.3-rc.1} [OpenComputers](OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
    Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.57-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)

TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
    GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 11.2.0' Renderer: 'Mesa DRI Intel(R) Sandybridge Mobile '
    EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  \* Optifine is installed. This is NOT supported.
                  \* Our API got loaded from Ender-IO-Mod-1.10.2.jar. That's unexpected.
                  \* Our API got loaded from Ender-IO-Mod-1.10.2.jar. That's unexpected.
                  \* Our API got loaded from Ender-IO-Mod-1.10.2.jar. That's unexpected.
                  \* Our API got loaded from Ender-IO-Mod-1.10.2.jar. That's unexpected.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2011
    LWJGL: 2.9.4
    OpenGL: Mesa DRI Intel(R) Sandybridge Mobile  GL version 3.0 Mesa 11.2.0, Intel Open Source Technology Center
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Intel(R) Pentium(R) CPU B980 @ 2.40GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C3
Render Distance Chunks: 8
Mipmaps: 0
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 3.0 Mesa 11.2.0
OpenGlRenderer: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGlVendor: Intel Open Source Technology Center
CpuCount: 2
```

**Comment by PapyRedstone** [comment]
i realize that when launching the game he said that 'there are error running the transformer class' so here is the log
[13:22:46] [Client thread/INFO]: Setting user: ThojeX14
[13:22:59] [Client thread/WARN]: Skipping bad option: lastServer:
[13:22:59] [Client thread/INFO]: LWJGL Version: 2.9.4
[13:23:16] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:MCMultiPart
[13:23:44] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:23:44] [Thread-8/INFO]: Initializing LWJGL OpenAL
[13:23:44] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:23:44] [Thread-8/INFO]: OpenAL initialized.
[13:23:44] [Sound Library Loader/INFO]: Sound engine started
[13:24:01] [Client thread/INFO]: Created: 8x8 textures-atlas
[13:24:17] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:MCMultiPart
[13:24:20] [Client thread/INFO]: SoundSystem shutting down...
[13:24:20] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[13:24:20] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:24:20] [Thread-12/INFO]: Initializing LWJGL OpenAL
[13:24:20] [Thread-12/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:24:20] [Thread-12/INFO]: OpenAL initialized.
[13:24:20] [Sound Library Loader/INFO]: Sound engine started
[13:24:30] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/#center_opaque.png, java.io.FileNotFoundException
[13:24:31] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/#side.png, java.io.FileNotFoundException
[13:24:31] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/#side_opaque.png, java.io.FileNotFoundException
[13:24:32] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/#center.png, java.io.FileNotFoundException
[13:24:32] [Client thread/INFO]: Created: 2048x2048 textures-atlas
[13:24:40] [Client thread/WARN]: Skipping bad option: lastServer:
[13:26:41] [Client thread/INFO]: Stopping!
[13:26:41] [Client thread/INFO]: SoundSystem shutting down...
[13:26:41] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by Vexatos** [comment]
You need to update JEI.
