### ISSUE TITLE
[1.10.2] Crash when placing drone

### ISSUE THREAD

**Issue by JomerDev** [MightyPirates/OpenComputers#2081]
My minecraft crashed when I tried to place a drone

Crashlog: http://hastebin.com/xezuqovure.sql

**Comment by SageStarCodes** [comment]
I too discovered this bug:

Log: http://paste.atlauncher.com/view/b3960688

**Comment by mandrewpowers** [comment]
This is happening still. Looks like wawla (wa**w**la not wa_i_la) is triggering something when it tries to pull the NBT data off the drone. Lastest OpenComputers running on server and client to date.

`````` java

java.lang.NullPointerException: Saving entity NBT
    at li.cil.oc.common.entity.Drone.func_70014_b(Drone.scala:592)
    at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582)
    at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:137)
    at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:22)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:122)
    at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:74)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:107)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1135_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)```
``````

**Comment by fnuecke** [comment]
Oh great, so we're back to having server methods called on the client again -.-

**Comment by fnuecke** [comment]
706905603d8a15cb2a02de32c2ca9df8d8f0c5e6
