### ISSUE TITLE
Computer case error spamming console - server kicks me after logging in

### ISSUE THREAD

**Issue by JunkiEDM** [MightyPirates/OpenComputers#2190]
On the latest version of OC, (OpenComputers-MC1.10.2-1.6.1.6.jar) there is something game-breakingly wrong.
I updated OC and now I can't login to the server anywhere around my computer without getting kicked soon after (cant interact with anything, it freezes when I join).
My console is spammed with:
```
A TileEntity type li.cil.oc.common.tileentity.Case has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException: 9
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$saveComponents$1.apply$mcVI$sp(ComponentInventory.scala:102) ~[ComponentInventory$$anonfun$saveComponents$1.class:?]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) ~[Range.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.saveComponents(ComponentInventory.scala:99) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Case.saveComponents(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.save(ComponentInventory.scala:94) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Case.save(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Inventory$class.writeToNBTForServer(Inventory.scala:28) ~[Inventory$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$RedstoneAware$$super$writeToNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.RedstoneAware$class.writeToNBTForServer(RedstoneAware.scala:114) ~[RedstoneAware$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$BundledRedstoneAware$$super$writeToNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.BundledRedstoneAware$class.writeToNBTForServer(BundledRedstoneAware.scala:148) ~[BundledRedstoneAware$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Computer$$super$writeToNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBTForServer(Computer.scala:161) ~[Computer$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$writeToNBTForServer(Case.scala:28) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Colored$class.writeToNBTForServer(Colored.scala:48) ~[Colored$class.class:?]
        at li.cil.oc.common.tileentity.Case.writeToNBTForServer(Case.scala:94) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.TileEntity$class.writeToNBT(TileEntity.scala:104) ~[TileEntity$class.class:?]
        at li.cil.oc.common.tileentity.Case.func_189515_b(Case.scala:28) ~[Case.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
        at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:514) [WorldManager.class:1.10.2-2171-5.1.0-BETA-1992]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:695) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zhk000(MinecraftServer.java:650) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:632) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```
For now I will downgrade OC, however please get this fixed as soon as you can! Thanks!

**Comment by payonel** [comment]
we have updated builds for 1.10
please test our latest dev build and reopen if this repros
http://ci.cil.li/
