### ISSUE TITLE
Incompatibility with MorePistons

### ISSUE THREAD

**Issue by itsfolf** [MightyPirates/OpenComputers#2201]
I got this error on startup:
```
[20:02:40 WARN]: ****************************************
[20:02:40 WARN]: * A broken ore dictionary registration with name craftingPiston has occurred. It adds an item (type: class com.gollum.morepistons.common.item.ItemMorePistonsVanillaProxy) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod OpenComputers report it to them!
[20:02:40 WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:542)
[20:02:40 WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:509)
[20:02:40 WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:508)
[20:02:40 WARN]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:41)
[20:02:40 WARN]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:37)
[20:02:40 WARN]: *  at li.cil.oc.OpenComputers.preInit(OpenComputers.scala)...
[20:02:40 WARN]: ****************************************
[20:02:40 WARN]: ****************************************
[20:02:40 WARN]: * A broken ore dictionary registration with name craftingPiston has occurred. It adds an item (type: class com.gollum.morepistons.common.item.ItemMorePistonsVanillaProxy) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod OpenComputers report it to them!
[20:02:40 WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:542)
[20:02:40 WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:509)
[20:02:40 WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:508)
[20:02:40 WARN]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:42)
[20:02:40 WARN]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:37)
[20:02:40 WARN]: *  at li.cil.oc.OpenComputers.preInit(OpenComputers.scala)...
[20:02:40 WARN]: ****************************************
```

**Comment by xarses** [comment]
Please identify the OC, MC, and MorePistons versions involved here

**Comment by itsfolf** [comment]
MC 1.7.10
Forge 7.99.4.1614
OC 1.6.0.9-universal
MorePistons 2.0.0

**Comment by payonel** [comment]
no longer seems to be an issue, does not repro
