### ISSUE TITLE
Server rack crashes world (server) upon placing. Players Can no longer login on server

### ISSUE THREAD

**Issue by Flashken** [MightyPirates/OpenComputers#2219]
[Server thread/ERROR] [FML/]: A TileEntity type li.cil.oc.common.tileentity.Rack has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException

Oddly enough placing a rack in single player did nothing unexpected. Perhaps it's server related?

Pack: Direwolf 20 1.10 version 1.3.2
edit: attachments
[error.txt](https://github.com/MightyPirates/OpenComputers/files/694519/error.txt)

**Comment by funniray** [comment]
Is there anything in the server rack?

**Comment by fnuecke** [comment]
There should be no way for anything to be null there. If you have a full log, please post that, might be caused by something that happened earlier.

**Comment by nrllewellyn** [comment]
Got a similar error when a player placed a computer case:

`java.lang.NullPointerException: Exception while updating neighbours
        at li.cil.oc.common.tileentity.Capacitor.recomputeCapacity(Capacitor.scala:58)
        at li.cil.oc.common.block.Capacitor.func_189540_a(Capacitor.scala:40)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)
        at net.minecraft.world.World.func_180496_d(World.java:519)
        at ic2.core.energy.leg.EnergyNetLocalLeg.tickStart(EnergyNetLocalLeg.java:192)
        at ic2.core.energy.leg.EventHandler.preTick(EventHandler.java:44)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_EventHandler_preTick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by xarses** [comment]
@Cobra1117 The tracebacks don't appear to be related.

Please create a separate issue and include your *full* server log (use pastebin or similar)(The full log will include a full version list, otherwise we need those too). Also include a list of any mod blocks adjacent to the case. If you have any other OpenComputers cables or blocks adjacent try again w/o any nearby, if it only occurs adjacent to OpenComputers connections, then we need a list of all those too.

**Comment by nrllewellyn** [comment]
@xarses Will do!

**Comment by payonel** [comment]
too long with repro sorry
open new ticket with repro steps if you re-encounter this issue
