### ISSUE TITLE
Crash when placing robot (Ticking block entity)

### ISSUE THREAD

**Issue by hAmpzter** [MightyPirates/OpenComputers#2233]
Our server crashed (running Direwolf20 1.10 Minecraft Modpack, version 1.3.2 with OC MC1.10.2-1.6.1.6).

The error happened when a player placed a robot that was picked up after have being froozen from an unloaded chunk.

```
java.lang.NullPointerException: Ticking block entity
	at li.cil.oc.common.tileentity.Robot.updateEntity(Robot.scala:338)
	at li.cil.oc.common.tileentity.RobotProxy.updateEntity(RobotProxy.scala:108)
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
	at li.cil.oc.common.tileentity.RobotProxy.func_73660_a(RobotProxy.scala:26)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

Full crash-report:
[crash-2017-01-22_15.27.50-server.txt](https://github.com/MightyPirates/OpenComputers/files/722094/crash-2017-01-22_15.27.50-server.txt)

**Comment by xorinzor** [comment]
Same thing happened here, built a robot in the assembler, placed it down, crashed right away.

```
Time: 2/25/17 6:41 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at li.cil.oc.common.tileentity.Robot.updateEntity(Robot.scala:338)
	at li.cil.oc.common.tileentity.RobotProxy.updateEntity(RobotProxy.scala:108)
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
	at li.cil.oc.common.tileentity.RobotProxy.func_73660_a(RobotProxy.scala:26)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:219)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2785)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjn000(WorldServer.java:2772)
	at net.minecraft.world.World.func_72939_s(World.java:5771)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2149)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

Running the Direwolf20 (1.10.2) modpack, with OpenComputers-MC1.10.2-1.6.1.6

**Comment by Vexatos** [comment]
Can you reproduce this using OpenComputers 1.6.2?

**Comment by xorinzor** [comment]
Tried with OpenComputers-MC1.10.2-1.6.2.7, Still happens although the error seems to have changed:

```
Time: 2/26/17 4:19 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: li.cil.oc.common.launch.CoreModContainer
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:363)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:521)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: li.cil.oc.common.launch.CoreModContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:358)
	... 6 more
Caused by: java.io.FileNotFoundException: /home/pp-direwo_p3xsc/public/mods/OpenComputers-MC1.10.2-1.6.2.7.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:145)
	... 12 more
```

**Comment by xorinzor** [comment]
Seems to have fixed it! I'll report it to the Direwolf20 team, thanks!

**Comment by fgoebel** [comment]
Hello there,
i had the very same crash today, running the Direwolf20 (1.10.2) modpack version 1.9.1 with Opencomputers-MC1.10.2-1.6.2.7.jar

`java.lang.NullPointerException: Ticking block entity
        at li.cil.oc.common.tileentity.Robot.updateEntity(Robot.scala:338)
        at li.cil.oc.common.tileentity.RobotProxy.updateEntity(RobotProxy.scala:108)
        at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
        at li.cil.oc.common.tileentity.RobotProxy.func_73660_a(RobotProxy.scala:26)
        at net.minecraft.world.World.func_72939_s(World.java:1804)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:748)
`

You can view the full crash log here: https://gist.github.com/Blast0r/860050bd6df9b4442ba03c1e2f513eb7

The Server started up fine after this crash and the robot seems to work. 

I assembled another robot and placed it, and it just worked

I hope this helps in any way.

Thanks for making this mod!
kind regards, Blast0r
