### ISSUE TITLE
[1.10.2] Keyboard appears broken in inventory

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#2238]
![broken_dirtcatcher](https://cloud.githubusercontent.com/assets/1530728/22315251/a3190e9a-e333-11e6-9438-9efb98c10a99.png)
Broken texture for the keyboard. Something must have gone wrong lately.

**Comment by xarses** [comment]
Please provide your OC version. There should be a relevant message in the client console log about the failed texture. Is this on a MP Server? Does it reproduce with the latest Jenkins build?

**Comment by Techokami** [comment]
Oh, derp. It's been a while!
OpenComputers-MC1.10.2-1.6.1.6, reproduced in both SP and MP. I'm using a server-oriented mod pack that, for once, is completely out of my control, so I can't test latest Jenkins builds. As such I have to page the pack manager responsible into this ticket.
@jaquadro get over here

**Comment by xarses** [comment]
Since the render is client sided, you should have a relevant message in your client's console log, so that would be helpful. You noted that it occurred in SP so switching the MC version on your client should be enough to validate if there is something possible wrong with a specific version. Also is the keyboard texture broken when you place it in the world?

**Comment by Techokami** [comment]
The keyboard looks fine when placed in the world. It's just the inventory model is broken. Trying to grep my client log for anything of relevence, and so far I've found this:
`[16:02:53] [Client thread/DEBUG] [FML/]: Item json isn't found for 'opencomputers:keyboard#inventory', trying to load the variant from the blockstate json`
...followed by...
```
[16:02:57] [Client thread/ERROR] [FML/]: Exception loading model for variant opencomputers:keyboard#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception checking if model opencomputers:item/keyboard can be loaded with loader INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:126) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:317) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 4 column 2
	at com.google.gson.Gson.assertFullConsumption(Gson.java:779) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:742) ~[Gson.class:?]
	at appeng.client.render.model.UVLModelLoader.accepts(UVLModelLoader.java:195) ~[UVLModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:115) ~[ModelLoaderRegistry.class:?]
	... 14 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 4 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.Gson.assertFullConsumption(Gson.java:775) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:742) ~[Gson.class:?]
	at appeng.client.render.model.UVLModelLoader.accepts(UVLModelLoader.java:195) ~[UVLModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:115) ~[ModelLoaderRegistry.class:?]
	... 14 more
[16:02:57] [Client thread/ERROR] [FML/]: Exception loading model for variant opencomputers:keyboard#inventory, blockstate location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model opencomputers:keyboard#inventory with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:325) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) ~[bpe.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 14 more
```

**Comment by xarses** [comment]
Please see if a different version has the problem, if not try a fresh download of your current version to rule out possible file corruption issue.

**Comment by jaquadro** [comment]
I downloaded a fresh copy of 1.6.1.6 from CurseForge.  /assets/opencomputers/models/item/keyboard.json is indeed malformed.  There is a rogue 'a' hanging out at the end.

```
{
    "parent": "opencomputers:block/keyboard"
}
a
```
