### ISSUE TITLE
LuaRuntimeException when trying to iterate a table, only in 5.3

### ISSUE THREAD

**Issue by AmandaCameron** [MightyPirates/OpenComputers#2319]
I'm getting the following stack when my mod tries to iterate the table given to it in a component's setter, and it only happens in 5.3, so I'm guessing something's wrong with the 5.3 handling of this case:

 Worth noting, it appears to always get triggered after the first element is handled okay, before I can get the second element.
```
[15:48:51] [Server thread/ERROR] [Butts]: THE SKY IS FALLING!
li.cil.repack.com.naef.jnlua.LuaRuntimeException: invalid key to 'next'
	at li.cil.repack.com.naef.jnlua.LuaStateFiveThree.lua_next(Native Method) ~[LuaStateFiveThree.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.next(LuaState.java:1602) ~[LuaState.class:?]
	at li.cil.repack.com.naef.jnlua.util.AbstractTableMap$EntryIterator.hasNext(AbstractTableMap.java:287) ~[AbstractTableMap$EntryIterator.class:?]
	at java.util.AbstractMap$2$1.hasNext(AbstractMap.java:414) ~[?:1.8.0_121]
	at net.darkdna.amanda.mc.butts.MyBlockEnvironment.messages(MyBlock.kt:189) [MyBlockEnvironment.class:?]
	at generated.li.cil.oc.CallWrapper_net_darkdna_amanda_mc_butts_MyBlockEnvironment_messages.call(Unknown Source) [?:?]
	at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123) [Callbacks$ComponentCallback.class:?]
	at li.cil.oc.server.network.Component$class.invoke(Component.scala:112) [Component$class.class:?]
	at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:608) [Network$ComponentBuilder$$anon$2.class:?]
	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:358) [Machine.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24) [ExtendedLuaState$ExtendedLuaState$$anon$1.class:?]
	at li.cil.repack.com.naef.jnlua.LuaStateFiveThree.lua_pcall(Native Method) [LuaStateFiveThree.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:681) [LuaState.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runSynchronized(NativeLuaArchitecture.scala:177) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.Machine.update(Machine.scala:562) [Machine.class:?]
	at li.cil.oc.common.tileentity.traits.Computer$class.updateComputer(Computer.scala:120) [Computer$class.class:?]
	at li.cil.oc.common.tileentity.Case.updateComputer(Case.scala:28) [Case.class:?]
	at li.cil.oc.common.tileentity.traits.Computer$class.updateEntity(Computer.scala:103) [Computer$class.class:?]
	at li.cil.oc.common.tileentity.Case.updateEntity(Case.scala:69) [Case.class:?]
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6) [Tickable$class.class:?]
	at li.cil.oc.common.tileentity.Case.update(Case.scala:28) [Case.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1945) [World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:646) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:783) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Relevent getter/setter (in kotlin) if requested, I'll try and find the energy to recreate the code in Java later on.
```kotlin

    @Callback(getter = true, setter = true, doc = "table of string")
    @Suppress("UNUSED")
    fun messages(ctx: Context?, args: Arguments?): Array<Any> {
        synchronized(myBlockTE) {
            when (args!!.count()) {
                0 -> return arrayOf(myBlockTE.messages)
                1 -> {
                    try {
                        var msgs: MutableList<String> = mutableListOf()
                        val tmp = args.checkTable(0)

                        tmp.values.forEach {
                            if (it is String) {
                                ButtsMod.log.info("[set messages] Beautiful values: $it")

                                msgs.add(it)
                            }
                        }

                        myBlockTE.messages = msgs
                        return emptyArray()
                    } catch(e: Exception) {
                        ButtsMod.log.error("THE SKY IS FALLING!", e)

                        return emptyArray()
                    }
                }
                else -> throw IllegalArgumentException("Expected either 0 or 1 arguments, Naughty Naughty!")
            }
        }
    }
```

**Comment by xarses** [comment]
Which OpenComputers, MC and Forge version is this?

**Comment by AmandaCameron** [comment]
Whoops, forgot about that, sorry.
```
MC 1.10.2
Forge 12.18.3.2185
OpenComputers from the maven repo: li.cil.oc:OpenComputers:MC1.10.2-1.6.2.7
```

( I discovered this in a dev environment while toying with making a mod for fun, thus the silly package name. )

**Comment by payonel** [comment]
jnlua and lua 5.3 and eris, not friends. we don't plan to support this
