### ISSUE TITLE
[MC1.10.2-1.6.2.7 / MC1.10.2-1.6.2.117-dev] Tileentity failing to save

### ISSUE THREAD

**Issue by GHXX** [MightyPirates/OpenComputers#2522]
I am playing the modpack "All the mods" for MC1.10.2 that includes the opencomputers version MC1.10.2-1.6.2.7.
When placing a computer and putting components into it it works just fine. Saving the world by pausing doesnt throw any errors, but leaving the singleplayer world causes FML to report an error regarding saving the tileentities (see [1]). It seems that an ArrayIndexOutOfBoundsException may cause this issue.
_____
Repro steps:
1.) place one or more computers (Tier 3 in this case) put the following things in them: https://prnt.sc/glzca1
one screen on top and a keyboard on the side of the screen http://prntscr.com/glzg50
the network stuff seems to be unrelated since two other pcs showed the same issue while testing.

2.) save the game (exit) so the world gets unloaded
2.1.) open the world again. now the computers appear to be black http://prntscr.com/glzeyp

3.) save and exit again and open the world again
3.1.) now all the contents of the computers are gone.
_____

This issue does NOT seem to affect server racks.

[1] https://paste.ee/p/8arwt#s=0&l=19827   line 19827 ( CTRL+F the text "indexoutof")

A side note: i saved and loaded a few times so the errors appeared a total of three times in the whole log.
I suggest just looking at the batch starting at line 19827.

If you need any additional info, just let me know.
Thanks!
____
EDIT: The error also seems to exists in "MC1.10.2-1.6.2.117-dev"

**Comment by GHXX** [comment]
It looks like this error is related to the config setting "ignorePower"
setting it to "ignorePower=true" seems to solve the issue. sadly then the power requirement is gone.

**Comment by brisingraerowing** [comment]
I'm not sure why ignorePower fixes it, but I think I figured out the exact issue here.

[This line](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/inventory/ComponentInventory.scala#L99) calls getSizeInventory, which returns a 1-based inventory size, and for loops use a 0-based indexing system. That call needs a '- 1' after it to fix this (most likely).

I'm going to test this in my custom 1.10 build (I applied several additional fixes from pull requests) and see what happens.

@fnuecke What do you think?

EDIT: Didn't work 😞

**Comment by brisingraerowing** [comment]
A quick reread of the stack trace and it is actually crashing on [this line](https://github.com/MightyPirates/OpenComputers/blob/06e7149573cc310254b691b3944eeb5d99619ff8/src/main/scala/li/cil/oc/common/inventory/ComponentInventory.scala#L102).

Not sure why yet.

**Comment by brisingraerowing** [comment]
A quick code change to work around that issue lead me to discover that MC is passing values larger than the component array's size into methods (e.g. onItemRemoved).

I think there is some kind of initialization sequence oddity, where something doesn't get initialized in the correct order.

**Comment by GHXX** [comment]
Any news? @BrisingrAerowing @fnuecke

**Comment by brisingraerowing** [comment]
I don't have the knowledge required to debug this, unfortunately.

**Comment by payonel** [comment]
@GHXX sorry i missed this ticket. does this still repro for you? i would like to investigate

**Comment by GHXX** [comment]
Well, i havent played that modpack since then tbh, But its the 'All the mods' pack from the twitch launcher if i recall correctly. It was still an issue when i stopped playing with it. Not sure about now, but i am fairly certain it will still be an issue.

If you want then i can check it for you.

**Comment by payonel** [comment]
If you could test first with *only* MC1.10.2-1.6.2.7
https://minecraft.curseforge.com/projects/opencomputers/files/2385987

(and if it does repro stand-alone, please retest with our latest builds. I have not ever seen this bug before)

If it does not repro, then we need to figure out the conflict

Do I need the curse launcher for that pack? Or is there an independent pack download I can use?

If you're feeling extra helpful, you could also try to repro this outside the ftb launcher and then start a binary search of disabling half the mods, and half again, until we can pinpoint the bad interop.

Thank you

**Comment by GHXX** [comment]
you would need the twitch launcher for the pack, that is the same as the curse launcher i think. The issue seems to be gone in the latest version (1.12.2) ill check out the old pack. Ill check the old All the mods pack.

**Comment by GHXX** [comment]
Reproducing succeeded in the modpack 'All the mods' (not all the mods 3) for version 1.10.2

```
	There was a problem writing a TileEntity description packet. Please report this if you see it!
java.lang.ArrayIndexOutOfBoundsException: 8
	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$saveComponents$1.apply$mcVI$sp(ComponentInventory.scala:102)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.common.inventory.ComponentInventory$class.saveComponents(ComponentInventory.scala:99)
	at li.cil.oc.common.tileentity.Case.saveComponents(Case.scala:28)
	at li.cil.oc.common.inventory.ComponentInventory$class.save(ComponentInventory.scala:94)
	at li.cil.oc.common.tileentity.Case.save(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.ComponentInventory$class.writeToNBTForClient(ComponentInventory.scala:178)
	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$RedstoneAware$$super$writeToNBTForClient(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.RedstoneAware$class.writeToNBTForClient(RedstoneAware.scala:128)
	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Computer$$super$writeToNBTForClient(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBTForClient(Computer.scala:179)
	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$writeToNBTForClient(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.Colored$class.writeToNBTForClient(Colored.scala:59)
	at li.cil.oc.common.tileentity.Case.writeToNBTForClient(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.TileEntity$class.getUpdateTag(TileEntity.scala:118)
	at li.cil.oc.common.tileentity.Case.func_189517_E_(Case.scala:28)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:156)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

and this error happened twice during autosaves (only one computer exists in the world)

`A TileEntity type li.cil.oc.common.tileentity.Case has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException: 8
	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$saveComponents$1.apply$mcVI$sp(ComponentInventory.scala:102)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.common.inventory.ComponentInventory$class.saveComponents(ComponentInventory.scala:99)
	at li.cil.oc.common.tileentity.Case.saveComponents(Case.scala:28)
	at li.cil.oc.common.inventory.ComponentInventory$class.save(ComponentInventory.scala:94)
	at li.cil.oc.common.tileentity.Case.save(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.Inventory$class.writeToNBTForServer(Inventory.scala:28)
	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$RedstoneAware$$super$writeToNBTForServer(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.RedstoneAware$class.writeToNBTForServer(RedstoneAware.scala:114)
	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$BundledRedstoneAware$$super$writeToNBTForServer(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.BundledRedstoneAware$class.writeToNBTForServer(BundledRedstoneAware.scala:146)
	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Computer$$super$writeToNBTForServer(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBTForServer(Computer.scala:161)
	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$writeToNBTForServer(Case.scala:28)
	at li.cil.oc.common.tileentity.traits.Colored$class.writeToNBTForServer(Colored.scala:48)
	at li.cil.oc.common.tileentity.Case.writeToNBTForServer(Case.scala:94)
	at li.cil.oc.common.tileentity.traits.TileEntity$class.writeToNBT(TileEntity.scala:101)
	at li.cil.oc.common.tileentity.Case.func_189515_b(Case.scala:28)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175)
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199)
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:216)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:134)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by GHXX** [comment]
It appears that 'Tesla-1.10.2-1.2.1.50' in conjunction with 'teslafied-1.10.2-1.1.0' causes that error. After adding them the issue came up. when removing 'teslafied-1.10.2-1.1.0' the issue disappeared again.

and yes, 'teslafied-1.10.2-1.1.0' is the correct spelling. Hope this helps.

**Comment by payonel** [comment]
this is a great help. thank you very much for your time. i'll see what we can do to safe guard from this type of failure

**Comment by GHXX** [comment]
Awesome, just let me know if you need any more info.

**Comment by payonel** [comment]
This is due to tesla calling `hasCapability`on the computer case before it has loaded its nbt data. The computer case is a ComponentInventory, which is designed to lazily populate its components slots array, intended to load afte nbt loading. This causes the computer case to run on improperly initialized data.

**Comment by GHXX** [comment]
Interesting, can you fix that though? I hope its not gonna be one of those 'willnotfix' issues like for other modder's mods.

**Comment by payonel** [comment]
I'm poking at it right now. Trying to find a balance between fix and hack

**Comment by brisingraerowing** [comment]
@GHXX Good find! I don't use Teslafied any more, as it broke a number of other mods as well (probably because of the same reason it broke OC). I just use Mekanism Universal Cables, as they will translate energy themselves.

**Comment by GHXX** [comment]
I find it wierd why someone would mess with stuff from other mods, whats the gain?
