### ISSUE TITLE
Crash with Industrial Craft classic/Thermal Expansion

### ISSUE THREAD

**Issue by Janrupf** [MightyPirates/OpenComputers#2612]
Hello,
I'm running Forge 1.7.10 and if I'm placing an redstone furnace on an adapter minecraft crashes with an  NoClassDefFoundError:
```java
[16:46:29] [Server thread/WARN] [OpenComputers]: A component of type 'li.cil.oc.common.tileentity.Adapter' threw an error while being connected to the component network.
java.lang.NoClassDefFoundError: ic2/core/block/reactor/tileentity/TileEntityReactorRedstonePort
	at li.cil.oc.integration.ic2.DriverReactorRedstonePort.getTileEntityClass(DriverReactorRedstonePort.java:20) ~[DriverReactorRedstonePort.class:?]
	at li.cil.oc.api.prefab.DriverSidedTileEntity.worksWith(DriverSidedTileEntity.java:16) ~[DriverSidedTileEntity.class:?]
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118) ~[Registry$$anonfun$2.class:?]
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118) ~[Registry$$anonfun$2.class:?]
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259) ~[TraversableLike$$anonfun$filterImpl$1.class:?]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[ResizableArray$class.class:?]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[ArrayBuffer.class:?]
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258) ~[TraversableLike$class.class:?]
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270) ~[TraversableLike$class.class:?]
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104) ~[AbstractTraversable.class:?]
	at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:118) ~[Registry$.class:?]
	at li.cil.oc.api.Driver.driverFor(Driver.java:174) ~[Driver.class:?]
	at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:91) ~[Adapter.class:?]
	at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:150) ~[Adapter$$anonfun$neighborChanged$2.class:?]
	at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:149) ~[Adapter$$anonfun$neighborChanged$2.class:?]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[IndexedSeqOptimized$class.class:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
	at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:149) ~[Adapter.class:?]
	at li.cil.oc.common.tileentity.Adapter.onConnect(Adapter.scala:160) ~[Adapter.class:?]
	at li.cil.oc.server.network.Node$class.onConnect(Node.scala:52) [Node$class.class:?]
	at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.onConnect(Network.scala:617) [Network$NodeBuilder$$anon$4.class:?]
	at li.cil.oc.server.network.Network.<init>(Network.scala:35) [Network.class:?]
	at li.cil.oc.server.network.Network$.joinNewNetwork(Network.scala:479) [Network$.class:?]
	at li.cil.oc.server.network.Network$$anonfun$joinOrCreateNetwork$1.apply(Network.scala:469) [Network$$anonfun$joinOrCreateNetwork$1.class:?]
	at li.cil.oc.server.network.Network$$anonfun$joinOrCreateNetwork$1.apply(Network.scala:447) [Network$$anonfun$joinOrCreateNetwork$1.class:?]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [IndexedSeqOptimized$class.class:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ArrayOps$ofRef.class:?]
	at li.cil.oc.server.network.Network$.joinOrCreateNetwork(Network.scala:447) [Network$.class:?]
	at li.cil.oc.api.Network.joinOrCreateNetwork(Network.java:48) [Network.class:?]
	at li.cil.oc.common.EventHandler$$anonfun$scheduleServer$1.apply$mcV$sp(EventHandler.scala:78) [EventHandler$$anonfun$scheduleServer$1.class:?]
	at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:146) [EventHandler$$anonfun$onServerTick$1.class:?]
	at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:145) [EventHandler$$anonfun$onServerTick$1.class:?]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [IndexedSeqOptimized$class.class:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [ArrayOps$ofRef.class:?]
	at li.cil.oc.common.EventHandler$.onServerTick(EventHandler.scala:145) [EventHandler$.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_157_EventHandler$_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.ClassNotFoundException: ic2.core.block.reactor.tileentity.TileEntityReactorRedstonePort
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	... 43 more
Caused by: java.lang.NullPointerException
[16:46:38] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: ic2/core/block/reactor/tileentity/TileEntityReactorRedstonePort
	at li.cil.oc.integration.ic2.DriverReactorRedstonePort.getTileEntityClass(DriverReactorRedstonePort.java:20) ~[DriverReactorRedstonePort.class:?]
	at li.cil.oc.api.prefab.DriverSidedTileEntity.worksWith(DriverSidedTileEntity.java:16) ~[DriverSidedTileEntity.class:?]
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118) ~[Registry$$anonfun$2.class:?]
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118) ~[Registry$$anonfun$2.class:?]
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259) ~[TraversableLike$$anonfun$filterImpl$1.class:?]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[ResizableArray$class.class:?]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[ArrayBuffer.class:?]
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258) ~[TraversableLike$class.class:?]
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270) ~[TraversableLike$class.class:?]
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104) ~[AbstractTraversable.class:?]
	at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:118) ~[Registry$.class:?]
	at li.cil.oc.api.Driver.driverFor(Driver.java:174) ~[Driver.class:?]
	at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:91) ~[Adapter.class:?]
	at li.cil.oc.common.block.Adapter.onNeighborChange(Adapter.scala:56) ~[Adapter.class:?]
	at net.minecraft.world.World.func_147453_f(World.java:3875) ~[ahb.class:?]
	at net.minecraft.world.World.func_147455_a(World.java:2603) ~[ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660) ~[apx.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:451) ~[ahb.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206) ~[abh.class:?]
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103) ~[abh.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[16:46:39] [Server thread/ERROR]: This crash report has been saved to: D:\Programme\MultiMC\instances\Crash Pack\minecraft\crash-reports\crash-2017-11-02_16.46.38-server.txt
[16:46:39] [Server thread/INFO]: Stopping server
[16:46:39] [Server thread/INFO]: Saving players
[16:46:39] [Server thread/INFO]: Saving worlds
[16:46:39] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/2/17 4:46 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: ic2/core/block/reactor/tileentity/TileEntityReactorRedstonePort
	at li.cil.oc.integration.ic2.DriverReactorRedstonePort.getTileEntityClass(DriverReactorRedstonePort.java:20)
	at li.cil.oc.api.prefab.DriverSidedTileEntity.worksWith(DriverSidedTileEntity.java:16)
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118)
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:118)
	at li.cil.oc.api.Driver.driverFor(Driver.java:174)
	at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:91)
	at li.cil.oc.common.block.Adapter.onNeighborChange(Adapter.scala:56)
	at net.minecraft.world.World.func_147453_f(World.java:3875)
	at net.minecraft.world.World.func_147455_a(World.java:2603)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

//EDIT:
It is crashing with every block, not only with a redstone furnace.

**Comment by Janrupf** [comment]
Ok, just noticed that it was already fixed, used an old version, sry :)
