### ISSUE TITLE
FTB Revelation 1.0 - OpenComputer: Received a badly formatted packet

### ISSUE THREAD

**Issue by GerritVK** [MightyPirates/OpenComputers#2695]
Server reports the following warning and the computer fails to start with no last error.
Every tick the server reports the same message, also when trying to power on the computer.

EDIT: No computers would start or respond to powering them on.

**ModPack:** FTBRevelation-1.0.0-1.12.2
**OpenComputers:** OpenComputers-MC1.12.1-1.7.1.43

```
[00:31:57] [Server thread/WARN] [opencomputers]: Received a badly formatted packet.
io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[AbstractByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[AbstractByteBuf.class:?]
        at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
        at io.netty.buffer.ByteBufInputStream.read(ByteBufInputStream.java:168) ~[ByteBufInputStream.class:?]
        at li.cil.oc.common.PacketHandler.li$cil$oc$common$PacketHandler$$process(PacketHandler.scala:49) [PacketHandler.class:?]
        at li.cil.oc.common.PacketHandler$$anon$1.run(PacketHandler.scala:38) [PacketHandler$$anon$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
```

**Comment by payonel** [comment]
can any computer start, or just the one?
was it working before?
what OC version (give full version name) is in this pack?

**Comment by payonel** [comment]
it appears to be OpenComputers-MC1.12.1-1.7.1.43.jar
our latest curseforge release version

**Comment by Vexatos** [comment]
Which version of Minecraft Forge are you using? There is a bug between 14.23.1.2574 and 14.23.1.2577 that would cause this. Update forge to version 14.23.1.2578 or later, or downgrade to 14.23.1.2573.

**Comment by payonel** [comment]
confirmed repro
ftb launcher's forge version is: forge-14.23.1.2575
this sounds like OC for 1.12 in all ftb packs for will FAIL
testing 2581

**Comment by payonel** [comment]
yeah, forge 1275 is definitely the problem. sorry mate

**Comment by GerritVK** [comment]
I can confirm downgrading forge to 2573 resolved the issue.
I tried to upgrade, all versions between 2577-2581 and it would crash during initializing. 

If it helps anyone using the twitch launcher:
1. View FTB Revelation Profile
2. Three dots top button top right under Current Profile: FTB Revelation
3. Profile Options
4. Change current Modloader Versons to forge-14.23.1.2573

P.S. I had to downgrade the server to the same version to get it to work. I didn't try newer versions of forge for the server.

**Comment by thiakil** [comment]
Technically the error implies that you guys are not using netty code correctly. See https://github.com/MinecraftForge/MinecraftForge/pull/4513 for some discussion on the topic.

It was reverted because people are not using this version of netty correctly. If you wish to use the buffer later you need to call `retain` on it and later `release`

**Comment by Baughn** [comment]
This is still a problem with Forge 14.23.1.2590.
