### ISSUE TITLE
Screen won't turn on.

### ISSUE THREAD

**Issue by mads256h** [MightyPirates/OpenComputers#2714]
Minecraft: 1.12.2
Mod version: 1.7.1.43
Modpack: FTB Revelation

As far as i know the error occurres when the computer has to talk to the screen. Everything works until i add a screen to my computer. It refuses to turn on or off and it spams the log with this message:

```
Received a badly formatted packet.
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
	at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864)
	at io.netty.buffer.ByteBufInputStream.read(ByteBufInputStream.java:168)
	at li.cil.oc.common.PacketHandler.li$cil$oc$common$PacketHandler$$process(PacketHandler.scala:49)
	at li.cil.oc.common.PacketHandler$$anon$1.run(PacketHandler.scala:38)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by mads256h** [comment]
Here is a screenshot of the log: https://i.imgur.com/wE0CZ0x.png

**Comment by mads256h** [comment]
Updated OpenComputers to version: 1.7.1.48
It now works and there is no log spam.
