### ISSUE TITLE
Ew...

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2749]
https://github.com/MightyPirates/OpenComputers/commit/eb5b44f59835a663d7b0494202da39391096f72a

This integration is great and all, but what if I remove BuildCraft... then I get this nasty PAGE LONG error in my log files... can we at least get the disabler working? Adding the buildcraft to the blacklist does nothing. 

`java.lang.NoClassDefFoundError: li/cil/oc/integration/buildcraft/recipes/LootDiskProgrammableRecipe$
        at li.cil.oc.integration.buildcraft.recipes.ModBuildCraftRecipes$.initialize(ModBuildCraftRecipes.scala:10) ~[ModBuildCraftRecipes$.class:?]
        at li.cil.oc.integration.Mods$.li$cil$oc$integration$Mods$$tryInit(Mods.scala:161) [Mods$.class:?]
        at li.cil.oc.integration.Mods$$anonfun$init$1.apply(Mods.scala:152) [Mods$$anonfun$init$1.class:?]
        at li.cil.oc.integration.Mods$$anonfun$init$1.apply(Mods.scala:151) [Mods$$anonfun$init$1.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.7.jar:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.7.jar:?]
        at li.cil.oc.integration.Mods$.init(Mods.scala:151) [Mods$.class:?]
        at li.cil.oc.common.Proxy.init(Proxy.scala:89) [Proxy.class:?]
        at li.cil.oc.server.Proxy.init(Proxy.scala:10) [Proxy.class:?]
        at li.cil.oc.OpenComputers$.init(OpenComputers.scala:43) [OpenComputers$.class:?]
        at li.cil.oc.OpenComputers.init(OpenComputers.scala) [OpenComputers.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:1.7.10-1614.58]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:1.7.10-1614.58]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:1.7.10-1614.58]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1614.58]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:1.7.10-1614.58]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) [FMLCommonHandler.class:1.7.10-1614.58]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: li.cil.oc.integration.buildcraft.recipes.LootDiskProgrammableRecipe$
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        ... 42 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/recipes/IProgrammingRecipe
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_161]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_161]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        ... 42 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.recipes.IProgrammingRecipe
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_161]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_161]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        ... 42 more
Caused by: java.lang.NullPointerException
`

**Comment by fnuecke** [comment]
Stuff like this usually indicates that some other mod is shipping a partial API. I'd wager this does not occur with only OC installed (or someone would have complained in the 2+ years this has been in). Please try to narrow it down to which mod adds the partial API.

**Comment by ghost** [comment]
So what you are saying is, I don't have BC installed, but some other mod has part of the BC API within it, thus OC detects it as BC. 

I can work with this I think. Most of them do have the disable BC config aspect. TY. Will post results, but you can close this.
