### ISSUE TITLE
Class Transformers Errors.    (Was told to report this)

### ISSUE THREAD

**Issue by MLMII** [MightyPirates/OpenComputers#2750]
[18:51:49] [main/INFO]: Setting user: MLMII
[18:51:53] [main/WARN]: Skipping bad option: lastServer:
[18:51:53] [main/INFO]: LWJGL Version: 2.9.4
[18:52:05] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:AbyssalCraft Integration, FMLFileResourcePack:AbyssalCraft, FMLFileResourcePack:Akashic Tome, FMLFileResourcePack:Amidst Bridge mod, FMLFileResourcePack:Angel of Vengeance, FMLFileResourcePack:Astral Sorcery, FMLFileResourcePack:AutoRegLib, FMLFileResourcePack:AutoWalk Mod, FMLFileResourcePack:Bark Books, FMLFileResourcePack:Baubles, FMLFileResourcePack:Better Advancements, FMLFileResourcePack:Bird's nests, FMLFileResourcePack:Bloodmoon, FMLFileResourcePack:Botania, FMLFileResourcePack:Botaunomy, FMLFileResourcePack:By The Gods, FMLFileResourcePack:CleanView, FMLFileResourcePack:Client Tweaks, FMLFileResourcePack:Comforts, FMLFileResourcePack:CosmeticArmorReworked, FMLFileResourcePack:Craftable Saddles, FMLFileResourcePack:[Unofficial] Forge Creeper Heal, FMLFileResourcePack:The Creeping Nether, FMLFileResourcePack:Cyberware, FMLFileResourcePack:Cyclops Core, FMLFileResourcePack:Davinci's Vessels, FMLFileResourcePack:Energy Converters, FMLFileResourcePack:EverlastingAbilities, FMLFileResourcePack:EvilCraft, FMLFileResourcePack:EvilCraft-Compat, FMLFileResourcePack:FL, FMLFileResourcePack:Flux Networks, FMLFileResourcePack:Friendly Fire, FMLFileResourcePack:Genetics Reborn, FMLFileResourcePack:Guide-API, FMLFileResourcePack:Hammer Core, FMLFileResourcePack:HerdCraft, FMLFileResourcePack:Better HUD, FMLFileResourcePack:Improvable Skills, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:Infini-TiC, FMLFileResourcePack:Iskallium Reactors, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Just a Few Fish, FMLFileResourcePack:Level Up! Reloaded, FMLFileResourcePack:Lycanites Arctic Mobs, FMLFileResourcePack:Lycanites Demon Mobs, FMLFileResourcePack:Lycanites Desert Mobs, FMLFileResourcePack:Lycanites Elemental Mobs, FMLFileResourcePack:Lycanites Forest Mobs, FMLFileResourcePack:Lycanites Freshwater Mobs, FMLFileResourcePack:Lycanites Inferno Mobs, FMLFileResourcePack:Lycanites Jungle Mobs, FMLFileResourcePack:Lycanites Mobs, FMLFileResourcePack:Lycanites Mountain Mobs, FMLFileResourcePack:Lycanites Plains Mobs, FMLFileResourcePack:Lycanites Saltwater Mobs, FMLFileResourcePack:Lycanites Shadow Mobs, FMLFileResourcePack:Lycanites Swamp Mobs, FMLFileResourcePack:Magical Psi, FMLFileResourcePack:Mana Wells, FMLFileResourcePack:Mantle, FMLFileResourcePack:Minecraft Comes Alive, FMLFileResourcePack:Mending Fix, FMLFileResourcePack:MmmMmmMmmMmm, FMLFileResourcePack:Moar Tinkers, FMLFileResourcePack:Morph-o-Tool, FMLFileResourcePack:Moving World, FMLFileResourcePack:Natural Absorption, FMLFileResourcePack:Nature's Compass, FMLFileResourcePack:NemesisSystem, FMLFileResourcePack:Nibbler, FMLFileResourcePack:No Enderman Pickup, FMLFileResourcePack:NotEnoughIDs, FMLFileResourcePack:Not Enough Wands, FMLFileResourcePack:OfflineSkins, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:p455w0rd's Library, FMLFileResourcePack:Pam's Squid Milking, FMLFileResourcePack:PiTweaks, FMLFileResourcePack:PlusTiC, FMLFileResourcePack:Potion Fingers, FMLFileResourcePack:ProjectE, FMLFileResourcePack:Psi, FMLFileResourcePack:RadixCore, FMLFileResourcePack:Redstone Flux, FMLFileResourcePack:ReWIRED, FMLFileResourcePack:SG Craft, FMLFileResourcePack:SonarCore, FMLFileResourcePack:TamModized, FMLFileResourcePack:Campfire Spit, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:The Betweenlands, FMLFileResourcePack:Tinkers' Addons, FMLFileResourcePack:Tinkers' Complement, FMLFileResourcePack:TinkersExtras, FMLFileResourcePack:Tinkers Tool Leveling, FMLFileResourcePack:ToroHealth Damage Indicators, FMLFileResourcePack:ToroQuest, FMLFileResourcePack:ToroTraits, FMLFileResourcePack:Totem Defender, FMLFileResourcePack:Tough As Nails, FMLFileResourcePack:Tough Expansion, FMLFileResourcePack:Tweakers Construct, FMLFileResourcePack:UI Tweaks, FMLFileResourcePack:Waystones, magipsi-texture-proxy
[18:52:36] [main/WARN]: File improvableskills:sounds/stats_book_open.ogg does not exist, cannot add it to event improvableskills:stats_book_open
[18:52:36] [main/WARN]: File improvableskills:sounds/stats_book_closed.ogg does not exist, cannot add it to event improvableskills:stats_book_closed
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.hellfirewall
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.hellfireorb
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.hellfirewave
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.hellfirewavepart
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.hellfirebarrier
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.hellfirebarrierpart
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.hellshield
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.helllaser
[18:52:36] [main/WARN]: Missing sound for event: demonmobs:projectile.helllaserend
[18:52:36] [main/WARN]: Missing sound for event: elementalmobs:projectile.lifedrainend
[18:52:36] [main/WARN]: Missing sound for event: freshwatermobs:projectile.waterjetend
[18:52:36] [main/WARN]: Missing sound for event: mountainmobs:projectile.arcanelaserend
[18:52:36] [main/WARN]: Missing sound for event: swampmobs:projectile.poisonrayend
[18:52:36] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:52:36] [Thread-8/INFO]: Initializing LWJGL OpenAL
[18:52:36] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:52:36] [Thread-8/INFO]: OpenAL initialized.
[18:52:37] [Sound Library Loader/INFO]: Sound engine started
[18:52:50] [main/INFO]: Created: 4096x2048 textures-atlas
[18:53:19] [main/ERROR]: Couldn't load loot table evilcraft:inject/chests/box_of_eternal_closure from jar:file:/C:/Users/Winterstar/AppData/Roaming/.minecraft/mods/EvilCraft-1.12.2-0.10.47.jar!/assets/evilcraft/loot_tables/inject/chests/box_of_eternal_closure.json
com.google.gson.JsonParseException: Loot Table "evilcraft:inject/chests/box_of_eternal_closure" Duplicate entry name "evilcraft:box_of_eternal_closure" for pool #-1 entry #1
	at net.minecraftforge.common.ForgeHooks$LootTableContext.validateEntryName(ForgeHooks.java:1198) ~[ForgeHooks$LootTableContext.class:?]
	at net.minecraftforge.common.ForgeHooks.readLootEntryName(ForgeHooks.java:1249) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootEntryItem.func_186367_a(LootEntryItem.java:82) ~[bfp.class:?]
	at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:69) ~[bfr$a.class:?]
	at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:45) ~[bfr$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188174_a(SourceFile:447) ~[rc.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:144) ~[bfq$a.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[bfq$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:204) ~[bfs$a.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:199) ~[bfs$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1149) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156) [bfv$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72) [bfv$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53) [bfv$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [guava-21.0.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40) [bfv.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:49) [bfv.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35) [bfv.class:?]
	at thebetweenlands.common.registries.LootTableRegistry.getManager(LootTableRegistry.java:168) [LootTableRegistry.class:?]
	at thebetweenlands.common.registries.LootTableRegistry.getItemsFromTable(LootTableRegistry.java:106) [LootTableRegistry.class:?]
	at thebetweenlands.compat.jei.recipes.animator.AnimatorRecipeJEI.getIngredients(AnimatorRecipeJEI.java:95) [AnimatorRecipeJEI.class:?]
	at mezz.jei.recipes.RecipeRegistry.getIngredients(RecipeRegistry.java:279) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:267) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:255) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:227) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:205) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipes(RecipeRegistry.java:163) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.<init>(RecipeRegistry.java:94) [RecipeRegistry.class:?]
	at mezz.jei.startup.ModRegistry.createRecipeRegistry(ModRegistry.java:302) [ModRegistry.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:64) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:118) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:728) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:53:24] [main/WARN]: Skipping bad option: lastServer:
[18:53:24] [main/INFO]: Narrator library for x64 successfully loaded
[18:53:31] [main/INFO]: Deleting level New World
[18:53:31] [main/INFO]: Attempt 1...
[18:53:42] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[18:53:42] [Server thread/INFO]: Generating keypair
[18:53:46] [Server thread/ERROR]: Couldn't load loot table evilcraft:inject/chests/box_of_eternal_closure from jar:file:/C:/Users/Winterstar/AppData/Roaming/.minecraft/mods/EvilCraft-1.12.2-0.10.47.jar!/assets/evilcraft/loot_tables/inject/chests/box_of_eternal_closure.json
com.google.gson.JsonParseException: Loot Table "evilcraft:inject/chests/box_of_eternal_closure" Duplicate entry name "evilcraft:box_of_eternal_closure" for pool #-1 entry #1
	at net.minecraftforge.common.ForgeHooks$LootTableContext.validateEntryName(ForgeHooks.java:1198) ~[ForgeHooks$LootTableContext.class:?]
	at net.minecraftforge.common.ForgeHooks.readLootEntryName(ForgeHooks.java:1249) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootEntryItem.func_186367_a(LootEntryItem.java:82) ~[bfp.class:?]
	at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:69) ~[bfr$a.class:?]
	at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:45) ~[bfr$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188174_a(SourceFile:447) ~[rc.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:144) ~[bfq$a.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[bfq$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:204) ~[bfs$a.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:199) ~[bfs$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1149) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156) [bfv$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72) [bfv$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53) [bfv$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [guava-21.0.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40) [bfv.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:49) [bfv.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35) [bfv.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[18:53:46] [Server thread/INFO]: Loaded 650 advancements
[18:53:46] [Server thread/WARN]: Unable to find spawn biome
[18:53:48] [Server thread/INFO]: Preparing start region for level 0
[18:53:49] [Server thread/INFO]: Preparing spawn area: 7%
[18:53:50] [Server thread/INFO]: Preparing spawn area: 14%
[18:53:51] [Server thread/INFO]: Preparing spawn area: 23%
[18:53:52] [Server thread/INFO]: Preparing spawn area: 31%
[18:53:53] [Server thread/INFO]: Preparing spawn area: 40%
[18:53:54] [Server thread/INFO]: Preparing spawn area: 49%
[18:53:55] [Server thread/INFO]: Preparing spawn area: 59%
[18:53:56] [Server thread/INFO]: Preparing spawn area: 70%
[18:53:57] [Server thread/INFO]: Preparing spawn area: 82%
[18:53:58] [Server thread/INFO]: Preparing spawn area: 93%
[18:54:00] [Server thread/INFO]: Changing view distance to 16, from 10
[18:54:01] [Server thread/INFO]: MLMII[local:E:96d9c9a6] logged in with entity id 2085 at (-75.5, 66.0, 68.5)
[18:54:01] [Server thread/INFO]: MLMII joined the game
[18:54:07] [main/INFO]: [CHAT] §aOpenComputers§f: There were §cerrors§f running the class transformer. Please report this, together with your (full!) FML §alatest.log§f/§afml-server-latest.log§f logfile, thank you!
[18:54:09] [main/INFO]: [CHAT] Izphis the Late has established rule of a new domain
[18:54:10] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 9337ms behind, skipping 186 tick(s)
[18:54:11] [main/INFO]: [CHAT] Izphis the Late has been promoted to level 2
[18:54:11] [main/INFO]: [CHAT] Odapus the Heart-Eater has established rule of a new domain
[18:54:11] [main/INFO]: [CHAT] Odapus the Heart-Eater has been promoted to level 2
[18:54:11] [main/INFO]: [CHAT] Hison the Tongue has established rule of a new domain
[18:54:11] [main/INFO]: [CHAT] Izphis the Late has been promoted to level 3
[18:54:11] [main/INFO]: [CHAT] Ocleling the Foul has established rule of a new domain
[18:54:11] [main/INFO]: [CHAT] Odapus the Heart-Eater has been promoted to level 3
[18:54:11] [main/INFO]: [CHAT] Egarora the Meat Hoarder has established rule of a new domain
[18:54:12] [main/INFO]: [CHAT] Ocleling the Foul has been promoted to level 2
[18:54:12] [main/INFO]: [CHAT] Risea the Barrel-Scraper has established rule of a new domain
[18:54:12] [main/INFO]: [CHAT] Odapus the Heart-Eater has been promoted to level 4
[18:54:12] [main/INFO]: [CHAT] Egoginia the Knife has established rule of a new domain
[18:54:12] [main/INFO]: [CHAT] Risea the Barrel-Scraper has been promoted to level 2
[18:54:12] [main/INFO]: [CHAT] Cora the Scar-Artist has established rule of a new domain
[18:54:24] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3202ms behind, skipping 64 tick(s)
[18:54:33] [Server thread/INFO]: Saving and pausing game...
[18:54:33] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[18:54:34] [Server thread/INFO]: Saving chunks for level 'New World'/the_nether
[18:54:34] [Server thread/INFO]: Saving chunks for level 'New World'/the_end
[18:54:34] [Server thread/INFO]: Saving chunks for level 'New World'/The Dark Realm
[18:54:34] [Server thread/INFO]: Saving chunks for level 'New World'/betweenlands
[18:54:34] [Server thread/INFO]: Saving chunks for level 'New World'/Omothol
[18:54:34] [Server thread/INFO]: Saving chunks for level 'New World'/The Dreadlands
[18:54:34] [Server thread/INFO]: Saving chunks for level 'New World'/The Abyssal Wasteland

**Comment by xarses** [comment]
Which versions of MC, Forge and OC are this for?

**Comment by MLMII** [comment]
Minecraft 1.12.2
Forge 1.12.2-14.23.2.2615
Open Computers MC1.12.1-1.7.1.43


How serious is the error if I may ask?


*Edit*


I get the same error message with Forge 1.12.2-14.23.2.2616  as well.   (Just noticed that my green "please update" light was on for Forge.
