### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Shybella** [MightyPirates/OpenComputers#2850]
`[12:03:43] [main/WARN] [opencomputers]: Error in item tooltip.
java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at li.cil.oc.common.item.Manual.tooltipLines(Manual.scala:22) ~[Manual.class:?]
	at li.cil.oc.common.item.Delegator.func_77624_a(Delegator.scala:196) ~[Delegator.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707) ~[aip.class:?]
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575) ~[bib.class:?]
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49) ~[cgw.class:?]
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44) ~[cgw.class:?]
	at java.lang.Iterable.forEach(Unknown Source) [?:1.8.0_73]
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: com.mojang.realmsclient.gui.ChatFormatting
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	... 17 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	... 17 more`

**Comment by payonel** [comment]
you should clarify crash vs stack printed to logs
if it is merely a WARN log report, I assume this is NOT a crash?

Anyways, I would guess that the manual (that you start the game with) is failing to generate the tooltip, trying to use the ChatFormatting class. This is a similar (not the same, but similar) bug to #2792

Anyways, when we fix 2792, I'll look at this bug as well.
Also, when you provide a bug report, you ought to provide more details. Some example detail you should always give:

1. full oc version
2. full mc version
3. Can you repro by creating a new flat world in creative mode
4. Do you see this as soon as a new world is loaded for the first time, without issuing any action or command?
5. Does it repro with OC only (and no other mod, but forge alone)

And for this specific stack trace, you can also test:

6. If you remove the manual from your person, then reload the world, does it still repro?

**Comment by Vexatos** [comment]
Closed via https://github.com/MightyPirates/OpenComputers/commit/225e907c49af61c8c3357ebd1ca8a43ea96127d4.

**Comment by Shybella** [comment]
Nice, thanks.
