### ISSUE TITLE
Shift-clicking crash on latest 1.12.2 build

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#2876]
```
java.lang.NullPointerException: Updating screen events
	at li.cil.oc.common.container.Player.tryMoveAllSlotToSlot(Player.scala:70)
	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$1.apply$mcVI$sp(Player.scala:110)
	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$1.apply(Player.scala:109)
	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$1.apply(Player.scala:109)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at li.cil.oc.common.container.Player.tryTransferStackInSlot(Player.scala:109)
	at li.cil.oc.common.container.Player.func_82846_b(Player.scala:46)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at li.cil.oc.common.container.Player.func_184996_a(Player.scala:34)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)```

```
	| UCHIJAAAA | minecraft          | 1.12.2         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                | 9.42           | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99      | forge-1.12.2-14.23.4.2725-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.4.2725   | forge-1.12.2-14.23.4.2725-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | foamfixcore        | 7.7.4          | minecraft.jar                           | None                                     |
	| UCHIJAAAA | opencomputers|core | 1.7.2.71       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | asielib            | 1.0.0          | Computronics-1.12.2-1.6.6.183-ssml2.jar | None                                     |
	| UCHIJAAAA | opencomputers      | 1.7.2.71       | OpenComputers-MC1.12.2-1.7.2.71.jar     | None                                     |
	| UCHIJAAAA | computronics       | 1.6.6          | Computronics-1.12.2-1.6.6.183-ssml2.jar | None                                     |
	| UCHIJAAAA | foamfix            | 0.9.9.1-1.12.2 | foamfix-0.9.9.1-1.12.2-anarchy.jar      | None                                     |```

**Comment by asiekierka** [comment]
duplicate of https://github.com/MightyPirates/OpenComputers/issues/2858
