### ISSUE TITLE
Unexpected error in Lua callback java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by bastetfurry** [MightyPirates/OpenComputers#2925]
Using the latest release, OpenComputers-MC1.12.2-1.7.2.67.jar, the following little snippet running on a robot

```
local function main()
  robot.select(1)
  print("Press 'q' to quit...")

  while true do
    -- do_work()
    local e, addr, ch, code, player = event.pull(0.1, "key_down")
    if e and keyboard.keys[code] == "q" then
      print("Exiting...")
      break
    end
  end
end

main()
```

generates the following error repeatedly

```
[19:06:53] [Server thread/WARN] [opencomputers]: Unexpected error in Lua callback.
java.lang.NullPointerException: null
```

Could you please at least turn off these warnings so that they don't clutter my logfile anymore?
It should error out the Lua program, my log doesn't care when someones Lua code might be bad. ;)

**Comment by payonel** [comment]
I could not repro this.
This exception log should only happen when a lua call being made throws an exception, and it would return a failure to the lua method making the call. Perhaps you had other lua states running, perhaps you had a component on your machine that was misbehaving, I don't know. But as for the value of logging these exceptions, we in general should keep this log warning as it helps us in other bug reports. If you are able to isolate this issue (what mods are required, does it repro in single player with nothing in the world but a robot on this script?, etc -- help us repro) then i can look into what was throwing the exception

**Comment by bastetfurry** [comment]
Got this one.
```
[16:18:55] [Server thread/WARN] [opencomputers]: Unexpected error in Lua callback.
java.lang.NullPointerException: null
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:432) ~[aip.class:?]
	at li.cil.oc.server.agent.Player.callUsingItemInSlot(Player.scala:507) ~[Player.class:?]
	at li.cil.oc.server.agent.Player.clickBlock(Player.scala:360) ~[Player.class:?]
	at li.cil.oc.server.component.Agent$class.click$1(Agent.scala:113) ~[Agent$class.class:?]
	at li.cil.oc.server.component.Agent$$anonfun$swing$1.apply(Agent.scala:135) ~[Agent$$anonfun$swing$1.class:?]
	at li.cil.oc.server.component.Agent$$anonfun$swing$1.apply(Agent.scala:122) ~[Agent$$anonfun$swing$1.class:?]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:?]
	at li.cil.oc.server.component.Agent$class.swing(Agent.scala:122) ~[Agent$class.class:?]
	at li.cil.oc.server.component.Robot.swing(Robot.scala:32) ~[Robot.class:?]
	at generated.li.cil.oc.CallWrapper_li_cil_oc_server_component_Robot_swing.call(Unknown Source) ~[?:?]
	at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123) ~[Callbacks$ComponentCallback.class:?]
	at li.cil.oc.server.network.Component$class.invoke(Component.scala:112) ~[Component$class.class:?]
	at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.invoke(Network.scala:631) ~[Network$ComponentConnectorBuilder$$anon$1.class:?]
	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:360) ~[Machine.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) ~[ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) ~[ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24) [ExtendedLuaState$ExtendedLuaState$$anon$1.class:?]
	at li.cil.repack.com.naef.jnlua.LuaStateFiveThree.lua_pcall(Native Method) ~[LuaStateFiveThree.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:681) [LuaState.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runSynchronized(NativeLuaArchitecture.scala:177) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.Machine.update(Machine.scala:564) [Machine.class:?]
	at li.cil.oc.common.EventHandler$$anonfun$onServerTick$2.apply(EventHandler.scala:168) [EventHandler$$anonfun$onServerTick$2.class:?]
	at li.cil.oc.common.EventHandler$$anonfun$onServerTick$2.apply(EventHandler.scala:166) [EventHandler$$anonfun$onServerTick$2.class:?]
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78) [scala-library-2.11.1.jar:?]
	at li.cil.oc.common.EventHandler$.onServerTick(EventHandler.scala:166) [EventHandler$.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_369_EventHandler$_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by payonel** [comment]
this needs a repro, not just a callstack
what item was your robot swinging?
does it happen every time, or how often does it happen?

**Comment by bastetfurry** [comment]
The robots hand was empty, if i place something into its hand the messages stop.

**Comment by payonel** [comment]
is anything else in the inventory, is there a block or entity in front of the robot
.... please provide repro steps and not just a stack trace
