### ISSUE TITLE
NPE when adding components to computer case

### ISSUE THREAD

**Issue by LemADEC** [MightyPirates/OpenComputers#2952]
Using OpenComputers-MC1.12.2-1.7.2.103, as part of world generation, I'm adding "random" components to a computer case for sake of variation.
When adding items in certain *valid* slots, an Null Pointer Exception is generated. Any thoughts on what's going on here?

Code extract:
```
if (inventory.isItemValidForSlot(indexSlot, itemStackLoot)) {
	try {
		inventory.setInventorySlotContents(indexSlot, itemStackLoot);
		isAdded = true;
	} catch (final Exception exception) {
		exception.printStackTrace();
		WarpDrive.logger.info(String.format("Exception while adding %s from LootSet %s in slot %d of inventory %s %s: %s",
		                                    itemStackLoot.getDisplayName(),
		                                    lootSet.getFullName(),
		                                    indexSlot,
		                                    inventory.getName() == null ? "-null name-" : inventory.getName(),
		                                    Commons.format(world, x, y, z),
		                                    exception.getMessage()));
	}
}
```

Related logs:
```
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: java.lang.NullPointerException
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.server.network.Node$class.connect(Node.scala:40)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.connect(Network.scala:631)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$class.connectItemNode(ComponentInventory.scala:185)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.connectItemNode(Case.scala:28)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:149)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:134)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at scala.Option.foreach(Option.scala:245)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$class.onItemAdded(ComponentInventory.scala:134)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$ComponentInventory$$super$onItemAdded(Case.scala:28)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.traits.ComponentInventory$class.onItemAdded(ComponentInventory.scala:86)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.onItemAdded(Case.scala:106)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.Inventory$class.setInventorySlotContents(Inventory.scala:43)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.setInventorySlotContents(Case.scala:28)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.world.WorldGenStructure.fillInventoryWithLoot(WorldGenStructure.java:210)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.world.WorldGenStructure.setComputerCore(WorldGenStructure.java:140)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.world.WorldGenSmallShip.generate(WorldGenSmallShip.java:355)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.command.CommandGenerate.execute(CommandGenerate.java:78)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:126)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:98)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1001)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:977)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:47)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:8)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.util.Util.runTask(Util.java:53)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at java.lang.Thread.run(Thread.java:748)
[23:18:22] [Server thread/INFO] [warpdrive]: Exception while adding Memory (Tier 1.5) from LootSet ship_computerCore:OpenComputers in slot 5 of inventory oc:container.case in @ solarSystem (-40184 100 30285): null
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: java.lang.NullPointerException
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.server.network.Node$class.connect(Node.scala:40)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.connect(Network.scala:631)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$class.connectItemNode(ComponentInventory.scala:185)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.connectItemNode(Case.scala:28)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:149)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:134)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at scala.Option.foreach(Option.scala:245)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.ComponentInventory$class.onItemAdded(ComponentInventory.scala:134)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$ComponentInventory$$super$onItemAdded(Case.scala:28)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.traits.ComponentInventory$class.onItemAdded(ComponentInventory.scala:86)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.onItemAdded(Case.scala:106)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.inventory.Inventory$class.setInventorySlotContents(Inventory.scala:43)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at li.cil.oc.common.tileentity.Case.setInventorySlotContents(Case.scala:28)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.world.WorldGenStructure.fillInventoryWithLoot(WorldGenStructure.java:210)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.world.WorldGenStructure.setComputerCore(WorldGenStructure.java:140)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.world.WorldGenSmallShip.generate(WorldGenSmallShip.java:355)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at cr0s.warpdrive.command.CommandGenerate.execute(CommandGenerate.java:78)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:126)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:98)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1001)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:977)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:47)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:8)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.util.Util.runTask(Util.java:53)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
[23:18:22] [Server thread/INFO] [STDERR]: [cr0s.warpdrive.world.WorldGenStructure:fillInventoryWithLoot:213]: 	at java.lang.Thread.run(Thread.java:748)
[23:18:22] [Server thread/INFO] [warpdrive]: Exception while adding Central Processing Unit (CPU) (Tier 1) from LootSet ship_computerCore:OpenComputers in slot 4 of inventory oc:container.case in @ solarSystem (-40184 100 30285): null
```

The exception isn't systematic.
I don't know which slot is which, so I'm trying multiple slots until the `isItemValidForSlot()` check is passed.

**Comment by payonel** [comment]
This workflow is slightly outside our support, but I'm interested in investigating it further for you. Can you provide a link to download a prototype of what you're working that I may run the command and test the npe myself? If you need a private link, you can private message me on our irc (esper.net) #oc 
This is probably a case where the node network is pending, and you are adding nodes before it is ready. There are actions that occur for our nodes at different world events. While we could check for null in this specific case, it might just delay the problem further down stream. But I would like to test that as well.

**Comment by LemADEC** [comment]
Thanks for looking into this!

On Esper, I've PM you the current 'in progress' version of the mod. In a fresh world, with just WarpDrive + OpenComputers, type `/generate ship`. It'll overwrite blocks in place.
Computer components are defined in the config/warpdrive/loot-default.xml (line 145+).

The sequence of execution in setComputerCore() is:
- call `world.setBlockState(world, blockPos, blockState, 2)`
- call `world.getTileEntity(blockPos)`
- on each inventory slots, call `inventory.getStackInSlot(indexSlot)`
- on a random slot,
-- call `inventory.isItemValidForSlot(indexSlot, itemStackLoot)`
-- call `inventory.setInventorySlotContents(indexSlot, itemStackLoot)`

**Comment by payonel** [comment]
btw, i've editted my previous comment....my typing must have auto corrected to 2092, i meant to write #oc not #2092 
weird, sorry
but i see the private message, thank you

**Comment by payonel** [comment]
creating a block creates the tile entity, which holds the nodes and networks used when installing components (setting component items in their inventories)

but there needs to be a synchronization between client and server. Every OC component has a UUID, and the UUID is either generated or loaded from the chunk data. For historical reasons, we generate the UUID during the first update pass of the tile entity in the world. The network of the tilentity does not exist until it has updated at least once

your `/generate ship` command is using the tile entities before any update pass, thus before the network exists.

I tested forcing the component network to initialize if onItemAdded was called before the network was ready. and this does provide a working network for you to add items to the block in this immediate fashion.

However, I have some real concerns about changing our init process this dramatically. This could cause tile entities to load their components before all tile entities adjacent have loaded. Such a situation would not trigger a "recheck for components" and systems would load in the world lacking components (from the perspective of the computer). Also, we have done it this way for quite some time

Using our block inventories in this fashion is not strictly supported. You could argue that we are not respecting the IInventory interface. It might work for OC to force the component network initialization I have lightly tested to support your workflow, but there is significant risk given that: **this is how we've done it for many years**

If at _all_ possible, given that your code knows when all blocks have been created in the world, if you could force a world update, and THEN add the component items in their inventories, this should resolve the problem

Closing for now as "not supported". I do hope my work around, and explanation, are to your satisfaction. Feel free to reach out to me on irc if you would like to investigate this further

**Comment by LemADEC** [comment]
I understand the mod design choice is to immediately react to inventory changes, however the network isn't necessarily 'initialized' at that time.
My experience in fixing other mods told me that immediate reaction tends to create cascading issues, and I usually end up postponing such task to the IIterable.update() method. I'm not sure how that would work here for OC.

I did a few tests on my side and noted that the world isn't set yet when I'm adding items to the inventory. By extension, the tile hasn't ticked yet either. I've tried setting the world manually and calling TileEntity.onLoad() and IIterable.update() but that didn't help and leads to the same callstack in OC. In other words, your proposed work around doesn't seem to work.

Since the network isn't initialized yet, I wonder what are the consequences of that NPE? since the item is still effectively added to the block, could I safely ignore the NPE here?

**Comment by payonel** [comment]
@LemADEC  i actually discussed this issue further with others familiar with OC networks, and it seems that the null check could be added safely, probably, because the network would still initialize on the next world tick, and all the component connection events would fire like i need them to
i'll add a null check. at worst it hides a component in some loading scenarios --- which would have npe'd anyways
