### ISSUE TITLE
Illegal extra prefix oc for name

### ISSUE THREAD

**Issue by 0uti** [MightyPirates/OpenComputers#296]
i got multiple errors like these.

20:40:51] [Client thread/WARN] [FML]: ****************************************
[20:40:51] [Client thread/WARN] [FML]: \* Illegal extra prefix oc for name oc:simple, invalid registry invocation/invalid name?
[20:40:51] [Client thread/WARN] [FML]: \*  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:789)
[20:40:51] [Client thread/WARN] [FML]: \*  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:212)
[20:40:51] [Client thread/WARN] [FML]: \*  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:171)
[20:40:51] [Client thread/WARN] [FML]: \*  at li.cil.oc.Blocks$.init(Blocks.scala:23)
[20:40:51] [Client thread/WARN] [FML]: \*  at li.cil.oc.common.Proxy.preInit(Proxy.scala:28)
[20:40:51] [Client thread/WARN] [FML]: \*  at li.cil.oc.client.Proxy.preInit(Proxy.scala:19)...
[20:40:51] [Client thread/WARN] [FML]: ****************************************

**Comment by Wuerfel21** [comment]
these are WARNINGS, they say MAYBE theres someting wrong, as long as it launches it is fine

**Comment by fnuecke** [comment]
Odd, I don't get those. Which Forge version are you using?

**Comment by 0uti** [comment]
unsing Forge  10.12.1.1112

**Comment by fnuecke** [comment]
Well, turns out they added that warning a little too late :P To fix it i'd have to adjust all of the blocks' and items' names... meaning all existing blocks and items in worlds would go poof. And I don't see any way to define 'aliases'... so for now I think I'll just ignore the warning. At some point I'll have to make the breaking change, but I don't the time is now.

**Comment by LordFokas** [comment]
glue the breaking change to another breaking change. 2 for 1.

**Comment by fnuecke** [comment]
Yeah, something like that. The changes in 1.3 aren't really breaking enough, though, that'd be ideal otherwise (since all that breaks can pretty much be fixed by placing down a disk drive with an OpenOS disk in it).
