### ISSUE TITLE
Crash when trying to use a remote-terminal when paired terminal-server is in inventory

### ISSUE THREAD

**Issue by fuami** [MightyPirates/OpenComputers#2994]
I'm not if its supposed to work or anything, but since it crashed I thought I would report it.

Versions:
forge-14.23.5.2772
OpenComputers-MC1.12.2-1.7.3.146.jar 

```
java.lang.NullPointerException: Unexpected error
	at li.cil.oc.client.GuiHandler$.getClientGuiElement(GuiHandler.scala:122)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at li.cil.oc.common.item.Terminal.onItemRightClick(Terminal.scala:59)
	at li.cil.oc.common.item.Delegator.func_77659_a(Delegator.scala:149)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1596)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by payonel** [comment]
Looks like you are right clicking with a terminal in your hand:
li.cil.oc.common.item.Terminal.onItemRightClick

but please be specific, as this doesn't match the title of this bug report you gave

1. what is in your right hand?
2. what is in your left hand?
3. what type of block are you clicking?

4. does this crash happen every single time you right click with these items (as listed in questions 1-3)?
5. are any devices running?
6. was the terminal connected to a server?
7. are there ways to right click where it doesn't crash?

Also, we recently saw a crash like this where the user was running a minecraft cracked version of forge. is this a crack version?

**Comment by fuami** [comment]
Yeah, sorry for the poor description, turns out I initially quite wrong.

Steps to reproduce from the top.

Setup a powered rack with server T1 ( T1 CPU, T1 HDD, T1 Ram, T1 GFX ) and terminal server so that the when you use the remote terminal you can see the server ( even a blank HDD with the Lua BIOS works so that you see the error message. ) I set this up in creative in a few minutes to re-produce.

Then pull the terminal server out into your inventory, and try using the remote terminal again ( crash )

The details you asked for,

1. Remote Terminal
2. Nothing
3. Air
4. Yes, every time.
5. The server in the rack was running, not sure it matters.
6. Yes, but the terminal server was not in the server.
7. Some blocks I clicked on like the screen and they keyboard open their own GUIs, however when the item opens its GUI it crashes.

I legitimately purchased the game from Mojang and do not use a cracked version.

**Comment by payonel** [comment]
ok thank you, you've improved the report which will help me repro and fix. if you think of any other details that pinpoint the repro (as in, cases where it doesn't crash) those are also good details to provide

**Comment by StoneLegion** [comment]
Just has the same crash or similar from my client side to playing on the server.
https://paste.dimdev.org/kudoyewudu.mccrash

Pretty much I was using the remote and I removed the terminal server and booted up the rack then click on the remote terminal and bang had that error on the client side. Server seems fine and no Errors.

**Comment by payonel** [comment]
couldn't repro :( but added some null checks on that crash line
