### ISSUE TITLE
[1.7.3] Turn off computers or robots if do not load the chunk

### ISSUE THREAD

**Issue by Romanok2805** [MightyPirates/OpenComputers#2999]
When I leave the robot and come again, it is turned off. I play multiplayer. If you load chunks, the robot does not turn off. I asked this question to the admin server and he looked at the logs. It was written there that when the robot reads data from NBT an error occurs and it goes into the pause state.
This problem appeared after upgrading from 1.7.2 to 1.7.3.
Minecraft version 1.7.10

**Comment by payonel** [comment]
we would need the logs to help, and a repro (REPRO means you reproduce the problem with steps that also work for us, test it yourself and find it reproducible before reporting. run your own server or single player, find the steps necessary, then give repro steps)

**Comment by Romanok2805** [comment]
`[15:07:11] [Server thread/ERROR]: Unexpected error loading a state of computer at (-528.5, 66.5, -1470.5). State: Paused. Unless you're upgrading/downgrading across a major version, please report this! Thank you. 
java.lang.Exception: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:351) ~[NativeLuaArchitecture.class:?]
at li.cil.oc.server.machine.Machine.liftedTree1$1(Machine.scala:727) [Machine.class:?]
at li.cil.oc.server.machine.Machine.load(Machine.scala:726) [Machine.class:?]
at li.cil.oc.common.tileentity.traits.Computer$class.readFromNBTForServer(Computer.scala:158) [Computer$class.class:?]
at li.cil.oc.common.tileentity.RobotProxy.readFromNBTForServer(RobotProxy.scala:151) [RobotProxy.class:?]
at li.cil.oc.common.tileentity.traits.TileEntity$class.readFromNBT(TileEntity.scala:80) [TileEntity$class.class:?]
at li.cil.oc.common.tileentity.RobotProxy.func_145839_a(RobotProxy.scala:25) [RobotProxy.class:?]
at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:134) [aor.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.class:?]
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:1.7.10-1614.58]
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1614.58]
at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-1614.58]
at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-1614.58]
at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-1614.58]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:844) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) ~[LuaState.class:?]
at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:681) ~[LuaState.class:?]
at li.cil.oc.server.machine.luac.PersistenceAPI.unpersist(PersistenceAPI.scala:164) ~[PersistenceAPI.class:?]
at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:356) ~[NativeLuaArchitecture.class:?]
... 18 more`
UPD:
`java.lang.NullPointerException: Ticking block entity 
 at li.cil.oc.common.tileentity.Robot.func_145845_h(Robot.scala:333) 
 at li.cil.oc.common.tileentity.RobotProxy.func_145845_h(RobotProxy.scala:120) 
 at net.minecraft.world.World.func_72939_s(World.java:2583) 
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) 
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) 
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) 
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:844) 
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695) 
 at java.lang.Thread.run(Unknown Source)`

**Comment by payonel** [comment]
good stack trace, but this sort of thing can be tricky to repro. any further info about when it does and very importantly when it does not repro would be quite helpful.
examples of repro help:
1. do other mods active in same chunk affect the repro?
2. does this happen with all robots?
3. does this happen with moving robots?
4. does this happen with robots that are touching oc blocks, or other mod blocks
5. seriously anything else you can learn about this issue

**Comment by Romanok2805** [comment]
1) Do not affect
2) Yes, and also with ordinary computers, servers, microcontrollers and drones.
3) Not moving, always standing still
4) Regardless of other mods
5) If you even make a robot out of new components, they will still be turned off when the chunk is unloaded. Just turn off and ordinary computers.
Mods on server:
AdvancedSolarPanel 3.5.1
AppliedenErgistics2 rv3-beta
BigReactors 0.4.3A
BiblioCraft 1.11.5
Buildcraft 7 7.1.23
ChristmasCraft 1.0
Carpenter's Blocks 3.3.7
Chisel 2 2.5.1.44
CompactSolars 4.4.39.315
Currency
ClientFixer 1.0
DamageIndicators 3.2.0
Dynmap
ExtraUtilities 1.2.12
Forestry 4.2.2.50
GraviSuite-moded-by-Artmoneyse 2.0.3
GrowthCraft 2.7.2
HVMC_christmas_Gift 1.0
HVMC_IronChestAddon 1.0
IC2 Backpack HUD 3.0
IC2 Combo Armors 1.14.5.06
IC2 NuclearControl 2 2.4.2
IC2 Simple Quarry
IndustrialCraft2 Experimental 2.2.825
Immersive Engineering 0.7.7
Inventory Tweaks 1.58-147
Iron Chests-modded-by-Artmoneyse
MrCrayfish's Furniture 3.4.8
MineTweaker3 3.0.9C
NotEnoughItems 1.0.5.118
OpenComputers 1.7.3.1258
OpenSecurity 1.0-91
Optifine HDU C1
QuarryPlus 2.1.0
PowerUtils 1.0.4
Railcraft 9.12.2.0
Reis Minimap
ShadersModCore 2.3.28
StevesCarts 2 2.0.0.b18
TreeCapitator 2.0.4
Waila 1.5.10
WeCUI
there was also such a bug on another server with a different mod build
Advanced Solar Panel 3.5.1
BiblioCraft 1.11.5
Baubles 1.0.1.10
BetterFonts 1.0
Buildcraft 7 7.1.23
ChristmasCraft 1.0
ClientFixer 1.0
Currency 1.0
DamageIndicators 3.2.0
ElectroMagicTools 1.2.6.2
Dynmap 1.0
GraviSuite (moded by Artmoneyse) 2.0.3
HVMC_christmas_Gift by Artmoneyse 1.0
HVMC_IronChestAddon by Artmoneyse 1.0
IC2 Backpack HUD 3.0
IC2 Combo Armors 1.14.5.06
IC2NuclearControl 2 2.4.2
IndustrialCraft2 Experimental 2.2.825
Inventory Tweaks 1.58-147
Iron Chests (moded by Artmoneyse) 1.0
MineTweaker3 3.0.9C
NotEnoughItems 1.0.5.118
OpenComputers 1.7.3.1258
Optifine HDU C1
PowerUtils 1.0.4
Reis Minimap 1.0
ShadersModCore 2.3.28
SoundFilters 0.8
Thaumcraft 4.2.3.5
ThaumicTinkerer 2.5-527
TreeCapitator 2.0.4
Twilightforest 2.3.7
Waila 1.5.10
WeCUI 1.0
