### ISSUE TITLE
Validate NBT to prevent crashes from wrong values.

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#30]
Modifying the NBT of various blocks has the potential to crash the server due to things like a 4th tier or a 0th tier block. Validating and wrapping back into bounds or resetting would fix an error of this type

An example crash log is given below

```
2013-12-27 22:48:23 [INFO] [STDERR] net.minecraft.util.ReportedException: Exception in world tick
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1946)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.main.Main.main(SourceFile:101)
2013-12-27 22:48:23 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-12-27 22:48:23 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-12-27 22:48:23 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-12-27 22:48:23 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2013-12-27 22:48:23 [INFO] [STDERR] Caused by: scala.MatchError: 3 (of class java.lang.Integer)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Case.func_70302_i_(Case.scala:29)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Inventory$class.items(Inventory.scala:14)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Computer.items$lzycompute(Computer.scala:14)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Computer.items(Computer.scala:14)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Inventory$$anonfun$load$1.apply(Inventory.scala:109)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Inventory$$anonfun$load$1.apply(Inventory.scala:107)
2013-12-27 22:48:23 [INFO] [STDERR]     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
2013-12-27 22:48:23 [INFO] [STDERR]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
2013-12-27 22:48:23 [INFO] [STDERR]     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
2013-12-27 22:48:23 [INFO] [STDERR]     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.util.ExtendedNBT$ExtendedNBTTagList.foreach(ExtendedNBT.scala:83)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Inventory$class.load(Inventory.scala:107)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Computer.li$cil$oc$common$tileentity$Rotatable$$super$load(Computer.scala:14)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Rotatable$class.load(Rotatable.scala:166)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Computer.li$cil$oc$common$tileentity$RedstoneAware$$super$load(Computer.scala:14)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.RedstoneAware$class.load(RedstoneAware.scala:76)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Computer.li$cil$oc$common$tileentity$BundledRedstoneAware$$super$load(Computer.scala:14)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.BundledRedstoneAware$class.load(BundledRedstoneAware.scala:86)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Computer.load(Computer.scala:14)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Environment.func_70307_a(Environment.scala:63)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Computer.func_70307_a(Computer.scala:118)
2013-12-27 22:48:23 [INFO] [STDERR]     at li.cil.oc.common.tileentity.Case.func_70307_a(Case.scala:17)
2013-12-27 22:48:23 [INFO] [STDERR]     at com.mcf.davidee.nbtedit.packets.ClientPacketHandler.onPacketData(ClientPacketHandler.java:69)
2013-12-27 22:48:23 [INFO] [STDERR]     at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2013-12-27 22:48:23 [INFO] [STDERR]     at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2013-12-27 22:48:23 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
2013-12-27 22:48:23 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
```

**Comment by fnuecke** [comment]
I'll add some checks.
