### ISSUE TITLE
Cable item incorrectly uses getDamage()

### ISSUE THREAD

**Issue by mightydanp** [MightyPirates/OpenComputers#3004]
i am having a problem with the cables in my script. i have done multiple possible causes for this and i came to the conclusion that it is opencomputers:cable causing this error.
`[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: open_computers.zs}: stack cannot be null
java.lang.IllegalArgumentException: stack cannot be null
	at crafttweaker.mc1120.item.MCItemStack.<init>(MCItemStack.java:67)
	at crafttweaker.mc1120.item.MCItemStack.withAmount(MCItemStack.java:200)
	at Open_computers.__script__(open_computers.zs:79)
	at __ZenMain__.run(Open_computers)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:218)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:101)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_658_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

line 79 and 80 is where the script begins
https://pastebin.com/rr0ttYWh

**Comment by payonel** [comment]
sounds like an issue with craft tweaker to me. open a bug with them. perhaps they'll ask us to add a feature to support their scripts, but that would be a feature request

**Comment by jaredlll08** [comment]
> sounds like an issue with craft tweaker to me.

Considering that this is ONLY reproducible with OpenComputers, ONLY affects open computer items (specifically the cable), maybe recheck that.

Your ItemStack is literally failing an isEmpty check, not sure how I can fix that.

Maybe don't use damage values for colours.
The 1.12 ItemStack#isEmpty() check:
```java
 public boolean isEmpty()
    {
        if (this == EMPTY)
        {
            return true;
        }
        else if (this.getItemRaw() != null && this.getItemRaw() != Items.AIR)
        {
            if (this.stackSize <= 0)
            {
                return true;
            }
            else
            {
                return this.itemDamage < -32768 || this.itemDamage > 65535;
            }
        }
        else
        {
            return true;
        }
    }
```

> https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/block/Item.scala#L62

Your custom ItemBlock returning `11250603` for the damage of the item.

**Comment by payonel** [comment]
i'll take a look

**Comment by bziemons** [comment]
I am going to join in on this one. This was brought to my attention from a crash https://github.com/RS485/LogisticsPipes/issues/1453

Because `ItemStack.isEmpty` returns true for the cable ItemStack, all kinds of weird things are happening.

I debugged it down to the `getItemDamage` from one of the cable stacks as well:
![Screenshot from 2020-06-16 18-19-48](https://user-images.githubusercontent.com/1096713/84800477-2b3a0c80-affe-11ea-9afb-845d6d7d48d7.png)

**Comment by payonel** [comment]
i'm aware of the root issue, thanks for confirming it too
damage is really metadata on the itemstsack, and sadly we used that for color data. these large "damage" values you see are rgb codes for the cables
and sadly, minecraft uses damage >= 32k or something in the isEmpty check
the fix will have to move the color metadata to something else, like nbt

**Comment by asiekierka** [comment]
It is not actually *stored* in the item stack. It's stored in NBT, as it should be. The `getDamage` call is overriden solely to pass the render color to the rendering logic, which is fairly easy to fix.
