### ISSUE TITLE
Exception when placing relay block

### ISSUE THREAD

**Issue by jcarrete5** [MightyPirates/OpenComputers#3017]
MC Version: 1.12.2
Forge Version: 14.23.5.2768
OC Version: 1.7.3.146

Here is the situation: I have a small network setup with two computers. Both computers have a network card (and all other necessary components required to boot) and are connected via a relay. Everything works perfectly fine. I am able to send messages from one computer to the other with no problems.

When I unload the chunk with this setup, the relay starts to behave strangely. I come back to the chunk with the setup and when I boot up one of the computers, I get this message in the server console:
```
[20:11:15] [Server thread/WARN] [opencomputers]: A component of type 'relay' disappeared (cd59da5d-fd8f-40b6-a52b-abf773904670)! This usually means that it didn't save its node.
```
the small network no longer works after this and when I replace the relay down, I get this message in the server console:
```
[20:11:47] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Null string not allowed
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException: Null string not allowed
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_191]
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19) ~[gm.class:?]
        at li.cil.oc.util.ExtendedNBT$.toNbt(ExtendedNBT.scala:37) ~[ExtendedNBT$.class:?]
        at li.cil.oc.util.ExtendedNBT$$anonfun$stringIterableToNbt$1.apply(ExtendedNBT.scala:183) ~[ExtendedNBT$$anonfun$stringIterableToNbt$1.class:?]
        at li.cil.oc.util.ExtendedNBT$$anonfun$stringIterableToNbt$1.apply(ExtendedNBT.scala:183) ~[ExtendedNBT$$anonfun$stringIterableToNbt$1.class:?]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[TraversableLike$$anonfun$map$1.class:?]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[TraversableLike$$anonfun$map$1.class:?]
        at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74) ~[ArraySeq.class:?]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[TraversableLike$class.class:?]
        at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[AbstractTraversable.class:?]
        at li.cil.oc.util.ExtendedNBT$.stringIterableToNbt(ExtendedNBT.scala:183) ~[ExtendedNBT$.class:?]
        at li.cil.oc.integration.waila.BlockDataProvider$.getNBTData(BlockDataProvider.scala:84) ~[BlockDataProvider$.class:?]
        at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```
Despite this error, replacing the relay seems to fix the network and I am able to send/receive messages again, however, this is very annoying as I have to replace the relay every time I load/unload the chunk.

Picture of setup (Ignore the fact that there is no power going to the relay in the picture. there was power going to it when I was testing):
![2019-01-03_20 13 45](https://user-images.githubusercontent.com/6133706/50669781-3d082b00-0f95-11e9-9b10-1b24853b2d35.png)

 It also might be worth mentioning that I have the same issue from #2890

**Comment by payonel** [comment]
closed in dev builds (>= oc for 1.12 version 1.7.3.147)
