### ISSUE TITLE
Remote Terminal causes GuiHandler null pointer.

### ISSUE THREAD

**Issue by sulljason** [MightyPirates/OpenComputers#3033]
Using version 1.12.2-1.7.3.146 from Curse Forge the remote terminal tries to fetch the servers environment but gets null and falls over. Pretty sure I was just out of range. Removing terminal server from rack and using the remote also causes the same crash.

Raw paste: https://paste.feed-the-beast.com/view/raw/af5b8d31

java.lang.NullPointerException: Unexpected error
	at li.cil.oc.client.GuiHandler$.getClientGuiElement(GuiHandler.scala:122)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at li.cil.oc.common.item.Terminal.onItemRightClick(Terminal.scala:59)
	at li.cil.oc.common.item.Delegator.func_77659_a(Delegator.scala:149)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)

**Comment by JomerDev** [comment]
I have exactly the same problem. Being out of range and having no bound terminal both cause the client to crash

**Comment by payonel** [comment]
closed in dev builds (>= oc for 1.12 version 1.7.3.147)
