### ISSUE TITLE
[1.12.2] java.lang.IllegalStateException: TickNextTick list out of synch

### ISSUE THREAD

**Issue by thakyZ** [MightyPirates/OpenComputers#3069]
I get periodic crashes that seem to have no clear cause, so I am not sure what is happening. I am also contacting the creators of the other core mods.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  AstralCore (astralsorcery-1.12.2-1.10.11.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  SoundUnpack (OpenSecurity-MC1.12.2-1.0-22.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 3/21/19 8:46 PM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:691)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:691)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
	Level name: world
	All players: 3 total; [EntityPlayerMP['cat2002'/1421, l='world', x=934.60, y=126.00, z=-2146.04], EntityPlayerMP['Scay'/170707, l='world', x=658.87, y=64.50, z=-1276.71], EntityPlayerMP['thakyZ'/225321, l='world', x=942.16, y=126.00, z=-2154.30]]
	Chunk stats: ServerChunkCache: 1162 Drop: 0
	Level seed: -3094403056888522971
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (192,64,256), Chunk: (at 0,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4132394 game time, 4260562 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 26771 (now: false), thunder time: 6151 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-142-generic
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 981967528 bytes (936 MB) / 4525129728 bytes (4315 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8192M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 124 mods loaded, 124 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                            | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2814-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2814      | forge-1.12.2-14.23.5.2814-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | opencomputers|core                | 1.7.4.153         | minecraft.jar                                     | None                                     |
	| LCHIJA | infinitylib                       | 1.12.2-1.12.0     | infinitylib-1.12.0.jar                            | None                                     |
	| LCHIJA | agricraft                         | 2.12.0-1.12.0-a6  | AgriCraft-2.12.0-1.12.0-a6.jar                    | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare                    | 1.12.2-2.7.0.574  | ancientwarfare-1.12.2-2.7.0.574.jar               | None                                     |
	| LCHIJA | ancientwarfarestructure           | @VERSION@         | ancientwarfare-1.12.2-2.7.0.574.jar               | None                                     |
	| LCHIJA | ancientwarfarevehicle             | 1.12.2-2.7.0.574  | ancientwarfare-1.12.2-2.7.0.574.jar               | None                                     |
	| LCHIJA | ancientwarfarenpc                 | 1.12.2-2.7.0.574  | ancientwarfare-1.12.2-2.7.0.574.jar               | None                                     |
	| LCHIJA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | ancientwarfareautomation          | 1.12.2-2.7.0.574  | ancientwarfare-1.12.2-2.7.0.574.jar               | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | astralsorcery                     | 1.10.11           | astralsorcery-1.12.2-1.10.11.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | autoreglib                        | 1.3-26            | AutoRegLib-1.3-26.jar                             | None                                     |
	| LCHIJA | backpack                          | 3.0.2             | backpack-3.0.2-1.12.2.jar                         | None                                     |
	| LCHIJA | patchouli                         | 1.0-18            | Patchouli-1.0-18.jar                              | None                                     |
	| LCHIJA | llibrary                          | 1.7.18            | llibrary-1.7.18-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | bewitchment                       | @VERSION@         | Bewitchment-1.12.2-0.0.19.42-indev.jar            | None                                     |
	| LCHIJA | bibliocraft                       | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCHIJA | jei                               | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LCHIJA | forestry                          | 5.8.2.387         | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
	| LCHIJA | binniecore                        | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| LCHIJA | binniedesign                      | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| LCHIJA | genetics                          | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| LCHIJA | botany                            | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| LCHIJA | extrabees                         | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| LCHIJA | extratrees                        | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2425        | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar     | None                                     |
	| LCHIJA | guideapi                          | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                       | None                                     |
	| LCHIJA | bloodmagic                        | 1.12.2-2.4.0-102  | BloodMagic-1.12.2-2.4.0-102.jar                   | None                                     |
	| LCHIJA | thaumcraft                        | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| LCHIJA | botania                           | r1.10-360         | Botania+r1.10-360.jar                             | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCHIJA | chiselsandbits                    | 14.31             | chiselsandbits-14.31.jar                          | None                                     |
	| LCHIJA | cofhcore                          | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar            | None                                     |
	| LCHIJA | cofhworld                         | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | compactmachines3                  | 3.0.15            | compactmachines3-1.12.2-3.0.15-b249.jar           | None                                     |
	| LCHIJA | asielib                           | 1.0.0             | Computronics-1.12.1-1.6.5.jar                     | None                                     |
	| LCHIJA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | opencomputers                     | 1.7.4.153         | OpenComputers-MC1.12.2-1.7.4.153.jar              | None                                     |
	| LCHIJA | mcmultipart                       | 2.5.3             | MCMultiPart-2.5.3.jar                             | None                                     |
	| LCHIJA | mekanism                          | 1.12.2-9.6.6.358  | Mekanism-1.12.2-9.6.6.358.jar                     | None                                     |
	| LCHIJA | computronics                      | 1.6.5             | Computronics-1.12.1-1.6.5.jar                     | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.42     | Mantle-1.12-1.3.3.42.jar                          | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.45     | EnderCore-1.12.2-0.5.45.jar                       | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                  | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                  | None                                     |
	| LCHIJA | conarm                            | 1.2.3             | conarm-1.12.2-1.2.3.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cucumber                          | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
	| LCHIJA | dimdoors                          | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                    | None                                     |
	| LCHIJA | dynamictrees                      | 1.12.2-0.9.4      | DynamicTrees-1.12.2-0.9.4.jar                     | None                                     |
	| LCHIJA | dynamictreesbop                   | 1.12.2-1.4.1e     | DynamicTreesBOP-1.12.2-1.4.1e.jar                 | None                                     |
	| LCHIJA | harvestcraft                      | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zb.jar                   | None                                     |
	| LCHIJA | dynamictreesphc                   | 1.12.2-1.4.2      | DynamicTreesPHC-1.12.2-1.4.2.jar                  | None                                     |
	| LCHIJA | dynamictreestc                    | 1.12.2-1.4.1e     | DynamicTreesTC-1.12.2-1.4.1e.jar                  | None                                     |
	| LCHIJA | ebwizardry                        | 4.1.4             | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar    | None                                     |
	| LCHIJA | embers                            | 1.12              | EmbersRekindled-1.12.jar                          | None                                     |
	| LCHIJA | enderiobase                       | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderioconduits                   | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiomachines                   | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | enderiopowertools                 | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                         | None                                     |
	| LCHIJA | zerocore                          | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                       | None                                     |
	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.65   | ExtremeReactors-1.12.2-0.4.5.65.jar               | None                                     |
	| LCHIJA | forgelin                          | 1.8.2             | Forgelin-1.8.2.jar                                | None                                     |
	| LCHIJA | forgemultipartcbe                 | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe                     | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCHIJA | minecraftmultipartcbe             | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCHIJA | fossil                            | 8.0.0             | fossilsarcheology-8.0.0.jar                       | None                                     |
	| LCHIJA | gardenofglass                     | sqrt(-1)          | GardenOfGlass.jar                                 | None                                     |
	| LCHIJA | hammercore                        | 2.0.4.2           | HammerCore-1.12.2-2.0.4.2.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | justenoughreactors                | 1.1.3.61          | JustEnoughReactors-1.12.2-1.1.3.61.jar            | 2238d4a92d81ab407741a2fdb741cebddfeacba6 |
	| LCHIJA | librarianlib                      | 4.15              | librarianlib-1.12.2-4.15.jar                      | None                                     |
	| LCHIJA | mekanismgenerators                | 1.12.2-9.6.6.358  | MekanismGenerators-1.12.2-9.6.6.358.jar           | None                                     |
	| LCHIJA | mekanismtools                     | 1.12.2-9.6.6.358  | MekanismTools-1.12.2-9.6.6.358.jar                | None                                     |
	| LCHIJA | mrtjpcore                         | 2.1.3.35          | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
	| LCHIJA | mysticalagriculture               | 1.7.3             | MysticalAgriculture-1.12.2-1.7.3.jar              | None                                     |
	| LCHIJA | nei                               | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ocdevices                         | snapshot_20190228 | ocdevices-snapshot_20190228.jar                   | None                                     |
	| LCHIJA | openglasses                       | 2.0.6             | OpenGlasses-MC1.12.2-2.0.6.jar                    | None                                     |
	| LCHIJA | opensecurity                      | 1.0-22            | OpenSecurity-MC1.12.2-1.0-22.jar                  | None                                     |
	| LCHIJA | projectred-core                   | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-Base.jar               | None                                     |
	| LCHIJA | psi                               | r1.1-72           | Psi-r1.1-72.jar                                   | None                                     |
	| LCHIJA | plustic                           | 7.0.5.2           | plustic-7.0.5.2.jar                               | None                                     |
	| LCHIJA | projectred-compat                 | 1.0               | ProjectRed-1.12.2-4.9.1.92-compat.jar             | None                                     |
	| LCHIJA | projectred-integration            | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCHIJA | projectred-transmission           | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCHIJA | projectred-fabrication            | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-fabrication.jar        | None                                     |
	| LCHIJA | projectred-illumination           | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-lighting.jar           | None                                     |
	| LCHIJA | projectred-expansion              | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| LCHIJA | projectred-relocation             | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| LCHIJA | projectred-transportation         | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| LCHIJA | satako                            | 2.23              | Satako+1.12-2.23.jar                              | None                                     |
	| LCHIJA | sereneseasons                     | 1.2.15            | SereneSeasons-1.12.2-1.2.15-universal.jar         | None                                     |
	| LCHIJA | thaumic_calculator                | 0.4               | Thaumic+Calculations-1.12.2-0.4.jar               | None                                     |
	| LCHIJA | thaumadditions                    | 12r               | ThaumicAdditions-1.12.2-12r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | thaumcomp                         | 0.4.4             | ThaumicComputers-MC1.12.2-0.4.4.jar               | None                                     |
	| LCHIJA | thaumicenergistics                | 2.2.1             | thaumicenergistics-2.2.1.jar                      | None                                     |
	| LCHIJA | thaumicperiphery                  | 0.3.0             | thaumicperiphery-0.3.0.jar                        | None                                     |
	| LCHIJA | thermalcultivation                | 0.3.2             | ThermalCultivation-1.12.2-0.3.2.11-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics                   | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalinnovation                 | 0.3.2             | ThermalInnovation-1.12.2-0.3.2.11-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thutcore                          | 5.19.9            | thutcore-1.12.2-5.19.9.jar                        | None                                     |
	| LCHIJA | thutcore_compat                   | 1.0               | thutcore-1.12.2-5.19.9.jar                        | None                                     |
	| LCHIJA | thuttech                          | 6.1.5             | thuttech-1.12.2-6.1.5.jar                         | None                                     |
	| LCHIJA | totemic                           | 1.12.2-0.11.5     | Totemic-1.12.2-0.11.5.jar                         | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| LCHIJA | treegrowingsimulator              | 0.0.4             | TreeGrowingSimulator2017-1.0.1.jar                | None                                     |
	| LCHIJA | wizardry                          | 0.9.9             | wizardry-0.9.9.jar                                | None                                     |
	| LCHIJA | worldedit                         | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | orelib                            | 3.5.2.2           | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | immersiveengineering              | 0.12-89           | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | librarianliblate                  | 4.15              | librarianlib-1.12.2-4.15.jar                      | None                                     |
	| LCHIJA | ocsensors                         | 1.0.4             | ocsensors-1.0.4-b23.jar                           | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.11.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
Wizardry Plugin (wizardry-0.9.9.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
SoundUnpack (OpenSecurity-MC1.12.2-1.0-22.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 3420 names; 7984 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Thaumic Additions: Reconstructed (thaumadditions) @12r

	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 3 / 20; [EntityPlayerMP['cat2002'/1421, l='world', x=934.60, y=126.00, z=-2146.04], EntityPlayerMP['Scay'/170707, l='world', x=658.87, y=64.50, z=-1276.71], EntityPlayerMP['thakyZ'/225321, l='world', x=942.16, y=126.00, z=-2154.30]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by payonel** [comment]
well, do you have any oc devices in the world? can you repro after removing OC? with a repro, and no stack ... this ticket will close for lack of data. i understand you don't have that data at this time, but i also do not have enough to go from to resolve this

**Comment by thakyZ** [comment]
Yes, I have open computer devices I will attempt to do this.

**Comment by malte0811** [comment]
This is a vanilla bug (or bad documentation of the standard library), see https://github.com/SleepyTrousers/EnderCore/issues/105#issuecomment-475957390.

**Comment by payonel** [comment]
nice find with endercore, i'm happy to close based on that finding
