### ISSUE TITLE
Smart Moving + Open Computers Clientside crash

### ISSUE THREAD

**Issue by Hague** [MightyPirates/OpenComputers#307]
I get an odd crash when I load OpenComputers (both latest and older) when I load it with the Smart Moving mod installed.

```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 6/8/14 3:46 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 72
    at net.smart.moving.SmartMovingContext.initialize(SmartMovingContext.java:77)
    at net.smart.moving.SmartMovingMod.init(SmartMovingMod.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.smart.moving.SmartMovingContext.initialize(SmartMovingContext.java:77)
    at net.smart.moving.SmartMovingMod.init(SmartMovingMod.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1329156760 bytes (1267 MB) / 2337275904 bytes (2229 MB) up to 2628255744 bytes (2506 MB)
    JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048M -Xmx2560M -XX:SurvivorRatio=15 -XX:TargetSurvivorRatio=90 -XX:MaxGCPauseMillis=500 -XX:+UseAdaptiveGCBoundary -XX:PermSize=256m -XX:MaxPermSize=512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.209.1112 Minecraft Forge 10.12.1.1112 69 mods loaded, 69 mods active
    mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.209.1112} [Forge Mod Loader] (forge-1.7.2-10.12.1.1112.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1112} [Minecraft Forge] (forge-1.7.2-10.12.1.1112.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.0} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gasesCore{1.4.4.1} [Glenn's Gases Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gasesFrameworkCore{1.0.3} [Gases Framework Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.1} [Not Enough Items] (NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PlayerAPI{1.4} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RenderPlayerAPI{1.2} [Render Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SmartCore{1.0} [Smart Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    battlegear2{1.0.5.4} [Mine & Blade Battlegear 2 - Bullseye] (1.7.2-MB_Battlegear2-Bullseye-1.0.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Trapcraft{v2.2.1a} [Trapcraft] ([1.7.2] Trapcraft - v2.2.1a.zip) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{3.1.2} [Damage Indicators] ([1.7.2]DamageIndicatorsMod-3.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.1.477-experimental} [IndustrialCraft 2] (industrialcraft-2-2.1.477-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedMachines{1.0.8} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.7.0} [BiblioCraft] (BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.0.16} [BuildCraft] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.0.16} [BC Builders] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.0.16} [BC Energy] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.0.16} [BC Factory] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.0.16} [BC Transport] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.0.16} [BC Silicon] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BWG4{1.2.0g} [Better World Generation 4] (BWG4-1.2.0g.jar) Unloaded->Constructed->Pre-initialized->Initialized
    customnpcs{1.7.2-2} [CustomNpcs] (CustomNPCs_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    flansmod{4.3.0} [Flan's Mod] (Flans Mod-1.7.2-4.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.282} [Forge Multipart] (ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FMPIntegration{1.0} [FMPIntegration] (fmpintegration-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    guilib{1.0.7.0} [GUI Library] (Forge_GuiLibv1.0.7.0.zip) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.282} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FortuneOres{1.7} [FortuneOres] (FortuneOres-MC1.7-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gasesFramework{1.0.3} [Gases Framework] (gasesFramework-1.0.3-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gases{1.4.4.1} [Glenn's Gases] (gases-1.4.4.1-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IH8LIQDS{1.01} [I Hate Liquids] (i_hate_liquids-1.7.2(1).jar) Unloaded->Constructed->Pre-initialized->Initialized
    IguanaTweaks{1.7.2-Beta-10} [Iguana Tweaks] (IguanaTweaks-1.7.2-Beta-10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.5.2_1.7.2} [Waila] (Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.3} [Jabba] (Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TeNNoX_KeyAndCodeLock{1.4} [KeyAndCodeLock] (KeyAndCodeLock-1.7.2-1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LotsOfFood{1.7.2} [Lots of Food] (Lots of Food-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    lycanitesmobs{1.5.2b - MC 1.7.2} [Lycanites Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    arcticmobs{1.5.2b - MC 1.7.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    demonmobs{1.5.2b - MC 1.7.2} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    desertmobs{1.5.2b - MC 1.7.2} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    forestmobs{1.5.2b - MC 1.7.2} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    infernomobs{1.5.2b - MC 1.7.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    junglemobs{1.5.2b - MC 1.7.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    mountainmobs{1.5.2b - MC 1.7.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    plainsmobs{1.5.2b - MC 1.7.2} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    saltwatermobs{1.5.2b - MC 1.7.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    swampmobs{1.5.2b - MC 1.7.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.5.2b [1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    radixcore{1.1.1} [RadixCore] (RadixCore-1.1.1 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mca{4.0.3} [Minecraft Comes Alive] (MCA-4.0.3 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mediccraft{1.0.1 - 1.7.2} [MedicCraft] (MedicCraft-1.0.1 - 1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MoreEnchants{1.3.0} [MoreEnchants] (MoreEnchants-MC1.7-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cfm{3.2.9.2} [§6MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.2.9.2-beta-build2(1.7.2).jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (OpenComputers-MC1.7.2-1.3.0.161-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers{1.3.0.161} [OpenComputers] (OpenComputers-MC1.7.2-1.3.0.161-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bonecraft{1.7.2b} [Pam's BoneCraft] (Pam's BoneCraft 1.7.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.2c} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.2c.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.0.0.0} [Railcraft] (Railcraft_1.7.2-9.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RopesPlus{1.6.1} [Ropes+] (RopePlus-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    secretroomsmod{@VERSION@} [The SecretRoomsMod] (secretroomsmod-1.7.2-4.6.3.345.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SimpleEnderPouch{1.1} [SimpleEnderPouch] (SimpleEnderPouch-MC1.7-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SmartMoving{15.0} [Smart Moving] (SmartMoving-1.7.2-15.0.jar) Unloaded->Constructed->Pre-initialized->Errored
    SmartRender{2.0} [Smart Render] (SmartRender-1.7.2-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    UndergroundBiomes{0.5} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.5h.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.18.4} [Witchery] (witchery-1.7.2-0.18.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MSC2{1.2.1} [Mob Spawn Controls 2] (Forge_MSC2v1.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.282} [Forge Microblocks] (ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    zzzzzcustomconfigs{1.3.0} [ZZZZZ Custom Configs] (ZZZZZCustomConfigs v1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Launched Version: 1.7.2-Forge10.12.1.1112-mcpatcher
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [Dead-End-RP.zip]
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: Off (1)
```

I wouldn't normally say this was related but the game loads otherwise without OpenComputers installed. I've forwarded this to Divisor of Smart Moving too.

**Comment by evg-zhabotinsky** [comment]
I tried googling for sources of that mod but found a lot of various crash reports instead. That is, Smart moving is quite unstable as I understand.
Also, minecraft crashes in their code so their sources are needed to debug the issue.

**Comment by LizzyTrickster** [comment]
From what i can see there is no mention of OC except in the mod list. Are you sure its OC that is causing it? What happens if you removed OC and try to start it?

**Comment by fnuecke** [comment]
As evg-zhabotinsky said, since OC doesn't even pop up in the stacktrace I don't think it's something for me to fix, but for the Smart Moving devs instead. If anything it might be that something is registered at the wrong time. Closed until proven wrong.

**Comment by LizzyTrickster** [comment]
@fnuecke that was me who said about it not showing up, not @evg-zhabotinsky :P

**Comment by fnuecke** [comment]
Typical reading comprehension fail :P Sorry about that.

**Comment by LizzyTrickster** [comment]
No problem :package:

**Comment by ghost** [comment]
I'd like to re-open this, as I have thoroughly tested it with all 1.7.2 versions of OpenComputers.
Same error on start. No problems if smart moving is removed, but if both Smart Moving and Open Computers  (1.2 or 1.3) are installed at the same time, I get this error.

**Comment by fnuecke** [comment]
@TriBlade9 did you bring this up with the Smart Moving devs? If so, what did they say? Any insights on what might be causing this?

**Comment by ghost** [comment]
I cannot find a location to bring this to the attention of the SmartMoving devs, other than on the minecraft forum topic, where it has been brought up twice and ignored. This post has the most information: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274224-smart-moving?comment=7754

**Comment by fnuecke** [comment]
All right, I sent Divisor a PM on the forums.

**Comment by ghost** [comment]
Good news! This seems has been fixed in the latest release of SmartMoving, I have tested both at the same time and it appears to work at least partially.

I have not noticed any issues, but haven't tested everything either.
