### ISSUE TITLE
SidedComponent with optiFine cause crash

### ISSUE THREAD

**Issue by antzhi** [MightyPirates/OpenComputers#3093]
In my code, run with optiFine mod:
`public class AmuletStoneTE extends TileEntity implements ITickable, ISidedInventory, SimpleComponent, SidedComponent {...}` cause crash

but
`public class AmuletStoneTE extends TileEntity implements ITickable, ISidedInventory, SimpleComponent {...}` is fine

build.gradle:
`    dependencies {
        compile "li.cil.oc:OpenComputers:MC1.12.2-1.7.+:api"
        deobfCompile "mcp.mobius.waila:Hwyla:1.8.26-B41_1.12.2:api"
    }
`

**Comment by antzhi** [comment]
`...
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: antzak.amulet_stone.AmuletStoneTE
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.NoClassDefFoundError: li/cil/oc/api/network/SidedComponent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more
Caused by: java.lang.ClassNotFoundException: li.cil.oc.api.network.SidedComponent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 50 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 52 more
`

**Comment by antzhi** [comment]
`...
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: antzak.amulet_stone.AmuletStoneTE
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.NoClassDefFoundError: li/cil/oc/api/network/SidedComponent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more
Caused by: java.lang.ClassNotFoundException: li.cil.oc.api.network.SidedComponent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 50 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 52 more
`

**Comment by payonel** [comment]
try running with the module provided, or build from source. this looks like an issue with your environment and not our code
