### ISSUE TITLE
Just doing what the console told me to do. [Report]

### ISSUE THREAD

**Issue by manaphoenix** [MightyPirates/OpenComputers#3165]
```java
[21:25:03] [Server thread/ERROR] [opencomputers]: Unexpected error loading a state of computer at (-73.5, 13.5, -43.5). State: Paused. Unless you're upgrading/downgrading across a major version, please report this! Thank you.
java.lang.Exception: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:351) ~[NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.Machine.liftedTree1$1(Machine.scala:746) [Machine.class:?]
	at li.cil.oc.server.machine.Machine.load(Machine.scala:745) [Machine.class:?]
	at li.cil.oc.common.tileentity.traits.Computer$class.readFromNBTForServer(Computer.scala:152) [Computer$class.class:?]
	at li.cil.oc.common.tileentity.RobotProxy.li$cil$oc$common$tileentity$traits$RotatableTile$$super$readFromNBTForServer(RobotProxy.scala:34) [RobotProxy.class:?]
	at li.cil.oc.common.tileentity.traits.RotatableTile$class.readFromNBTForServer(RotatableTile.scala:38) [RotatableTile$class.class:?]
	at li.cil.oc.common.tileentity.RobotProxy.readFromNBTForServer(RobotProxy.scala:178) [RobotProxy.class:?]
	at li.cil.oc.common.tileentity.traits.TileEntity$class.readFromNBT(TileEntity.scala:90) [TileEntity$class.class:?]
	at li.cil.oc.common.tileentity.RobotProxy.readFromNBT(RobotProxy.scala:34) [RobotProxy.class:?]
	at net.minecraft.tileentity.TileEntity.create(TileEntity.java:120) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
	at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) ~[LuaState.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:681) ~[LuaState.class:?]
	at li.cil.oc.server.machine.luac.PersistenceAPI.unpersist(PersistenceAPI.scala:164) ~[PersistenceAPI.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:356) ~[NativeLuaArchitecture.class:?]
	... 17 more
```

**Other Useful Info:**
OC Version (OpenComputers-MC1.12.2-1.7.4.153)
Forge Version (forge-1.12.2-14.23.5.2847-universal)

**Possibly Unrelated:**
This error occured after a user logged into the server. The server had just restarted after a "force-crash" from the server saying a tick took longer than 60 seconds.

Reason for Edit: I can english I sware! V.V

**Comment by payonel** [comment]
machine persistence is saved to nbt, and if that save is interrupted, the machine state is interrupted. given that you had a forced crash/stop, and this machine failure, it is not unexpected. sorry, no fix
