### ISSUE TITLE
Exploding/breaking the computer case block while code is executing crashes the game

### ISSUE THREAD

**Issue by m00nwtchr** [MightyPirates/OpenComputers#3175]
This is the error
```
java.lang.IllegalArgumentException: Cannot set property PropertyBool{name=running, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:221)
	at li.cil.oc.common.tileentity.Case.onRunningChanged(Case.scala:82)
	at li.cil.oc.common.tileentity.traits.Computer$class.updateEntity(Computer.scala:111)
	at li.cil.oc.common.tileentity.Case.updateEntity(Case.scala:74)
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
	at li.cil.oc.common.tileentity.Case.update(Case.scala:28)
	at net.minecraft.world.World.updateEntities(World.java:2007)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:643)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by payonel** [comment]
mc version, oc version
repro steps (you said you break it, but i've done this thousands of times)
how often does this happen
sp or mp
does it happen again
etc...anything helpful is...helpful :)

**Comment by payonel** [comment]
anyways, i can see how this could fail, i'll make the code safer here. thanks for reporting
