### ISSUE TITLE
SMP Computer boot crash

### ISSUE THREAD

**Issue by lordtet** [MightyPirates/OpenComputers#3180]
Hello, hope i'm in the right place! I couldn't find any mention of this happening (besides some sound based suggestions). I made my own little modpack to play with some friends, and on building my first tier-1 computer, it crashes my game when i try to power it on using the eeprom. Strangely, this crash only occurs in multiplayer, as replicating a similar (same computer, different power source) setup works in my singleplayer world. The server log wouldn't claim anything was wrong during the crash besides the usual player crash network exception.

Below is the crash snipped of the client log, if you need anything else just ask :)
[crashlog_snip.txt](https://github.com/MightyPirates/OpenComputers/files/3884275/crashlog_snip.txt)

**Comment by payonel** [comment]
Minecraft Version: 1.7.10
OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1443)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:270)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2013)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

OC is not in the stack, and we dont have reports of this (some older issues from mc 1.8, but this was resolved)

I do not have enough information to resolve this. You'll need to isolate the issue more for us.
Some ideas to pinpoint the issue
1. smp, creative new flat world. look at ground in front of you and run `./oc_sp` to spawn our test creative machine, start it. does it also crash your client? same stack?
2. does this repro with oc alone? is there a mod that has to be there to cause this?
3. does this repro with our previous release?
