### ISSUE TITLE
crash with IC2

### ISSUE THREAD

**Issue by 0uti** [MightyPirates/OpenComputers#319]
after placing IC2 tin cable to robot assembler the server crashed and won't start again
Crashlog:

```
[18:52:48] [Server thread/WARN] [OpenComputers]: Error in scheduled tick action.
net.minecraft.util.ReportedException: Exception while updating neighbours
        at net.minecraft.world.World.func_147460_e(World.java:707) ~[afn.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:137) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:57) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:27) ~[EventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_40_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:?]
        at li.cil.oc.common.EventHandler$$anonfun$scheduleIC2Add$1.apply$mcV$sp(EventHandler.scala:40) ~[EventHandler$$anonfun$scheduleIC2Add$1.class:?]
        at li.cil.oc.common.EventHandler$$anonfun$onTick$1.apply(EventHandler.scala:60) [EventHandler$$anonfun$onTick$1.class:?]
        at li.cil.oc.common.EventHandler$$anonfun$onTick$1.apply(EventHandler.scala:59) [EventHandler$$anonfun$onTick$1.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [IndexedSeqOptimized$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108) [ArrayOps$ofRef.class:?]
        at li.cil.oc.common.EventHandler$.onTick(EventHandler.scala:59) [EventHandler$.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_310_EventHandler$_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) [ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:520) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669) [kx.class:?]
Caused by: java.lang.AbstractMethodError: li.cil.oc.common.tileentity.RobotAssembler.canConnect(Lnet/minecraftforge/common/util/ForgeDirection;)Z
        at li.cil.oc.common.tileentity.traits.power.IndustrialCraft2$class.acceptsEnergyFrom(IndustrialCraft2.scala:36) ~[IndustrialCraft2$class.class:?]
        at li.cil.oc.common.tileentity.RobotAssembler.acceptsEnergyFrom(RobotAssembler.scala:17) ~[RobotAssembler.class:?]
        at ic2.core.block.wiring.TileEntityCable.onNeighborBlockChange(TileEntityCable.java:202) ~[TileEntityCable.class:?]
        at ic2.core.block.wiring.BlockCable.func_149695_a(BlockCable.java:385) ~[BlockCable.class:?]
        at net.minecraft.world.World.func_147460_e(World.java:674) ~[afn.class:?]
        ... 19 more
[18:52:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AbstractMethodError: li.cil.oc.common.tileentity.RobotAssembler.canConnect(Lnet/minecraftforge/common/util/ForgeDirection;)Z
        at li.cil.oc.common.tileentity.traits.power.IndustrialCraft2$class.acceptsEnergyFrom(IndustrialCraft2.scala:36) ~[IndustrialCraft2$class.class:?]
        at li.cil.oc.common.tileentity.RobotAssembler.acceptsEnergyFrom(RobotAssembler.scala:17) ~[RobotAssembler.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileToGrids(EnergyNetLocal.java:373) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:141) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:57) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:27) ~[EventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_40_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:?]
        at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:166) ~[TileEntityCable.class:?]
        at ic2.core.block.TileEntityBlock$1.tickCallback(TileEntityBlock.java:53) ~[TileEntityBlock$1.class:?]
        at ic2.core.TickHandler.processTickCallbacks(TickHandler.java:137) ~[TickHandler.class:?]
        at ic2.core.TickHandler.onWorldTick(TickHandler.java:32) ~[TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_23_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:604) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:326) ~[lj.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669) [kx.class:?]
```

Using forge 10.12.1.1112
OC 1.3.0.172
IC2-Exp 2.1.478

happens only in multiplayer

**Comment by fnuecke** [comment]
Should also be fixed by ab355a2.
