### ISSUE TITLE
opencomputers crash

### ISSUE THREAD

**Issue by JonathanFraser** [MightyPirates/OpenComputers#350]
I was throwing a bunch of resonant ender florbs around (nowhere near any computer) and the follow crash occured:

`2014-06-22 16:30:48 [INFO] [STDOUT] ---- Minecraft Crash Report ----
2014-06-22 16:30:48 [INFO] [STDOUT] // You should try our sister game, Minceraft!
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] Time: 22/06/14 4:30 PM
2014-06-22 16:30:48 [INFO] [STDOUT] Description: Ticking tile entity
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] java.lang.NullPointerException
2014-06-22 16:30:48 [INFO] [STDOUT]     at java.io.DataOutputStream.writeUTF(DataOutputStream.java:347)
2014-06-22 16:30:48 [INFO] [STDOUT]     at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.server.PacketSender$.sendTextBufferColorChange(PacketSender.scala:236)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.component.TextBuffer$ServerProxy.onScreenColorChange(TextBuffer.scala:536)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.component.TextBuffer.setForegroundColor(TextBuffer.scala:222)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.tileentity.Screen$$anonfun$updateEntity$2.apply(Screen.scala:204)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.tileentity.Screen$$anonfun$updateEntity$2.apply(Screen.scala:187)
2014-06-22 16:30:48 [INFO] [STDOUT]     at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:60)
2014-06-22 16:30:48 [INFO] [STDOUT]     at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.tileentity.Screen.func_70316_g(Screen.scala:187)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.world.World.func_72939_s(World.java:2209)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] A detailed walkthrough of the error, its code path and all known details is as follows:
2014-06-22 16:30:48 [INFO] [STDOUT] ---------------------------------------------------------------------------------------
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] -- Head --
2014-06-22 16:30:48 [INFO] [STDOUT] Stacktrace:
2014-06-22 16:30:48 [INFO] [STDOUT]     at java.io.DataOutputStream.writeUTF(DataOutputStream.java:347)
2014-06-22 16:30:48 [INFO] [STDOUT]     at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.server.PacketSender$.sendTextBufferColorChange(PacketSender.scala:236)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.component.TextBuffer$ServerProxy.onScreenColorChange(TextBuffer.scala:536)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.component.TextBuffer.setForegroundColor(TextBuffer.scala:222)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.tileentity.Screen$$anonfun$updateEntity$2.apply(Screen.scala:204)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.tileentity.Screen$$anonfun$updateEntity$2.apply(Screen.scala:187)
2014-06-22 16:30:48 [INFO] [STDOUT]     at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:60)
2014-06-22 16:30:48 [INFO] [STDOUT]     at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
2014-06-22 16:30:48 [INFO] [STDOUT]     at li.cil.oc.common.tileentity.Screen.func_70316_g(Screen.scala:187)
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] -- Tile entity being ticked --
2014-06-22 16:30:48 [INFO] [STDOUT] Details:
2014-06-22 16:30:48 [INFO] [STDOUT]     Name: oc:screen // li.cil.oc.common.tileentity.Screen
2014-06-22 16:30:48 [INFO] [STDOUT]     Block type: ID #3651 (tile.null // li.cil.oc.common.block.SimpleRedstoneDelegator)
2014-06-22 16:30:48 [INFO] [STDOUT]     Block data value: 7 / 0x7 / 0b0111
2014-06-22 16:30:48 [INFO] [STDOUT]     Block location: World: (-631,68,-714), Chunk: (at 9,4,6 in -40,-45; contains blocks -640,0,-720 to -625,255,-705), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
2014-06-22 16:30:48 [INFO] [STDOUT]     Actual block type: ID #3651 (tile.null // li.cil.oc.common.block.SimpleRedstoneDelegator)
2014-06-22 16:30:48 [INFO] [STDOUT]     Actual block data value: 7 / 0x7 / 0b0111
2014-06-22 16:30:48 [INFO] [STDOUT] Stacktrace:
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.world.World.func_72939_s(World.java:2209)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] -- Affected level --
2014-06-22 16:30:48 [INFO] [STDOUT] Details:
2014-06-22 16:30:48 [INFO] [STDOUT]     Level name: New World
2014-06-22 16:30:48 [INFO] [STDOUT]     All players: 1 total; [EntityPlayerMP['binaryblade'/201, l='New World', x=-803.77, y=82.99, z=-796.97]]
2014-06-22 16:30:48 [INFO] [STDOUT]     Chunk stats: ServerChunkCache: 1171 Drop: 0
2014-06-22 16:30:48 [INFO] [STDOUT]     Level seed: 3563052032707975543
2014-06-22 16:30:48 [INFO] [STDOUT]     Level generator: ID 00 - default, ver 1. Features enabled: true
2014-06-22 16:30:48 [INFO] [STDOUT]     Level generator options: 
2014-06-22 16:30:48 [INFO] [STDOUT]     Level spawn location: World: (12,64,252), Chunk: (at 12,4,12 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
2014-06-22 16:30:48 [INFO] [STDOUT]     Level time: 446005 game time, 509894 day time
2014-06-22 16:30:48 [INFO] [STDOUT]     Level dimension: 0
2014-06-22 16:30:48 [INFO] [STDOUT]     Level storage version: 0x04ABD - Anvil
2014-06-22 16:30:48 [INFO] [STDOUT]     Level weather: Rain time: 108024 (now: false), thunder time: 114697 (now: false)
2014-06-22 16:30:48 [INFO] [STDOUT]     Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
2014-06-22 16:30:48 [INFO] [STDOUT] Stacktrace:
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-06-22 16:30:48 [INFO] [STDOUT]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-06-22 16:30:48 [INFO] [STDOUT] 
2014-06-22 16:30:48 [INFO] [STDOUT] -- System Details --
2014-06-22 16:30:48 [INFO] [STDOUT] Details:
2014-06-22 16:30:48 [INFO] [STDOUT]     Minecraft Version: 1.6.4
2014-06-22 16:30:48 [INFO] [STDOUT]     Operating System: Linux (amd64) version 3.12.21-gentoo-r1
2014-06-22 16:30:48 [INFO] [STDOUT]     Java Version: 1.7.0_55, Oracle Corporation
2014-06-22 16:30:48 [INFO] [STDOUT]     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
2014-06-22 16:30:48 [INFO] [STDOUT]     Memory: 368811480 bytes (351 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
2014-06-22 16:30:48 [INFO] [STDOUT]     JVM Flags: 5 total; -Xms1G -Xmx1G -XX:PermSize=128M -XX:+UseG1GC -XX:+AggressiveOpts
2014-06-22 16:30:48 [INFO] [STDOUT]     AABB Pool Size: 4187 (234472 bytes; 0 MB) allocated, 3911 (219016 bytes; 0 MB) used
2014-06-22 16:30:48 [INFO] [STDOUT]     Suspicious classes: FML and Forge are installed
2014-06-22 16:30:48 [INFO] [STDOUT]     IntCache: cache: 2, tcache: 0, allocated: 2, tallocated: 64
2014-06-22 16:30:48 [INFO] [STDOUT]     FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 MCUpdater: Hawk777’s Industrial (rev 2014062000) 26 mods loaded, 26 mods active
2014-06-22 16:30:48 [INFO] [STDOUT]     mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     FML{6.4.49.965} [Forge Mod Loader] (forge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     Forge{9.11.1.965} [Minecraft Forge] (forge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     BuildCraft|Core{4.2.2} [BuildCraft] (Buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     BuildCraft|Builders{4.2.2} [BC Builders] (Buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     BuildCraft|Energy{4.2.2} [BC Energy] (Buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     BuildCraft|Factory{4.2.2} [BC Factory] (Buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     BuildCraft|Transport{4.2.2} [BC Transport] (Buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     BuildCraft|Silicon{4.2.2} [BC Silicon] (Buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     Forestry{2.3.1.1} [Forestry for Minecraft] (Forestry.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     IronChest{5.4.1.702} [Iron Chest] (IronChest.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     NEIPlugins{1.1.0.6} [NEI Plugins] (NEIPlugins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     ForgeMultipart{1.0.0.219} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     ThermalExpansion{3.0.0.7} [Thermal Expansion] (ThermalExpansion.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     OpenComputers|Core{1.0.0} [OpenComputers (Core)] (OpenComputers.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     OpenComputers{1.3.0.429} [OpenComputers] (OpenComputers.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     Railcraft{8.4.0.0} [Railcraft] (Railcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     McMultipart{1.0.0.219} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     ForgeMicroblock{1.0.0.219} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2014-06-22 16:30:48 [INFO] [STDOUT]     Profiler Position: N/A (disabled)
2014-06-22 16:30:48 [INFO] [STDOUT]     Vec3 Pool Size: 1944 (108864 bytes; 0 MB) allocated, 1585 (88760 bytes; 0 MB) used
2014-06-22 16:30:48 [INFO] [STDOUT]     Player Count: 1 / 8; [EntityPlayerMP['binaryblade'/201, l='New World', x=-803.77, y=82.99, z=-796.97]]
2014-06-22 16:30:48 [INFO] [STDOUT]     Type: Integrated Server (map_client.txt)
2014-06-22 16:30:48 [INFO] [STDOUT]     Is Modded: Definitely; Client brand changed to 'fml,forge'
2014-06-22 16:30:48 [INFO] [STDOUT] #@!@# Game crashed! Crash report saved to: #@!@# /home/binaryblade/.MCUpdater/instances/hawk777-industrial/crash-reports/crash-2014-06-22_16.30.48-server.txt
2014-06-22 16:30:48 [INFO] [Minecraft-Server] Stopping server
2014-06-22 16:30:48 [INFO] [Minecraft-Server] Saving players
2014-06-22 16:30:48 [INFO] [Minecraft-Server] Saving worlds
AL lib: (EE) alc_cleanup: 1 device not closed`

**Comment by fnuecke** [comment]
Hmm, weird one. I'll look into it.
