### ISSUE TITLE
[MC1.12.2] Crash I click right on the rack

### ISSUE THREAD

**Issue by OptimusZeGaming** [MightyPirates/OpenComputers#3576]
When I right click on the block rack, it crashes. 

Version : OC 1.7.7

`Time: 11/14/22 2:48 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at li.cil.oc.client.gui.Rack$$anonfun$drawScreen$1$$anonfun$apply$mcVI$sp$1$$anonfun$apply$mcVI$sp$2.apply$mcVI$sp(Rack.scala:126)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.client.gui.Rack$$anonfun$drawScreen$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(Rack.scala:125)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.client.gui.Rack$$anonfun$drawScreen$1.apply$mcVI$sp(Rack.scala:123)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.client.gui.Rack.drawScreen(Rack.scala:122)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.run(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at li.cil.oc.client.gui.Rack$$anonfun$drawScreen$1$$anonfun$apply$mcVI$sp$1$$anonfun$apply$mcVI$sp$2.apply$mcVI$sp(Rack.scala:126)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.client.gui.Rack$$anonfun$drawScreen$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(Rack.scala:125)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.client.gui.Rack$$anonfun$drawScreen$1.apply$mcVI$sp(Rack.scala:123)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.client.gui.Rack.drawScreen(Rack.scala:122)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: li.cil.oc.client.gui.Rack
	Mouse location: Scaled: (240, 127). Absolute: (960, 508)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player775'/163, l='MpServer', x=-4.15, y=65.00, z=-280.39]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (19,64,-184), Chunk: (at 3,4,8 in 1,-12; contains blocks 16,0,-192 to 31,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 161080 game time, 1203 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 81 total; [EntitySpider['Spider'/9, l='MpServer', x=-48.50, y=17.00, z=-354.50], EntityPig['Pig'/10, l='MpServer', x=-53.37, y=64.00, z=-328.26], EntitySquid['Squid'/11, l='MpServer', x=-52.97, y=57.95, z=-298.06], EntityCreeper['Creeper'/15, l='MpServer', x=-47.92, y=17.00, z=-357.43], EntityCreeper['Creeper'/17, l='MpServer', x=-46.50, y=17.00, z=-356.19], EntityPig['Pig'/18, l='MpServer', x=-32.70, y=64.00, z=-348.27], EntityPig['Pig'/19, l='MpServer', x=-44.54, y=64.00, z=-319.21], EntitySquid['Squid'/20, l='MpServer', x=-35.12, y=59.00, z=-265.20], EntityBat['Bat'/21, l='MpServer', x=-28.42, y=41.01, z=-207.50], EntityCow['Cow'/26, l='MpServer', x=-17.86, y=67.00, z=-331.86], EntityCreeper['Creeper'/27, l='MpServer', x=-24.77, y=29.00, z=-296.50], EntityCreeper['Creeper'/28, l='MpServer', x=-17.50, y=32.00, z=-293.50], EntityCreeper['Creeper'/29, l='MpServer', x=-20.21, y=33.00, z=-298.53], EntitySkeleton['Skeleton'/30, l='MpServer', x=-12.52, y=25.00, z=-282.29], EntityZombie['Zombie'/31, l='MpServer', x=-25.50, y=26.00, z=-286.50], EntityZombie['Zombie'/32, l='MpServer', x=-26.50, y=26.00, z=-285.50], EntityZombie['Zombie'/33, l='MpServer', x=-16.50, y=17.00, z=-278.50], EntityBat['Bat'/34, l='MpServer', x=-21.25, y=25.10, z=-282.25], EntitySquid['Squid'/35, l='MpServer', x=-35.60, y=58.00, z=-266.40], EntitySquid['Squid'/36, l='MpServer', x=-22.10, y=61.17, z=-243.81], EntityCreeper['Creeper'/37, l='MpServer', x=-17.50, y=29.00, z=-230.50], EntityZombieVillager['Zombie Villager'/38, l='MpServer', x=-30.73, y=27.00, z=-225.54], EntityBat['Bat'/39, l='MpServer', x=-24.03, y=39.00, z=-201.25], EntityBat['Bat'/40, l='MpServer', x=-26.25, y=22.10, z=-207.75], EntitySkeleton['Skeleton'/42, l='MpServer', x=-30.77, y=41.00, z=-201.48], EntityCreeper['Creeper'/46, l='MpServer', x=-0.50, y=31.00, z=-319.78], EntityCreeper['Creeper'/47, l='MpServer', x=-2.45, y=30.00, z=-310.80], EntityCreeper['Creeper'/48, l='MpServer', x=-11.50, y=33.00, z=-304.50], EntityBat['Bat'/49, l='MpServer', x=-12.22, y=22.68, z=-262.46], EntityPlayerSP['Player775'/163, l='MpServer', x=-4.15, y=65.00, z=-280.39], EntitySquid['Squid'/50, l='MpServer', x=-19.46, y=62.52, z=-265.98], EntityCreeper['Creeper'/51, l='MpServer', x=-4.22, y=19.00, z=-235.44], EntityCow['Cow'/52, l='MpServer', x=-14.64, y=70.00, z=-220.32], EntityCreeper['Creeper'/53, l='MpServer', x=-10.50, y=19.00, z=-217.50], EntitySkeleton['Skeleton'/54, l='MpServer', x=-15.50, y=17.00, z=-205.50], EntityZombie['Zombie'/66, l='MpServer', x=3.50, y=21.00, z=-336.50], EntityZombie['Zombie'/67, l='MpServer', x=1.45, y=21.00, z=-335.77], EntityCow['Cow'/68, l='MpServer', x=9.82, y=65.00, z=-327.49], EntitySkeleton['Skeleton'/69, l='MpServer', x=-4.23, y=20.00, z=-236.52], EntityCow['Cow'/74, l='MpServer', x=24.25, y=69.00, z=-361.18], EntityCow['Cow'/75, l='MpServer', x=19.22, y=67.00, z=-337.50], EntityCow['Cow'/76, l='MpServer', x=18.50, y=67.00, z=-334.22], EntitySkeleton['Skeleton'/77, l='MpServer', x=23.49, y=13.00, z=-310.24], EntityZombie['Zombie'/78, l='MpServer', x=25.50, y=31.00, z=-308.50], EntityBat['Bat'/81, l='MpServer', x=37.12, y=15.12, z=-351.81], EntityCow['Cow'/82, l='MpServer', x=39.81, y=68.00, z=-356.48], EntityCow['Cow'/84, l='MpServer', x=41.13, y=68.00, z=-348.20], EntityCow['Cow'/85, l='MpServer', x=45.50, y=68.00, z=-356.80], EntityCow['Cow'/86, l='MpServer', x=46.84, y=66.00, z=-338.46], EntityCow['Cow'/87, l='MpServer', x=43.89, y=67.00, z=-347.55], EntityCow['Cow'/88, l='MpServer', x=34.59, y=67.00, z=-332.85], EntityCow['Cow'/89, l='MpServer', x=47.17, y=67.00, z=-322.31], EntityCow['Cow'/90, l='MpServer', x=29.81, y=70.00, z=-312.54], EntityCow['Cow'/91, l='MpServer', x=40.48, y=69.00, z=-310.20], EntityBat['Bat'/92, l='MpServer', x=42.67, y=17.00, z=-287.25], EntityBat['Bat'/93, l='MpServer', x=41.76, y=15.02, z=-289.89], EntitySkeleton['Skeleton'/94, l='MpServer', x=48.50, y=18.00, z=-218.27], EntitySkeleton['Skeleton'/95, l='MpServer', x=38.47, y=16.00, z=-209.76], EntityCreeper['Creeper'/96, l='MpServer', x=45.21, y=17.00, z=-211.51], EntitySkeleton['Skeleton'/97, l='MpServer', x=47.47, y=17.00, z=-213.28], EntityBat['Bat'/98, l='MpServer', x=38.85, y=18.17, z=-213.41], EntityBat['Bat'/99, l='MpServer', x=35.61, y=16.61, z=-213.68], EntityCow['Cow'/100, l='MpServer', x=44.66, y=63.00, z=-221.45], EntityCow['Cow'/101, l='MpServer', x=45.80, y=66.00, z=-210.50], EntityEnderman['Enderman'/104, l='MpServer', x=52.44, y=16.00, z=-284.48], EntityBat['Bat'/105, l='MpServer', x=51.00, y=16.42, z=-286.37], EntitySkeleton['Skeleton'/106, l='MpServer', x=50.73, y=18.00, z=-219.50], EntitySkeleton['Skeleton'/107, l='MpServer', x=56.72, y=15.00, z=-217.92], EntitySkeleton['Skeleton'/108, l='MpServer', x=49.46, y=17.00, z=-218.22], EntitySkeleton['Skeleton'/109, l='MpServer', x=55.50, y=16.00, z=-218.50], EntitySkeleton['Skeleton'/110, l='MpServer', x=56.50, y=16.00, z=-220.50], EntityBat['Bat'/111, l='MpServer', x=61.46, y=16.05, z=-221.43], EntityCreeper['Creeper'/112, l='MpServer', x=60.30, y=28.00, z=-206.30], EntityZombie['Zombie'/114, l='MpServer', x=60.92, y=28.00, z=-206.64], EntityZombie['Zombie'/120, l='MpServer', x=73.48, y=25.00, z=-356.20], EntityBat['Bat'/121, l='MpServer', x=75.25, y=32.99, z=-338.48], EntityZombie['Zombie'/122, l='MpServer', x=73.50, y=34.00, z=-255.50], EntityZombie['Zombie'/124, l='MpServer', x=72.50, y=20.00, z=-227.50], EntityZombie['Zombie'/125, l='MpServer', x=72.79, y=20.00, z=-228.50], EntityZombie['Zombie'/126, l='MpServer', x=72.50, y=31.00, z=-238.50], EntityZombie['Zombie'/127, l='MpServer', x=66.29, y=26.00, z=-203.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:420)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.run(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)
`

**Comment by asiekierka** [comment]
Was there no earlier crash? This NPE should not occur unless `initGui()` failed...

**Comment by OptimusZeGaming** [comment]
No, this is not the case.

However, what's weird is that when I run it on my Minecraft Launcher it works fine, but when I run my test client on Intellij Idea it crashes, yet I don't touch the Rack.

**Comment by OptimusZeGaming** [comment]
I have just tried again with version 1.8.3 and in addition to the previous error, there is also this one:

[14:38:57] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.guiLeft from class li.cil.oc.client.gui.Rack$$anonfun$initGui$1$$anonfun$apply$mcVI$sp$3
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_221]
	at net.minecraft.util.Util.runTask(Util.java:51) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:398) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at net.minecraftforge.legacydev.Main.start(Main.java:86) [legacydev-0.2.3.1-fatjar.jar:0.2.3.1+4+372be23]
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29) [legacydev-0.2.3.1-fatjar.jar:0.2.3.1+4+372be23]
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.guiLeft from class li.cil.oc.client.gui.Rack$$anonfun$initGui$1$$anonfun$apply$mcVI$sp$3
	at li.cil.oc.client.gui.Rack$$anonfun$initGui$1$$anonfun$apply$mcVI$sp$3.apply$mcVI$sp(Rack.scala:150) ~[Rack$$anonfun$initGui$1$$anonfun$apply$mcVI$sp$3.class:?]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) ~[Range.class:?]
	at li.cil.oc.client.gui.Rack$$anonfun$initGui$1.apply$mcVI$sp(Rack.scala:145) ~[Rack$$anonfun$initGui$1.class:?]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) ~[Range.class:?]
	at li.cil.oc.client.gui.Rack.initGui(Rack.scala:144) ~[Rack.class:?]
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:478) ~[GuiScreen.class:?]
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1018) ~[Minecraft.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501) ~[FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322) ~[FMLCommonHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[EntityPlayer.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_221]
	at net.minecraft.util.Util.runTask(Util.java:50) ~[Util.class:?]
	... 15 more
