### ISSUE TITLE
ArrayIndexOutOfBoundsException when using servers with 3 network cards

### ISSUE THREAD

**Issue by IgorTimofeev** [MightyPirates/OpenComputers#3635]
Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2855
OpenComputers version: OpenComputers-MC1.12.2-1.8.0+9833087.jar

Steps to reproduce:

1. Insert 3 network cards into server
![image](https://github.com/MightyPirates/OpenComputers/assets/11760002/f4a7ca82-0df3-4d28-a6d1-a1ac9eaf83f1)
3. Connect last network node
4. Disconnect it
5. See logs:
```log
[15:02:06] [Server thread/WARN]: Received a badly formatted packet.
java.lang.ArrayIndexOutOfBoundsException: 3
	at li.cil.oc.common.tileentity.Rack.connect(Rack.scala:69) ~[Rack.class:?]
	at li.cil.oc.server.PacketHandler$.onRackMountableMapping(PacketHandler.scala:251) ~[PacketHandler$.class:?]
	at li.cil.oc.server.PacketHandler$.dispatch(PacketHandler.scala:50) ~[PacketHandler$.class:?]
	at li.cil.oc.common.PacketHandler.li$cil$oc$common$PacketHandler$$process(PacketHandler.scala:55) [PacketHandler.class:?]
	at li.cil.oc.common.PacketHandler$$anon$1.run(PacketHandler.scala:40) [PacketHandler$$anon$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Found it accidentally when implementing servers in Ocelot emulator. The reason is in missing substraction:

```scala
li.cil.oc.common.tileentity.Rack

...

if (connectableIndex == 0) {
  val node = mountable.node
  val plug = sidedNode(toGlobal(oldSide.get))
  if (node != null && plug != null) {
    node.disconnect(plug)
  }
}
else {
  // Here, connectableIndex is always in range [1; 3], but snifferNodes array length is 3
  snifferNodes(slot)(connectableIndex).remove()
}
```

**Comment by asiekierka** [comment]
Could you please test the proposed fix?

**Comment by asiekierka** [comment]
Build should be available here in a few minutes: https://github.com/MightyPirates/OpenComputers/actions/runs/5401692819

**Comment by IgorTimofeev** [comment]
Yep, seems like it fixed & working, thanks!
