### ISSUE TITLE
[MC1.12.2] The Simple Component interface produces an error when creating a new device

### ISSUE THREAD

**Issue by OptimusZeGaming** [MightyPirates/OpenComputers#3637]
Hello, I tried to create a new peripheral block following the instructions in the API https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/README.md 
but it gives me the error below.

I'm using the latest version 1.12.2 : 1.8.3

java.lang.AssertionError: Couldn't find 'validate' in template implementation.
	at li.cil.oc.common.asm.ClassTransformer.replace$1(ClassTransformer.scala:337) ~[OpenComputers-MC1.12.2-1.8.3+274990f.jar:?]
	at li.cil.oc.common.asm.ClassTransformer.injectEnvironmentImplementation(ClassTransformer.scala:340) ~[OpenComputers-MC1.12.2-1.8.3+274990f.jar:?]
	at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:139) [OpenComputers-MC1.12.2-1.8.3+274990f.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_221]

**Comment by brisingraerowing** [comment]
There are some additional Java arguments you need to pass in a development environment to get class transformers working. I don't know what they are for OC, though.
