### ISSUE TITLE
Game Crashes when Right-click on a Robot

### ISSUE THREAD

**Issue by Klsnjns** [MightyPirates/OpenComputers#3677]
I Right-clicked on a Robot with a Analyzer and the Game Just Stopped the Internal Server and Closed, this is the Exception from the mod Thrown with Log Level Fatal:      

[19:54:03] [Client thread/FATAL]:
 Unreported exception thrown!
net.minecraft.util.ChatComponentTranslationFormatException: Error parsing: TranslatableComponent{key='|0 0 0|
there is no suitable tool in the manipulator
energy level: 99%', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}: Unsupported format: '%'
	at net.minecraft.util.ChatComponentTranslation.func_150269_b(SourceFile:91) ~[fr.class:?]
	at net.minecraft.util.ChatComponentTranslation.func_150270_g(SourceFile:48) ~[fr.class:?]
	at net.minecraft.util.ChatComponentTranslation.iterator(SourceFile:147) ~[fr.class:?]
	at net.minecraft.util.ChatComponentStyle$1.apply(SourceFile:87) ~[ff.class:?]
	at net.minecraft.util.ChatComponentStyle$1.apply(SourceFile:84) ~[ff.class:?]
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794) ~[guava-17.0.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-17.0.jar:?]
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543) ~[guava-17.0.jar:?]
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43) ~[guava-17.0.jar:?]
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542) ~[guava-17.0.jar:?]
	at com.google.common.collect.Iterators.addAll(Iterators.java:356) ~[guava-17.0.jar:?]
	at com.google.common.collect.Lists.newArrayList(Lists.java:147) ~[guava-17.0.jar:?]
	at com.google.common.collect.Lists.newArrayList(Lists.java:129) ~[guava-17.0.jar:?]
	at net.minecraft.client.gui.GuiNewChat.func_146237_a(GuiNewChat.java:168) ~[bcc.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146234_a(GuiNewChat.java:148) ~[bcc.class:?]
	at net.minecraft.client.gui.GuiNewChat.func_146227_a(GuiNewChat.java:143) ~[bcc.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:696) ~[bjb.class:?]
	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:38) ~[gj.class:?]
	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:9) ~[gj.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]

**Comment by foxp552** [comment]
As i knew that's about translation 😳
How and what, nobody knows...
(Suspicious_mojang_works)

**Comment by PublicVoidUpdate** [comment]
is it language specific?

**Comment by ff66theone** [comment]
No it is the **percent sign** (%). In programming languages such as Java and C, when text is printed on screen, a format is applied, so to print a number, i need to write "%d", and for a string, it'll be "%s". In that precise crash, there is no letter (I don't know why) so **the format is %** , that is **invalid.** As I understand, we should **add in some string, another % sign** so the format is %% and prints the % sign
