### ISSUE TITLE
Crash with IC2

### ISSUE THREAD

**Issue by LiEyWe** [MightyPirates/OpenComputers#395]
When it place a computer case while ic2 is installed, i get this crash:

java.lang.AbstractMethodError: li.cil.oc.common.tileentity.Case.getDemandedEnergy()D
    at ic2.core.energy.Grid.prepareCalculation(Grid.java:208) ~[Grid.class:?]
    at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:309) ~[EnergyNetLocal.class:?]
    at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:56) ~[EnergyNetGlobal.class:?]
    at ic2.core.TickHandler.onWorldTick(TickHandler.java:51) ~[TickHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_9_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by fnuecke** [comment]
Version numbers of everything please. Also, full crash log (pastebin/gist/...).

**Comment by LiEyWe** [comment]
crash log: http://pastebin.com/CxdNbguk

the mods i used are:
AsieLib-1.7.10-0.2.6
Computronics-1.7-0.5.1
OpenComputers-MC1.7.10-1.3.0.17-universal
industrialcraft-2-2.2.509-experimental

**Comment by asiekierka** [comment]
It's not my fault this time, I promise!

**Comment by fnuecke** [comment]
Looks like the IC2 API changed, will update.

**Comment by fnuecke** [comment]
[Build 25](http://ci.cil.li/job/OpenComputers-1.3-MC1.7.10/) should fix this (once it's done).

**Comment by b0bst3r** [comment]
Can you not package the ic2 API? Every time it changes you're going to cause world crashes and going to be playing catch up? Or don't you package it?

**Comment by Techokami** [comment]
Two questions I have for @b0bst3r 
1) Does IC2 have a maven repo to get the latest API from?
2) Why the heck is IC2's API in such turmoil, anyway?

**Comment by b0bst3r** [comment]
I don't know all I do know is there are quite a few mods with the exact same issue and it's the single biggest pain in the ass putting together a 1.7.10 modpack.   We've reported loads of API problems not just IC2 either, but then this isn't the place to discuss such matters (sorry fnuecke).

**Comment by Techokami** [comment]
I just looked things up, and there does indeed exist a maven repo with the API, so Sangar doesn't have to package it up: http://forum.industrial-craft.net/index.php?page=Thread&postID=157858

**Comment by Huls** [comment]
1. Ic2 509 is ONLY DEVELOPERS VERSION, NOT OUR USAGE...
2. There is newer version os OC 1.7.10 on jenkins.
3. Change Ic2 to 508 build, don't use devs build

**Comment by asiekierka** [comment]
@Huls - by the time OC 1.3.1 will be out, IC2 might update their API anyway . . .

**Comment by b0bst3r** [comment]
We're using industrialcraft-2-2.2.507-experimental and get the same issue.

**Comment by Huls** [comment]
@asiekierka still tho - it worked for me but i have some issues with robots and theirs "swing" command

**Comment by Huls** [comment]
@b0bst3r I'm using right now Ic 508 and .25 OC and don't have problem with this.

**Comment by b0bst3r** [comment]
Where did u get .25 from everywhere I look at shows .17 as latest available?

**Comment by asiekierka** [comment]
@Huls that is because .25 updated the API to the one you told people not to use
@b0bst3r http://ci.cil.li has _EXPERIMENTAL_ builds

**Comment by Huls** [comment]
@b0bst3r Jenkins: http://ci.cil.li/job/OpenComputers-1.3-MC1.7.10/?auto_refresh=false

@asiekierka Sorry, but i don't see anywhere written that 1.7.10. 25 is experimental build.
Quote:
Last stable build (#25), 5 hr 53 min ago

**Comment by asiekierka** [comment]
@Huls all builds which are not officially released on http://oc.cil.li/ are technically experimental. The only reason IC2_exp only releases on Jenkins is licensing issues due to the disapperance of Alblaka.

**Comment by Huls** [comment]
@asiekierka sorry i'm just not so much oriented in that topic. I'm just startingmy server and i have some issues also trying to help peez
