### ISSUE TITLE
Illegal Extra Prefix in Forge log

### ISSUE THREAD

**Issue by access-ible** [MightyPirates/OpenComputers#402]
Using OpenComputers-MC1.7.10-1.3.0.17-universal.jar

```
[19:50:28] [Server thread/INFO] [OpenComputers/OpenComputers]: Initializing blocks and items.
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:simple, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:791)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:23)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:simple, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:739)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:242)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:23)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:simple_redstone, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:791)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:24)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:simple_redstone, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:739)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:242)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:24)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:special, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:791)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:25)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:special, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:739)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:242)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:25)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:special_redstone, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:791)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:26)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:special_redstone, invalid registry invocation/invalid name?
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:739)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:242)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:26)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:28] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:keyboard, invalid registry invocation/invalid name?
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:791)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.recipe.Recipes$.addNewBlock(Recipes.scala:33)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:77)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)...
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:keyboard, invalid registry invocation/invalid name?
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:739)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:242)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.recipe.Recipes$.addNewBlock(Recipes.scala:33)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Blocks$.init(Blocks.scala:77)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:30)...
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: ****************************************
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: * Illegal extra prefix oc for name oc:item, invalid registry invocation/invalid name?
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:739)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:170)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:158)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.Items$.init(Items.scala:118)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.common.Proxy.preInit(Proxy.scala:31)
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: *  at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)...
[19:50:29] [Server thread/WARN] [FML/OpenComputers]: ****************************************
```

**Comment by fnuecke** [comment]
I'm aware of it, but it's non-critical and there's nothing I can do about it right now without making every OC block and item vanish in existing worlds (or hacking my way into the internals of FML using reflection which would probably end badly). I'm waiting for [this method in FML](https://github.com/MinecraftForge/FML/blob/master/src/main/java/cpw/mods/fml/common/registry/GameRegistry.java#L148-L151) to get implemented and hope it'll do what it sounds like - allowing to rename blocks and items (i.e. their internal name).

I'll leave this open for now, so that people who notice this won't open duplicate issues.

**Comment by Techokami** [comment]
This is an issue my friend @jaquadro had run into with Modular Flower Pots. He did the refactor, then released a tool to convert old worlds to the new prefix.
Here is said tool's source: https://github.com/jaquadro/ForgeMods/tree/master/Tools/ModularpotsIDFix

**Comment by fnuecke** [comment]
Oh, cool, thanks! Browsing the FML sources to see if could maybe contribute an implementation for `addAlias` myself, I stumbled upon a much better way to handle this, though - the intended way: using `FMLMissingMappingsEvent`. Will push the fix after cleaning it up a little.
