### ISSUE TITLE
When I hover over certain items it causes me to crash

### ISSUE THREAD

**Issue by Shadowxd1221** [MightyPirates/OpenComputers#442]
This occurs on items like the server rack. I'll just hover my mouse over it in the menu and it just freezes. It does it on several other items but this is just one I confirmed.

```
--- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/28/14 11:37 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: dan200/computer/api/IMedia
    at li.cil.oc.util.mods.ComputerCraft15$.isDisk(ComputerCraft15.scala:10)
    at li.cil.oc.server.driver.item.CC15Media$.worksWith(CC15Media.scala:27)
    at li.cil.oc.server.driver.Registry$$anonfun$driverFor$1.apply(Registry.scala:62)
    at li.cil.oc.server.driver.Registry$$anonfun$driverFor$1.apply(Registry.scala:62)
    at scala.collection.IndexedSeqOptimized$$anonfun$1.apply(IndexedSeqOptimized.scala:44)
    at scala.collection.IndexedSeqOptimized$$anonfun$1.apply(IndexedSeqOptimized.scala:44)
    at scala.collection.IndexedSeqOptimized$class.segmentLength(IndexedSeqOptimized.scala:189)
    at scala.collection.mutable.ArrayBuffer.segmentLength(ArrayBuffer.scala:47)
    at scala.collection.GenSeqLike$class.prefixLength(GenSeqLike.scala:92)
    at scala.collection.AbstractSeq.prefixLength(Seq.scala:40)
    at scala.collection.IndexedSeqOptimized$class.find(IndexedSeqOptimized.scala:44)
    at scala.collection.mutable.ArrayBuffer.find(ArrayBuffer.scala:47)
    at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:62)
    at li.cil.oc.api.Driver.driverFor(Driver.java:106)
    at li.cil.oc.common.item.Delegate$class.tierFromDriver(Delegate.scala:62)
    at li.cil.oc.common.item.ControlUnit.tierFromDriver(ControlUnit.scala:3)
    at li.cil.oc.common.item.Delegate$class.rarity(Delegate.scala:58)
    at li.cil.oc.common.item.ControlUnit.rarity(ControlUnit.scala:3)
    at li.cil.oc.common.item.Delegator.func_77613_e(Delegator.scala:80)
    at net.minecraft.item.ItemStack.func_77953_t(ItemStack.java:773)
    at net.minecraft.client.gui.inventory.GuiContainer.func_74184_a(GuiContainer.java:232)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_74184_a(GuiContainerCreative.java:778)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:202)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(SourceFile:31)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:683)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1153)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: dan200.computer.api.IMedia
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 35 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at universalelectricity.core.asm.ASMHelper.createClassNode(ASMHelper.java:118)
    at universalelectricity.core.asm.ASMHelper.createClassNode(ASMHelper.java:112)
    at universalelectricity.core.asm.UniversalTransformer.transform(UniversalTransformer.java:39)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:274)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:172)
    ... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at li.cil.oc.util.mods.ComputerCraft15$.isDisk(ComputerCraft15.scala:10)
    at li.cil.oc.server.driver.item.CC15Media$.worksWith(CC15Media.scala:27)
    at li.cil.oc.server.driver.Registry$$anonfun$driverFor$1.apply(Registry.scala:62)
    at li.cil.oc.server.driver.Registry$$anonfun$driverFor$1.apply(Registry.scala:62)
    at scala.collection.IndexedSeqOptimized$$anonfun$1.apply(IndexedSeqOptimized.scala:44)
    at scala.collection.IndexedSeqOptimized$$anonfun$1.apply(IndexedSeqOptimized.scala:44)
    at scala.collection.IndexedSeqOptimized$class.segmentLength(IndexedSeqOptimized.scala:189)
    at scala.collection.mutable.ArrayBuffer.segmentLength(ArrayBuffer.scala:47)
    at scala.collection.GenSeqLike$class.prefixLength(GenSeqLike.scala:92)
    at scala.collection.AbstractSeq.prefixLength(Seq.scala:40)
    at scala.collection.IndexedSeqOptimized$class.find(IndexedSeqOptimized.scala:44)
    at scala.collection.mutable.ArrayBuffer.find(ArrayBuffer.scala:47)
    at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:62)
    at li.cil.oc.api.Driver.driverFor(Driver.java:106)
    at li.cil.oc.common.item.Delegate$class.tierFromDriver(Delegate.scala:62)
    at li.cil.oc.common.item.ControlUnit.tierFromDriver(ControlUnit.scala:3)
    at li.cil.oc.common.item.Delegate$class.rarity(Delegate.scala:58)
    at li.cil.oc.common.item.ControlUnit.rarity(ControlUnit.scala:3)
    at li.cil.oc.common.item.Delegator.func_77613_e(Delegator.scala:80)
    at net.minecraft.item.ItemStack.func_77953_t(ItemStack.java:773)
    at net.minecraft.client.gui.inventory.GuiContainer.func_74184_a(GuiContainer.java:232)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_74184_a(GuiContainerCreative.java:778)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:202)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(SourceFile:31)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:683)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (270, 155). Absolute: (1082, 459)
    Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Ezio_Morte'/8692, l='MpServer', x=-53.32, y=93.78, z=298.15]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-80,64,256), Chunk: (at 0,4,0 in -5,16; contains blocks -80,0,256 to -65,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 3446 game time, 3446 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 97 total; [EntityZombie['Zombie'/8533, l='MpServer', x=-13.69, y=20.00, z=352.31], EntityBat['Bat'/7053, l='MpServer', x=-2.66, y=20.10, z=289.25], EntityZombie['Zombie'/8534, l='MpServer', x=-12.75, y=20.00, z=353.25], EntityClientPlayerMP['Ezio_Morte'/8692, l='MpServer', x=-53.32, y=93.78, z=298.15], EntityZombie['Zombie'/9078, l='MpServer', x=-112.16, y=37.00, z=253.16], EntitySkeleton['Skeleton'/6808, l='MpServer', x=-102.31, y=39.00, z=246.41], EntityBat['Bat'/8159, l='MpServer', x=-83.47, y=23.00, z=364.84], EntityWolf['Wolf'/31, l='MpServer', x=-132.50, y=63.00, z=252.50], EntityWolf['Wolf'/30, l='MpServer', x=-132.50, y=63.00, z=252.50], EntityBat['Bat'/8160, l='MpServer', x=-87.09, y=24.68, z=364.41], EntityBat['Bat'/8161, l='MpServer', x=1.44, y=24.93, z=320.22], EntityWolf['Wolf'/32, l='MpServer', x=-132.50, y=63.00, z=254.50], EntityBat['Bat'/8163, l='MpServer', x=3.31, y=34.43, z=365.28], EntityManaElemental['Mana Elemental'/9249, l='MpServer', x=-101.19, y=40.00, z=242.68], EntityZombie['Zombie'/6838, l='MpServer', x=-9.50, y=26.00, z=311.50], EntitySkeleton['Skeleton'/7078, l='MpServer', x=-99.31, y=40.00, z=241.50], EntityWolf['Wolf'/40, l='MpServer', x=-106.69, y=64.00, z=262.50], EntityCreeper['Creeper'/7929, l='MpServer', x=-115.50, y=22.00, z=360.50], EntityWolf['Wolf'/41, l='MpServer', x=-106.41, y=64.00, z=270.16], EntityWolf['Wolf'/46, l='MpServer', x=-123.38, y=66.00, z=320.34], EntityCreeper['Creeper'/7074, l='MpServer', x=-17.50, y=30.00, z=352.50], EntityWolf['Wolf'/44, l='MpServer', x=-117.50, y=66.00, z=313.50], EntityWolf['Wolf'/45, l='MpServer', x=-119.78, y=66.00, z=313.09], EntityZombie['Zombie'/9024, l='MpServer', x=-130.00, y=27.00, z=249.47], EntityZombie['Zombie'/9025, l='MpServer', x=-129.50, y=26.00, z=248.50], EntityWolf['Wolf'/50, l='MpServer', x=-85.34, y=66.00, z=324.34], EntityWolf['Wolf'/49, l='MpServer', x=-97.06, y=64.00, z=330.50], EntityWolf['Wolf'/48, l='MpServer', x=-82.75, y=64.00, z=327.41], EntityZombie['Zombie'/8305, l='MpServer', x=-121.50, y=21.00, z=366.50], EntityZombie['Zombie'/7584, l='MpServer', x=-6.50, y=33.00, z=349.50], EntityWolf['Wolf'/69, l='MpServer', x=-33.50, y=69.00, z=275.69], EntityWolf['Wolf'/70, l='MpServer', x=-33.50, y=69.00, z=267.88], EntityZombie['Zombie'/7587, l='MpServer', x=-16.50, y=33.00, z=348.50], EntityWolf['Wolf'/71, l='MpServer', x=-34.72, y=69.00, z=268.59], EntityZombie['Zombie'/9023, l='MpServer', x=-121.22, y=25.00, z=248.53], EntityCow['Cow'/76, l='MpServer', x=-41.97, y=68.00, z=276.97], EntityWolf['Wolf'/72, l='MpServer', x=-36.50, y=69.00, z=276.50], EntityCow['Cow'/73, l='MpServer', x=-38.16, y=64.00, z=256.16], EntityCow['Cow'/74, l='MpServer', x=-35.47, y=68.00, z=264.50], EntityCow['Cow'/75, l='MpServer', x=-35.50, y=68.00, z=267.50], EntityWolf['Wolf'/85, l='MpServer', x=-4.50, y=81.00, z=330.50], EntitySkeleton['Skeleton'/8211, l='MpServer', x=13.50, y=17.00, z=305.50], EntitySkeleton['Skeleton'/8210, l='MpServer', x=8.50, y=17.00, z=306.50], EntityWolf['Wolf'/87, l='MpServer', x=-5.50, y=81.00, z=329.50], EntityBat['Bat'/8997, l='MpServer', x=-1.53, y=25.00, z=314.53], EntityWolf['Wolf'/86, l='MpServer', x=-7.50, y=90.00, z=329.50], EntityCreeper['Creeper'/6651, l='MpServer', x=-90.50, y=39.00, z=262.69], EntityCow['Cow'/92, l='MpServer', x=-2.78, y=77.00, z=343.47], EntityCow['Cow'/89, l='MpServer', x=-7.53, y=78.00, z=346.69], EntityWolf['Wolf'/88, l='MpServer', x=-4.50, y=80.00, z=334.50], EntityCow['Cow'/91, l='MpServer', x=0.50, y=78.00, z=341.50], EntityCow['Cow'/90, l='MpServer', x=4.50, y=75.00, z=343.50], EntityChicken['Chicken'/102, l='MpServer', x=26.50, y=82.00, z=285.50], EntityZombie['Zombie'/8102, l='MpServer', x=-17.50, y=24.00, z=326.50], EntityItem['item.item.rottenFlesh'/8109, l='MpServer', x=-82.16, y=64.13, z=280.78], EntityCreeper['Creeper'/6593, l='MpServer', x=-23.50, y=18.00, z=296.50], EntitySkeleton['Skeleton'/8965, l='MpServer', x=-110.50, y=52.00, z=221.50], EntityWaypointContainer['unknown'/115, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.item.ItemResource.5'/8112, l='MpServer', x=-81.53, y=64.13, z=282.47], EntitySkeleton['Skeleton'/7843, l='MpServer', x=12.50, y=32.00, z=232.50], EntityBat['Bat'/7572, l='MpServer', x=-78.25, y=34.10, z=243.75], EntityCreeper['Creeper'/9333, l='MpServer', x=-0.50, y=37.00, z=347.50], EntityZombie['Zombie'/9344, l='MpServer', x=2.50, y=15.00, z=318.50], EntityCreeper['Creeper'/9355, l='MpServer', x=3.50, y=38.00, z=340.50], EntitySkeleton['Skeleton'/6927, l='MpServer', x=-111.09, y=37.00, z=257.38], EntitySkeleton['Skeleton'/9354, l='MpServer', x=3.50, y=38.00, z=334.50], EntitySpider['Spider'/7287, l='MpServer', x=-30.19, y=36.00, z=366.94], EntitySkeleton['Skeleton'/7521, l='MpServer', x=-13.53, y=53.00, z=288.72], EntityBat['Bat'/8385, l='MpServer', x=13.74, y=26.01, z=320.73], EntityBat['Bat'/9187, l='MpServer', x=-128.23, y=29.91, z=246.50], EntityCreeper['Creeper'/7537, l='MpServer', x=-126.50, y=39.00, z=376.50], EntityCreeper['Creeper'/7260, l='MpServer', x=9.50, y=36.00, z=316.50], EntitySkeleton['Skeleton'/8428, l='MpServer', x=16.41, y=25.00, z=270.13], EntityCreeper['Creeper'/7259, l='MpServer', x=5.50, y=36.00, z=318.50], EntityBat['Bat'/8690, l='MpServer', x=-12.00, y=22.20, z=324.28], EntityBat['Bat'/8688, l='MpServer', x=3.25, y=26.10, z=310.75], EntityItem['item.item.arrow'/6964, l='MpServer', x=-11.41, y=31.13, z=345.47], EntityZombie['Zombie'/7516, l='MpServer', x=4.50, y=25.00, z=301.50], EntityZombie['Zombie'/9152, l='MpServer', x=-14.50, y=34.00, z=321.97], EntityCreeper['Creeper'/9154, l='MpServer', x=21.50, y=22.00, z=364.50], EntityZombie['Zombie'/9150, l='MpServer', x=-18.50, y=33.00, z=325.50], EntityZombie['Zombie'/9151, l='MpServer', x=-19.50, y=33.00, z=325.50], EntityZombie['Zombie'/9149, l='MpServer', x=-16.50, y=33.00, z=326.50], EntityEnderman['Enderman'/7699, l='MpServer', x=11.69, y=37.00, z=237.31], EntityCreeper['Creeper'/7209, l='MpServer', x=-129.56, y=26.00, z=247.66], EntitySkeleton['Skeleton'/8337, l='MpServer', x=-22.50, y=53.00, z=288.50], EntityCreeper['Creeper'/8340, l='MpServer', x=22.50, y=34.00, z=262.50], EntitySpider['Spider'/8843, l='MpServer', x=-9.13, y=21.00, z=347.94], EntitySpider['Spider'/8842, l='MpServer', x=-11.19, y=21.00, z=348.22], EntityBrainyZombie['Angry Zombie'/9115, l='MpServer', x=-26.50, y=17.00, z=295.50], EntitySpider['Spider'/8619, l='MpServer', x=22.28, y=11.00, z=311.06], EntityEnderman['Enderman'/8617, l='MpServer', x=23.91, y=11.00, z=311.34], EntityCreeper['Creeper'/7993, l='MpServer', x=-122.22, y=21.00, z=232.94], EntitySkeleton['Skeleton'/7991, l='MpServer', x=-123.50, y=22.00, z=240.50], EntityCreeper['Creeper'/7716, l='MpServer', x=-124.50, y=22.00, z=237.50], EntityCreeper['Creeper'/6767, l='MpServer', x=-89.59, y=42.00, z=239.00], EntityEnderman['Enderman'/8614, l='MpServer', x=18.50, y=11.00, z=313.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 170107232 bytes (162 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 14692 (822752 bytes; 0 MB) allocated, 1238 (69328 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 Optifine OptiFine_1.6.4_HD_U_D1 35 mods loaded, 35 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    battlegear2{1.0.3.5} [Mine & Blade Battlegear 2 - Warcry] (1.6.4-MB_Battlegear2-Warcry-1.0.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    arsmagica2{1.1.2b} [Ars Magica 2] (AM2_1.1.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AnimationAPI{1.1.1} [AnimationAPI] (AnimationAPI v1.1.2 mc1.6.4 copy.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BetterDungeons{2.0} [Chocolate quest] (BetterDungeons2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core{4.1.2} [BuildCraft] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders{4.1.2} [BC Builders] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy{4.1.2} [BC Energy] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory{4.1.2} [BC Factory] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport{4.1.2} [BC Transport] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon{4.1.2} [BC Silicon] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    craftguide{1.5.2} [CraftGuide] (CraftGuide-1.6.7.4 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    UniversalElectricity{3.1.0} [Universal Electricity] (Universal-Electricity-3.1.0.115-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.0.1.268} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.0.1.268} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (OpenComputers-MC1.6.4-1.3.2.525-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [ResonantEngine] (Resonant-Engine-Development-1.2.0.266-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ICBM{1.4.2} [ICBM] (ICBM-1.4.2.386.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ICBM|Sentry{1.4.2} [ICBM Sentry] (ICBM-1.4.2.386.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ICBM|Explosion{1.4.2} [ICBM Explosion] (ICBM-1.4.2.386.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    madscience{1.00.165} [Mad Science] (MadScience-MC1.6.4-F9.11.1.964_v1.00.165-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFFS{3.6.3} [Modular Force Field System] (Modular-Force-Field-System-3.6.3.91-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MutantCreatures{1.4.4} [Mutant Creatures] (Mutant_Creatures_v1.4.4_mc1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenComputers{1.3.2.525} [OpenComputers] (OpenComputers-MC1.6.4-1.3.2.525-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ResonantInduction|Core{0.3.1} [Resonant Induction] (Resonant-Induction-0.3.1.369-Resonant-Induction Core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.1.0g} [Thaumcraft] (Thaumcraft4.1.0g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer{2.0} [Thaumic Tinkerer] (ThaumicTinkerer 2.0-25 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TooMuchTNT{2.6} [TooMuchTNT] (TooMuchTNT v2.6) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TC{4.2.1_012} [Traincraft] (traincraft-4.2.1_011.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TwilightForest{1.20.1} [The Twilight Forest] (twilightforest-1.20.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ted_996_universalcoins{0.1.0} [Universal Coins] (UniversalCoins_1.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ZanMinimap{0.9.4} [Zan's Minimap] (ZansMinimap1.6.4 (2).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.0.1.268} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: Intel(R) HD Graphics 2000 GL version 3.1.0 - Build 9.17.10.3223, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2205 (123480 bytes; 0 MB) allocated, 411 (23016 bytes; 0 MB) used
```

**Comment by fnuecke** [comment]
While it looks like the underlying issue is actually UE's class transformer derping for some reason, I added an additional check which hopefully prevents this. Please try the [latest build](http://ci.cil.li/) once it's done.
