### ISSUE TITLE
robot.use() will crash the game if used with an ender perl equipped.

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#556]
As the title says.

In addition when reloading the world, the robot will be replaced with a different robot with different components. In this case it was named "Wobbo".

Stacktrace:

```
java.lang.NullPointerException
  at net.minecraft.entity.item.EntityEnderPearl.func_70184_a(EntityEnderPearl.java:54)
  at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:191)
  at net.minecraft.world.World.func_72866_a(World.java:2350)
  at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:719)
  at net.minecraft.world.World.func_72870_g(World.java:2311)
  at net.minecraft.world.World.func_72939_s(World.java:2157)
  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
  at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
  at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

**Comment by fnuecke** [comment]
Ugh, this has the same cause as part of #544... will have to dig deeper into adding a fake network handler after all I guess...

**Comment by twothe** [comment]
I like how fast you fix bugs. ^^

**Comment by fnuecke** [comment]
You had good timing with reporting it ;-)

**Comment by rmellema** [comment]
Robots with my nickname :D
