### ISSUE TITLE
IC2 API Crash when IC2 not present - Caused by RedstoneArsenal

### ISSUE THREAD

**Issue by nexx** [MightyPirates/OpenComputers#567]
## Issue

OpenComputers crashes with the following java stacktrace when placing an Computer case, or server rack (I haven't tried other blocks):

```
java.lang.NoClassDefFoundError: ic2/api/energy/event/EnergyTileLoadEvent
    at li.cil.oc.common.EventHandler$.scheduleIC2Add(EventHandler.scala:48)
    at li.cil.oc.common.tileentity.traits.power.IndustrialCraft2Experimental$class.validate(IndustrialCraft2Experimental.scala:20)
    at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$power$IndustrialCraft2Classic$$super$validate(Case.scala:16)
    at li.cil.oc.common.tileentity.traits.power.IndustrialCraft2Classic$class.validate(IndustrialCraft2Classic.scala:21)
    at li.cil.oc.common.tileentity.Case.func_145829_t(Case.scala:16)
    at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:886)
    at net.minecraft.world.World.func_147455_a(World.java:2572)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
    at net.minecraft.world.World.func_147438_o(World.java:2512)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:398)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:259)
    at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:151)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Caused by: java.lang.ClassNotFoundException: ic2.api.energy.event.EnergyTileLoadEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 22 more

Caused by: java.lang.NullPointerException
```
### Installed Mods

```
CoFHCore-[1.7.10]3.0.0B6-32.jar
CoFHLib-[1.7.10]1.0.0B6-26.jar
OpenComponents-MC1.7.10-0.2.0.20-universal.jar
OpenComputers-MC1.7.10-1.3.4.137-dev-universal.jar
RedstoneArsenal-[1.7.10]1.1.0B4-10.jar
ThermalExpansion-[1.7.10]4.0.0B5-13.jar
ThermalFoundation-[1.7.10]1.0.0B3-8.jar
```
### Configuration

My OpenComputers config is the default generated one. I tried adding IC2 to the modBlacklist, but the crash still occurs.
## Diagnosis

Removing Redstone Arsenal stops the crash from occurring. Taking a look into the jar shows partial copy of the IC2 API:

```
RedstoneArsenal-[1.7.10]1.1.0B4-10.jar\ic2\api\tile\IWrenchable.class
RedstoneArsenal-[1.7.10]1.1.0B4-10.jar\ic2\api\tile\package-info.class
```

Removing the IC2 API from the RedstoneArsenal-[1.7.10]1.1.0B4-10.jar, also stops the crash.
## Conclusion

This appears to be the same issue as described in #518. I'm unsure if the solution is a change in OpenComputers, or for Team COFH to remove the IC2 API from the Redstone Arsenal mod.

Hopefully this helps =)

**Comment by fnuecke** [comment]
Thanks for the detailed report! (if only every report was this detailed :P)

The core issue, IMHO, lies with IC2, in that it doesn't specify a separate ID per package, but `IC2API` for each one. So when mods ship it partially the check for the API's presence still succeeds... even though it's not present/complete. I'm not sure how I'm to understand [Player's stance on this](http://bt.industrial-craft.net/view.php?id=1361), but if anything he'll probably only change that in a next major API version change. So I suppose I have work around this by manually checking if the actually needed classes are present... gah.

**Comment by nexx** [comment]
No problem, glad I could help!

As for player's response to that issue, yeah, I'm not sure I follow either. Then again I've only dabbled with Minecraft modding, so it's a little over my head regardless _shrug_

I'll test a new release when I see a commit regarding this and let you know =)

**Comment by fnuecke** [comment]
Please try [build 138](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) when it's done, hopefully it'll be fixed in there.

**Comment by nexx** [comment]
Confirmed as fixed. Thanks for sorting it so quickly!

**Comment by fnuecke** [comment]
Great :)
