### ISSUE TITLE
Serverplay problem about a Tile Entity that I should report

### ISSUE THREAD

**Issue by BakermanLP** [MightyPirates/OpenComputers#600]
Hello there,

I have a little problem, on our server there are a bunch of error messages in the logfile. Could you have a look?

[14:42:56 WARN]: There was a problem writing a TileEntity description packet. Please report this if you see it!
java.lang.NoSuchMethodError: li.cil.oc.common.tileentity.traits.Computer.isRunning()Z
        at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBTForClient(Computer.scala:171) ~[Computer$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$writeToNBTForClient(Case.scala:21) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Colored$class.writeToNBTForClient(Colored.scala:49) ~[Colored$class.class:?]
        at li.cil.oc.common.tileentity.Case.writeToNBTForClient(Case.scala:21) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.TileEntity$class.getDescriptionPacket(TileEntity.scala:80) [TileEntity$class.class:?]
        at li.cil.oc.common.tileentity.Case.func_145844_m(Case.scala:21) [Case.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:699) [mw.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:374) [mw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2648) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2601) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2413) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]

**Comment by fnuecke** [comment]
Thanks! I hope this was using OC1.4? If not I'll have to dig deeper.

**Comment by BakermanLP** [comment]
It was OpenComputers-MC1.7.10-1.4.0.180-dev-universal.jar and that was nearly lightning speed fix! I'll test it in the next few days.

**Comment by Vexatos** [comment]
@BakermanLP You should wait with updating to 1.4 until all the OC addons you use also update, it contains some massive breaking changes in its API. Keep in mind it's not even in beta yet ;)
