### ISSUE TITLE
openComputer crash

### ISSUE THREAD

**Issue by Grindsted** [MightyPirates/OpenComputers#617]
In a new world, I tried to test the redstone IO component. 

local component = require("component")
local sides = require("component")
local rs = component.redstone

rs.setOutput(sides.south, 15)

This seems to work the program was running. 
I forgot to place a piston next to the redstone I/O, so when I placed the piston, minecraft froze a second, then all openComputer parts vanished and then minecraft crashed.

Does any one know whats wrong

**Comment by Wuerfel21** [comment]
aaarrrrrrrrggggghhhh, use pastebin and save our eyes!

**Comment by Kilobyte22** [comment]
This line

``` lua
local sides = require("component")
```

should be replaced with

``` lua
local sides = require("sides")
```

Please also post the crashlog on http://gist.github.com/. This ensures that we can find out what is wrong

**Comment by fnuecke** [comment]
Well, looking at the stacktrace (in the mail Github sent me), this actually looks more like an NEI issue... is this reproducible, and if so, have you tried updating NEI to see if that fixes it?

For the record, the reported stacktrace was:

```
java.lang.NullPointerException: Unexpected error
    at codechicken.nei.DefaultHighlightHandler.handleTextData(DefaultHighlightHandler.java:33)
    at codechicken.nei.api.ItemInfo.getText(ItemInfo.java:494)
    at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:55)
    at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:163)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_98_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:992)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Kilobyte22** [comment]
Ah, didn't see that there was one. Maybe @Chicken-Bones should take a look at this

**Comment by fnuecke** [comment]
[Full log copied from mail is here](https://gist.github.com/fnuecke/362e09f0651981d6be6d).

**Comment by Kilobyte22** [comment]
i hope that my message did inform ChickenBones (i edited that part in later on, so github might not have notified him, we'll see). Other than that you should switch to either the recommented builds or [update to latest version](http://chickenbones.net/Pages/links.html)

**Comment by Grindsted** [comment]
Thanks, fnuecke! Like you said. The problem was NEI.
