### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by evsey9** [MightyPirates/OpenComputers#625]
Please help me with this crash!
Here's the crashlog: 

```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 25.10.14 22:38
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: li/cil/oc/common/block/Cable
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: li/cil/oc/common/block/Cable
    at li.cil.oc.common.Proxy.preInit(Proxy.scala:26)
    at li.cil.oc.client.Proxy.preInit(Proxy.scala:30)
    at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:36)
    at li.cil.oc.OpenComputers.preInit(OpenComputers.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: li.cil.oc.common.block.Cable
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more
Caused by: java.lang.VerifyError: class li.cil.oc.common.block.Cable overrides final method func_149731_a.(Lnet/minecraft/world/World;IIILnet/minecraft/util/Vec3;Lnet/minecraft/util/Vec3;)Lnet/minecraft/util/MovingObjectPosition;
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 42 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 577384464 bytes (550 MB) / 2279137280 bytes (2173 MB) up to 7301496832 bytes (6963 MB)
    Mod Pack: ~~ERROR~~ NullPointerException: null
    LiteLoader Mods: ~~ERROR~~ NullPointerException: null
    LaunchWrapper: 47 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: cofh.asm.TransformerCore
          - Transformer: cofh.asm.PCCASMTransformer
          - Transformer: mods.immibis.microblocks.coremod.MicroblockSupporterTransformer
          - Transformer: mods.immibis.microblocks.crossmod.MicroblocksBCTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: li.cil.oc.common.asm.ClassTransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: net.smart.core.SmartCoreTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: openmods.OpenModsClassTransformer
          - Transformer: openblocks.asm.OpenBlocksClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: com.arisux.airi.AIRIAccessTransformer
          - Transformer: pl.asie.lib.core.AsieLibCoremodTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.PCCAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: shadersmodcore.transform.SMCClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.worldeditwrapper.asm.InteractionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
          - Transformer: mods.immibis.core.impl.MultiInterfaceClassTransformer
          - Transformer: mods.immibis.core.impl.TraitTransformer
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G -XX:PermSize=256m -XX:MaxPermSize=512m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1231 Minecraft Forge 10.13.2.1231 Optifine OptiFine_1.7.10_HD_U_A4 96 mods loaded, 95 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1231} [Forge Mod Loader] (forge-1.7.10-10.13.2.1231.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1231} [Minecraft Forge] (forge-1.7.10-10.13.2.1231.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    ImmibisMicroblocks{59.0.3} [Immibis's Microblocks] (immibis-microblocks-59.0.3.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.64} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.64-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    SmartCore{1.0} [Smart Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    AIRI{3.0.0-1.7.10} [AIRI] ([1.7.10-10.13.0.1158][3.0.0-1.7.10] AIRI.jar) Unloaded->Constructed->Pre-initialized
    AliensVsPredator{3.9.14-1.7.10} [AliensVsPredator] ([1.7.10-10.13.0.1158][3.9.14-1.7.10] AliensVsPredator.jar) Unloaded->Constructed->Pre-initialized
    furnace3d{1.2.0} [Furnace 3D] ([1.7.10] 3D Furnace-1.3a.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.650-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.650-experimental.jar) Unloaded->Constructed->Pre-initialized
    advancedgenetics{1.5.7} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized
    asielib{0.3.2} [asielib] (AsieLib-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.1.2} [BuildCraft] (buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.1.2} [BC Builders] (buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.1.2} [BC Transport] (buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.1.2} [BC Silicon] (buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.1.2} [BC Factory] (buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.1.2} [BC Energy] (buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.14} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized
    ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized
    gregtech{MC1710} [GregTech] (gregtech_1.7.10-5.05.13.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity] (universal-electricity-4.0.0.83-core.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.311} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Core{4.5.1.51} [ProjectRed] (ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission] (ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ImmibisCore{59.0.3} [Immibis Core] (immibis-core-59.0.3.jar) Unloaded->Constructed->Pre-initialized
    RedLogic{59.0.5} [RedLogic] (redlogic-59.0.5.jar) Unloaded->Constructed->Pre-initialized
    nedocomputers{0.3} [NedoComputers] (NedoComputers-1.7.10-0.3.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.24} [EnderStorage] (EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.4.0.5-beta.2} [OpenComputers] (OpenComputers-MC1.7.10-1.4.0.5-beta.2-universal.jar) Unloaded->Constructed->Errored
    computronics{1.2.0} [Computronics] (Computronics-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized
    customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b.jar) Unloaded->Constructed->Pre-initialized
    iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
    HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized
    ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine] (resonant-engine-2.0.0.145-core.jar) Unloaded->Constructed->Pre-initialized
    MFFS{@MAJOR@.@MINOR@.@REVIS@} [Modular Force Field System] (mffs-4.1.0.33-core.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration] (ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    numina{0.4.0.98} [Numina] (Numina-0.4.0.98.jar) Unloaded->Constructed->Pre-initialized
    powersuits{0.11.0.174} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.174.jar) Unloaded->Constructed->Pre-initialized
    Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized
    NBTEdit{1.7.2.2} [In-game NBTEdit] (NBTEdit_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-231.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-454.jar) Unloaded->Constructed->Pre-initialized
    planetguyLib{1.0} [planetguyLib] (PlanetguyLib-1.0.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transportation{4.5.1.51} [ProjectRed-Transportation] (ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility] (ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration] (ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination] (ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Expansion{4.5.1.51} [ProjectRed-Expansion] (ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    JAKJ_RedstoneInMotion{2.1.4} [Remain In Motion] (RemainInMotion-2.1.4.jar) Unloaded->Constructed->Pre-initialized
    JAKJ_RedstoneInMotion_HollowCarriages{1.0} [JAKJ_RedstoneInMotion_HollowCarriages] (RemainInMotion-2.1.4.jar) Unloaded->Constructed->Pre-initialized
    rivalrebels{1.7.10A} [Rival Rebels] (rivalrebels-1.7.10A.jar) Unloaded->Constructed->Pre-initialized
    secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.376.jar) Unloaded->Constructed->Pre-initialized
    securitycraft{v1.6.1} [SecurityCraft] (SecurityCraft v1.6.0 for 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    SmartMoving{15.2} [Smart Moving] (SmartMoving-1.7.10-15.2.jar) Unloaded->Constructed->Pre-initialized
    SmartRender{2.0} [Smart Render] (SmartRender-1.7.10-2.0.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Core{1.4.1.7} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Addons{1.4.1.7} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Logic{1.4.1.7} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.311} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.311} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized
    asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech
```

But heres the main problem:
Most of all times, when its mod conflict, it would show that two mods haves errors, but theres only one! I maybe would have fixed it by myself, it there was two mods with error statement.

**Comment by LizzyTrickster** [comment]
1) use pastebin or GitHub's Gist service for crashlogs
2) what were you doing when this occurred and what steps could be taken to reproduce it?

**Comment by evsey9** [comment]
It shows mod names as links, i dont know why.

**Comment by evsey9** [comment]
It crashed on startup
EDIT: Okay, i will use pastebin if something bad happens again
EDIT 2: Here's the pastebin link if you need it: http://pastebin.com/E5Rw5aVU

**Comment by LizzyTrickster** [comment]
Can you provide either a list or a screenshot of the mods you're using? (preferably with the full filenames visible)

**Comment by evsey9** [comment]
Okay, i will provide mod list:
![mods part1](https://cloud.githubusercontent.com/assets/7791364/4780457/22476292-5c69-11e4-9f7c-b71cce14ed0a.png)
![mods part2](https://cloud.githubusercontent.com/assets/7791364/4780458/251d0a58-5c69-11e4-8000-da66acb86fa2.png)

EDIT: Sorry for the poor quality, i did mod list in paint

**Comment by evsey9** [comment]
Help me please?

**Comment by LizzyTrickster** [comment]
@evsey9 get the latest build from http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/ (should be 206 when it's built) and try again

**Comment by alphaalphaalpha2** [comment]
outdated mod and it needs to be updated
