### ISSUE TITLE
Crash with Reika DragonAPI v2

### ISSUE THREAD

**Issue by aarondandy** [MightyPirates/OpenComputers#628]
For the past few beta versions I have tried my game crashes when using the creative mode item search tab. It crashes right when I click on the search (compass) tab and I only notice this when I add the new beta mods to my MultiMC instance. I have a boat load of mods installed so it is hard to say which one it is but the stack-trace seems to implicate `DragonAPI 1.7.10 V2` and it wouldn't be the first time they have used reflection to do some "fucky shit".

```
[10:33:29] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1643) ~[bao.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
at Reika.DragonAPI.Base.TileEntityBase.createNode(TileEntityBase.java:639) ~[TileEntityBase.class:?]
at Reika.DragonAPI.Base.TileEntityBase.<init>(TileEntityBase.java:560) ~[TileEntityBase.class:?]
at Reika.RotaryCraft.Base.TileEntity.RotaryCraftTileEntity.<init>(RotaryCraftTileEntity.java:38) ~[RotaryCraftTileEntity.class:?]
at Reika.RotaryCraft.Base.TileEntity.TileEntityIOMachine.<init>(TileEntityIOMachine.java:24) ~[TileEntityIOMachine.class:?]
at Reika.RotaryCraft.Base.TileEntity.TileEntityPowerReceiver.<init>(TileEntityPowerReceiver.java:42) ~[TileEntityPowerReceiver.class:?]
at Reika.RotaryCraft.Base.TileEntity.InventoriedPowerReceiver.<init>(InventoriedPowerReceiver.java:24) ~[InventoriedPowerReceiver.class:?]
at Reika.RotaryCraft.TileEntities.Production.TileEntityBedrockBreaker.<init>(TileEntityBedrockBreaker.java:48) ~[TileEntityBedrockBreaker.class:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_60]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_60]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_60]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.7.0_60]
at java.lang.Class.newInstance(Unknown Source) ~[?:1.7.0_60]
at Reika.RotaryCraft.Registry.MachineRegistry.createTEInstanceForRender(MachineRegistry.java:1247) ~[MachineRegistry.class:?]
at Reika.RotaryCraft.Items.Placers.ItemMachinePlacer.func_150895_a(ItemMachinePlacer.java:225) ~[ItemMachinePlacer.class:?]
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:347) ~[bfl.class:?]
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550) ~[bfl.class:?]
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456) ~[bfl.class:?]
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) ~[bdw.class:?]
at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) ~[bex.class:?]
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566) ~[bfl.class:?]
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) ~[bao.class:?]
... 17 more
[10:33:29] [Server thread/INFO] [FML]: Applying holder lookups
[10:33:29] [Server thread/INFO] [FML]: Holder lookups applied
[10:33:29] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I feel sad now :(

Time: 10/26/14 10:33 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
at Reika.DragonAPI.Base.TileEntityBase.createNode(TileEntityBase.java:639)
at Reika.DragonAPI.Base.TileEntityBase.<init>(TileEntityBase.java:560)
at Reika.RotaryCraft.Base.TileEntity.RotaryCraftTileEntity.<init>(RotaryCraftTileEntity.java:38)
at Reika.RotaryCraft.Base.TileEntity.TileEntityIOMachine.<init>(TileEntityIOMachine.java:24)
at Reika.RotaryCraft.Base.TileEntity.TileEntityPowerReceiver.<init>(TileEntityPowerReceiver.java:42)
at Reika.RotaryCraft.Base.TileEntity.InventoriedPowerReceiver.<init>(InventoriedPowerReceiver.java:24)
at Reika.RotaryCraft.TileEntities.Production.TileEntityBedrockBreaker.<init>(TileEntityBedrockBreaker.java:48)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at Reika.RotaryCraft.Registry.MachineRegistry.createTEInstanceForRender(MachineRegistry.java:1247)
at Reika.RotaryCraft.Items.Placers.ItemMachinePlacer.func_150895_a(ItemMachinePlacer.java:225)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:347)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at Reika.DragonAPI.Base.TileEntityBase.createNode(TileEntityBase.java:639)
at Reika.DragonAPI.Base.TileEntityBase.<init>(TileEntityBase.java:560)
at Reika.RotaryCraft.Base.TileEntity.RotaryCraftTileEntity.<init>(RotaryCraftTileEntity.java:38)
at Reika.RotaryCraft.Base.TileEntity.TileEntityIOMachine.<init>(TileEntityIOMachine.java:24)
at Reika.RotaryCraft.Base.TileEntity.TileEntityPowerReceiver.<init>(TileEntityPowerReceiver.java:42)
at Reika.RotaryCraft.Base.TileEntity.InventoriedPowerReceiver.<init>(InventoriedPowerReceiver.java:24)
at Reika.RotaryCraft.TileEntities.Production.TileEntityBedrockBreaker.<init>(TileEntityBedrockBreaker.java:48)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at Reika.RotaryCraft.Registry.MachineRegistry.createTEInstanceForRender(MachineRegistry.java:1247)
at Reika.RotaryCraft.Items.Placers.ItemMachinePlacer.func_150895_a(ItemMachinePlacer.java:225)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:347)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
```

Also my version of NEI is `NotEnoughItems-1.7.10-1.0.3.64-universal` . I would be happy to provide other details so long as I can still reproduce, just ask.

**Comment by LizzyTrickster** [comment]
This doesn't seem to have OC in it at all, `java.lang.NullPointerException: Updating screen events` looks like an error in Reika's mod(s). I'd suggest sending this to him because OC is not mentioned at all (and AFAIK, OC doesn't have a screen render api that other mods hook into)

**Comment by aarondandy** [comment]
The issue is definitely in Reika's mod, here is the location:
https://github.com/ReikaKalseki/DragonAPI/blob/424eb1537fddabbd0c35aaede41d0929c82e7f84/Base/TileEntityBase.java#L647

**Comment by fnuecke** [comment]
Ah, right, forgot to let him know, yet (this is most like an API incompat with OC 1.4, see #609).

Will let him know to update to the OC 1.4 API now that it's stable (the API that is).
