### ISSUE TITLE
NEI Crash OC 1.4.0

### ISSUE THREAD

**Issue by adigyran** [MightyPirates/OpenComputers#631]
http://pastebin.com/3T10AkQj
1.3 version works perfectly. all mods is latest versions

OC
OpenComputers-MC1.7.10-1.4.0.206-dev-universal
OpenComputers-MC1.7.10-1.4.0.6-rc.1-universal
same error occurred

**Comment by adigyran** [comment]
this occurred on world load. OC with mcrc2 occurred this error on game startup

**Comment by fnuecke** [comment]
Hmm, could you post the full log, please? Alos, what's `mcrc2`?

**Comment by adigyran** [comment]
Minecraft-Resource-Calculator 
Full log is very big error on 99341 line
because "logs\fml-client-latest.log" error only here 
100185 lines
https://dl.dropboxusercontent.com/u/21763955/fml-client-latest.log

**Comment by fnuecke** [comment]
Ah, I'd hoped there'd be a short on in crash-reports/, but that'll do.
A couple of things to try:
- Update NEI and CCC.
- Try using Java 7 instead of Java 8.

**Comment by adigyran** [comment]
JDK 1.8.0 x64, latest NEI and CCC - still crash (crash only internal server) 
Java 7 x64 - crash

**Comment by Moltenkore** [comment]
Same problem, when I try and launch a single player game it shuts down the internal server. My NEI version is 1.0.2.15 and my OC version is 1.4.0.206

Java 7 x64 (71)

Here is an extract of the log:

<pre>
[15:53:48] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel NEI
java.lang.NoClassDefFoundError: Could not initialize class li.cil.oc.common.Loot$
at li.cil.oc.common.init.Items$$anon$1.func_150895_a(Items.scala:103) ~[Items$$anon$1.class:?]
at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:393) ~[ItemInfo.class:?]
at codechicken.nei.api.ItemInfo.load(ItemInfo.java:97) ~[ItemInfo.class:?]
at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:247) ~[NEIClientConfig.class:?]
at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:197) ~[NEIClientConfig.class:?]
at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) ~[NEICPH.class:?]
at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) ~[NEICPH.class:?]
at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) ~[PacketCustom$ClientInboundHandler.class:?]
at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2050) [bao.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
</pre>

**Comment by fnuecke** [comment]
I'm afraid I can't reproduce this. Does this also happen if OC and NEI are the only mods present?

**Comment by Moltenkore** [comment]
I actually have quite a few mods installed, would you like the list?
I'll try my best to test each one but it may take a while.
Edit here's the list: 
http://i.imgur.com/gYXvw8y.jpg
http://i.imgur.com/dqmxW9f.jpg

**Comment by adigyran** [comment]
Dragon Api caused that bug, I`m deleted Dragon API - works perfectly. Can you please tell Reika to update Dragon Api?

**Comment by Moltenkore** [comment]
I can confirm, removing Dragon Api (and all dependent mods) solved the problem and the game world loads correctly. @adigyran thanks :)

**Comment by fnuecke** [comment]
That's... quite interesting. Thanks for investigating! I did let him know about the 1.4 API change, so he'll probably update soon. I have no idea whatsoever how that would lead to this error, though (in particular if it also happens on Java 1.8, meaning it can't be a well hidden out of permgen space error).

**Comment by ynerant** [comment]
You can also delete the 'opencomputers' dir in the DragonAPI jar, that works too.
