### ISSUE TITLE
Crashed Crash Handler

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#646]
```
java.lang.IndexOutOfBoundsException: No group 4
at java.util.regex.Matcher.start(Matcher.java:374)
at java.util.regex.Matcher.appendReplacement(Matcher.java:831)
at scala.util.matching.Regex$Replacement$class.replace(Regex.scala:722)
at scala.util.matching.Regex$MatchIterator$$anon$1.replace(Regex.scala:700)
at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:410)
at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:410)
at scala.collection.Iterator$class.foreach(Iterator.scala:743)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
at scala.util.matching.Regex.replaceAllIn(Regex.scala:410)
at li.cil.oc.server.component.GraphicsCard$$anonfun$onMessage$1.apply(GraphicsCard.scala:293)
at li.cil.oc.server.component.GraphicsCard$$anonfun$onMessage$1.apply(GraphicsCard.scala:277)
at li.cil.oc.server.component.GraphicsCard.screen(GraphicsCard.scala:31)
at li.cil.oc.server.component.GraphicsCard.onMessage(GraphicsCard.scala:277)
at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
at scala.collection.immutable.List.foreach(List.scala:383)
at li.cil.oc.server.network.Network.send(Network.scala:311)
at li.cil.oc.server.network.Network.sendToReachable(Network.scala:194)
at li.cil.oc.server.network.Network$Wrapper.sendToReachable(Network.scala:708)
at li.cil.oc.server.network.Network$Wrapper.sendToReachable(Network.scala:684)
at li.cil.oc.server.network.NodeVarargPart$class.sendToReachable(Node.scala:96)
at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToReachable(Network.scala:582)
at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToReachable(Network.scala:582)
at li.cil.oc.server.machine.Machine.update(Machine.scala:473)
at li.cil.oc.common.tileentity.traits.Computer$class.updateEntity(Computer.scala:112)
at li.cil.oc.common.tileentity.Case.func_145845_h(Case.scala:83)
at net.minecraft.world.World.func_72939_s(World.java:1912)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

The error was:

```
com.loomcom.symon.exceptions.MemoryAccessException: Bus write failed. No device at address $4000
```

**Comment by fnuecke** [comment]
Fixed in af6a2755424d9861c886aba28c4651864e6624f2
