### ISSUE TITLE
Troubles with Resonant Induction 0.3.4.168 and OpenComputers 1.4.0.7 RC1

### ISSUE THREAD

**Issue by walkerjonny** [MightyPirates/OpenComputers#647]
Hi, 
There is an issue with Resonant Induction.
Here is the crash report:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 03.11.14 01:52
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: li/cil/oc/api/network/Context
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: li/cil/oc/api/network/Context
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.getDeclaredMethods(Unknown Source)
    at resonant.lib.network.discriminator.PacketAnnotationManager.constructPacketSets(PacketAnnotationManager.java:83)
    at resonant.lib.network.discriminator.PacketAnnotationManager.register(PacketAnnotationManager.java:48)
    at resonant.content.CommonRegistryProxy.registerTileEntity(CommonRegistryProxy.java:20)
    at resonant.content.loader.ModManager.newBlock(ModManager.java:131)
    at resonant.content.loader.ModManager.newBlock(ModManager.java:102)
    at resonant.content.loader.ContentLoader$$anonfun$preInit$1.apply(ContentLoader.scala:64)
    at resonant.content.loader.ContentLoader$$anonfun$preInit$1.apply(ContentLoader.scala:22)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at resonant.content.loader.ContentLoader$class.preInit(ContentLoader.scala:22)
    at resonantinduction.atomic.AtomicContent$.preInit(AtomicContent.scala:132)
    at resonant.lib.loadable.LoadableHandler.preInit(LoadableHandler.java:91)
    at resonantinduction.core.ResonantInduction$.preInit(ResonantInduction.scala:58)
    at resonantinduction.core.ResonantInduction.preInit(ResonantInduction.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: li.cil.oc.api.network.Context
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 54 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1730018184 bytes (1649 MB) / 2112618496 bytes (2014 MB) up to 6944456704 bytes (6622 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx6656m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+UseCMSCompactAtFullCollection -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 10 mods loaded, 10 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1232} [Forge Mod Loader](forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1232} [Minecraft Forge](forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.312} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.312-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.4.0.7-rc.1} [OpenComputers](OpenComputers-MC1.7.10-1.4.0.7-rc.1-universal.jar) Unloaded->Constructed->Pre-initialized
    ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine](resonant-engine-2.2.0.178-core.jar) Unloaded->Constructed->Pre-initialized
    ResonantInductionCore{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction](resonant-induction-0.3.4.168-core.jar) Unloaded->Constructed->Errored
    McMultipart{1.1.0.312} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.312-universal.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.312} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.312-universal.jar) Unloaded->Constructed->Pre-initialized

**Comment by fnuecke** [comment]
API incompatibility. They've updated it on the repo, so try updating or expect it to be fixed in one of the next builds of Resonant Engine.
