### ISSUE TITLE
Networking packets make OC go into infinite recursion

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [MightyPirates/OpenComputers#735]
I could not reliably reproduce bug nor find out exact cause. My best shot is that it has something to do with servers but after I re-placed racks it started working fine. Apparently, it cannot find somebody to send packet to, but I'm no Java expert. Here's the stack trace (I did not copy the whole thing as it seems to be repeating itself, but I'm not sure and my eyes may be lying to me):

```
    at scala.collection.mutable.ArrayBuffer.initialSize(ArrayBuffer.scala:48)
    at scala.collection.mutable.ResizableArray$class.$init$(ResizableArray.scala:32)
    at scala.collection.mutable.ArrayBuffer.<init>(ArrayBuffer.scala:49)
    at scala.collection.mutable.ArrayBuffer.<init>(ArrayBuffer.scala:63)
    at scala.collection.mutable.ArrayBuffer$.newBuilder(ArrayBuffer.scala:190)
    at scala.collection.generic.GenericTraversableTemplate$class.genericBuilder(GenericTraversableTemplate.scala:70)
    at scala.collection.AbstractTraversable.genericBuilder(Traversable.scala:104)
    at scala.collection.generic.GenTraversableFactory$GenericCanBuildFrom.apply(GenTraversableFactory.scala:57)
    at scala.collection.generic.GenTraversableFactory$GenericCanBuildFrom.apply(GenTraversableFactory.scala:52)
    at scala.collection.TraversableLike$class.builder$1(TraversableLike.scala:240)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at li.cil.oc.server.network.Network.neighbors(Network.scala:168)
    at li.cil.oc.server.network.Network.sendToNeighbors(Network.scala:188)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:709)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:688)
    at li.cil.oc.server.network.NodeVarargPart$class.sendToNeighbors(Node.scala:93)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.component.Server$$anonfun$onMessage$1.apply$mcVI$sp(Server.scala:117)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at li.cil.oc.server.component.Server.onMessage(Server.scala:115)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at li.cil.oc.server.network.Network.send(Network.scala:311)
    at li.cil.oc.server.network.Network.sendToNeighbors(Network.scala:188)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:709)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:688)
    at li.cil.oc.server.network.NodeVarargPart$class.sendToNeighbors(Node.scala:93)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.component.Server$$anonfun$onMessage$1.apply$mcVI$sp(Server.scala:117)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at li.cil.oc.server.component.Server.onMessage(Server.scala:115)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at li.cil.oc.server.network.Network.send(Network.scala:311)
    at li.cil.oc.server.network.Network.sendToNeighbors(Network.scala:188)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:709)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:688)
    at li.cil.oc.server.network.NodeVarargPart$class.sendToNeighbors(Node.scala:93)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.component.Server$$anonfun$onMessage$1.apply$mcVI$sp(Server.scala:117)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at li.cil.oc.server.component.Server.onMessage(Server.scala:115)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at li.cil.oc.server.network.Network.send(Network.scala:311)
    at li.cil.oc.server.network.Network.sendToNeighbors(Network.scala:188)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:709)
    at li.cil.oc.server.network.Network$Wrapper.sendToNeighbors(Network.scala:688)
    at li.cil.oc.server.network.NodeVarargPart$class.sendToNeighbors(Node.scala:93)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToNeighbors(Network.scala:584)
    at li.cil.oc.server.component.Server$$anonfun$onMessage$1.apply$mcVI$sp(Server.scala:117)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at li.cil.oc.server.component.Server.onMessage(Server.scala:115)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:311)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
```

One more thing: if I modify file on a computer disk outside Minecraft, it doesn't get updated on the inside until I take the disk out of the computer and place it back, restarting the thing afterwards. Is this planned to be like that?

Besides, thank you very much for great mod! (In case it sounds like sarcasm, it's not one)

**Comment by fnuecke** [comment]
Thanks for the report. I'm guessing you're on 1.4.1 or an earlier dev build? This should be fixed in the latest dev build (http://ci.cil.li/). This could happen when sending a network message from a side-less server when there was another side-less server in the rack IIRC.

File systems are buffered until the next world save by default, to avoid them desyncing from computers' states when the game crashes. You can disable this in the config (filesystem.bufferChanges = false).

**Comment by HiTECNOLOGYs** [comment]
I see. Thanks for help.
