### ISSUE TITLE
Can't start computers (1.4.2/1.4.3 latest build)

### ISSUE THREAD

**Issue by theron61** [MightyPirates/OpenComputers#749]
Hello,

I have a server rack with a single Tier 3 server which appears to not be operational.  I get the following in my client log when I try to power it on.  Nothing in the server log as far as I can tell.

```
[19:44:55] [Client thread/WARN] [OpenComputers]: Received a badly formatted packet.
org.lwjgl.openal.OpenALException: OpenAL error: Out of Memory (40965)
    at org.lwjgl.openal.Util.checkALError(Util.java:64) ~[lwjgl-2.9.1.jar:?]
    at li.cil.oc.util.Audio$Source.liftedTree1$1(Audio.scala:104) ~[Audio$Source.class:?]
    at li.cil.oc.util.Audio$Source.<init>(Audio.scala:99) ~[Audio$Source.class:?]
    at li.cil.oc.util.Audio$.play(Audio.scala:72) ~[Audio$.class:?]
    at li.cil.oc.client.PacketHandler$.onSoundPattern(PacketHandler.scala:490) ~[PacketHandler$.class:?]
    at li.cil.oc.client.PacketHandler$.dispatch(PacketHandler.scala:78) ~[PacketHandler$.class:?]
    at li.cil.oc.common.PacketHandler.onPacketData(PacketHandler.scala:30) [PacketHandler.class:?]
    at li.cil.oc.client.PacketHandler$.onPacket(PacketHandler.scala:28) [PacketHandler$.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_723_PacketHandler$_onPacket_ClientCustomPacketEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by fnuecke** [comment]
This is unrelated to the server not starting, it's a client side issue (your sound card is running out of memory). I'll be adding some nicer handling for that.

Assuming you're on 1.4.2, double check your server has a working EEPROM (e.g. Lua BIOS) and a bootable file system (e.g. OpenOS floppy), as well as that it's powered. Use the analyzer on the server to see the reason it failed booting.
