### ISSUE TITLE
Robots getting killed by growing trees (probably)

### ISSUE THREAD

**Issue by Namarius** [MightyPirates/OpenComputers#808]
I have a automatic tree farm on a GregTech based server and from time to time the working robot disappears. Today is the 4th time that this happens and it happened since version 1.3.x up to the current (1.4.4a). I don't know the curse of the disappearing, but I suspect that it is some kind of an in transition overriding or some chunk border problem.

So any ideas?

**Comment by fnuecke** [comment]
AFAIK this is a vanilla issue - I read something about growing trees even breaking bedrock, I think?

So I'm not sure there's anything I could do about that. Would be happy to be proven wrong, though.

Edit: possibly related: https://bugs.mojang.com/browse/MC-10176

**Comment by Namarius** [comment]
Okay I will try to change my program to avoid the "danger zone".

And just as a side note: It is a birch tree farm

**Comment by technolem** [comment]
I think enderIO tried to fix this for their pipes: https://github.com/CrazyPants/EnderIO/issues/1357 not sure if he actually fixed it or gave up though.

**Comment by fnuecke** [comment]
Hmm, looks like EnderIO might have been missing an override for `canBeReplacedByLeaves`. That's already in place for [all OC blocks](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/block/SimpleBlock.scala#L155), however, so I'm afraid that's not it.

**Comment by technolem** [comment]
Ah yeah, I must have misread that...

**Comment by fnuecke** [comment]
I did some testing, and while I could reproduce the bug linked above, but unless you have some mod that adds birch trees with branches that should not be related. I.e. if all your birch trees only have the central pillar of birch wood this may be something else. No clue what, though...

**Comment by Namarius** [comment]
The robot doesn't ever travel in the "leaves zone" and birches are vanilla as long as forestry doesn't influence them so just central pillar. The only moment where a tree could kill a robot is the moment where the robot moves in or out of the block directly above of the sapling.

Well it happens ruthlessly every 15 days ^^ and the server itself runs 24 hour with two full backups every 12 hours. The farm itself isn't loaded all the time, here are no chunkloaders or anything else, but the place is visited daily.

So if it doesn't happen in the next 15 to 30 days we could assume that trees doesn't like being uses by robots ^^ if it happens again its something else.

**Comment by Namarius** [comment]
I've got some good and bad news.

Good news is that it wasn't the trees.

Bad news is that it seems to be a world save error. I have a world where the robot block position and the tile entity block position are seriousy out of sync. See picture at bottom. The lower left is the tile entity and the upper right the robot block.
This error seems to be triggered by this ConcurrentModificationException and I don't know who to blame.

One last note:
The server where this happens have pretty long autosave pauses.

```
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.ConcurrentModificationException
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:23)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_150298_a(SourceFile:314)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_150298_a(SourceFile:314)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_150298_a(SourceFile:314)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_150298_a(SourceFile:314)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:265)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[00:25:47] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.Thread.run(Thread.java:745)
```

![robot](https://cloud.githubusercontent.com/assets/873938/6307488/91bc68b8-b93c-11e4-970d-cae7b8105d3a.png)

**Comment by fnuecke** [comment]
Thanks for the update. CMEs are an utter pain to track down, because, well, the actual cause is usually unknown. And it's hard to tell if that's even related. I've been reviewing the robot movement code again and again, but I don't see how something like this could happen.
I might try to backport the change made to it in the 1.8 branch, where this code would run in a tick handler, as opposed to the tile entity's update method, which might help if this is caused by some weird corner-case... or non-"standard" behavior maybe. Are you using Cauldron perchance?

**Comment by Namarius** [comment]
No just plain forge. I tried Fastcraft http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820 from player to boost up my server. Fastcraft actually increased the chance of broken robots by a factor of 5 to 10. Without Fastcraft the server got some serious problems with chunk loading and saving (stops for 1-3 seconds).
Currently I am running a test with Fastcraft and personal anchors from Railcraft that keeping the working area loaded.

**Comment by fnuecke** [comment]
Cauldron: All right, good, at least that's ruled out then.

Fastcraft: hmm, then it might indeed have to do with some behavior in tile entity ticking I'm not aware of. I guess. I'll backport the change in a bit and let you know when the build is up so you can test with that.

**Comment by fnuecke** [comment]
Please see if this still happens with the [latest build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/), 437 at the time of writing. Thanks.

**Comment by Namarius** [comment]
I've tested build 437 for some days and no sign of an ConcurrentModificationException in logs and no problems on any robot.
It seems like it's been fixed.

**Comment by fnuecke** [comment]
Cool! If it does pop up again, lemme know and I'll reopen this.
