### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lieven121** [MightyPirates/OpenComputers#846]
for testing i deleted al my other mods and now if i use seach or hold my cursor above the item in the gui i crash 

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 24/01/15 16:59
Description: Rendering screen

java.lang.IndexOutOfBoundsException
    at java.nio.Buffer.checkIndex(Unknown Source)
    at java.nio.DirectByteBuffer.get(Unknown Source)
    at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
    at li.cil.oc.client.KeyBindings$.showExtendedTooltips(KeyBindings.scala:8)
    at li.cil.oc.util.Tooltip$.get(Tooltip.scala:22)
    at li.cil.oc.common.block.Hologram.tooltipBody(Hologram.scala:43)
    at li.cil.oc.common.block.SimpleBlock.addInformation(SimpleBlock.scala:105)
    at li.cil.oc.common.block.Item.func_77624_a(Item.scala:30)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.nio.Buffer.checkIndex(Unknown Source)
    at java.nio.DirectByteBuffer.get(Unknown Source)
    at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
    at li.cil.oc.client.KeyBindings$.showExtendedTooltips(KeyBindings.scala:8)
    at li.cil.oc.util.Tooltip$.get(Tooltip.scala:22)
    at li.cil.oc.common.block.Hologram.tooltipBody(Hologram.scala:43)
    at li.cil.oc.common.block.SimpleBlock.addInformation(SimpleBlock.scala:105)
    at li.cil.oc.common.block.Item.func_77624_a(Item.scala:30)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (258, 91). Absolute: (517, 296)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['lieven121'/0, l='MpServer', x=103,50, y=65,62, z=-54,50]]
    Chunk stats: MultiplayerChunkCache: 624, 624
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (113,4,-64), Chunk: (at 1,0,0 in 7,-4; contains blocks 112,0,-64 to 127,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 1305 game time, 1305 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 25 total; [EntityClientPlayerMP['lieven121'/0, l='MpServer', x=103,50, y=65,62, z=-54,50], EntityBat['Bat'/23907, l='MpServer', x=136,49, y=12,68, z=-127,41], EntityBat['Bat'/23908, l='MpServer', x=132,03, y=13,04, z=-123,48], EntityBat['Bat'/6085, l='MpServer', x=155,00, y=32,13, z=-84,29], EntityBat['Bat'/13499, l='MpServer', x=59,84, y=53,77, z=-61,34], EntityBat['Bat'/25424, l='MpServer', x=132,52, y=34,00, z=17,34], EntityItem['item.tile.flower2.poppy'/39, l='MpServer', x=154,03, y=64,13, z=-37,56], EntitySquid['Squid'/20632, l='MpServer', x=62,50, y=53,22, z=-59,38], EntityBat['Bat'/7911, l='MpServer', x=165,03, y=25,10, z=5,47], EntitySquid['Squid'/20634, l='MpServer', x=57,50, y=53,38, z=-60,16], EntityBat['Bat'/25422, l='MpServer', x=132,31, y=34,24, z=17,55], EntityBat['Bat'/20307, l='MpServer', x=153,72, y=8,71, z=-40,76], EntityCow['Cow'/8347, l='MpServer', x=79,72, y=64,00, z=-79,72], EntityCow['Cow'/8350, l='MpServer', x=75,50, y=64,00, z=-70,50], EntityChicken['Chicken'/8351, l='MpServer', x=77,50, y=64,00, z=-77,50], EntityCow['Cow'/8348, l='MpServer', x=75,94, y=64,00, z=-76,78], EntityCow['Cow'/8349, l='MpServer', x=78,56, y=64,00, z=-74,28], EntityBat['Bat'/14323, l='MpServer', x=150,75, y=32,00, z=-84,94], EntityBat['Bat'/8983, l='MpServer', x=100,22, y=12,05, z=-43,93], EntityChicken['Chicken'/8353, l='MpServer', x=75,06, y=64,00, z=-76,81], EntityChicken['Chicken'/8352, l='MpServer', x=76,50, y=64,00, z=-79,50], EntityChicken['Chicken'/8354, l='MpServer', x=72,50, y=64,00, z=-79,50], EntityBat['Bat'/8105, l='MpServer', x=136,18, y=34,14, z=17,53], EntityBat['Bat'/2422, l='MpServer', x=130,75, y=35,10, z=18,75], EntitySheep['Sheep'/8372, l='MpServer', x=26,50, y=64,00, z=-91,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 192358464 bytes (183 MB) / 447336448 bytes (426 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 5 mods loaded, 5 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1232} [Forge Mod Loader] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1232} [Minecraft Forge] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.4.5.28} [OpenComputers] (OpenComputers-MC1.7.10-1.4.5.28-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1232
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 2.1.0 - Build 8.15.10.2622, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by fnuecke** [comment]
I have no actual idea as to what might be causing this. I did find some posts with crashes in the same location that suggested this can be caused by duplicate key bindings. Either way, I'll just wrap a try-catch around the relevant pieces to avoid the crash.

**Comment by lieven121** [comment]
Thx for looking at it 
And I have a lot of keybind conflicts so I will "fix" those and reply if it worked this will not be to soon (its now 23:10 here )
