### ISSUE TITLE
NoSuckFieldError: transmissionAPI

### ISSUE THREAD

**Issue by godeatgod** [MightyPirates/OpenComputers#85]
Reproduced on  version 1.1.3, linux java 64, forge 9.11.1.965
by placing down any mod block or by entering an area with one placed.

MC crashes with the following error message:

java.lang.NoSuchFieldError: transmissionAPI
    at li.cil.oc.common.tileentity.BundledRedstoneAware$class.computeBundledInput(BundledRedstoneAware.scala:141)
    at li.cil.oc.common.tileentity.Computer.computeBundledInput(Computer.scala:18)
    at li.cil.oc.common.tileentity.BundledRedstoneAware$$anonfun$updateRedstoneInput$1.apply(BundledRedstoneAware.scala:68)
    at li.cil.oc.common.tileentity.BundledRedstoneAware$$anonfun$updateRedstoneInput$1.apply(BundledRedstoneAware.scala:66)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
    at li.cil.oc.common.tileentity.BundledRedstoneAware$class.updateRedstoneInput(BundledRedstoneAware.scala:66)
    at li.cil.oc.common.tileentity.Computer.updateRedstoneInput(Computer.scala:18)
    at li.cil.oc.common.tileentity.Computer.func_70316_g(Computer.scala:106)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

**Comment by fnuecke** [comment]
The version of Project: Red you're using is probably too old. Try with the newest one, please.
