### ISSUE TITLE
Touch Events Crash

### ISSUE THREAD

**Issue by marcbinz** [MightyPirates/OpenComputers#852]
Hi there OC-Team,
I've discovered an issue I can't get rid of.
I'm not sure if another mod interferes here, but I actually don't think so :P 

The problem is, whenever I click with my mouse (event handler) or even at the editor when I try to reposition the cursor by clicking a specific spot, the game crashes.

Sadly there is not much more information I could hand to you, but still don't hesitate to ask me :)

Greetings,
Yoppha

**Comment by marcbinz** [comment]
PS: Just to make sure, I used version 1.4.5 until now, but already installed version 1.4.6 today.
Sadly, it did not fix it magically ;D

**Comment by fnuecke** [comment]
If the game crashes, there should be a crash log (check your `.minecraft/crash-reports` directory).
Could you please post that (on pastebin, gist, or here directly).
Thanks.

**Comment by marcbinz** [comment]
Totally forgot that there are logs for nearly everything...
Here you go:

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 1/25/15 3:21 PM
Description: Unexpected error

java.lang.NoSuchMethodError: li.cil.oc.api.component.TextBuffer.mouseDown(DDILnet/minecraft/entity/player/EntityPlayer;)V
    at li.cil.oc.common.tileentity.Screen.click(Screen.scala:140)
    at li.cil.oc.common.block.Screen.rightClick(Screen.scala:345)
    at li.cil.oc.common.block.Screen.onBlockActivated(Screen.scala:330)
    at li.cil.oc.common.block.SimpleBlock.func_149727_a(SimpleBlock.scala:259)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

Thanks for the help :)

**Comment by fnuecke** [comment]
Looks like some other mod is shipping an older version of the OC API.

Please look through your mod JARs and if one (other than OC) contains a `li/cil/oc` directory, check if there's an update for that mod. If the update fixes it, great, otherwise remove that directory from the JAR. That should fix it. Also let me know which mod it was so I can inform them to update.

**Comment by marcbinz** [comment]
OK, that's worth a big thank you man :D 
I found the mod, deleted the folder and boom - it works!

Mod: Reika's Dragon API V3d (for 1.7.10)

So thank you for the great help (and the fast reply)

Greetings,
Yoppha

**Comment by MrabEzreb** [comment]
Woaw, good to see that this issue was put up here and fixed, hopefully fixing dragon api will help me too :D

**Comment by fnuecke** [comment]
Good news, v4 of DragonAPI will have the updated OC API in it.

Will leave this open until then so people running into this issue have an easier time finding this.
