### ISSUE TITLE
Selecting EEPROM or lua BIOS causing crash, 1.4.6.30, Single-Player

### ISSUE THREAD

**Issue by tgeak** [MightyPirates/OpenComputers#880]
This crash occurred in version 1.4.6.30 of OpenComputers, there was also a similar occurrence when running version 1.4.5. This crash also occurs even with a clean install of the minecraft client. Here is the latest crash report; when opening the inventory in creative, highlighting either the lua BIOS or EEPROM causes the client to crash. This has only been done in single-player.

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/02/15 6:06 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: Could not initialize class li.cil.oc.util.ItemCosts$
    at li.cil.oc.common.item.SimpleItem.func_77624_a(SimpleItem.scala:45)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at li.cil.oc.common.item.SimpleItem.func_77624_a(SimpleItem.scala:45)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (372, 194). Absolute: (745, 330)
    Screen size: Scaled: (640, 360). Absolute: (1280, 720). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['tgeak'/0, l='MpServer', x=-367.50, y=57.62, z=-1262.50]]
    Chunk stats: MultiplayerChunkCache: 529, 529
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-366,4,-1260), Chunk: (at 2,0,4 in -23,-79; contains blocks -368,0,-1264 to -353,255,-1249), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
    Level time: 578 game time, 578 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['tgeak'/0, l='MpServer', x=-367.50, y=57.62, z=-1262.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 138104912 bytes (131 MB) / 414380032 bytes (395 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 5 mods loaded, 5 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    OpenComputers{1.4.6.30} [OpenComputers] (OpenComputers-MC1.7.10-1.4.6.30-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: Intel HD Graphics 3000 OpenGL Engine GL version 2.1 INTEL-10.0.19, Intel Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by Vexatos** [comment]
Are you able to reproduce it with 1.4.6?

**Comment by tgeak** [comment]
This log was done in 1.4.6, I was just stating that a similar result had been seen in 1.4.5. The description made here with the included log was done in 1.4.6.30. Sorry if I caused some confusion, I guess I did not state in the description that a similar occurrence had happened in 1.4.5 as well as 1.4.6.30. So, yes you can reproduce it in 1.4.6.

*Edit
I have changed the first comment to indicate a similar occurrence had happened in 1.4.5 as well as 1.4.6.30

**Comment by fnuecke** [comment]
Hmm, I cannot reproduce this. The only major difference I can spot is that you're using Java 1.6 (well, and that you're on a Mac). Could you please try running MC using Java 1.7?

**Comment by tgeak** [comment]
Updated to Java 1.8, it seems to be working. I guess it was just an outdated java version, thanks.
