### ISSUE TITLE
luaj-jse-3.0 + OpenComputers = Client Crash

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#908]
I'm using luaj with CustomNPCs to script NPCs using lua. However, it seems to mess up ItemCost related functions and ItemStackWrapper? I know this is due to the luaj library because the issue stops when it's removed from the mods folder.

Basically, it will crash only when trying to retrieve Material Cost information for items in the inventory. Is there a way to add compatibility with luaj libraries? or just ignore luaj all together?

Here's the crash report:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/11/15 10:41 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: Could not initialize class li.cil.oc.util.ItemCosts$
    at li.cil.oc.common.item.SimpleItem.func_77624_a(SimpleItem.scala:45)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:523)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:731)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:635)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1355)
    at sushen.aeiao.func_78480_b(Unknown Source)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at li.cil.oc.common.item.SimpleItem.func_77624_a(SimpleItem.scala:45)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:523)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:731)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:635)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (255, 216). Absolute: (511, 287)
    Screen size: Scaled: (640, 360). Absolute: (1280, 720). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1355)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['hckarbiter'/0, l='MpServer', x=-1928.53, y=5.62, z=134.72]]
    Chunk stats: MultiplayerChunkCache: 457, 466
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-1924,4,138), Chunk: (at 12,0,10 in -121,8; contains blocks -1936,0,128 to -1921,255,143), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,0,0 to -1537,255,511)
    Level time: 58732 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['hckarbiter'/0, l='MpServer', x=-1928.53, y=5.62, z=134.72]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10.2
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 200724416 bytes (191 MB) / 407494656 bytes (388 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.18.1180 Minecraft Forge 10.13.0.1180 Optifine OptiFine_1.7.10_HD_U_B4 9 mods loaded, 9 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.18.1180} [Forge Mod Loader](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.0.1180} [Minecraft Forge](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CameraStudio{2.1710} [Camera Studio](CameraStudioV2.1710%28mc1.7.10%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customnpcs{1.7.10c} [CustomNpcs](CustomNPCs_1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NBTEdit{1.7.2.2} [In-game NBTEdit](NBTEdit_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.4.9.35} [OpenComputers](OpenComputers-MC1.7.10-1.4.9.35-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel HD Graphics 3000 OpenGL Engine GL version 2.1 INTEL-10.0.19, Intel Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by ghost** [comment]
Well now it happens with or without the luaj library.. maybe there is something else causing the issue.

**Comment by fnuecke** [comment]
Huh, it's odd that the presence of the library would have any effect, but either way: the last two times this was reported, updating the Java version used solved the issue.
(And yes, it was the exact Java version you have both times)
