### ISSUE TITLE
OC 1.8-1.5.1.41-dev doesn't read override recipes

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/OpenComputers#934]
There is another mod in pack the registers the iron ingot and apparently not the iron nugget. So my nei shows I have two iron nuggets derivable from the same iron ingot. I've been in contact with the other mod author to try to solve the issue, but I feel there might be some issue in the OC mod as well.
1. oc mod for 1.8 registers an iron nugget when an iron nugget already exists within the system.
2. oc mod for 1.8 doesn't read the override recipes, if did, I would be happy and not be reporting this.

here is an example transistor recipe that updated inside of my "your_custom.recipes" file:

```
transistor {
  input: [["basemetals:copper_nugget", "basemetals:copper_nugget", "basemetals:copper_nugget"]
          [nuggetGold, paper, nuggetGold]
          ["", redstone, ""]]
}
```

the NEI still reports the recipe as being nuggetIron instead of the "basemetals:copper_nugget", I specified above.

My user.recipes file is as follows:

```
# To use different sets of recipes, include other recipe files in the order of
# priority to use the recipes defined in them. The last include has the highest
# priority (i.e. included recipes simply replace the current definition for all
# already known recipes).

#include file("default.recipes")
#include file("hardmode.recipes")
#include file("gregtech.recipes")
include file("your_custom.recipes")
```

There is no strange information in the logfiles either. :(

**Comment by fnuecke** [comment]
1. OC probably gets initialized before the other mod, so when it checks if there already is a recipe registered for an iron nugget the other mod's nugget isn't registered, yet. And the other mod probably doesn't do such a check, so it just registers its own recipe either way. Shouldn't really matter though, since it's in the oredict.
2. Can't reproduce, works fine for me. Make sure `basemetals:copper_nugget` is an actual oredictionary name. If it isn't, and it's an item name instead, you have to specify it this way: `{item="basemetals:copper_nugget"}`. If the definition is invalid OC will log that, though; look for warnings starting with `Failed adding shaped recipe for 'transistor'` for example.

**Comment by kreezxil** [comment]
Ok, cool, I'll try the other mod you stated in #2 
and by can't reproduce do you have at least the following mods installed:
first you gotta use forge 1.8
mods needed to test:
nei
dr cyanos base metals (1.1.1)
and of course OC 1.8 from curseforge or jenkins

you should experience my problem at that point. Actually as soon as you install base metals.

**Comment by kreezxil** [comment]
and I'll pass on the information from #1 to Dr. Cyano.

**Comment by kreezxil** [comment]
Woah!!! I tried your suggestion, it didn't fix anything. So I manually parse the fml server latest log and found a thread error that says the following:[code][21:27:00] [Server thread/ERROR] [OpenComputers/OpenComputers]: Error parsing recipes, you may not be able to craft any items from this mod!
com.typesafe.config.ConfigException$Parse: Reader: 304: expecting a close brace or a field name here, got '{'
	at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser$ParseContext.parseKey(Parser.java:592) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:757) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser.parse(Parser.java:34) ~[Parser.class:?]
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:227) ~[Parseable.class:?]
	at com.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:579) ~[ConfigFactory.class:?]
	at li.cil.oc.common.recipe.Recipes$$anon$1.includeFile(Recipes.scala:115) ~[Recipes$$anon$1.class:?]
	at com.typesafe.config.impl.SimpleIncluder$Proxy.includeFile(SimpleIncluder.java:290) ~[SimpleIncluder$Proxy.class:?]
	at com.typesafe.config.impl.Parser$ParseContext.parseInclude(Parser.java:679) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:752) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993) ~[Parser$ParseContext.class:?]
	at com.typesafe.config.impl.Parser.parse(Parser.java:34) ~[Parser.class:?]
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170) ~[Parseable.class:?]
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:227) ~[Parseable.class:?]
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:595) ~[ConfigFactory.class:?]
	at li.cil.oc.common.recipe.Recipes$.init(Recipes.scala:120) [Recipes$.class:?]
	at li.cil.oc.common.Proxy.init(Proxy.scala:83) [Proxy.class:?]
	at li.cil.oc.server.Proxy.init(Proxy.scala:10) [Proxy.class:?]
	at li.cil.oc.OpenComputers$.init(OpenComputers.scala:40) [OpenComputers$.class:?]
	at li.cil.oc.OpenComputers.init(OpenComputers.scala) [OpenComputers.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:692) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:360) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [po.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31][/code]
Hopefully that means you guys have a missing } and not me. I'll double check my config to be sure tho.

**Comment by fnuecke** [comment]
Did you delete the message with the error log? Good thing I get mail notifications, so here it is for reference:

> Woah!!! I tried your suggestion, it didn't fix anything. So I manually parse the fml server latest log and found a thread error that says the following:
> 
> ```
> [21:27:00] [Server thread/ERROR] [OpenComputers/OpenComputers]: Error parsing recipes, you may not be able to craft any items from this mod!
> com.typesafe.config.ConfigException$Parse: Reader: 304: expecting a close brace or a field name here, got '{'
>     at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser$ParseContext.parseKey(Parser.java:592) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:757) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser.parse(Parser.java:34) ~[Parser.class:?]
>     at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.parse(Parseable.java:227) ~[Parseable.class:?]
>     at com.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:579) ~[ConfigFactory.class:?]
>     at li.cil.oc.common.recipe.Recipes$$anon$1.includeFile(Recipes.scala:115) ~[Recipes$$anon$1.class:?]
>     at com.typesafe.config.impl.SimpleIncluder$Proxy.includeFile(SimpleIncluder.java:290) ~[SimpleIncluder$Proxy.class:?]
>     at com.typesafe.config.impl.Parser$ParseContext.parseInclude(Parser.java:679) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:752) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993) ~[Parser$ParseContext.class:?]
>     at com.typesafe.config.impl.Parser.parse(Parser.java:34) ~[Parser.class:?]
>     at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170) ~[Parseable.class:?]
>     at com.typesafe.config.impl.Parseable.parse(Parseable.java:227) ~[Parseable.class:?]
>     at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:595) ~[ConfigFactory.class:?]
>     at li.cil.oc.common.recipe.Recipes$.init(Recipes.scala:120) [Recipes$.class:?]
>     at li.cil.oc.common.Proxy.init(Proxy.scala:83) [Proxy.class:?]
>     at li.cil.oc.server.Proxy.init(Proxy.scala:10) [Proxy.class:?]
>     at li.cil.oc.OpenComputers$.init(OpenComputers.scala:40) [OpenComputers$.class:?]
>     at li.cil.oc.OpenComputers.init(OpenComputers.scala) [OpenComputers.class:?]
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
>     at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
>     at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) [FMLModContainer.class:?]
>     at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
>     at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
>     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
>     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
>     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
>     at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
>     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.jar:?]
>     at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.jar:?]
>     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
>     at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:692) [Loader.class:?]
>     at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
>     at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:360) [FMLCommonHandler.class:?]
>     at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [po.class:?]
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
> ```
> 
> Hopefully that means you guys have a missing } and not me. I'll double check my config to be sure tho.

That means you have an error in your recipe file, on line 304 going by the message. It's definitely not an issue with OC's own recipe files.

**Comment by kreezxil** [comment]
Yeah, that's why I deleted that out, because I realized it was talking
about my file.

Once I got the recipes reading in I discovered that it still didn't like my
recipes I've tried making the recipe with {item="basemetals:copper_nugget"}
and "basemetals:copper_nugget" quotes included in both cases. No effect, OC
still registers it's own nugget and still insists that all of the recipes
where I wanted to use basemtals:copper_nugget were replaced with its own
nugget.

On top of that, OC refuses to acknowledge any recipe using 'button'.

the only reason I was even trying to use metal from another mod was because
as initially state OC insists on its own nugget. But something else is
going on here.

btw, in creative I can do _/give Kreezxil basemetals:copper_nugget 10_ and
get 10 of those; knowing that should've helped me to formulate the recipes,
but perhaps there is something about the config that still baffles me. :(

My "your_custom.recipe" file is http://paste.ee/p/NSttt

**Comment by fnuecke** [comment]
Well I'm not sure what it is you're doing wrong, but your doing something wrong.
![It's working](http://i.imgur.com/1uVQgnQ.png)
This is using the [recipe file you posted](http://paste.ee/p/NSttt). In the post you deleted. Again. Seriously, don't do that, it makes it unnecessarily hard to discuss this.

Also, I don't know what you mean with buttons not working in recipes? I can craft keyboards perfectly fine.

**Comment by kreezxil** [comment]
ok, cool, this is good information. please don't close this, because when I find the mod causing the problems, I'm posting that here, that way others might learn quickly which mod not to trust. or what to tweak as the case may be.

**Comment by kreezxil** [comment]
Discovered that [Craft++](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2342595-craft-v2-1-a-simple-vanilla-enhancing-mod-reviewed) knocks out the default minecraft button, rendering any recipe depending on the button useless. The author's page says that stone and wooden buttons are renamed in the internal system. So that explains that. I'd definitely mark Craft++ as incompatible with OC.

Tbe mod that registers a strange iron nugget that messes with OC's recipes is [Spectral Guns Mod](http://www.planetminecraft.com/mod/spectralguns/) and therefore is incompatible as well.

You may now mark this thread as closed.

Thank You for the opportunity to find the issues.

**Comment by fnuecke** [comment]
Thanks for sharing that info. You might want to inform the author(s) of the guns mod that it'd be a good idea to add their nugget to the ore dictionary, that would avoid this conflict (and it conflicting with pretty much every other mod out there using iron nuggets). As for the mod removing the default button, that's... uh. Well, to each their own. Good thing OC allows customizing its recipes :P

**Comment by kreezxil** [comment]
Cool, I let that author know about it.
