### ISSUE TITLE
mod incapatible with the spectralguns mod.

### ISSUE THREAD

**Issue by sigurd4** [MightyPirates/OpenComputers#951]
opencomputers is not capatible with our mod spectralguns. i can't seem to find the problem in your code (i firstly don't understand scala very well, and secondly the the log is pointing to a line that is an import in your code, which i simply cannot get to make sense as it has nothing to do with my code whatsoever). in the stacktrace it mentions the field "field_151573_f", but i see no reference to it in this class, either. it would be awesome if our mods were capatible with each other. do you know what is causing the problem?
crash:

```
[19:33:18] [main/INFO] [GradleStart]: Extra: []
[19:33:18] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Sigurd/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --accessToken, {REDACTED}, --version, 1.8, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker]
[19:33:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:33:18] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:33:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker
[19:33:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:33:18] [main/INFO] [FML]: Forge Mod Loader version 8.0.37.1334 for Minecraft 1.8 loading
[19:33:18] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_25
[19:33:18] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[19:33:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker
[19:33:18] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[19:33:18] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[19:33:18] [main/INFO] [GradleStart]: Injecting location in coremod li.cil.oc.common.launch.TransformerLoader
[19:33:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:33:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:33:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:33:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:33:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:33:18] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[19:33:21] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[19:33:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:33:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:33:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:33:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:33:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:33:23] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:33:23] [Client thread/INFO]: Setting user: Player975
[19:33:25] [Client thread/INFO] [OpenComputers]: Successfully patched net/minecraft/entity/EntityLiving.recreateLeash.
[19:33:26] [Client thread/INFO]: LWJGL Version: 2.9.1
[19:33:27] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[19:33:27] [Client thread/INFO] [FML]: MinecraftForge v11.14.1.1334 Initialized
[19:33:27] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[19:33:27] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[19:33:27] [Client thread/INFO] [FML]: Searching C:\Users\Sigurd\Documents\Minecraft\bioshock mod workspace\SpectralGuns\eclipse\client\mods for mods
[19:33:28] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[19:33:29] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, OpenComputers|Core, spectralguns, OpenComputers] at CLIENT
[19:33:29] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, OpenComputers|Core, spectralguns, OpenComputers] at SERVER
[19:33:29] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Spectral Guns, FMLFileResourcePack:OpenComputers
[19:33:29] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[19:33:29] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[19:33:29] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[19:33:30] [Client thread/WARN] [OpenComputers]: Failed saving config.
java.io.FileNotFoundException: C:\Users\Sigurd\Documents\Minecraft\bioshock mod workspace\SpectralGuns\eclipse\client\config\opencomputers\settings.conf (Systemet finner ikke angitt bane)
    at java.io.FileOutputStream.open(Native Method) ~[?:1.8.0_25]
    at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_25]
    at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_25]
    at java.io.PrintWriter.<init>(Unknown Source) ~[?:1.8.0_25]
    at li.cil.oc.Settings$.load(Settings.scala:380) [Settings$.class:?]
    at li.cil.oc.common.Proxy.preInit(Proxy.scala:31) [Proxy.class:?]
    at li.cil.oc.client.Proxy.preInit(Proxy.scala:32) [Proxy.class:?]
    at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34) [OpenComputers$.class:?]
    at li.cil.oc.OpenComputers.preInit(OpenComputers.scala) [OpenComputers.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) [FMLModContainer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:412) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:325) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85) [start/:?]
    at GradleStart.main(GradleStart.java:45) [start/:?]
[19:33:30] [Client thread/INFO] [OpenComputers]: Initializing blocks and items.
[19:33:30] [Client thread/INFO] [OpenComputers]: Skipping interface buildcraft.api.tiles.IHasWork from missing mod BuildCraft|Core.
[19:33:31] [Client thread/INFO] [FML]: Applying holder lookups
[19:33:31] [Client thread/INFO] [FML]: Holder lookups applied
[19:33:31] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[19:33:31] [Client thread/ERROR] [FML]: 
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{8.0.37.1334} [Forge Mod Loader] (forgeSrc-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized
    Forge{11.14.1.1334} [Minecraft Forge] (forgeSrc-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    spectralguns{1.1} [Spectral Guns] (bin) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.5.2.7} [OpenComputers] (OpenComputers-MC1.8-1.5.2.7-universal.jar) Unloaded->Constructed->Errored
[19:33:31] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[19:33:31] [Client thread/ERROR] [FML]: Caught exception from OpenComputers
java.lang.NoSuchFieldError: field_151573_f
    at li.cil.oc.common.block.SimpleBlock$.$lessinit$greater$default$1(SimpleBlock.scala:25) ~[SimpleBlock$.class:?]
//i assume this is where the error is at? this is the part that confuses me, cause the line it is referring to is no actual code, just an import declaration^
    at li.cil.oc.common.block.Switch.<init>(Switch.scala:8) ~[Switch.class:?]
    at li.cil.oc.common.block.AccessPoint.<init>(AccessPoint.scala:7) ~[AccessPoint.class:?]
    at li.cil.oc.common.init.Blocks$.init(Blocks.scala:36) ~[Blocks$.class:?]
    at li.cil.oc.common.Proxy.preInit(Proxy.scala:35) ~[Proxy.class:?]
    at li.cil.oc.client.Proxy.preInit(Proxy.scala:32) ~[Proxy.class:?]
    at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34) ~[OpenComputers$.class:?]
    at li.cil.oc.OpenComputers.preInit(OpenComputers.scala) ~[OpenComputers.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) ~[forgeSrc-1.8-11.14.1.1334.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[forgeSrc-1.8-11.14.1.1334.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[forgeSrc-1.8-11.14.1.1334.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:412) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:325) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85) [start/:?]
    at GradleStart.main(GradleStart.java:45) [start/:?]
[19:33:31] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:568]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8-1.5.2.7-universal.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 05.03.15 19:33
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: field_151573_f
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:516)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:412)
    at net.minecraft.client.Minecraft.run(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(Main.java:117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85)
    at GradleStart.main(GradleStart.java:45)
Caused by: java.lang.NoSuchFieldError: field_151573_f
    at li.cil.oc.common.block.SimpleBlock$.$lessinit$greater$default$1(SimpleBlock.scala:25)
    at li.cil.oc.common.block.Switch.<init>(Switch.scala:8)
    at li.cil.oc.common.block.AccessPoint.<init>(AccessPoint.scala:7)
    at li.cil.oc.common.init.Blocks$.init(Blocks.scala:36)
    at li.cil.oc.common.Proxy.preInit(Proxy.scala:35)
    at li.cil.oc.client.Proxy.preInit(Proxy.scala:32)
    at li.cil.oc.OpenComputers$.preInit(OpenComputers.scala:34)
    at li.cil.oc.OpenComputers.preInit(OpenComputers.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514)
    ... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 666037232 bytes (635 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.37.1334 Minecraft Forge 11.14.1.1334 6 mods loaded, 6 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{8.0.37.1334} [Forge Mod Loader] (forgeSrc-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized
    Forge{11.14.1.1334} [Minecraft Forge] (forgeSrc-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    spectralguns{1.1} [Spectral Guns] (bin) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.5.2.7} [OpenComputers] (OpenComputers-MC1.8-1.5.2.7-universal.jar) Unloaded->Constructed->Errored
    Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8-1.5.2.7-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
[19:33:31] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:568]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Sigurd\Documents\Minecraft\bioshock mod workspace\SpectralGuns\eclipse\client\.\crash-reports\crash-2015-03-05_19.33.31-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```

**Comment by Kubuxu** [comment]
It looks like you are in development environment. Can you try using deobf version of OpenComputer?

**Comment by fnuecke** [comment]
Maybe try using the deobf JAR (`-dev` instead of `-universal`), which you can get on the [Jenkins](http://ci.cil.li/).

**Comment by fnuecke** [comment]
Bloody ninjas :-P

**Comment by sigurd4** [comment]
it works now. thank you! someone reported that our mod was incapatible because of the fact that i didnt register my iron nugget item to the ore dictionary. i guess he/she just ment that the recipes werent working. hah :P

**Comment by fnuecke** [comment]
Ah yes, probably via [this issue](https://github.com/MightyPirates/OpenComputers/issues/934#issuecomment-75890292).
